```{r setup, include=FALSE}
library(stringr)

require(gmodels)
require(vcd)
require(lme4)
library(nlme)
library(caret)
library(pscl)
library(DT)
library(ggplot2)
theme_set(theme_bw())
library(GGally)
library(dplyr, warn.conflicts = F)
library(broom)

library(car)
library(readr)

source("../analisaICPorFoto.R")

sample_size <- function(x) { 
    return ( ( ( sd(x) * qnorm(1-(0.05/2)) )  / ( 0.05 * mean(x) ) ) ** 2)  #95% confidence interval, significance level of 0.05 (alpha) - sample 100
  }

mergeSort <- function(x){
  if(length(x) == 1){
    inv <- 0
  } else {
    n <- length(x)
    n1 <- ceiling(n/2)
    n2 <- n-n1
    y1 <- mergeSort(x[1:n1])
    y2 <- mergeSort(x[n1+1:n2])
    inv <- y1$inversions + y2$inversions
    x1 <- y1$sortedVector
    x2 <- y2$sortedVector
    i1 <- 1
    i2 <- 1
    while(i1+i2 <= n1+n2+1){
      if(i2 > n2 || (i1 <= n1 && x1[i1] <= x2[i2])){
        x[i1+i2-1] <- x1[i1]
        i1 <- i1 + 1
      } else {
        inv <- inv + n1 + 1 - i1
        x[i1+i2-1] <- x2[i2]
        i2 <- i2 + 1
      }
    }
  }
  return (list(inversions=inv,sortedVector=x))
}

numberOfInversions <- function(x){
  r <- mergeSort(x)
  return (r$inversions)
}

normalizedKendallTauDistance2 <- function(data1, data2){
  x <- data1
  y <- data2
  
  tau = numberOfInversions(order(x)[rank(y)])
  print(tau)
  nItens = length(x)
  maxNumberOfInverstions <- (nItens*(nItens-1))/2
  normalized = tau/maxNumberOfInverstions

  print (normalized)
}

#Reading CrowdFlower features data
dadosg1 <- read.csv("../regressao100/g1.csv")
dadosg2 <- read.csv("../regressao100/g2.csv")
dadosg3 <- read.csv("../regressao100/g3.csv")
dadosg4 <- read.csv("../regressao100/g4.csv")
dadosg5 <- read.csv("../regressao100/g5.csv")
dadosg6 <- read.csv("../regressao100/g6.csv")
dadosg7 <- read.csv("../regressao100/g7.csv")
dadosg8 <- read.csv("../regressao100/g8.csv")
dadosg9 <- read.csv("../regressao100/g9.csv")
dadosg10 <- read.csv("../regressao100/g10.csv")
dadosg11 <- read.csv("../regressao100/g11.csv")
dadosg12 <- read.csv("../regressao100/g12.csv")
dadosg13 <- read.csv("../regressao100/g13.csv")

#Summing features values  - left and right
somaValores <- function(dados1, dados2, desvio1, desvio2, uplimit){
    dados1[is.na(dados1)] <- 0
    dados2[is.na(dados2)] <- 0
    
    soma = dados1 + dados2
    desvios = (desvio1 + desvio2)/2
    
    desvio = sd(soma)
        soma <- ifelse(soma < 0, 0, soma)
        soma <- ifelse(soma > uplimit, uplimit, soma)
        return (mean(soma))
}

#Mean of features values - left and right
mediaValores <- function(dados1, dados2, desvio1, desvio2, uplimit){
   for (i in 1:length(dados1)){
       if(is.na(dados1[i])){
         dados1[i] <- dados2[i]
       }
       if(is.na(dados2[i])){
         dados2[i] <- dados1[i]
       }
    }
    
    soma = (dados1 + dados2) / 2
    desvios = (desvio1 + desvio2)/2
    
    desvio = sd(soma)
        soma <- ifelse(soma < 0, 0, soma)
        soma <- ifelse(soma > uplimit, uplimit, soma)
        return (mean(soma))
}


#Creating values for the cases where only 1 answer was obtained considering the desviations of other features answers
geraValores <- function(lista, question, desvios, uplimit){
   #desvio = sd(lista)
   return (mean(lista, na.rm = TRUE))
}

Mode <- function(x) {
  ux <- unique(x)
  ux[which.max(tabulate(match(x, ux)))]
}

#Grouping by image and question - G1
by_image <- group_by(dadosg1, image_url)
desvios <- summarise (by_image, 
                  sd1 = sd(question1, na.rm = TRUE),
                  sd2l = sd(question2__left_side, na.rm = TRUE),
                  sd2r = sd(question2__right_side, na.rm = TRUE),
                  sd3 = sd(question3, na.rm = TRUE) )
groupedData1 <- summarise(by_image,
  #count = n(),
  q1 = geraValores(question1, "1", desvios, 100),
  #sdq1 = sd(question1, na.rm = TRUE),
  q2 = mediaValores(question2__left_side, question2__right_side, desvios$sd2l, desvios$sd2r, 100),
  q2_left = geraValores(question2__left_side, "2l", desvios, 100),
  #sdq2_left = sd(question2__left_side, na.rm = TRUE),
  q2_right = geraValores(question2__right_side, "2r", desvios, 100),
  #sdq2_right = sd(question2__right_side, na.rm = TRUE),
  q3 = geraValores(question3, "3", desvios, 100)
  #sdq3 = sd(question3, na.rm = TRUE) 
  )

#Grouping by image and question- G2
by_image <- group_by(dadosg2, image_url)
desvios <- summarise (by_image, 
                  sd1 = sd(question1, na.rm = TRUE),
                  sd2l = sd(question2__left_side, na.rm = TRUE),
                  sd2r = sd(question2__right_side, na.rm = TRUE),
                  sd3 = sd(question3, na.rm = TRUE) )
groupedData2 <- summarise(by_image,
  count = n(),
  q1 = geraValores(question1, "1", desvios, 100),
  #sdq1 = sd(question1, na.rm = TRUE),
  q2 = somaValores(question2__left_side, question2__right_side, desvios$sd2l, desvios$sd2r, 200),
  q2_left = geraValores(question2__left_side, "2l", desvios, 100),
  #sdq2_left = sd(question2__left_side, na.rm = TRUE),
  q2_right = geraValores(question2__right_side, "2r", desvios, 100),
  #sdq2_right = sd(question2__right_side, na.rm = TRUE),
  q3 = geraValores(question3, "3", desvios, 100)
  #sdq3 = sd(question3, na.rm = TRUE) 
  )

#Grouping by image and question - G3
by_image <- group_by(dadosg3, image_url)
desvios <- summarise (by_image, 
                  sd1l = sd(question1__left_side, na.rm = TRUE),
                  sd1r = sd(question1__right_side, na.rm = TRUE),
                  sd2l = sd(question2__left_side, na.rm = TRUE),
                  sd2r = sd(question2__right_side, na.rm = TRUE),
                  sd3l = sd(question3__left_side, na.rm = TRUE),
                  sd3r = sd(question3__right_side, na.rm = TRUE) )
groupedData3 <- summarise(by_image,
  count = n(),
  q1 = mediaValores(question1__left_side, question1__right_side, desvios$sd1l, desvios$sd1r, 5),
  q1_left = geraValores(question1__left_side, "1l", desvios, 5),
  #sdq1_left = sd(question1__left_side, na.rm = TRUE),
  q1_right = geraValores(question1__right_side, "1r", desvios, 5),
  #sdq1_right = sd(question1__right_side, na.rm = TRUE),
  q2 = mediaValores(question2__left_side, question2__right_side, desvios$sd2l, desvios$sd2r, 5),
  q2_left = geraValores(question2__left_side, "2l", desvios, 5),
  #sdq2_left = sd(question2__left_side, na.rm = TRUE),
  q2_right = geraValores(question2__right_side, "2r", desvios, 5),
  #sdq2_right = sd(question2__right_side, na.rm = TRUE),
  q3 = mediaValores(question3__left_side, question3__right_side, desvios$sd3l, desvios$sd3r, 5),
  q3_left = geraValores(question3__left_side, "3l", desvios, 5),
  #sdq3_left = sd(question3__left_side, na.rm = TRUE),
  q3_right = geraValores(question3__right_side, "3r", desvios, 5)
  #sdq3_right = sd(question3__right_side, na.rm = TRUE)  
  )

#Grouping by image and question - G4
by_image <- group_by(dadosg4, image_url)
desvios <- summarise (by_image, 
                  sd1 = sd(question1, na.rm = TRUE),
                  sd2 = sd(question2, na.rm = TRUE))
groupedData4 <- summarise(by_image,
  count = n(),
  q1 = geraValores(question1, "1", desvios, 10),
  #sdq1 = sd(question1, na.rm = TRUE),
  q2 = geraValores(question2, "2", desvios, 10)
  #sdq2 = sd(question2, na.rm = TRUE) 
  )

#Grouping by image and question - G5
by_image <- group_by(dadosg5, image_url)
desvios <- summarise (by_image, 
                  sd1 = sd(question1, na.rm = TRUE),
                  sd2 = sd(your_answer_is, na.rm = TRUE))
groupedData5 <- summarise(by_image,
  count = n(),
  q1 = geraValores(question1, "1", desvios, 20),
  #sdq1 = sd(question1, na.rm = TRUE),
  q2 = geraValores(your_answer_is, "2", desvios, 20)
  #sdq2 = sd(question2, na.rm = TRUE) 
  )

#Grouping by image and question - G6
by_image <- group_by(dadosg6, image_url)
desvios <- summarise (by_image, 
                  sd1l = sd(question1__left_side, na.rm = TRUE),
                  sd1r = sd(question1__right_side, na.rm = TRUE),
                  sd2l = sd(question2__left_side, na.rm = TRUE),
                  sd2r = sd(question2__right_side, na.rm = TRUE) )
groupedData6 <- summarise(by_image,
  count = n(),
  q1 = mediaValores(question1__left_side, question1__right_side, desvios$sd1l, desvios$sd1r, 1),
  q1_left = geraValores(question1__left_side, "1l", desvios, 1),
  #sdq1_left = sd(question1__left_side, na.rm = TRUE),
  q1_right = geraValores(question1__right_side, "1r", desvios, 1),
  #sdq1_right = sd(question1__right_side, na.rm = TRUE),
  q2 = mediaValores(question2__left_side, question2__right_side, desvios$sd2l, desvios$sd2r, 1),
  q2_left = geraValores(question2__left_side, "2l", desvios, 1),
  #sdq2_left = sd(question2__left_side, na.rm = TRUE),
  q2_right = geraValores(question2__right_side, "2r", desvios, 1)
  #sdq2_right = sd(question2__right_side, na.rm = TRUE) 
  )

#Grouping by image and question - G7
by_image <- group_by(dadosg7, image_url)
desvios <- summarise (by_image, 
                  sd1 = sd(question1, na.rm = TRUE),
                  sd2 = sd(question2, na.rm = TRUE),
                  sd3l = sd(question3__left_side, na.rm = TRUE),
                  sd3r = sd(question3__right_side, na.rm = TRUE) )
groupedData7 <- summarise(by_image,
  count = n(),
  q1 = geraValores(question1, "1", desvios, 3),
  #sdq1 = sd(question1, na.rm = TRUE),
  q2 = geraValores(question2, "2", desvios, 1),
  #sdq2 = sd(question2, na.rm = TRUE),
  q3 = mediaValores(question3__left_side, question3__right_side, desvios$sd3l, desvios$sd3r, 1),
  q3_left = geraValores(question3__left_side, "3l", desvios, 1),
  #sdq3_left = sd(question3__left_side, na.rm = TRUE),
  q3_right = geraValores(question3__right_side, "3r", desvios, 1)
  #sdq3_right = sd(question3__right_side, na.rm = TRUE)  
  )

#Grouping by image and question - G8
by_image <- group_by(dadosg8, image_url)
desvios <- summarise (by_image, 
                  sd1 = sd(question1, na.rm = TRUE),
                  sd2l = sd(question2__left_side, na.rm = TRUE),
                  sd2r = sd(question2_right_side, na.rm = TRUE),
                  sd3l = sd(question3__left_side, na.rm = TRUE),
                  sd3r = sd(question3_right_side, na.rm = TRUE)
                  )
groupedData8 <- summarise(by_image,
  count = n(),
  q1 = Mode(question1),
  #sdq1 = sd(question1, na.rm = TRUE),
  q2 = somaValores(question2__left_side, question2_right_side, desvios$sd2l, desvios$sd2r, 40),
  q2_left = geraValores(question2__left_side, "2l", desvios, 20),
  #sdq2_left = sd(question2__left_side, na.rm = TRUE),
  q2_right = geraValores(question2_right_side, "2r", desvios, 20),
  #sdq2_right = sd(question2__right_side, na.rm = TRUE)  
  q3 = somaValores(question3__left_side, question3_right_side, desvios$sd3l, desvios$sd3r, 40),
  q3_left = geraValores(question3__left_side, "3l", desvios, 20),
  q3_right = geraValores(question3_right_side, "3r", desvios, 20)
  )

#Grouping by image and question - G9
by_image <- group_by(dadosg9, image_url)
desvios <- summarise (by_image, 
                  sd1l = sd(question1__left_side, na.rm = TRUE),
                  sd1r = sd(question1__right_side, na.rm = TRUE) )
groupedData9 <- summarise(by_image,
  count = n(),
  q1 = mediaValores(question1__left_side, question1__right_side, desvios$sd1l, desvios$sd1r, 200),
  q1_left = geraValores(question1__left_side, "1l", desvios, 200),
  #sdq1_left = sd(question1__left_side, na.rm = TRUE),
  q1_right = geraValores(question1__right_side, "1r", desvios, 200)
  #sdq1_right = sd(question1__right_side, na.rm = TRUE)  
  )

#Grouping by image and question - G10
by_image <- group_by(dadosg10, image_url)
desvios <- summarise (by_image, 
                  sd1 = sd(question1, na.rm = TRUE),
                  sd2 = sd(question2, na.rm = TRUE),
                  sd3 = sd(question3, na.rm = TRUE))
groupedData10 <- summarise(by_image,
  count = n(),
  q1 = Mode(x = question1),
  #sdq1 = sd(question1, na.rm = TRUE),
  q2 = geraValores(question2, "2", desvios, 50),
  #sdq2 = sd(question2, na.rm = TRUE),
  q3 = geraValores(question3, "3", desvios, 1)
  #sdq3 = sd(question3, na.rm = TRUE)  
  )

#Grouping by image and question - G11
by_image <- group_by(dadosg11, image_url)
desvios <- summarise (by_image, 
                  sd2l = sd(question2__left_side, na.rm = TRUE),
                  sd2r = sd(question2__right_side, na.rm = TRUE),
                  sd3l = sd(question3__left_side, na.rm = TRUE),
                  sd3r = sd(question3__right_side, na.rm = TRUE) )
groupedData11 <- summarise(by_image,
  count = n(),
  q2 = somaValores(question2__left_side, question2__right_side, desvios$sd2l, desvios$sd2r, 20),
  q2_left = geraValores(question2__left_side, "2l", desvios, 10),
  #sdq2_left = sd(question2__left_side, na.rm = TRUE),
  q2_right = geraValores(question2__right_side, "2r", desvios, 10),
  #sdq2_right = sd(question2__right_side, na.rm = TRUE),
  q3 = somaValores(question3__left_side, question3__right_side, desvios$sd3l, desvios$sd3r, 80),
  q3_left = geraValores(question3__left_side, "3l", desvios, 40),
  #sdq3_left = sd(question3__left_side, na.rm = TRUE),
  q3_right = geraValores(question3__right_side, "3r", desvios, 40)
  #sdq3_right = sd(question3__right_side, na.rm = TRUE)  
  )

#Grouping by image and question - G12
by_image <- group_by(dadosg12, image_url)
desvios <- summarise (by_image, 
                  sd1 = sd(question1, na.rm = TRUE),
                  sd2l = sd(question2__left_side, na.rm = TRUE),
                  sd2r = sd(question2__right_side, na.rm = TRUE),
                  sd3 = sd(question3, na.rm = TRUE))
groupedData12 <- summarise(by_image,
  count = n(),
  q1 = geraValores(question1, "1", desvios, 10),
  #sdq1 = sd(question1, na.rm = TRUE),
  q2 = somaValores(question2__left_side, question2__right_side, desvios$sd2l, desvios$sd2r, 20),
  q2_left = geraValores(question2__left_side, "2l", desvios, 10),
  #sdq2_left = sd(question2__left_side, na.rm = TRUE),
  q2_right = geraValores(question2__right_side, "2r", desvios, 10),
  #sdq2_right = sd(question2__right_side, na.rm = TRUE),
  q3 = geraValores(question3, "3", desvios,10)
  #sdq3 = sd(question3, na.rm = TRUE)  
  )

#Grouping by image and question - G13
by_image <- group_by(dadosg13, image_url)
desvios <- summarise (by_image, 
                  sd1l = sd(question1__left_side, na.rm = TRUE),
                  sd1r = sd(question1__right_side, na.rm = TRUE),
                  sd2l = sd(question2__left_side, na.rm = TRUE),
                  sd2r = sd(question2__right_side, na.rm = TRUE) )
groupedData13 <- summarise(by_image,
  count = n(),
  q1 = somaValores(question1__left_side, question1__right_side, desvios$sd1l, desvios$sd1r, 30),
  q1_left = geraValores(question1__left_side, "1l", desvios, 10),
  #sdq1_left = sd(question1__left_side, na.rm = TRUE),
  q1_right = geraValores(question1__right_side, "1r", desvios, 15),
  #sdq1_right = sd(question1__right_side, na.rm = TRUE),
  q2 = mediaValores(question2__left_side, question2__right_side, desvios$sd2l, desvios$sd2r, 1),
  q2_left = geraValores(question2__left_side, "2l", desvios, 1),
  #sdq2_left = sd(question2__left_side, na.rm = TRUE),
  q2_right = geraValores(question2__right_side, "2r", desvios, 1)
  #sdq2_right = sd(question2__right_side, na.rm = TRUE) 
  )

#Renaming columns according to a fixed id
renomeiaGrupos <- function(dadosPorGrupo, listaColunas, idGrupo) {
    for (coluna in listaColunas){
        colnames(dadosPorGrupo)[colnames(dadosPorGrupo) == coluna] <- paste(idGrupo, coluna, sep="")
    }
    return(dadosPorGrupo)
}

renomeiaGrupos2 <- function(dadosPorGrupo, listaColunas, novosNomes) {
    for (i in seq(1, length(listaColunas))){
        coluna = listaColunas[i]
        colnames(dadosPorGrupo)[colnames(dadosPorGrupo) == coluna] <- novosNomes[i]
    }
    return(dadosPorGrupo)
}

groupedData1 <- renomeiaGrupos(groupedData1, c("q2_left", "q2_right", "count"), "g1")
groupedData2 <- renomeiaGrupos(groupedData2, c("q2_left", "q2_right", "count"), "g2")
groupedData3 <- renomeiaGrupos(groupedData3, c("q1_left", "q1_right","q2_left", "q2_right","q3_left", "q3_right", "count"), "g3")
groupedData4 <- renomeiaGrupos(groupedData4, c("count"), "g4")
groupedData5 <- renomeiaGrupos(groupedData5, c("count"), "g5")
groupedData6 <- renomeiaGrupos(groupedData6, c("q1_left", "q1_right", "q2_left", "q2_right", "count"), "g6")
groupedData7 <- renomeiaGrupos(groupedData7, c("q3_left", "q3_right", "count"), "g7")
groupedData8 <- renomeiaGrupos(groupedData8, c("q2_left", "q2_right","q3_left", "q3_right", "count"), "g8")
groupedData9 <- renomeiaGrupos(groupedData9, c("q1_left", "q1_right", "count"), "g9")
groupedData10 <- renomeiaGrupos(groupedData10, c("count"), "g10")
groupedData11 <- renomeiaGrupos(groupedData11, c("q2_left", "q2_right","q3_left", "q3_right", "count"), "g11")
groupedData12 <- renomeiaGrupos(groupedData12, c("q2_left", "q2_right", "count"), "g12")
groupedData13 <- renomeiaGrupos(groupedData13, c("q1_left", "q1_right", "q2_left", "q2_right", "count"), "g13")

groupedData1 <- renomeiaGrupos2(groupedData1, c("q1", "q2", "q3"), c("street_wid", "sidewalk_wid", "public_art"))
groupedData2 <- renomeiaGrupos2(groupedData2, c("q1", "q2", "q3"), c("mov_cars", "park_cars", "mov_ciclyst"))
groupedData3 <- renomeiaGrupos2(groupedData3, c("q1", "q2", "q3"), c("debris", "pavement", "landscape"))
groupedData4 <- renomeiaGrupos2(groupedData4, c("q1", "q2"), c("courtyards", "major_landsc"))
groupedData5 <- renomeiaGrupos2(groupedData5, c("q1", "q2"), c("build_ident", "build_nrectan"))
groupedData6 <- renomeiaGrupos2(groupedData6, c("q1", "q2"), c("prop_street_wall", "prop_wind"))
groupedData7 <- renomeiaGrupos2(groupedData7, c("q1", "q2", "q3"), c("long_sight", "prop_sky_ahead", "prop_sky_across"))
groupedData8 <- renomeiaGrupos2(groupedData8, c("q1", "q2", "q3"), c("graffiti", "trees", "small_planters"))
groupedData9 <- renomeiaGrupos2(groupedData9, c("q1"), c("build_height"))
groupedData10 <- renomeiaGrupos2(groupedData10, c("q1", "q2", "q3"), c("build_diff_ages", "diff_build", "prop_hist_build"))
groupedData11 <- renomeiaGrupos2(groupedData11, c("q2", "q3"), c("outdoor_table", "street_furnit"))
groupedData12 <- renomeiaGrupos2(groupedData12, c("q1", "q2", "q3"), c("basic_col", "lights", "accent_col"))
groupedData13 <- renomeiaGrupos2(groupedData13, c("q1","q2"), c("people", "prop_active_use"))
```

## Comparing scenes differences between different sides in terms of Q-Score and ranking
```{r read}
all_original <- read.table("../all100/all_ordenado.dat")
ag_orig <- filter(all_original, V1 != "seguro?")
seg_orig <- filter(all_original, V1 == "seguro?")

agrad.l <- ag_orig %>% do(arrange(., V3)) %>%
mutate(rank = 1:n())

seg.l <- seg_orig %>% do(arrange(., V3)) %>%
mutate(rank = 1:n())

#Computing differences between each element and its next!
agrad.l$rank_diff <- c(0, diff(agrad.l$rank))
agrad.l$score_diff <- c(0, diff(agrad.l$V3))

#Evaluating differences
sink("fotos_ordenadas_agrad_rank_diff.dat")
for(i in 1:nrow(agrad.l)){
  for(j in i+1:nrow(agrad.l)){
      first_elem <- agrad.l[i,]
      second_elem <- agrad.l[j,]
      
      score_diff <- second_elem$V3 - first_elem$V3
      if(score_diff > 1.0){
          rank_diff <- second_elem$rank - first_elem$rank
          print(paste("Diff ", score_diff, rank_diff), quote=FALSE)
      }
  }
}
sink()

diff_data <- read.table("fotos_ordenadas_agrad_rank_diff.dat")
print(summary(diff_data$V4))

#Computing differences between each element and its next! - Safety
seg.l$rank_diff <- c(0, diff(seg.l$rank))
seg.l$score_diff <- c(0, diff(seg.l$V3))

#Evaluating differences
sink("fotos_ordenadas_seg_rank_diff.dat")
for(i in 1:nrow(seg.l)){
  for(j in i+1:nrow(seg.l)){
      first_elem <- seg.l[i,]
      second_elem <- seg.l[j,]
      
      score_diff <- second_elem$V3 - first_elem$V3
      if(score_diff > 1.0){
          rank_diff <- second_elem$rank - first_elem$rank
          print(paste("Diff ", score_diff, rank_diff), quote=FALSE)
      }
  }
}
sink()

diff_data <- read.table("fotos_ordenadas_seg_rank_diff.dat")
print(summary(diff_data$V4))

#Evaluating photos divergences and urban elements
same_places_diff_agrad <- read.table("fotos_ordenadas_agrad_rank_diff.dat", sep="+")
centro <- filter(same_places_diff_agrad, grepl('centro', V2))
centro$V1 <- paste("https://contribua.org/bairros/norte/", centro$V1, sep="")
centro$V2 <- paste("https://contribua.org/bairros/norte/", centro$V2, sep="")
liberdade <- filter(same_places_diff_agrad, grepl('liberdade', V2))
liberdade$V1 <- paste("https://contribua.org/bairros/oeste/", liberdade$V1, sep="")
liberdade$V2 <- paste("https://contribua.org/bairros/oeste/", liberdade$V2, sep="")
catole <- filter(same_places_diff_agrad, grepl('catole', V2))
catole$V1 <- paste("https://contribua.org/bairros/oeste/", catole$V1, sep="")
catole$V2 <- paste("https://contribua.org/bairros/oeste/", catole$V2, sep="")
same_places_diff_agrad <- rbind(centro, liberdade, catole)

same_places_diff_seg <- read.table("fotos_ordenadas_seg_rank_diff.dat", sep="+")
centro <- filter(same_places_diff_seg, grepl('centro', V2))
centro$V1 <- paste("https://contribua.org/bairros/norte/", centro$V1, sep="")
centro$V2 <- paste("https://contribua.org/bairros/norte/", centro$V2, sep="")
liberdade <- filter(same_places_diff_seg, grepl('liberdade', V2))
liberdade$V1 <- paste("https://contribua.org/bairros/oeste/", liberdade$V1, sep="")
liberdade$V2 <- paste("https://contribua.org/bairros/oeste/", liberdade$V2, sep="")
catole <- filter(same_places_diff_seg, grepl('catole', V2))
catole$V1 <- paste("https://contribua.org/bairros/oeste/", catole$V1, sep="")
catole$V2 <- paste("https://contribua.org/bairros/oeste/", catole$V2, sep="")
same_places_diff_seg <- rbind(centro, liberdade, catole)

#Combining all street features
combineFeaturesAndTestRegression <- function(dataset){
      
      temp <- merge(groupedData1, dataset, by.x="image_url", by.y="V1")
      temp <- merge(temp, groupedData2, by.x="image_url", by.y="image_url")
      temp <- merge(temp, groupedData3, by.x="image_url", by.y="image_url")
      temp <- merge(temp, groupedData4, by.x="image_url", by.y="image_url")
      temp <- merge(temp, groupedData5, by.x="image_url", by.y="image_url")
      temp <- merge(temp, groupedData6, by.x="image_url", by.y="image_url")
      temp <- merge(temp, groupedData7, by.x="image_url", by.y="image_url")
      temp <- merge(temp, groupedData8, by.x="image_url", by.y="image_url")
      temp<- merge(temp, groupedData9, by.x="image_url", by.y="image_url")
      temp <- merge(temp, groupedData10, by.x="image_url", by.y="image_url")
      temp <- merge(temp, groupedData11, by.x="image_url", by.y="image_url")
      temp <- merge(temp, groupedData12, by.x="image_url", by.y="image_url")
      temp <- merge(temp, groupedData13, by.x="image_url", by.y="image_url")
      
      temp <- merge(temp, groupedData1, by.x="V2", by.y="image_url")
      temp <- merge(temp, groupedData2, by.x="V2", by.y="image_url")
      temp <- merge(temp, groupedData3, by.x="V2", by.y="image_url")
      temp <- merge(temp, groupedData4, by.x="V2", by.y="image_url")
      temp <- merge(temp, groupedData5, by.x="V2", by.y="image_url")
      temp <- merge(temp, groupedData6, by.x="V2", by.y="image_url")
      temp <- merge(temp, groupedData7, by.x="V2", by.y="image_url")
      temp <- merge(temp, groupedData8, by.x="V2", by.y="image_url")
      temp<- merge(temp, groupedData9, by.x="V2", by.y="image_url")
      temp <- merge(temp, groupedData10, by.x="V2", by.y="image_url")
      temp <- merge(temp, groupedData11, by.x="V2", by.y="image_url")
      temp <- merge(temp, groupedData12, by.x="V2", by.y="image_url")
      temp <- merge(temp, groupedData13, by.x="V2", by.y="image_url")
      
      temp$diff_street_wid <- abs(temp$street_wid.x - temp$street_wid.y)
      temp$diff_mov_cars <- abs(temp$mov_cars.x - temp$mov_cars.y)
      temp$diff_park_cars <- abs(temp$park_cars.x - temp$park_cars.y)
      temp$diff_landscape <- abs(temp$landscape.x - temp$landscape.y)
      temp$diff_mov_ciclyst <- abs(temp$mov_ciclyst.x - temp$mov_ciclyst.y)
      temp$diff_build_ident <- abs(temp$build_ident.x - temp$build_ident.y)
      temp$diff_trees <- abs(temp$trees.x - temp$trees.y)
      temp$diff_build_height <- abs(log2(temp$build_height.x+1) - log2(temp$build_height.y+1))
      temp$diff_people <- abs(temp$people.x - temp$people.y)
      temp$diff_diff_build <- abs(temp$diff_build.x - temp$diff_build.y)
      temp$diff_graffiti <- abs((temp$graffiti.x == "Yes") - (temp$graffiti.y == "Yes"))
      
      temp1 <- lapply(as.character(temp$image_url), function (x) strsplit(x, split="/", fixed=TRUE)[[1]][6])
      neigs1 <- unlist(lapply(temp1, '[[', 1))
      temp$bairro <- neigs1
      
      temp <- arrange(temp, V3)  %>% mutate(rank = 1:n()) #arrange(temp, mean)  %>% mutate(rank = 1:n())
      temp$centro <- 0
      temp$catole <- 0
      temp$liberdade <- 0
      temp$centro[temp$bairro == "centro"] <- 1
      temp$catole[temp$bairro == "catole"] <- 1
      temp$liberdade[temp$bairro == "liberdade"] <- 1
      #temp$graffiti <- factor(temp$graffiti, levels = c("Yes", "No"))
      #temp$graffiti <- relevel(temp$graffiti,  "No")
      
      regGeneral <- lm(rank ~  diff_street_wid + diff_mov_cars + diff_park_cars + diff_mov_ciclyst + diff_landscape + diff_build_ident + diff_trees + diff_build_height + diff_people + diff_diff_build + diff_graffiti, na.action = na.exclude, data = temp)
      print(summary(regGeneral))
      return(summary(regGeneral))
}

sink("all_divergences_x_elements.dat")
print(">>>>> Pleasantness")
combineFeaturesAndTestRegression(same_places_diff_agrad)
print(">>>>> Top 11 divergences Pleasantness")
combineFeaturesAndTestRegression(arrange(same_places_diff_agrad, -V3)[1:11,])
print(">>>>> Safety")
combineFeaturesAndTestRegression(same_places_diff_seg)
sink()

```

