#!/bin/Rscript

#Agradavel
data = read.table("rgbQScoreAgrad.dat", header=TRUE)

print("Agradável")
#Spearman, analise do rho  > 0,90 a 1,0 indica correlação muito forte; +- 0,70 a +- 0,90 indica correlação forte; +- 0,50 a +- 0,70 moderada
print("Spearman red")
cor.test(data$qscore, data$red, method="spearman")
print("Spearman green")
cor.test(data$qscore, data$green, method="spearman")
print("Spearman blue")
cor.test(data$qscore, data$blue, method="spearman")
print("Spearman diag")
cor.test(data$qscore, data$diag, method="spearman")
print("Spearman hor")
cor.test(data$qscore, data$hor, method="spearman")
print("Spearman ver")
cor.test(data$qscore, data$ver, method="spearman")

print("Kendall red")
cor.test(data$qscore, data$red, method="kendall")
print("Kendall green")
cor.test(data$qscore, data$green, method="kendall")
print("Kendall blue")
cor.test(data$qscore, data$blue, method="kendall")
print("Kendall diag")
cor.test(data$qscore, data$diag, method="kendall")
print("Kendall hor")
cor.test(data$qscore, data$hor, method="kendall")
print("Kendall ver")
cor.test(data$qscore, data$ver, method="kendall")

pdf(file="histAgrad.pdf", paper="special")
par(mfrow = c(4,2))
hist(data$qscore, prob=TRUE, main="QScore")
hist(data$red, prob=TRUE, main="Red")
hist(data$green, prob=TRUE, main="Green")
hist(data$blue, prob=TRUE, main="Blue")
hist(data$diag, prob=TRUE, main="Diag")
hist(data$hor, prob=TRUE, main="Hor")
hist(data$ver, prob=TRUE, main="Ver")

pdf(file="boxAgrad.pdf", paper="special")
#par(mfrow = c(4,2))
boxplot(data$qscore, prob=TRUE, main="QScore")
#boxplot(data$red, prob=TRUE, main="Red")
#boxplot(data$green, prob=TRUE, main="Green")
#boxplot(data$blue, prob=TRUE, main="Blue")
#boxplot(data$diag, prob=TRUE, main="Diag")
#boxplot(data$hor, prob=TRUE, main="Hor")
#boxplot(data$ver, prob=TRUE, main="Ver")

pdf(file="qqplotsAgrad.pdf", paper="special")
par(mfrow = c(4,2))
qqnorm(data$qscore, main="QScore");qqline(data$qscore)
qqnorm(data$red, main="Red");qqline(data$red)
qqnorm(data$green, main="Green");qqline(data$green)
qqnorm(data$blue, main="Blue");qqline(data$blue)
qqnorm(data$diag, main="Diag");qqline(data$diag)
qqnorm(data$hor, main="Hor");qqline(data$hor)
qqnorm(data$ver, main="Ver");qqline(data$ver)

pdf(file="plotsAgrad.pdf", paper="special")
par(mfrow = c(3,2))
plot(data$red, data$qscore, main="Red")
plot(data$green, data$qscore, main="Green")
plot(data$blue, data$qscore, main="Blue")
plot(data$diag, data$qscore, main="Diag")
plot(data$hor, data$qscore, main="Hor")
plot(data$ver, data$qscore, main="Ver")



#Segurança
data = read.table("rgbQScoreSeg.dat", header=TRUE)

print("Segurança")
#Spearman, analise do rho  > 0,90 a 1,0 indica correlação muito forte; +- 0,70 a +- 0,90 indica correlação forte; +- 0,50 a +- 0,70 moderada
print("Spearman red")
cor.test(data$qscore, data$red, method="spearman")
print("Spearman green")
cor.test(data$qscore, data$green, method="spearman")
print("Spearman blue")
cor.test(data$qscore, data$blue, method="spearman")
print("Spearman diag")
cor.test(data$qscore, data$diag, method="spearman")
print("Spearman hor")
cor.test(data$qscore, data$hor, method="spearman")
print("Spearman ver")
cor.test(data$qscore, data$ver, method="spearman")

print("Kendall red")
cor.test(data$qscore, data$red, method="kendall")
print("Kendall green")
cor.test(data$qscore, data$green, method="kendall")
print("Kendall blue")
cor.test(data$qscore, data$blue, method="kendall")
print("Kendall diag")
cor.test(data$qscore, data$diag, method="kendall")
print("Kendall hor")
cor.test(data$qscore, data$hor, method="kendall")
print("Kendall ver")
cor.test(data$qscore, data$ver, method="kendall")

pdf(file="histSeg.pdf", paper="special")
par(mfrow = c(4,2))
hist(data$qscore, prob=TRUE, main="QScore")
hist(data$red, prob=TRUE, main="Red")
hist(data$green, prob=TRUE, main="Green")
hist(data$blue, prob=TRUE, main="Blue")
hist(data$diag, prob=TRUE, main="Diag")
hist(data$hor, prob=TRUE, main="Hor")
hist(data$ver, prob=TRUE, main="Ver")

pdf(file="boxSeg.pdf", paper="special")
#par(mfrow = c(4,2))
boxplot(data$qscore, prob=TRUE, main="QScore")
#boxplot(data$red, prob=TRUE, main="Red")
#boxplot(data$green, prob=TRUE, main="Green")
#boxplot(data$blue, prob=TRUE, main="Blue")
#boxplot(data$diag, prob=TRUE, main="Diag")
#boxplot(data$hor, prob=TRUE, main="Hor")
#boxplot(data$ver, prob=TRUE, main="Ver")

pdf(file="qqplotsSeg.pdf", paper="special")
par(mfrow = c(4,2))
qqnorm(data$qscore, main="QScore");qqline(data$qscore)
qqnorm(data$red, main="Red");qqline(data$red)
qqnorm(data$green, main="Green");qqline(data$green)
qqnorm(data$blue, main="Blue");qqline(data$blue)
qqnorm(data$diag, main="Diag");qqline(data$diag)
qqnorm(data$hor, main="Hor");qqline(data$hor)
qqnorm(data$ver, main="Ver");qqline(data$ver)

pdf(file="plotsSeg.pdf", paper="special")
par(mfrow = c(3,2))
plot(data$red, data$qscore, main="Red")
plot(data$green, data$qscore, main="Green")
plot(data$blue, data$qscore, main="Blue")
plot(data$diag, data$qscore, main="Diag")
plot(data$hor, data$qscore, main="Hor")
plot(data$ver, data$qscore, main="Ver")
