<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">

<head>

<meta charset="utf-8" />
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="generator" content="pandoc" />




<title>analisaPorRua2</title>

<script src="analisaPorRua2_files/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="analisaPorRua2_files/bootstrap-3.3.5/css/bootstrap.min.css" rel="stylesheet" />
<script src="analisaPorRua2_files/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="analisaPorRua2_files/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="analisaPorRua2_files/bootstrap-3.3.5/shim/respond.min.js"></script>
<script src="analisaPorRua2_files/navigation-1.1/tabsets.js"></script>
<link href="analisaPorRua2_files/highlightjs-1.1/default.css" rel="stylesheet" />
<script src="analisaPorRua2_files/highlightjs-1.1/highlight.js"></script>

<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>
<script type="text/javascript">
if (window.hljs && document.readyState && document.readyState === "complete") {
   window.setTimeout(function() {
      hljs.initHighlighting();
   }, 0);
}
</script>



<style type="text/css">
h1 {
  font-size: 34px;
}
h1.title {
  font-size: 38px;
}
h2 {
  font-size: 30px;
}
h3 {
  font-size: 24px;
}
h4 {
  font-size: 18px;
}
h5 {
  font-size: 16px;
}
h6 {
  font-size: 12px;
}
.table th:not([align]) {
  text-align: left;
}
</style>


</head>

<body>

<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img {
  max-width:100%;
  height: auto;
}
.tabbed-pane {
  padding-top: 12px;
}
button.code-folding-btn:focus {
  outline: none;
}
</style>



<div class="container-fluid main-container">

<!-- tabsets -->
<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});
</script>

<!-- code folding -->






<div class="fluid-row" id="header">



<h1 class="title toc-ignore">analisaPorRua2</h1>

</div>


<p>Aqui apresenta-se uma análise mais detalhada, rua a rua, a partir das percepções capturadas.</p>
<p>Alguns pontos importantes:</p>
<ul>
<li>O número da rua indica o que? Metros? <a href="http://campinagrandepb.com.br/wp-content/uploads/2014/10/codigo-de-obras-Lei-5410.131.pdf" class="uri">http://campinagrandepb.com.br/wp-content/uploads/2014/10/codigo-de-obras-Lei-5410.131.pdf</a></li>
<li>Índices de dispersão/quebra (entre números da rua, entre lados da rua, no mesmo lado, etc.)? Séries temporais?
<ul>
<li>Anomalias? <a href="https://www.datascience.com/blog/python-anomaly-detection" class="uri">https://www.datascience.com/blog/python-anomaly-detection</a></li>
<li>Derivadas, máximos e mínimos locais? Pacote features do R?</li>
</ul></li>
<li>Dados surpreendentes?
<ul>
<li>Surprise Maps? <a href="https://medium.com/@uwdata/surprise-maps-showing-the-unexpected-e92b67398865" class="uri">https://medium.com/@uwdata/surprise-maps-showing-the-unexpected-e92b67398865</a></li>
<li>Surprise na rua? Tendo como base um modelo uniforme, um base rate (pela média e pela mediana dos pontos) e um modelo normal extraído (média e desvio) de todos os pontos da rua.</li>
<li>Como temos o sorteio de valores pelo modelo normal, foram feitas 500 iterações para cálculo da média e da mediana. Os gráficos abaixo apresentam a média das médias/medianas nos surprise maps.</li>
</ul></li>
</ul>
<p>TO DO:</p>
<ul>
<li>Avaliar o mínimo de respostas necessárias?</li>
<li>O que um especialista diria de útil na análise</li>
<li>Comparação de modelo treinado x pessoas respondendo? Vantagens e desvantagens?</li>
</ul>
<p>De acordo com a heterogeneidade de cada rua (abaixo) vamos apresentar a discussão, a partir da próxima seção, da mais heterogênea para a mais homogênea.</p>
<pre><code>##   labels variable      value
## 1   Gini cristina 0.07784902
## 2   Gini   inacio 0.06499596
## 3   Gini   edesio 0.05558386
## 4   Gini floriano 0.03507198
## 5   Gini   manoel 0.02760162
## 6   Gini   maciel 0.02734805</code></pre>
<pre><code>##    labels variable       value
## 1 Entropy cristina 0.011161129
## 2 Entropy   inacio 0.006824837
## 3 Entropy   edesio 0.004873370
## 4 Entropy floriano 0.002176359
## 5 Entropy   manoel 0.001241221
## 6 Entropy   maciel 0.001149303</code></pre>
<pre><code>##   labels variable     value
## 1     SD cristina 0.7201075
## 2     SD   inacio 0.5487980
## 3     SD   edesio 0.4719678
## 4     SD floriano 0.3305999
## 5     SD   maciel 0.2344981
## 6     SD   manoel 0.1883041</code></pre>
<p>O que procurar?</p>
<ol style="list-style-type: decimal">
<li>Ponto mais heterogeneo/homogeneo</li>
<li>Melhor e pior local da rua</li>
<li>Melhor e pior área da rua (considerando os dois lados)</li>
<li>Áreas muito diferentes entre lados</li>
<li>Descontinuidades no mesmo lado</li>
<li>Heterogeneidade/Homogeneidade no ponto -&gt; Isso tudo pode ser explicado pela regressão geral das features?</li>
<li>O que é a rua?</li>
</ol>
<div id="cristina-procopio" class="section level1">
<h1>Cristina Procópio</h1>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  cristina$qscore
## W = 0.93023, p-value = 0.01639</code></pre>
<pre><code>##       mean          sd    
##   4.97966875   0.71104919 
##  (0.11242675) (0.07949772)</code></pre>
<pre><code>## [1] &quot;&gt;&gt;&gt; GINI da rua: &quot;</code></pre>
<pre><code>## [1] 0.07784902</code></pre>
<pre><code>##    num      value
## 1  305 0.10968214
## 2  350 0.10408033
## 3  436 0.04408976
## 4    2 0.03968838
## 5   66 0.03599606
## 6  390 0.02374677
## 7  105 0.02329330
## 8  261 0.01893199
## 9  210 0.01244132
## 10 160 0.01224060</code></pre>
<pre><code>##    num value
## 1    2   NaN
## 2   66   NaN
## 3  105   NaN
## 4  160   NaN
## 5  210   NaN
## 6  261   NaN
## 7  305   NaN
## 8  350   NaN
## 9  390   NaN
## 10 436   NaN</code></pre>
<pre><code>##    num value
## 1    2   NaN
## 2   66   NaN
## 3  105   NaN
## 4  160   NaN
## 5  210   NaN
## 6  261   NaN
## 7  305   NaN
## 8  350   NaN
## 9  390   NaN
## 10 436   NaN</code></pre>
<pre><code>## Adding missing grouping variables: `num`</code></pre>
<p><img src="analisaPorRua2_files/figure-html/unnamed-chunk-4-1.png" width="1152" /></p>
<table>
<thead>
<tr class="header">
<th align="left">xlabel</th>
<th align="left">side</th>
<th align="right">num</th>
<th align="right">angle</th>
<th align="right">V3</th>
<th align="left">street</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">2 - p1</td>
<td align="left">Side 1</td>
<td align="right">2</td>
<td align="right">45</td>
<td align="right">4.453842</td>
<td align="left">R._Cristina_Procópio_Silva</td>
</tr>
<tr class="even">
<td align="left">2 - p2</td>
<td align="left">Side 1</td>
<td align="right">6</td>
<td align="right">293</td>
<td align="right">4.559239</td>
<td align="left">R._Cristina_Procópio_Silva</td>
</tr>
<tr class="odd">
<td align="left">66 - p1</td>
<td align="left">Side 1</td>
<td align="right">66</td>
<td align="right">45</td>
<td align="right">5.452532</td>
<td align="left">R._Cristina_Procópio_Silva</td>
</tr>
<tr class="even">
<td align="left">66 - p2</td>
<td align="left">Side 1</td>
<td align="right">70</td>
<td align="right">315</td>
<td align="right">5.370995</td>
<td align="left">R._Cristina_Procópio_Silva</td>
</tr>
<tr class="odd">
<td align="left">105 - p1</td>
<td align="left">Side 1</td>
<td align="right">108</td>
<td align="right">45</td>
<td align="right">5.196042</td>
<td align="left">R._Cristina_Procópio_Silva</td>
</tr>
<tr class="even">
<td align="left">105 - p2</td>
<td align="left">Side 1</td>
<td align="right">112</td>
<td align="right">315</td>
<td align="right">5.151960</td>
<td align="left">R._Cristina_Procópio_Silva</td>
</tr>
<tr class="odd">
<td align="left">160 - p1</td>
<td align="left">Side 1</td>
<td align="right">160</td>
<td align="right">45</td>
<td align="right">5.476950</td>
<td align="left">R._Cristina_Procópio_Silva</td>
</tr>
<tr class="even">
<td align="left">160 - p2</td>
<td align="left">Side 1</td>
<td align="right">164</td>
<td align="right">315</td>
<td align="right">5.434023</td>
<td align="left">R._Cristina_Procópio_Silva</td>
</tr>
<tr class="odd">
<td align="left">210 - p1</td>
<td align="left">Side 1</td>
<td align="right">210</td>
<td align="right">45</td>
<td align="right">6.099406</td>
<td align="left">R._Cristina_Procópio_Silva</td>
</tr>
<tr class="even">
<td align="left">210 - p2</td>
<td align="left">Side 1</td>
<td align="right">214</td>
<td align="right">315</td>
<td align="right">5.728927</td>
<td align="left">R._Cristina_Procópio_Silva</td>
</tr>
<tr class="odd">
<td align="left">261 - p1</td>
<td align="left">Side 1</td>
<td align="right">264</td>
<td align="right">22</td>
<td align="right">5.213054</td>
<td align="left">R._Cristina_Procópio_Silva</td>
</tr>
<tr class="even">
<td align="left">261 - p2</td>
<td align="left">Side 1</td>
<td align="right">268</td>
<td align="right">315</td>
<td align="right">5.306152</td>
<td align="left">R._Cristina_Procópio_Silva</td>
</tr>
<tr class="odd">
<td align="left">305 - p1</td>
<td align="left">Side 1</td>
<td align="right">308</td>
<td align="right">45</td>
<td align="right">4.807596</td>
<td align="left">R._Cristina_Procópio_Silva</td>
</tr>
<tr class="even">
<td align="left">305 - p2</td>
<td align="left">Side 1</td>
<td align="right">312</td>
<td align="right">293</td>
<td align="right">5.096545</td>
<td align="left">R._Cristina_Procópio_Silva</td>
</tr>
<tr class="odd">
<td align="left">350 - p1</td>
<td align="left">Side 1</td>
<td align="right">350</td>
<td align="right">45</td>
<td align="right">5.284007</td>
<td align="left">R._Cristina_Procópio_Silva</td>
</tr>
<tr class="even">
<td align="left">350 - p2</td>
<td align="left">Side 1</td>
<td align="right">354</td>
<td align="right">315</td>
<td align="right">4.671185</td>
<td align="left">R._Cristina_Procópio_Silva</td>
</tr>
<tr class="odd">
<td align="left">390 - p1</td>
<td align="left">Side 1</td>
<td align="right">390</td>
<td align="right">45</td>
<td align="right">4.180123</td>
<td align="left">R._Cristina_Procópio_Silva</td>
</tr>
<tr class="even">
<td align="left">390 - p2</td>
<td align="left">Side 1</td>
<td align="right">394</td>
<td align="right">315</td>
<td align="right">4.066808</td>
<td align="left">R._Cristina_Procópio_Silva</td>
</tr>
<tr class="odd">
<td align="left">436 - p1</td>
<td align="left">Side 1</td>
<td align="right">436</td>
<td align="right">135</td>
<td align="right">5.363136</td>
<td align="left">R._Cristina_Procópio_Silva</td>
</tr>
<tr class="even">
<td align="left">436 - p2</td>
<td align="left">Side 1</td>
<td align="right">440</td>
<td align="right">22</td>
<td align="right">5.078572</td>
<td align="left">R._Cristina_Procópio_Silva</td>
</tr>
<tr class="odd">
<td align="left">2 - p1</td>
<td align="left">Side 2</td>
<td align="right">5</td>
<td align="right">135</td>
<td align="right">5.330287</td>
<td align="left">R._Cristina_Procópio_Silva</td>
</tr>
<tr class="even">
<td align="left">2 - p2</td>
<td align="left">Side 2</td>
<td align="right">9</td>
<td align="right">225</td>
<td align="right">5.000870</td>
<td align="left">R._Cristina_Procópio_Silva</td>
</tr>
<tr class="odd">
<td align="left">66 - p1</td>
<td align="left">Side 2</td>
<td align="right">69</td>
<td align="right">135</td>
<td align="right">4.637055</td>
<td align="left">R._Cristina_Procópio_Silva</td>
</tr>
<tr class="even">
<td align="left">66 - p2</td>
<td align="left">Side 2</td>
<td align="right">73</td>
<td align="right">225</td>
<td align="right">5.621716</td>
<td align="left">R._Cristina_Procópio_Silva</td>
</tr>
<tr class="odd">
<td align="left">105 - p1</td>
<td align="left">Side 2</td>
<td align="right">105</td>
<td align="right">135</td>
<td align="right">5.677544</td>
<td align="left">R._Cristina_Procópio_Silva</td>
</tr>
<tr class="even">
<td align="left">105 - p2</td>
<td align="left">Side 2</td>
<td align="right">109</td>
<td align="right">225</td>
<td align="right">5.637728</td>
<td align="left">R._Cristina_Procópio_Silva</td>
</tr>
<tr class="odd">
<td align="left">160 - p1</td>
<td align="left">Side 2</td>
<td align="right">163</td>
<td align="right">135</td>
<td align="right">5.715077</td>
<td align="left">R._Cristina_Procópio_Silva</td>
</tr>
<tr class="even">
<td align="left">160 - p2</td>
<td align="left">Side 2</td>
<td align="right">167</td>
<td align="right">225</td>
<td align="right">5.370386</td>
<td align="left">R._Cristina_Procópio_Silva</td>
</tr>
<tr class="odd">
<td align="left">210 - p1</td>
<td align="left">Side 2</td>
<td align="right">213</td>
<td align="right">135</td>
<td align="right">5.872188</td>
<td align="left">R._Cristina_Procópio_Silva</td>
</tr>
<tr class="even">
<td align="left">210 - p2</td>
<td align="left">Side 2</td>
<td align="right">217</td>
<td align="right">225</td>
<td align="right">5.937082</td>
<td align="left">R._Cristina_Procópio_Silva</td>
</tr>
<tr class="odd">
<td align="left">261 - p1</td>
<td align="left">Side 2</td>
<td align="right">261</td>
<td align="right">135</td>
<td align="right">4.796765</td>
<td align="left">R._Cristina_Procópio_Silva</td>
</tr>
<tr class="even">
<td align="left">261 - p2</td>
<td align="left">Side 2</td>
<td align="right">265</td>
<td align="right">225</td>
<td align="right">5.241681</td>
<td align="left">R._Cristina_Procópio_Silva</td>
</tr>
<tr class="odd">
<td align="left">305 - p1</td>
<td align="left">Side 2</td>
<td align="right">305</td>
<td align="right">135</td>
<td align="right">3.002633</td>
<td align="left">R._Cristina_Procópio_Silva</td>
</tr>
<tr class="even">
<td align="left">305 - p2</td>
<td align="left">Side 2</td>
<td align="right">309</td>
<td align="right">225</td>
<td align="right">3.771914</td>
<td align="left">R._Cristina_Procópio_Silva</td>
</tr>
<tr class="odd">
<td align="left">350 - p1</td>
<td align="left">Side 2</td>
<td align="right">353</td>
<td align="right">135</td>
<td align="right">3.862171</td>
<td align="left">R._Cristina_Procópio_Silva</td>
</tr>
<tr class="even">
<td align="left">350 - p2</td>
<td align="left">Side 2</td>
<td align="right">357</td>
<td align="right">203</td>
<td align="right">3.193076</td>
<td align="left">R._Cristina_Procópio_Silva</td>
</tr>
<tr class="odd">
<td align="left">390 - p1</td>
<td align="left">Side 2</td>
<td align="right">393</td>
<td align="right">135</td>
<td align="right">4.419806</td>
<td align="left">R._Cristina_Procópio_Silva</td>
</tr>
<tr class="even">
<td align="left">390 - p2</td>
<td align="left">Side 2</td>
<td align="right">397</td>
<td align="right">203</td>
<td align="right">4.531448</td>
<td align="left">R._Cristina_Procópio_Silva</td>
</tr>
<tr class="odd">
<td align="left">436 - p1</td>
<td align="left">Side 2</td>
<td align="right">439</td>
<td align="right">203</td>
<td align="right">4.264181</td>
<td align="left">R._Cristina_Procópio_Silva</td>
</tr>
<tr class="even">
<td align="left">436 - p2</td>
<td align="left">Side 2</td>
<td align="right">443</td>
<td align="right">315</td>
<td align="right">5.312050</td>
<td align="left">R._Cristina_Procópio_Silva</td>
</tr>
</tbody>
</table>
<p>++++++ Median all 4.80758224866 <br>++++++ Mean all 4.68814353441181 <br></p>
<table style="width:100%;">
<colgroup>
<col width="31%" />
<col width="10%" />
<col width="10%" />
<col width="12%" />
<col width="12%" />
<col width="10%" />
<col width="10%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">street</th>
<th align="right">mean</th>
<th align="right">median</th>
<th align="right">sd</th>
<th align="right">gini</th>
<th align="right">upper</th>
<th align="right">lower</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">R._Manoel_Pereira_de_Araújo</td>
<td align="right">3.672485</td>
<td align="right">3.637284</td>
<td align="right">0.1883041</td>
<td align="right">0.0276016</td>
<td align="right">3.755012</td>
<td align="right">3.589957</td>
</tr>
<tr class="even">
<td align="left">R._Edésio_Silva</td>
<td align="right">4.711095</td>
<td align="right">4.700303</td>
<td align="right">0.4719678</td>
<td align="right">0.0555839</td>
<td align="right">4.917944</td>
<td align="right">4.504246</td>
</tr>
<tr class="odd">
<td align="left">R._Inácio_Marquês_da_Silva</td>
<td align="right">4.713531</td>
<td align="right">4.859461</td>
<td align="right">0.5487980</td>
<td align="right">0.0649960</td>
<td align="right">4.954052</td>
<td align="right">4.473010</td>
</tr>
<tr class="even">
<td align="left">R._Maciel_Pinheiro</td>
<td align="right">4.777779</td>
<td align="right">4.798712</td>
<td align="right">0.2344981</td>
<td align="right">0.0273481</td>
<td align="right">4.880552</td>
<td align="right">4.675006</td>
</tr>
<tr class="odd">
<td align="left">Av._Mal._Floriano_Peixoto</td>
<td align="right">4.957391</td>
<td align="right">5.028135</td>
<td align="right">0.3305999</td>
<td align="right">0.0350720</td>
<td align="right">5.102283</td>
<td align="right">4.812499</td>
</tr>
<tr class="even">
<td align="left">R._Cristina_Procópio_Silva</td>
<td align="right">4.979669</td>
<td align="right">5.204548</td>
<td align="right">0.7201075</td>
<td align="right">0.0778490</td>
<td align="right">5.295270</td>
<td align="right">4.664068</td>
</tr>
</tbody>
</table>
<div class='row'>
<div class="col-xs-3" style="background-color:#007f00">
<img src='/home/davidcmm/workspace_doutorado/campinaPulse/scripts/analise/dadosSet17/percepcaoLocal/agradavel/piores/intersects/R._Cristina_Proc%C3%B3pio_Silva_2_45' width='300px'>
<p style="color:white;font-size:90%">
worst<br>R._Cristina_Procópio_Silva_2_45-&gt; 4.453842(-0.003669455)
</p>
</div>
<div class="col-xs-3" style="background-color:#00cc00">
<img src='/home/davidcmm/workspace_doutorado/campinaPulse/scripts/analise/dadosSet17/percepcaoLocal/agradavel/melhores/intersects/R._Cristina_Proc%C3%B3pio_Silva_2_135' width='300px'>
<p style="color:white;font-size:90%">
best<br>R._Cristina_Procópio_Silva_2_135-&gt; 5.330287(0.003132565)
</p>
</div>
<div class="col-xs-3" style="background-color:#00b200">
<img src='/home/davidcmm/workspace_doutorado/campinaPulse/scripts/analise/dadosSet17/percepcaoLocal/agradavel/piores/intersects/R._Cristina_Proc%C3%B3pio_Silva_2_225' width='300px'>
<p style="color:white;font-size:90%">
worst<br>R._Cristina_Procópio_Silva_2_225-&gt; 5.00087(0.0001387112)
</p>
</div>
<div class="col-xs-3" style="background-color:#007f00">
<img src='/home/davidcmm/workspace_doutorado/campinaPulse/scripts/analise/dadosSet17/percepcaoLocal/agradavel/piores/intersects/R._Cristina_Proc%C3%B3pio_Silva_2_293' width='300px'>
<p style="color:white;font-size:90%">
worst<br>R._Cristina_Procópio_Silva_2_293-&gt; 4.559239(-0.002804458)
</p>
</div>
<div class="col-xs-3" style="background-color:#00cc00">
<img src='/home/davidcmm/workspace_doutorado/campinaPulse/scripts/analise/dadosSet17/percepcaoLocal/agradavel/melhores/intersects/R._Cristina_Proc%C3%B3pio_Silva_66_45' width='300px'>
<p style="color:white;font-size:90%">
best<br>R._Cristina_Procópio_Silva_66_45-&gt; 5.452532(0.002815287)
</p>
</div>
<div class="col-xs-3" style="background-color:#007f00">
<img src='/home/davidcmm/workspace_doutorado/campinaPulse/scripts/analise/dadosSet17/percepcaoLocal/agradavel/piores/intersects/R._Cristina_Proc%C3%B3pio_Silva_66_135' width='300px'>
<p style="color:white;font-size:90%">
worst<br>R._Cristina_Procópio_Silva_66_135-&gt; 4.637055(-0.003528924)
</p>
</div>
<div class="col-xs-3" style="background-color:#00e500">
<img src='/home/davidcmm/workspace_doutorado/campinaPulse/scripts/analise/dadosSet17/percepcaoLocal/agradavel/melhores/intersects/R._Cristina_Proc%C3%B3pio_Silva_66_225' width='300px'>
<p style="color:white;font-size:90%">
best<br>R._Cristina_Procópio_Silva_66_225-&gt; 5.621716(0.004155726)
</p>
</div>
<div class="col-xs-3" style="background-color:#00cc00">
<img src='/home/davidcmm/workspace_doutorado/campinaPulse/scripts/analise/dadosSet17/percepcaoLocal/agradavel/melhores/intersects/R._Cristina_Proc%C3%B3pio_Silva_66_315' width='300px'>
<p style="color:white;font-size:90%">
best<br>R._Cristina_Procópio_Silva_66_315-&gt; 5.370995(0.002052528)
</p>
</div>
<div class="col-xs-3" style="background-color:#00b200">
<img src='/home/davidcmm/workspace_doutorado/campinaPulse/scripts/analise/dadosSet17/percepcaoLocal/agradavel/piores/intersects/R._Cristina_Proc%C3%B3pio_Silva_105_45' width='300px'>
<p style="color:white;font-size:90%">
worst<br>R._Cristina_Procópio_Silva_105_45-&gt; 5.196042(0.0007860624)
</p>
</div>
<div class="col-xs-3" style="background-color:#00e500">
<img src='/home/davidcmm/workspace_doutorado/campinaPulse/scripts/analise/dadosSet17/percepcaoLocal/agradavel/melhores/intersects/R._Cristina_Proc%C3%B3pio_Silva_105_135' width='300px'>
<p style="color:white;font-size:90%">
best<br>R._Cristina_Procópio_Silva_105_135-&gt; 5.677544(0.004178964)
</p>
</div>
<div class="col-xs-3" style="background-color:#00e500">
<img src='/home/davidcmm/workspace_doutorado/campinaPulse/scripts/analise/dadosSet17/percepcaoLocal/agradavel/melhores/intersects/R._Cristina_Proc%C3%B3pio_Silva_105_225' width='300px'>
<p style="color:white;font-size:90%">
best<br>R._Cristina_Procópio_Silva_105_225-&gt; 5.637728(0.003820109)
</p>
</div>
<div class="col-xs-3" style="background-color:#00b200">
<img src='/home/davidcmm/workspace_doutorado/campinaPulse/scripts/analise/dadosSet17/percepcaoLocal/agradavel/piores/intersects/R._Cristina_Proc%C3%B3pio_Silva_105_315' width='300px'>
<p style="color:white;font-size:90%">
worst<br>R._Cristina_Procópio_Silva_105_315-&gt; 5.15196(0.0004343865)
</p>
</div>
<div class="col-xs-3" style="background-color:#00cc00">
<img src='/home/davidcmm/workspace_doutorado/campinaPulse/scripts/analise/dadosSet17/percepcaoLocal/agradavel/piores/intersects/R._Cristina_Proc%C3%B3pio_Silva_160_45' width='300px'>
<p style="color:white;font-size:90%">
worst<br>R._Cristina_Procópio_Silva_160_45-&gt; 5.47695(0.002422995)
</p>
</div>
<div class="col-xs-3" style="background-color:#00e500">
<img src='/home/davidcmm/workspace_doutorado/campinaPulse/scripts/analise/dadosSet17/percepcaoLocal/agradavel/melhores/intersects/R._Cristina_Proc%C3%B3pio_Silva_160_135' width='300px'>
<p style="color:white;font-size:90%">
best<br>R._Cristina_Procópio_Silva_160_135-&gt; 5.715077(0.004219859)
</p>
</div>
<div class="col-xs-3" style="background-color:#00cc00">
<img src='/home/davidcmm/workspace_doutorado/campinaPulse/scripts/analise/dadosSet17/percepcaoLocal/agradavel/piores/intersects/R._Cristina_Proc%C3%B3pio_Silva_160_225' width='300px'>
<p style="color:white;font-size:90%">
worst<br>R._Cristina_Procópio_Silva_160_225-&gt; 5.370386(0.001788257)
</p>
</div>
<div class="col-xs-3" style="background-color:#00cc00">
<img src='/home/davidcmm/workspace_doutorado/campinaPulse/scripts/analise/dadosSet17/percepcaoLocal/agradavel/melhores/intersects/R._Cristina_Proc%C3%B3pio_Silva_160_315' width='300px'>
<p style="color:white;font-size:90%">
best<br>R._Cristina_Procópio_Silva_160_315-&gt; 5.434023(0.002181891)
</p>
</div>
<div class="col-xs-3" style="background-color:#00ff00">
<img src='/home/davidcmm/workspace_doutorado/campinaPulse/scripts/analise/dadosSet17/percepcaoLocal/agradavel/melhores/intersects/R._Cristina_Proc%C3%B3pio_Silva_210_45' width='300px'>
<p style="color:white;font-size:90%">
best<br>R._Cristina_Procópio_Silva_210_45-&gt; 6.099406(0.005912996)
</p>
</div>
<div class="col-xs-3" style="background-color:#00ff00">
<img src='/home/davidcmm/workspace_doutorado/campinaPulse/scripts/analise/dadosSet17/percepcaoLocal/agradavel/melhores/intersects/R._Cristina_Proc%C3%B3pio_Silva_210_135' width='300px'>
<p style="color:white;font-size:90%">
best<br>R._Cristina_Procópio_Silva_210_135-&gt; 5.872188(0.004457328)
</p>
</div>
<div class="col-xs-3" style="background-color:#00ff00">
<img src='/home/davidcmm/workspace_doutorado/campinaPulse/scripts/analise/dadosSet17/percepcaoLocal/agradavel/piores/intersects/R._Cristina_Proc%C3%B3pio_Silva_210_225' width='300px'>
<p style="color:white;font-size:90%">
worst<br>R._Cristina_Procópio_Silva_210_225-&gt; 5.937082(0.00475087)
</p>
</div>
<div class="col-xs-3" style="background-color:#00e500">
<img src='/home/davidcmm/workspace_doutorado/campinaPulse/scripts/analise/dadosSet17/percepcaoLocal/agradavel/piores/intersects/R._Cristina_Proc%C3%B3pio_Silva_210_315' width='300px'>
<p style="color:white;font-size:90%">
worst<br>R._Cristina_Procópio_Silva_210_315-&gt; 5.728927(0.004012253)
</p>
</div>
<div class="col-xs-3" style="background-color:#00b200">
<img src='/home/davidcmm/workspace_doutorado/campinaPulse/scripts/analise/dadosSet17/percepcaoLocal/agradavel/melhores/intersects/R._Cristina_Proc%C3%B3pio_Silva_261_22' width='300px'>
<p style="color:white;font-size:90%">
best<br>R._Cristina_Procópio_Silva_261_22-&gt; 5.213054(0.001073594)
</p>
</div>
<div class="col-xs-3" style="background-color:#009900">
<img src='/home/davidcmm/workspace_doutorado/campinaPulse/scripts/analise/dadosSet17/percepcaoLocal/agradavel/piores/intersects/R._Cristina_Proc%C3%B3pio_Silva_261_135' width='300px'>
<p style="color:white;font-size:90%">
worst<br>R._Cristina_Procópio_Silva_261_135-&gt; 4.796765(-0.001638929)
</p>
</div>
<div class="col-xs-3" style="background-color:#00b200">
<img src='/home/davidcmm/workspace_doutorado/campinaPulse/scripts/analise/dadosSet17/percepcaoLocal/agradavel/melhores/intersects/R._Cristina_Proc%C3%B3pio_Silva_261_225' width='300px'>
<p style="color:white;font-size:90%">
best<br>R._Cristina_Procópio_Silva_261_225-&gt; 5.241681(0.001305321)
</p>
</div>
<div class="col-xs-3" style="background-color:#00cc00">
<img src='/home/davidcmm/workspace_doutorado/campinaPulse/scripts/analise/dadosSet17/percepcaoLocal/agradavel/melhores/intersects/R._Cristina_Proc%C3%B3pio_Silva_261_315' width='300px'>
<p style="color:white;font-size:90%">
best<br>R._Cristina_Procópio_Silva_261_315-&gt; 5.306152(0.001906442)
</p>
</div>
<div class="col-xs-3" style="background-color:#009900">
<img src='/home/davidcmm/workspace_doutorado/campinaPulse/scripts/analise/dadosSet17/percepcaoLocal/agradavel/melhores/intersects/R._Cristina_Proc%C3%B3pio_Silva_305_45' width='300px'>
<p style="color:white;font-size:90%">
best<br>R._Cristina_Procópio_Silva_305_45-&gt; 4.807596(0.0006025217)
</p>
</div>
<div class="col-xs-3" style="background-color:#000000">
<img src='/home/davidcmm/workspace_doutorado/campinaPulse/scripts/analise/dadosSet17/percepcaoLocal/agradavel/piores/intersects/R._Cristina_Proc%C3%B3pio_Silva_305_135' width='300px'>
<p style="color:white;font-size:90%">
worst<br>R._Cristina_Procópio_Silva_305_135-&gt; 3.002633(-0.01224259)
</p>
</div>
<div class="col-xs-3" style="background-color:#003300">
<img src='/home/davidcmm/workspace_doutorado/campinaPulse/scripts/analise/dadosSet17/percepcaoLocal/agradavel/piores/intersects/R._Cristina_Proc%C3%B3pio_Silva_305_225' width='300px'>
<p style="color:white;font-size:90%">
worst<br>R._Cristina_Procópio_Silva_305_225-&gt; 3.771914(-0.006759792)
</p>
</div>
<div class="col-xs-3" style="background-color:#00b200">
<img src='/home/davidcmm/workspace_doutorado/campinaPulse/scripts/analise/dadosSet17/percepcaoLocal/agradavel/melhores/intersects/R._Cristina_Proc%C3%B3pio_Silva_305_293' width='300px'>
<p style="color:white;font-size:90%">
best<br>R._Cristina_Procópio_Silva_305_293-&gt; 5.096545(0.003428251)
</p>
</div>
<div class="col-xs-3" style="background-color:#00cc00">
<img src='/home/davidcmm/workspace_doutorado/campinaPulse/scripts/analise/dadosSet17/percepcaoLocal/agradavel/melhores/intersects/R._Cristina_Proc%C3%B3pio_Silva_350_45' width='300px'>
<p style="color:white;font-size:90%">
best<br>R._Cristina_Procópio_Silva_350_45-&gt; 5.284007(0.004633534)
</p>
</div>
<div class="col-xs-3" style="background-color:#004c00">
<img src='/home/davidcmm/workspace_doutorado/campinaPulse/scripts/analise/dadosSet17/percepcaoLocal/agradavel/piores/intersects/R._Cristina_Proc%C3%B3pio_Silva_350_135' width='300px'>
<p style="color:white;font-size:90%">
worst<br>R._Cristina_Procópio_Silva_350_135-&gt; 3.862171(-0.006346584)
</p>
</div>
<div class="col-xs-3" style="background-color:#000000">
<img src='/home/davidcmm/workspace_doutorado/campinaPulse/scripts/analise/dadosSet17/percepcaoLocal/agradavel/piores/intersects/R._Cristina_Proc%C3%B3pio_Silva_350_203' width='300px'>
<p style="color:white;font-size:90%">
worst<br>R._Cristina_Procópio_Silva_350_203-&gt; 3.193076(-0.01107737)
</p>
</div>
<div class="col-xs-3" style="background-color:#007f00">
<img src='/home/davidcmm/workspace_doutorado/campinaPulse/scripts/analise/dadosSet17/percepcaoLocal/agradavel/piores/intersects/R._Cristina_Proc%C3%B3pio_Silva_350_315' width='300px'>
<p style="color:white;font-size:90%">
worst<br>R._Cristina_Procópio_Silva_350_315-&gt; 4.671185(-0.001009932)
</p>
</div>
<div class="col-xs-3" style="background-color:#006600">
<img src='/home/davidcmm/workspace_doutorado/campinaPulse/scripts/analise/dadosSet17/percepcaoLocal/agradavel/piores/intersects/R._Cristina_Proc%C3%B3pio_Silva_390_45' width='300px'>
<p style="color:white;font-size:90%">
worst<br>R._Cristina_Procópio_Silva_390_45-&gt; 4.180123(-0.00423652)
</p>
</div>
<div class="col-xs-3" style="background-color:#007f00">
<img src='/home/davidcmm/workspace_doutorado/campinaPulse/scripts/analise/dadosSet17/percepcaoLocal/agradavel/melhores/intersects/R._Cristina_Proc%C3%B3pio_Silva_390_135' width='300px'>
<p style="color:white;font-size:90%">
best<br>R._Cristina_Procópio_Silva_390_135-&gt; 4.419806(-0.002850302)
</p>
</div>
<div class="col-xs-3" style="background-color:#007f00">
<img src='/home/davidcmm/workspace_doutorado/campinaPulse/scripts/analise/dadosSet17/percepcaoLocal/agradavel/melhores/intersects/R._Cristina_Proc%C3%B3pio_Silva_390_203' width='300px'>
<p style="color:white;font-size:90%">
best<br>R._Cristina_Procópio_Silva_390_203-&gt; 4.531448(-0.002166461)
</p>
</div>
<div class="col-xs-3" style="background-color:#004c00">
<img src='/home/davidcmm/workspace_doutorado/campinaPulse/scripts/analise/dadosSet17/percepcaoLocal/agradavel/piores/intersects/R._Cristina_Proc%C3%B3pio_Silva_390_315' width='300px'>
<p style="color:white;font-size:90%">
worst<br>R._Cristina_Procópio_Silva_390_315-&gt; 4.066808(-0.005047923)
</p>
</div>
<div class="col-xs-3" style="background-color:#00b200">
<img src='/home/davidcmm/workspace_doutorado/campinaPulse/scripts/analise/dadosSet17/percepcaoLocal/agradavel/melhores/intersects/R._Cristina_Proc%C3%B3pio_Silva_436_22' width='300px'>
<p style="color:white;font-size:90%">
best<br>R._Cristina_Procópio_Silva_436_22-&gt; 5.078572(0.0004015023)
</p>
</div>
<div class="col-xs-3" style="background-color:#00cc00">
<img src='/home/davidcmm/workspace_doutorado/campinaPulse/scripts/analise/dadosSet17/percepcaoLocal/agradavel/melhores/intersects/R._Cristina_Proc%C3%B3pio_Silva_436_135' width='300px'>
<p style="color:white;font-size:90%">
best<br>R._Cristina_Procópio_Silva_436_135-&gt; 5.363136(0.002929795)
</p>
</div>
<div class="col-xs-3" style="background-color:#006600">
<img src='/home/davidcmm/workspace_doutorado/campinaPulse/scripts/analise/dadosSet17/percepcaoLocal/agradavel/piores/intersects/R._Cristina_Proc%C3%B3pio_Silva_436_203' width='300px'>
<p style="color:white;font-size:90%">
worst<br>R._Cristina_Procópio_Silva_436_203-&gt; 4.264181(-0.005490666)
</p>
</div>
<div class="col-xs-3" style="background-color:#00cc00">
<img src='/home/davidcmm/workspace_doutorado/campinaPulse/scripts/analise/dadosSet17/percepcaoLocal/agradavel/melhores/intersects/R._Cristina_Proc%C3%B3pio_Silva_436_315' width='300px'>
<p style="color:white;font-size:90%">
best<br>R._Cristina_Procópio_Silva_436_315-&gt; 5.31205(0.00241968)
</p>
</div>
<ol style="list-style-type: decimal">
<li>Locais problemáticos na rua (olhando as fotos):
<ul>
<li>2 side1 (terreno com lixo)</li>
<li>305 side2 (lixo, pouca manutenção)</li>
<li>436 side2 203 (construção/menor manutenção)</li>
</ul></li>
<li>Virtudes na rua (olhando as fotos):
<ul>
<li>2 side2 (prédios bem mantidos, verde)</li>
<li>66 inteiro (prédios bem mantidos, verde)</li>
<li>261 inteiro (verde, prédios bem mantidos)</li>
<li>436 menos o 203 (verde, casas bem mantidas)</li>
</ul></li>
</ol>
<blockquote>
<blockquote>
<p>Olhando os Q-Scores ao longo da rua</p>
</blockquote>
</blockquote>
<ol start="2" style="list-style-type: decimal">
<li>Melhor e pior local da rua:
<ul>
<li>66-p2 side2 (melhor)</li>
<li>305-p1 side2 (pior) diferença de 2.5 -&gt; boa manutenção, verde, ruas largas x falta de manutenção, lixo</li>
</ul></li>
<li>Melhor e pior lado da rua:
<ul>
<li>O side1 parece ligeiramente melhor (2 side2, 66 empate, 261, 305, 436 side1)</li>
</ul></li>
<li>Melhor e pior área da rua (considerando os dois lados):
<ul>
<li>66 a 261 side1 (melhor)</li>
<li>305 a 436 side2 (pior) menor dif. de aprox. 2.1 -&gt; verde, boa manutenção x lixo, menor manutenção, menos verde aparente (no 436 tem um ponto bacana que tem verde e boa manutenção, o outro nem tanto)</li>
</ul></li>
<li>Áreas muito diferentes entre lados:
<ul>
<li>305 a 436 menor diferenca de aprox. 1 -&gt; boa manutenção, verde x lixo, pouca manutenção, menos verde aparente (no 436 tem um ponto bacana que tem verde e boa manutenção, o outro nem tanto)</li>
</ul></li>
<li>Descontinuidades no mesmo lado
<ul>
<li>66 side2 dif de 0.8 -&gt; manutenção e verde aparente</li>
<li>305 side2 dif de 0.8 -&gt; no meio da falta de manutenção, lixo a segunda imagem tem um prédio melhor conservado</li>
<li>305 side1 dif. de 0.45 -&gt; mais prédios mais conservados</li>
<li>436 side2 dif. de 1.3 -&gt; mais verde aparente, construção/manutenção</li>
</ul></li>
<li>Heterogeneidade/Homogeneidade no ponto:
<ul>
<li>os pontos mais heterogêneros foram o 305 (lixo, falta de manutenção) e 436 (falta de manuteção, verde aparente).</li>
<li>o mais homogêneo foi o 261 que é um ponto bem mantido e com verde</li>
</ul></li>
<li>Foram encontrados os problemas?
<ul>
<li>Dois (305 e 436) dos três pontos foram encontrados. Tanto no número 305 como no 436, dentre os pontos avaliados, pôde-se perceber locais que necessitam de melhoria na rua.</li>
<li>O ponto 2 seria encontrado se seguissemos a lista de heterogeneidade (2 mais homogeneo) ou se avaliassemos diferenças entre os dois lados por ponto (complicado em vários casos).</li>
<li>Além disso, no ponto 66 sugere-se uma melhoria com um pouco mais de verde de modo a homogenizar ainda mais o ponto.</li>
</ul></li>
<li>O que é a rua?
<ul>
<li>A nota média/mediana é boa ou ruim? De mediana para boa</li>
<li>Existe muita variação? Variações de locais melhores e piores ao longo de toda a rua, alguns números com grande variação no local</li>
<li>Existe um lado melhor? No final da rua side1 parece despertar maiores preferências que o outro lado. Média e mediana de side1 melhores</li>
<li>Existe uma área melhor pior? Conforme questão 4 do número 66 ao 261 parece termos a melhor área da rua e do número 305 ao 436 a pior área.</li>
</ul></li>
</ol>
<blockquote>
<blockquote>
<p>Olhando o surprise maps (uniforme + base rate + normal)</p>
</blockquote>
</blockquote>
<ol style="list-style-type: decimal">
<li>Máximo e Mínimo?
<ul>
<li>66 p2 side2</li>
<li>305 p1 side2 diferença de 2.5 -&gt; boa manutenção, verde, ruas largas x falta de manutenção, lixo</li>
</ul></li>
<li>Mais diversidade?</li>
</ol>
<ul>
<li>305, 2 lados separados: verde, manutenção x lixo, muro acabado</li>
<li>436, 1 estranho: verde, manutenção x construção, menor manutenção, problema na pista, lixo</li>
<li>66, 1 estranho: verde, prédios bem mantidos x verde menos destacado, manutenção</li>
<li>261, pontos do mesmo lado separados, 135 pior: verde, boa manutenção x lixo, árvores pequenas, poste, muro cego</li>
<li>2, 2 lados separados, mas 45 mais próximo ao side2 e 293 pior: verde, prédios mantidos x terreno, lixo</li>
</ul>
<ol start="3" style="list-style-type: decimal">
<li>Menor diversidade?</li>
</ol>
<ul>
<li>2 e 261 como mais homogêneos, mas ainda com dispersão</li>
</ul>
<ol start="4" style="list-style-type: decimal">
<li>Diferenças/saltos no lado?</li>
</ol>
<ul>
<li>2, side1 separado</li>
<li>66, side2 -&gt; recaem nos pontos acima</li>
<li>261, side1 e side2 separados</li>
<li>305, side1 melhor que side2 e cada side separados internamente</li>
<li>436, side2 mais separado que side1</li>
</ul>
<ol start="5" style="list-style-type: decimal">
<li>Avaliação Problemas (minha opinião)</li>
</ol>
<ul>
<li>Pesquisador: 3 problemas (descritos acima)</li>
<li>Recall = método / pesquisador = 3/3 = 1</li>
<li>Precisão = reais / método = 4/5 = 0.8 (menos o 66 1 estranho)</li>
</ul>
<ol start="6" style="list-style-type: decimal">
<li>Avaliação Virtudes (minha opinião)</li>
</ol>
<ul>
<li>Pesquisador: 4 virtudes (descritos acima)</li>
<li>Recall = método / pesquisador = 4/4 = 1</li>
<li>Precisão = reais / método = 4/5 = 0.75 (menos o 305 2 lados separdos)</li>
</ul>
<ol start="7" style="list-style-type: decimal">
<li>Descrição</li>
</ol>
<ul>
<li>Média/mediana: 4.92/5.12 &gt; 4.68/4.82 -&gt; rua de mediana para boa</li>
<li>Variação no surprise? Variações ao longo da rua, alternando locais legais e não tão legais</li>
<li>Lado melhor? Side1 (8) x Side2 (5)</li>
<li>Região melhor? não fica claro no surprise, mas <strong>nos scores pode-se falar do 66 ao 261</strong></li>
</ul>
</div>
<div id="edesio-silva" class="section level1">
<h1>Edésio Silva</h1>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  edesio$qscore
## W = 0.95255, p-value = 0.4075</code></pre>
<pre><code>##       mean          sd    
##   4.71109467   0.46001726 
##  (0.10286299) (0.07273512)</code></pre>
<pre><code>## [1] &quot;&gt;&gt;&gt; GINI da rua:  0.0555838608882523&quot;</code></pre>
<pre><code>##    num      value
## 1   70 0.07275862
## 2  602 0.04218876
## 3 1136 0.03252513
## 4  306 0.02503933
## 5 1546 0.01146904</code></pre>
<pre><code>##    num value
## 1   70   NaN
## 2  306   NaN
## 3  602   NaN
## 4 1136   NaN
## 5 1546   NaN</code></pre>
<pre><code>##    num value
## 1   70   NaN
## 2  306   NaN
## 3  602   NaN
## 4 1136   NaN
## 5 1546   NaN</code></pre>
<pre><code>## Adding missing grouping variables: `num`</code></pre>
<p><img src="analisaPorRua2_files/figure-html/unnamed-chunk-6-1.png" width="1152"  /></p>
<table>
<thead>
<tr class="header">
<th align="left">xlabel</th>
<th align="left">side</th>
<th align="right">num</th>
<th align="right">angle</th>
<th align="right">V3</th>
<th align="left">street</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">70 - p1</td>
<td align="left">Side 1</td>
<td align="right">70</td>
<td align="right">135</td>
<td align="right">3.806808</td>
<td align="left">R._Edésio_Silva</td>
</tr>
<tr class="even">
<td align="left">70 - p2</td>
<td align="left">Side 1</td>
<td align="right">74</td>
<td align="right">22</td>
<td align="right">5.390646</td>
<td align="left">R._Edésio_Silva</td>
</tr>
<tr class="odd">
<td align="left">306 - p1</td>
<td align="left">Side 1</td>
<td align="right">306</td>
<td align="right">135</td>
<td align="right">4.672172</td>
<td align="left">R._Edésio_Silva</td>
</tr>
<tr class="even">
<td align="left">306 - p2</td>
<td align="left">Side 1</td>
<td align="right">310</td>
<td align="right">22</td>
<td align="right">4.890795</td>
<td align="left">R._Edésio_Silva</td>
</tr>
<tr class="odd">
<td align="left">602 - p1</td>
<td align="left">Side 1</td>
<td align="right">602</td>
<td align="right">135</td>
<td align="right">4.722831</td>
<td align="left">R._Edésio_Silva</td>
</tr>
<tr class="even">
<td align="left">602 - p2</td>
<td align="left">Side 1</td>
<td align="right">606</td>
<td align="right">22</td>
<td align="right">4.929043</td>
<td align="left">R._Edésio_Silva</td>
</tr>
<tr class="odd">
<td align="left">1136 - p1</td>
<td align="left">Side 1</td>
<td align="right">1136</td>
<td align="right">135</td>
<td align="right">4.585656</td>
<td align="left">R._Edésio_Silva</td>
</tr>
<tr class="even">
<td align="left">1136 - p2</td>
<td align="left">Side 1</td>
<td align="right">1140</td>
<td align="right">22</td>
<td align="right">4.079527</td>
<td align="left">R._Edésio_Silva</td>
</tr>
<tr class="odd">
<td align="left">1546 - p1</td>
<td align="left">Side 1</td>
<td align="right">1546</td>
<td align="right">135</td>
<td align="right">5.228232</td>
<td align="left">R._Edésio_Silva</td>
</tr>
<tr class="even">
<td align="left">1546 - p2</td>
<td align="left">Side 1</td>
<td align="right">1550</td>
<td align="right">22</td>
<td align="right">4.976108</td>
<td align="left">R._Edésio_Silva</td>
</tr>
<tr class="odd">
<td align="left">70 - p1</td>
<td align="left">Side 2</td>
<td align="right">73</td>
<td align="right">203</td>
<td align="right">4.375526</td>
<td align="left">R._Edésio_Silva</td>
</tr>
<tr class="even">
<td align="left">70 - p2</td>
<td align="left">Side 2</td>
<td align="right">77</td>
<td align="right">315</td>
<td align="right">4.009834</td>
<td align="left">R._Edésio_Silva</td>
</tr>
<tr class="odd">
<td align="left">306 - p1</td>
<td align="left">Side 2</td>
<td align="right">309</td>
<td align="right">203</td>
<td align="right">5.232028</td>
<td align="left">R._Edésio_Silva</td>
</tr>
<tr class="even">
<td align="left">306 - p2</td>
<td align="left">Side 2</td>
<td align="right">313</td>
<td align="right">315</td>
<td align="right">4.655531</td>
<td align="left">R._Edésio_Silva</td>
</tr>
<tr class="odd">
<td align="left">602 - p1</td>
<td align="left">Side 2</td>
<td align="right">605</td>
<td align="right">203</td>
<td align="right">4.323727</td>
<td align="left">R._Edésio_Silva</td>
</tr>
<tr class="even">
<td align="left">602 - p2</td>
<td align="left">Side 2</td>
<td align="right">609</td>
<td align="right">315</td>
<td align="right">5.341616</td>
<td align="left">R._Edésio_Silva</td>
</tr>
<tr class="odd">
<td align="left">1136 - p1</td>
<td align="left">Side 2</td>
<td align="right">1139</td>
<td align="right">203</td>
<td align="right">4.109785</td>
<td align="left">R._Edésio_Silva</td>
</tr>
<tr class="even">
<td align="left">1136 - p2</td>
<td align="left">Side 2</td>
<td align="right">1143</td>
<td align="right">315</td>
<td align="right">4.677774</td>
<td align="left">R._Edésio_Silva</td>
</tr>
<tr class="odd">
<td align="left">1546 - p1</td>
<td align="left">Side 2</td>
<td align="right">1549</td>
<td align="right">203</td>
<td align="right">5.016951</td>
<td align="left">R._Edésio_Silva</td>
</tr>
<tr class="even">
<td align="left">1546 - p2</td>
<td align="left">Side 2</td>
<td align="right">1553</td>
<td align="right">315</td>
<td align="right">5.197303</td>
<td align="left">R._Edésio_Silva</td>
</tr>
</tbody>
</table>
<p>++++++ Median all 4.80758224866 <br>++++++ Mean all 4.68814353441181 <br></p>
<table style="width:100%;">
<colgroup>
<col width="31%" />
<col width="10%" />
<col width="10%" />
<col width="12%" />
<col width="12%" />
<col width="10%" />
<col width="10%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">street</th>
<th align="right">mean</th>
<th align="right">median</th>
<th align="right">sd</th>
<th align="right">gini</th>
<th align="right">upper</th>
<th align="right">lower</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">R._Manoel_Pereira_de_Araújo</td>
<td align="right">3.672485</td>
<td align="right">3.637284</td>
<td align="right">0.1883041</td>
<td align="right">0.0276016</td>
<td align="right">3.755012</td>
<td align="right">3.589957</td>
</tr>
<tr class="even">
<td align="left">R._Edésio_Silva</td>
<td align="right">4.711095</td>
<td align="right">4.700303</td>
<td align="right">0.4719678</td>
<td align="right">0.0555839</td>
<td align="right">4.917944</td>
<td align="right">4.504246</td>
</tr>
<tr class="odd">
<td align="left">R._Inácio_Marquês_da_Silva</td>
<td align="right">4.713531</td>
<td align="right">4.859461</td>
<td align="right">0.5487980</td>
<td align="right">0.0649960</td>
<td align="right">4.954052</td>
<td align="right">4.473010</td>
</tr>
<tr class="even">
<td align="left">R._Maciel_Pinheiro</td>
<td align="right">4.777779</td>
<td align="right">4.798712</td>
<td align="right">0.2344981</td>
<td align="right">0.0273481</td>
<td align="right">4.880552</td>
<td align="right">4.675006</td>
</tr>
<tr class="odd">
<td align="left">Av._Mal._Floriano_Peixoto</td>
<td align="right">4.957391</td>
<td align="right">5.028135</td>
<td align="right">0.3305999</td>
<td align="right">0.0350720</td>
<td align="right">5.102283</td>
<td align="right">4.812499</td>
</tr>
<tr class="even">
<td align="left">R._Cristina_Procópio_Silva</td>
<td align="right">4.979669</td>
<td align="right">5.204548</td>
<td align="right">0.7201075</td>
<td align="right">0.0778490</td>
<td align="right">5.295270</td>
<td align="right">4.664068</td>
</tr>
</tbody>
</table>
<div class='row'>
<div class="col-xs-3" style="background-color:#00cc00">
<img src='/home/davidcmm/workspace_doutorado/campinaPulse/scripts/analise/dadosSet17/percepcaoLocal/agradavel/melhores/intersects/R._Ed%C3%A9sio_Silva_70_22' width='300px'>
<p style="color:white;font-size:90%">
best<br>R._Edésio_Silva_70_22-&gt; 5.390646(0.01212149)
</p>
</div>
<div class="col-xs-3" style="background-color:#003300">
<img src='/home/davidcmm/workspace_doutorado/campinaPulse/scripts/analise/dadosSet17/percepcaoLocal/agradavel/piores/intersects/R._Ed%C3%A9sio_Silva_70_135' width='300px'>
<p style="color:white;font-size:90%">
worst<br>R._Edésio_Silva_70_135-&gt; 3.806809(-0.01223032)
</p>
</div>
<div class="col-xs-3" style="background-color:#006600">
<img src='/home/davidcmm/workspace_doutorado/campinaPulse/scripts/analise/dadosSet17/percepcaoLocal/agradavel/piores/intersects/R._Ed%C3%A9sio_Silva_70_203' width='300px'>
<p style="color:white;font-size:90%">
worst<br>R._Edésio_Silva_70_203-&gt; 4.375526(-0.003529989)
</p>
</div>
<div class="col-xs-3" style="background-color:#004c00">
<img src='/home/davidcmm/workspace_doutorado/campinaPulse/scripts/analise/dadosSet17/percepcaoLocal/agradavel/piores/intersects/R._Ed%C3%A9sio_Silva_70_315' width='300px'>
<p style="color:white;font-size:90%">
worst<br>R._Edésio_Silva_70_315-&gt; 4.009834(-0.009215043)
</p>
</div>
<div class="col-xs-3" style="background-color:#009900">
<img src='/home/davidcmm/workspace_doutorado/campinaPulse/scripts/analise/dadosSet17/percepcaoLocal/agradavel/piores/intersects/R._Ed%C3%A9sio_Silva_306_22' width='300px'>
<p style="color:white;font-size:90%">
worst<br>R._Edésio_Silva_306_22-&gt; 4.890795(0.001698643)
</p>
</div>
<div class="col-xs-3" style="background-color:#007f00">
<img src='/home/davidcmm/workspace_doutorado/campinaPulse/scripts/analise/dadosSet17/percepcaoLocal/agradavel/piores/intersects/R._Ed%C3%A9sio_Silva_306_135' width='300px'>
<p style="color:white;font-size:90%">
worst<br>R._Edésio_Silva_306_135-&gt; 4.672172(-0.0009342731)
</p>
</div>
<div class="col-xs-3" style="background-color:#00b200">
<img src='/home/davidcmm/workspace_doutorado/campinaPulse/scripts/analise/dadosSet17/percepcaoLocal/agradavel/melhores/intersects/R._Ed%C3%A9sio_Silva_306_203' width='300px'>
<p style="color:white;font-size:90%">
best<br>R._Edésio_Silva_306_203-&gt; 5.232028(0.007421607)
</p>
</div>
<div class="col-xs-3" style="background-color:#007f00">
<img src='/home/davidcmm/workspace_doutorado/campinaPulse/scripts/analise/dadosSet17/percepcaoLocal/agradavel/piores/intersects/R._Ed%C3%A9sio_Silva_306_315' width='300px'>
<p style="color:white;font-size:90%">
worst<br>R._Edésio_Silva_306_315-&gt; 4.655531(-0.001188314)
</p>
</div>
<div class="col-xs-3" style="background-color:#009900">
<img src='/home/davidcmm/workspace_doutorado/campinaPulse/scripts/analise/dadosSet17/percepcaoLocal/agradavel/melhores/intersects/R._Ed%C3%A9sio_Silva_602_22' width='300px'>
<p style="color:white;font-size:90%">
best<br>R._Edésio_Silva_602_22-&gt; 4.929043(0.002661208)
</p>
</div>
<div class="col-xs-3" style="background-color:#009900">
<img src='/home/davidcmm/workspace_doutorado/campinaPulse/scripts/analise/dadosSet17/percepcaoLocal/agradavel/melhores/intersects/R._Ed%C3%A9sio_Silva_602_135' width='300px'>
<p style="color:white;font-size:90%">
best<br>R._Edésio_Silva_602_135-&gt; 4.722831(-6.831614e-05)
</p>
</div>
<div class="col-xs-3" style="background-color:#006600">
<img src='/home/davidcmm/workspace_doutorado/campinaPulse/scripts/analise/dadosSet17/percepcaoLocal/agradavel/piores/intersects/R._Ed%C3%A9sio_Silva_602_203' width='300px'>
<p style="color:white;font-size:90%">
worst<br>R._Edésio_Silva_602_203-&gt; 4.323727(-0.006987583)
</p>
</div>
<div class="col-xs-3" style="background-color:#00cc00">
<img src='/home/davidcmm/workspace_doutorado/campinaPulse/scripts/analise/dadosSet17/percepcaoLocal/agradavel/melhores/intersects/R._Ed%C3%A9sio_Silva_602_315' width='300px'>
<p style="color:white;font-size:90%">
best<br>R._Edésio_Silva_602_315-&gt; 5.341616(0.009184468)
</p>
</div>
<div class="col-xs-3" style="background-color:#004c00">
<img src='/home/davidcmm/workspace_doutorado/campinaPulse/scripts/analise/dadosSet17/percepcaoLocal/agradavel/piores/intersects/R._Ed%C3%A9sio_Silva_1136_22' width='300px'>
<p style="color:white;font-size:90%">
worst<br>R._Edésio_Silva_1136_22-&gt; 4.079527(-0.008007843)
</p>
</div>
<div class="col-xs-3" style="background-color:#007f00">
<img src='/home/davidcmm/workspace_doutorado/campinaPulse/scripts/analise/dadosSet17/percepcaoLocal/agradavel/melhores/intersects/R._Ed%C3%A9sio_Silva_1136_135' width='300px'>
<p style="color:white;font-size:90%">
best<br>R._Edésio_Silva_1136_135-&gt; 4.585656(-0.0006232917)
</p>
</div>
<div class="col-xs-3" style="background-color:#004c00">
<img src='/home/davidcmm/workspace_doutorado/campinaPulse/scripts/analise/dadosSet17/percepcaoLocal/agradavel/piores/intersects/R._Ed%C3%A9sio_Silva_1136_203' width='300px'>
<p style="color:white;font-size:90%">
worst<br>R._Edésio_Silva_1136_203-&gt; 4.109785(-0.007558915)
</p>
</div>
<div class="col-xs-3" style="background-color:#007f00">
<img src='/home/davidcmm/workspace_doutorado/campinaPulse/scripts/analise/dadosSet17/percepcaoLocal/agradavel/melhores/intersects/R._Ed%C3%A9sio_Silva_1136_315' width='300px'>
<p style="color:white;font-size:90%">
best<br>R._Edésio_Silva_1136_315-&gt; 4.677774(0.001050442)
</p>
</div>
<div class="col-xs-3" style="background-color:#00b200">
<img src='/home/davidcmm/workspace_doutorado/campinaPulse/scripts/analise/dadosSet17/percepcaoLocal/agradavel/piores/intersects/R._Ed%C3%A9sio_Silva_1546_22' width='300px'>
<p style="color:white;font-size:90%">
worst<br>R._Edésio_Silva_1546_22-&gt; 4.976108(0.002595757)
</p>
</div>
<div class="col-xs-3" style="background-color:#00b200">
<img src='/home/davidcmm/workspace_doutorado/campinaPulse/scripts/analise/dadosSet17/percepcaoLocal/agradavel/melhores/intersects/R._Ed%C3%A9sio_Silva_1546_135' width='300px'>
<p style="color:white;font-size:90%">
best<br>R._Edésio_Silva_1546_135-&gt; 5.228233(0.006073802)
</p>
</div>
<div class="col-xs-3" style="background-color:#00b200">
<img src='/home/davidcmm/workspace_doutorado/campinaPulse/scripts/analise/dadosSet17/percepcaoLocal/agradavel/piores/intersects/R._Ed%C3%A9sio_Silva_1546_203' width='300px'>
<p style="color:white;font-size:90%">
worst<br>R._Edésio_Silva_1546_203-&gt; 5.016951(0.003133517)
</p>
</div>
<div class="col-xs-3" style="background-color:#00b200">
<img src='/home/davidcmm/workspace_doutorado/campinaPulse/scripts/analise/dadosSet17/percepcaoLocal/agradavel/melhores/intersects/R._Ed%C3%A9sio_Silva_1546_315' width='300px'>
<p style="color:white;font-size:90%">
best<br>R._Edésio_Silva_1546_315-&gt; 5.197303(0.005602079)
</p>
</div>
<ol style="list-style-type: decimal">
<li>Locais problemáticos na rua (olhando as fotos):
<ul>
<li>70 side1 135 (construção, menor manutenção, lixo) e side2 315 (menor manutenção), 203 (um pouco de lixo e menor manutenção);</li>
<li>602 side 203 (terreno com muito lixo);</li>
<li>1136 todos os lados (pouca manutenção, lixo, terrenos);</li>
</ul></li>
<li>Virtudes na rua (olhando as fotos):
<ul>
<li>70 22 (verde, casas bem mantidas)</li>
<li>306 menos o 315 (verde, casas bem mantidas)</li>
<li>602 22 e 315 (verde, casas bem mantidas)</li>
<li>1546 todo (casas bem mantidas, verde)</li>
</ul></li>
</ol>
<blockquote>
<blockquote>
<p>Olhando os Q-Scores ao longo da rua</p>
</blockquote>
</blockquote>
<ol start="2" style="list-style-type: decimal">
<li>Melhor e pior local da rua:
<ul>
<li>602 p2 side2</li>
<li>70 p1 side1. Dif de 1.6 -&gt; boa manutenção, algum verde x construção, pouca manutenção, sem verde</li>
</ul></li>
<li>Melhor e pior lado da rua:
<ul>
<li>Não fica claro</li>
</ul></li>
<li>Melhor e pior área da rua (considerando os dois lados):
<ul>
<li>confuso, não dá pra discernir facilmente</li>
</ul></li>
<li>Áreas muito diferentes entre lados:
<ul>
<li>70 a 306 melhora em side2 e piora em side1
<ul>
<li>No side1 temos um ponto muito bom (70, 22) que foge do padrão de melhoria que sairia de pouca manutenção e falta de áŕvore para melhor manutenção e mais árvores.</li>
<li>No side2 temos uma certa melhoria de manutenção + árvores aparentes</li>
</ul></li>
</ul></li>
<li>Descontinuidades no mesmo lado
<ul>
<li>70 no side1, diferença de 1.55 -&gt; construção, falta de verde x melhor manutenção, verde</li>
<li>602 no side1, diferença de 0.6 -&gt; falta de manutenção, menos verde aparente x melhor manutenção, verde</li>
<li>602 no side2, diferença de 1.15 -&gt; manutenção, verde x lixão</li>
<li>1136 no side2, diferença de 0.6 -&gt; lixão</li>
</ul></li>
<li>Heterogeneidade/Homogeneidade no ponto:
<ul>
<li>os pontos mais heterogêneos foram o 70 (construção, menor manutenção x melhor manutenção e algum verde) e 602 (menor manutenção, lixão x melhor manutenção, verde)</li>
<li>o ponto mais homogêneo foi o 1546, é bem mantido e com alguma vegetação.</li>
</ul></li>
<li>Foram encontrados os problemas?
<ul>
<li>O número 1136 no side1 não foi apontado dentre os 5 problemas levantados.</li>
<li>O 1136 seria encontrado (diferença de 0.45) se continuássemos olhando as descontinuidades no mesmo lado da rua ou as piores notas (2 pior nota)</li>
</ul></li>
<li>O que é a rua?
<ul>
<li>A nota média/mediana é boa ou ruim? De mediana para boa</li>
<li>Existe muita variação? Variações de locais melhores e piores ao longo de toda a rua, alguns números com grande variação no local</li>
<li>Existe um lado melhor? Não</li>
<li>Existe uma área melhor pior? Não</li>
</ul></li>
</ol>
<blockquote>
<blockquote>
<p>Olhando o surprise maps (uniforme + base rate + normal)</p>
</blockquote>
</blockquote>
<ol style="list-style-type: decimal">
<li>Máximo e Mínimo?
<ul>
<li>70 p2 side1</li>
<li>70 p1 side1. Dif de 1.6 -&gt; boa manutenção, algum verde x construção, pouca manutenção, sem verde</li>
</ul></li>
<li>Mais diversidade?</li>
</ol>
<ul>
<li>70, 22 estranho: casa bem mantida, verde x construção, casas mal mantidas, casas mais simples, carro</li>
<li>602, um ponto de cada side separado: casas bem mantidas, verde x terreno, muro mal mantido</li>
<li>1136, um ponto de cada side separado: casa melhor mantida, verde x terreno, casas muito mal mantidas</li>
<li>306, 203 estranho positivamente: casas bem mantidas, árvores</li>
</ul>
<ol start="3" style="list-style-type: decimal">
<li>Menor diversidade?</li>
</ol>
<ul>
<li>1546, mais homogêneo e positivo</li>
</ul>
<ol start="4" style="list-style-type: decimal">
<li>Diferenças/saltos no lado?</li>
</ol>
<ul>
<li>70, side1 mais separado que side2</li>
<li>306, side2 mais separado que side1</li>
<li>602, um ponto de cada side separado</li>
<li>1136, um ponto de cada side separado</li>
</ul>
<ol start="5" style="list-style-type: decimal">
<li>Avaliação Problemas</li>
</ol>
<ul>
<li>Pesquisador: 3 problemas (descritos acima)</li>
<li>Recall = método / pesquisador = 2.5/3 = 0.833 (dois de 4 problemas faltando no 1136)</li>
<li>Precisão = reais / método = 3/5 = 0.6 (1546 tem problema? 306 nao foi percebido) 6 Avaliação Virtudes</li>
<li>Pesquisador: 4 virtudes (descritos acima)</li>
<li>Recall = método / pesquisador = 3.75/4 = 0.93 (1 ponto do 1546 ficou como estranho negativo)</li>
<li>Precisão = reais / método = 4/5 = 0.75 (menos o 1136)</li>
</ul>
<ol start="7" style="list-style-type: decimal">
<li>Descrição</li>
</ol>
<ul>
<li>Média/mediana: 4.77/4.82 &gt; 4.68/4.82 -&gt; rua de mediana para boa</li>
<li>Variação no surprise? Variações ao longo da rua, alternando locais legais e não tão legais</li>
<li>Lado melhor? Não fica tão claro, Side1 (5) x Side2 (6)</li>
<li>Região melhor? não fica claro nem no surprise e nem nos scores</li>
</ul>
</div>
<div id="inacio-marques" class="section level1">
<h1>Inácio Marques</h1>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  inacio$qscore
## W = 0.95932, p-value = 0.1588</code></pre>
<pre><code>##       mean          sd    
##   4.71353096   0.54189458 
##  (0.08568106) (0.06058566)</code></pre>
<pre><code>## [1] &quot;&gt;&gt;&gt; GINI da rua:  0.0649959619143621&quot;</code></pre>
<pre><code>##    num       value
## 1  120 0.058672318
## 2   54 0.058459356
## 3  434 0.056168171
## 4    2 0.051918138
## 5  199 0.029666522
## 6  360 0.024122901
## 7  500 0.016683395
## 8  239 0.012540129
## 9  160 0.009720794
## 10 300 0.007573856</code></pre>
<pre><code>##    num value
## 1    2   NaN
## 2   54   NaN
## 3  120   NaN
## 4  160   NaN
## 5  199   NaN
## 6  239   NaN
## 7  300   NaN
## 8  360   NaN
## 9  434   NaN
## 10 500   NaN</code></pre>
<pre><code>##    num value
## 1    2   NaN
## 2   54   NaN
## 3  120   NaN
## 4  160   NaN
## 5  199   NaN
## 6  239   NaN
## 7  300   NaN
## 8  360   NaN
## 9  434   NaN
## 10 500   NaN</code></pre>
<pre><code>## Adding missing grouping variables: `num`</code></pre>
<p><img src="analisaPorRua2_files/figure-html/unnamed-chunk-8-1.png" width="1152"  /></p>
<table>
<thead>
<tr class="header">
<th align="left">xlabel</th>
<th align="left">side</th>
<th align="right">num</th>
<th align="right">angle</th>
<th align="right">V3</th>
<th align="left">street</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">2 - p1</td>
<td align="left">Side 1</td>
<td align="right">2</td>
<td align="right">112</td>
<td align="right">4.191532</td>
<td align="left">R._Inácio_Marquês_da_Silva</td>
</tr>
<tr class="even">
<td align="left">2 - p2</td>
<td align="left">Side 1</td>
<td align="right">6</td>
<td align="right">203</td>
<td align="right">4.507195</td>
<td align="left">R._Inácio_Marquês_da_Silva</td>
</tr>
<tr class="odd">
<td align="left">54 - p1</td>
<td align="left">Side 1</td>
<td align="right">54</td>
<td align="right">112</td>
<td align="right">4.988591</td>
<td align="left">R._Inácio_Marquês_da_Silva</td>
</tr>
<tr class="even">
<td align="left">54 - p2</td>
<td align="left">Side 1</td>
<td align="right">58</td>
<td align="right">203</td>
<td align="right">4.324356</td>
<td align="left">R._Inácio_Marquês_da_Silva</td>
</tr>
<tr class="odd">
<td align="left">120 - p1</td>
<td align="left">Side 1</td>
<td align="right">120</td>
<td align="right">112</td>
<td align="right">5.132631</td>
<td align="left">R._Inácio_Marquês_da_Silva</td>
</tr>
<tr class="even">
<td align="left">120 - p2</td>
<td align="left">Side 1</td>
<td align="right">124</td>
<td align="right">203</td>
<td align="right">3.942704</td>
<td align="left">R._Inácio_Marquês_da_Silva</td>
</tr>
<tr class="odd">
<td align="left">160 - p1</td>
<td align="left">Side 1</td>
<td align="right">160</td>
<td align="right">112</td>
<td align="right">4.852780</td>
<td align="left">R._Inácio_Marquês_da_Silva</td>
</tr>
<tr class="even">
<td align="left">160 - p2</td>
<td align="left">Side 1</td>
<td align="right">164</td>
<td align="right">203</td>
<td align="right">4.621917</td>
<td align="left">R._Inácio_Marquês_da_Silva</td>
</tr>
<tr class="odd">
<td align="left">199 - p1</td>
<td align="left">Side 1</td>
<td align="right">202</td>
<td align="right">112</td>
<td align="right">5.784865</td>
<td align="left">R._Inácio_Marquês_da_Silva</td>
</tr>
<tr class="even">
<td align="left">199 - p2</td>
<td align="left">Side 1</td>
<td align="right">206</td>
<td align="right">180</td>
<td align="right">5.192919</td>
<td align="left">R._Inácio_Marquês_da_Silva</td>
</tr>
<tr class="odd">
<td align="left">239 - p1</td>
<td align="left">Side 1</td>
<td align="right">242</td>
<td align="right">90</td>
<td align="right">5.145902</td>
<td align="left">R._Inácio_Marquês_da_Silva</td>
</tr>
<tr class="even">
<td align="left">239 - p2</td>
<td align="left">Side 1</td>
<td align="right">246</td>
<td align="right">203</td>
<td align="right">5.135271</td>
<td align="left">R._Inácio_Marquês_da_Silva</td>
</tr>
<tr class="odd">
<td align="left">300 - p1</td>
<td align="left">Side 1</td>
<td align="right">300</td>
<td align="right">112</td>
<td align="right">4.866142</td>
<td align="left">R._Inácio_Marquês_da_Silva</td>
</tr>
<tr class="even">
<td align="left">300 - p2</td>
<td align="left">Side 1</td>
<td align="right">304</td>
<td align="right">180</td>
<td align="right">5.045754</td>
<td align="left">R._Inácio_Marquês_da_Silva</td>
</tr>
<tr class="odd">
<td align="left">360 - p1</td>
<td align="left">Side 1</td>
<td align="right">360</td>
<td align="right">90</td>
<td align="right">4.667856</td>
<td align="left">R._Inácio_Marquês_da_Silva</td>
</tr>
<tr class="even">
<td align="left">360 - p2</td>
<td align="left">Side 1</td>
<td align="right">364</td>
<td align="right">203</td>
<td align="right">4.736766</td>
<td align="left">R._Inácio_Marquês_da_Silva</td>
</tr>
<tr class="odd">
<td align="left">434 - p1</td>
<td align="left">Side 1</td>
<td align="right">434</td>
<td align="right">112</td>
<td align="right">4.959634</td>
<td align="left">R._Inácio_Marquês_da_Silva</td>
</tr>
<tr class="even">
<td align="left">434 - p2</td>
<td align="left">Side 1</td>
<td align="right">438</td>
<td align="right">180</td>
<td align="right">4.016052</td>
<td align="left">R._Inácio_Marquês_da_Silva</td>
</tr>
<tr class="odd">
<td align="left">500 - p1</td>
<td align="left">Side 1</td>
<td align="right">500</td>
<td align="right">90</td>
<td align="right">4.416113</td>
<td align="left">R._Inácio_Marquês_da_Silva</td>
</tr>
<tr class="even">
<td align="left">500 - p2</td>
<td align="left">Side 1</td>
<td align="right">504</td>
<td align="right">203</td>
<td align="right">4.138628</td>
<td align="left">R._Inácio_Marquês_da_Silva</td>
</tr>
<tr class="odd">
<td align="left">2 - p1</td>
<td align="left">Side 2</td>
<td align="right">5</td>
<td align="right">22</td>
<td align="right">3.598719</td>
<td align="left">R._Inácio_Marquês_da_Silva</td>
</tr>
<tr class="even">
<td align="left">2 - p2</td>
<td align="left">Side 2</td>
<td align="right">9</td>
<td align="right">293</td>
<td align="right">3.612833</td>
<td align="left">R._Inácio_Marquês_da_Silva</td>
</tr>
<tr class="odd">
<td align="left">54 - p1</td>
<td align="left">Side 2</td>
<td align="right">57</td>
<td align="right">22</td>
<td align="right">5.086038</td>
<td align="left">R._Inácio_Marquês_da_Silva</td>
</tr>
<tr class="even">
<td align="left">54 - p2</td>
<td align="left">Side 2</td>
<td align="right">61</td>
<td align="right">293</td>
<td align="right">3.882486</td>
<td align="left">R._Inácio_Marquês_da_Silva</td>
</tr>
<tr class="odd">
<td align="left">120 - p1</td>
<td align="left">Side 2</td>
<td align="right">123</td>
<td align="right">22</td>
<td align="right">5.418074</td>
<td align="left">R._Inácio_Marquês_da_Silva</td>
</tr>
<tr class="even">
<td align="left">120 - p2</td>
<td align="left">Side 2</td>
<td align="right">127</td>
<td align="right">293</td>
<td align="right">5.367713</td>
<td align="left">R._Inácio_Marquês_da_Silva</td>
</tr>
<tr class="odd">
<td align="left">160 - p1</td>
<td align="left">Side 2</td>
<td align="right">163</td>
<td align="right">22</td>
<td align="right">4.632502</td>
<td align="left">R._Inácio_Marquês_da_Silva</td>
</tr>
<tr class="even">
<td align="left">160 - p2</td>
<td align="left">Side 2</td>
<td align="right">167</td>
<td align="right">293</td>
<td align="right">4.613665</td>
<td align="left">R._Inácio_Marquês_da_Silva</td>
</tr>
<tr class="odd">
<td align="left">199 - p1</td>
<td align="left">Side 2</td>
<td align="right">199</td>
<td align="right">10</td>
<td align="right">4.972919</td>
<td align="left">R._Inácio_Marquês_da_Silva</td>
</tr>
<tr class="even">
<td align="left">199 - p2</td>
<td align="left">Side 2</td>
<td align="right">203</td>
<td align="right">293</td>
<td align="right">5.275967</td>
<td align="left">R._Inácio_Marquês_da_Silva</td>
</tr>
<tr class="odd">
<td align="left">239 - p1</td>
<td align="left">Side 2</td>
<td align="right">239</td>
<td align="right">22</td>
<td align="right">5.450853</td>
<td align="left">R._Inácio_Marquês_da_Silva</td>
</tr>
<tr class="even">
<td align="left">239 - p2</td>
<td align="left">Side 2</td>
<td align="right">243</td>
<td align="right">270</td>
<td align="right">5.251709</td>
<td align="left">R._Inácio_Marquês_da_Silva</td>
</tr>
<tr class="odd">
<td align="left">300 - p1</td>
<td align="left">Side 2</td>
<td align="right">303</td>
<td align="right">10</td>
<td align="right">4.947092</td>
<td align="left">R._Inácio_Marquês_da_Silva</td>
</tr>
<tr class="even">
<td align="left">300 - p2</td>
<td align="left">Side 2</td>
<td align="right">307</td>
<td align="right">293</td>
<td align="right">5.010201</td>
<td align="left">R._Inácio_Marquês_da_Silva</td>
</tr>
<tr class="odd">
<td align="left">360 - p1</td>
<td align="left">Side 2</td>
<td align="right">363</td>
<td align="right">22</td>
<td align="right">5.188208</td>
<td align="left">R._Inácio_Marquês_da_Silva</td>
</tr>
<tr class="even">
<td align="left">360 - p2</td>
<td align="left">Side 2</td>
<td align="right">367</td>
<td align="right">270</td>
<td align="right">5.073327</td>
<td align="left">R._Inácio_Marquês_da_Silva</td>
</tr>
<tr class="odd">
<td align="left">434 - p1</td>
<td align="left">Side 2</td>
<td align="right">437</td>
<td align="right">10</td>
<td align="right">3.752687</td>
<td align="left">R._Inácio_Marquês_da_Silva</td>
</tr>
<tr class="even">
<td align="left">434 - p2</td>
<td align="left">Side 2</td>
<td align="right">441</td>
<td align="right">270</td>
<td align="right">4.198138</td>
<td align="left">R._Inácio_Marquês_da_Silva</td>
</tr>
<tr class="odd">
<td align="left">500 - p1</td>
<td align="left">Side 2</td>
<td align="right">503</td>
<td align="right">22</td>
<td align="right">4.127347</td>
<td align="left">R._Inácio_Marquês_da_Silva</td>
</tr>
<tr class="even">
<td align="left">500 - p2</td>
<td align="left">Side 2</td>
<td align="right">507</td>
<td align="right">270</td>
<td align="right">4.413154</td>
<td align="left">R._Inácio_Marquês_da_Silva</td>
</tr>
</tbody>
</table>
<p>++++++ Median all 4.80758224866 <br>++++++ Mean all 4.68814353441181 <br></p>
<table style="width:100%;">
<colgroup>
<col width="31%" />
<col width="10%" />
<col width="10%" />
<col width="12%" />
<col width="12%" />
<col width="10%" />
<col width="10%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">street</th>
<th align="right">mean</th>
<th align="right">median</th>
<th align="right">sd</th>
<th align="right">gini</th>
<th align="right">upper</th>
<th align="right">lower</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">R._Manoel_Pereira_de_Araújo</td>
<td align="right">3.672485</td>
<td align="right">3.637284</td>
<td align="right">0.1883041</td>
<td align="right">0.0276016</td>
<td align="right">3.755012</td>
<td align="right">3.589957</td>
</tr>
<tr class="even">
<td align="left">R._Edésio_Silva</td>
<td align="right">4.711095</td>
<td align="right">4.700303</td>
<td align="right">0.4719678</td>
<td align="right">0.0555839</td>
<td align="right">4.917944</td>
<td align="right">4.504246</td>
</tr>
<tr class="odd">
<td align="left">R._Inácio_Marquês_da_Silva</td>
<td align="right">4.713531</td>
<td align="right">4.859461</td>
<td align="right">0.5487980</td>
<td align="right">0.0649960</td>
<td align="right">4.954052</td>
<td align="right">4.473010</td>
</tr>
<tr class="even">
<td align="left">R._Maciel_Pinheiro</td>
<td align="right">4.777779</td>
<td align="right">4.798712</td>
<td align="right">0.2344981</td>
<td align="right">0.0273481</td>
<td align="right">4.880552</td>
<td align="right">4.675006</td>
</tr>
<tr class="odd">
<td align="left">Av._Mal._Floriano_Peixoto</td>
<td align="right">4.957391</td>
<td align="right">5.028135</td>
<td align="right">0.3305999</td>
<td align="right">0.0350720</td>
<td align="right">5.102283</td>
<td align="right">4.812499</td>
</tr>
<tr class="even">
<td align="left">R._Cristina_Procópio_Silva</td>
<td align="right">4.979669</td>
<td align="right">5.204548</td>
<td align="right">0.7201075</td>
<td align="right">0.0778490</td>
<td align="right">5.295270</td>
<td align="right">4.664068</td>
</tr>
</tbody>
</table>
<div class='row'>
<div class="col-xs-3" style="background-color:#003300">
<img src='/home/davidcmm/workspace_doutorado/campinaPulse/scripts/analise/dadosSet17/percepcaoLocal/agradavel/piores/intersects/R._In%C3%A1cio_Marqu%C3%AAs_da_Silva_2_22' width='300px'>
<p style="color:white;font-size:90%">
worst<br>R._Inácio_Marquês_da_Silva_2_22-&gt; 3.598719(-0.00665442)
</p>
</div>
<div class="col-xs-3" style="background-color:#006600">
<img src='/home/davidcmm/workspace_doutorado/campinaPulse/scripts/analise/dadosSet17/percepcaoLocal/agradavel/melhores/intersects/R._In%C3%A1cio_Marqu%C3%AAs_da_Silva_2_112' width='300px'>
<p style="color:white;font-size:90%">
best<br>R._Inácio_Marquês_da_Silva_2_112-&gt; 4.191532(-0.003032634)
</p>
</div>
<div class="col-xs-3" style="background-color:#007f00">
<img src='/home/davidcmm/workspace_doutorado/campinaPulse/scripts/analise/dadosSet17/percepcaoLocal/agradavel/melhores/intersects/R._In%C3%A1cio_Marqu%C3%AAs_da_Silva_2_203' width='300px'>
<p style="color:white;font-size:90%">
best<br>R._Inácio_Marquês_da_Silva_2_203-&gt; 4.507195(-4.326795e-06)
</p>
</div>
<div class="col-xs-3" style="background-color:#003300">
<img src='/home/davidcmm/workspace_doutorado/campinaPulse/scripts/analise/dadosSet17/percepcaoLocal/agradavel/piores/intersects/R._In%C3%A1cio_Marqu%C3%AAs_da_Silva_2_293' width='300px'>
<p style="color:white;font-size:90%">
worst<br>R._Inácio_Marquês_da_Silva_2_293-&gt; 3.612833(-0.006546172)
</p>
</div>
<div class="col-xs-3" style="background-color:#00b200">
<img src='/home/davidcmm/workspace_doutorado/campinaPulse/scripts/analise/dadosSet17/percepcaoLocal/agradavel/melhores/intersects/R._In%C3%A1cio_Marqu%C3%AAs_da_Silva_54_22' width='300px'>
<p style="color:white;font-size:90%">
best<br>R._Inácio_Marquês_da_Silva_54_22-&gt; 5.086038(0.003527193)
</p>
</div>
<div class="col-xs-3" style="background-color:#00b200">
<img src='/home/davidcmm/workspace_doutorado/campinaPulse/scripts/analise/dadosSet17/percepcaoLocal/agradavel/melhores/intersects/R._In%C3%A1cio_Marqu%C3%AAs_da_Silva_54_112' width='300px'>
<p style="color:white;font-size:90%">
best<br>R._Inácio_Marquês_da_Silva_54_112-&gt; 4.988591(0.002719075)
</p>
</div>
<div class="col-xs-3" style="background-color:#006600">
<img src='/home/davidcmm/workspace_doutorado/campinaPulse/scripts/analise/dadosSet17/percepcaoLocal/agradavel/piores/intersects/R._In%C3%A1cio_Marqu%C3%AAs_da_Silva_54_203' width='300px'>
<p style="color:white;font-size:90%">
worst<br>R._Inácio_Marquês_da_Silva_54_203-&gt; 4.324356(-0.002758372)
</p>
</div>
<div class="col-xs-3" style="background-color:#004c00">
<img src='/home/davidcmm/workspace_doutorado/campinaPulse/scripts/analise/dadosSet17/percepcaoLocal/agradavel/piores/intersects/R._In%C3%A1cio_Marqu%C3%AAs_da_Silva_54_293' width='300px'>
<p style="color:white;font-size:90%">
worst<br>R._Inácio_Marquês_da_Silva_54_293-&gt; 3.882486(-0.006059989)
</p>
</div>
<div class="col-xs-3" style="background-color:#00cc00">
<img src='/home/davidcmm/workspace_doutorado/campinaPulse/scripts/analise/dadosSet17/percepcaoLocal/agradavel/melhores/intersects/R._In%C3%A1cio_Marqu%C3%AAs_da_Silva_120_22' width='300px'>
<p style="color:white;font-size:90%">
best<br>R._Inácio_Marquês_da_Silva_120_22-&gt; 5.418074(0.004869867)
</p>
</div>
<div class="col-xs-3" style="background-color:#00b200">
<img src='/home/davidcmm/workspace_doutorado/campinaPulse/scripts/analise/dadosSet17/percepcaoLocal/agradavel/melhores/intersects/R._In%C3%A1cio_Marqu%C3%AAs_da_Silva_120_112' width='300px'>
<p style="color:white;font-size:90%">
best<br>R._Inácio_Marquês_da_Silva_120_112-&gt; 5.132631(0.002703912)
</p>
</div>
<div class="col-xs-3" style="background-color:#004c00">
<img src='/home/davidcmm/workspace_doutorado/campinaPulse/scripts/analise/dadosSet17/percepcaoLocal/agradavel/piores/intersects/R._In%C3%A1cio_Marqu%C3%AAs_da_Silva_120_203' width='300px'>
<p style="color:white;font-size:90%">
worst<br>R._Inácio_Marquês_da_Silva_120_203-&gt; 3.942704(-0.006600194)
</p>
</div>
<div class="col-xs-3" style="background-color:#00cc00">
<img src='/home/davidcmm/workspace_doutorado/campinaPulse/scripts/analise/dadosSet17/percepcaoLocal/agradavel/melhores/intersects/R._In%C3%A1cio_Marqu%C3%AAs_da_Silva_120_293' width='300px'>
<p style="color:white;font-size:90%">
best<br>R._Inácio_Marquês_da_Silva_120_293-&gt; 5.367713(0.004508996)
</p>
</div>
<div class="col-xs-3" style="background-color:#007f00">
<img src='/home/davidcmm/workspace_doutorado/campinaPulse/scripts/analise/dadosSet17/percepcaoLocal/agradavel/piores/intersects/R._In%C3%A1cio_Marqu%C3%AAs_da_Silva_160_22' width='300px'>
<p style="color:white;font-size:90%">
worst<br>R._Inácio_Marquês_da_Silva_160_22-&gt; 4.632501(-0.0003755522)
</p>
</div>
<div class="col-xs-3" style="background-color:#009900">
<img src='/home/davidcmm/workspace_doutorado/campinaPulse/scripts/analise/dadosSet17/percepcaoLocal/agradavel/melhores/intersects/R._In%C3%A1cio_Marqu%C3%AAs_da_Silva_160_112' width='300px'>
<p style="color:white;font-size:90%">
best<br>R._Inácio_Marquês_da_Silva_160_112-&gt; 4.85278(0.0009931379)
</p>
</div>
<div class="col-xs-3" style="background-color:#007f00">
<img src='/home/davidcmm/workspace_doutorado/campinaPulse/scripts/analise/dadosSet17/percepcaoLocal/agradavel/piores/intersects/R._In%C3%A1cio_Marqu%C3%AAs_da_Silva_160_203' width='300px'>
<p style="color:white;font-size:90%">
worst<br>R._Inácio_Marquês_da_Silva_160_203-&gt; 4.621917(-0.0004081508)
</p>
</div>
<div class="col-xs-3" style="background-color:#007f00">
<img src='/home/davidcmm/workspace_doutorado/campinaPulse/scripts/analise/dadosSet17/percepcaoLocal/agradavel/piores/intersects/R._In%C3%A1cio_Marqu%C3%AAs_da_Silva_160_293' width='300px'>
<p style="color:white;font-size:90%">
worst<br>R._Inácio_Marquês_da_Silva_160_293-&gt; 4.613665(-0.0004513745)
</p>
</div>
<div class="col-xs-3" style="background-color:#009900">
<img src='/home/davidcmm/workspace_doutorado/campinaPulse/scripts/analise/dadosSet17/percepcaoLocal/agradavel/piores/intersects/R._In%C3%A1cio_Marqu%C3%AAs_da_Silva_199_10' width='300px'>
<p style="color:white;font-size:90%">
worst<br>R._Inácio_Marquês_da_Silva_199_10-&gt; 4.972919(0.001065562)
</p>
</div>
<div class="col-xs-3" style="background-color:#00e500">
<img src='/home/davidcmm/workspace_doutorado/campinaPulse/scripts/analise/dadosSet17/percepcaoLocal/agradavel/melhores/intersects/R._In%C3%A1cio_Marqu%C3%AAs_da_Silva_199_112' width='300px'>
<p style="color:white;font-size:90%">
best<br>R._Inácio_Marquês_da_Silva_199_112-&gt; 5.784865(0.006653562)
</p>
</div>
<div class="col-xs-3" style="background-color:#00b200">
<img src='/home/davidcmm/workspace_doutorado/campinaPulse/scripts/analise/dadosSet17/percepcaoLocal/agradavel/piores/intersects/R._In%C3%A1cio_Marqu%C3%AAs_da_Silva_199_180' width='300px'>
<p style="color:white;font-size:90%">
worst<br>R._Inácio_Marquês_da_Silva_199_180-&gt; 5.192919(0.002651727)
</p>
</div>
<div class="col-xs-3" style="background-color:#00cc00">
<img src='/home/davidcmm/workspace_doutorado/campinaPulse/scripts/analise/dadosSet17/percepcaoLocal/agradavel/piores/intersects/R._In%C3%A1cio_Marqu%C3%AAs_da_Silva_199_293' width='300px'>
<p style="color:white;font-size:90%">
worst<br>R._Inácio_Marquês_da_Silva_199_293-&gt; 5.275967(0.002979981)
</p>
</div>
<div class="col-xs-3" style="background-color:#00cc00">
<img src='/home/davidcmm/workspace_doutorado/campinaPulse/scripts/analise/dadosSet17/percepcaoLocal/agradavel/melhores/intersects/R._In%C3%A1cio_Marqu%C3%AAs_da_Silva_239_22' width='300px'>
<p style="color:white;font-size:90%">
best<br>R._Inácio_Marquês_da_Silva_239_22-&gt; 5.450853(0.004345318)
</p>
</div>
<div class="col-xs-3" style="background-color:#00b200">
<img src='/home/davidcmm/workspace_doutorado/campinaPulse/scripts/analise/dadosSet17/percepcaoLocal/agradavel/piores/intersects/R._In%C3%A1cio_Marqu%C3%AAs_da_Silva_239_90' width='300px'>
<p style="color:white;font-size:90%">
worst<br>R._Inácio_Marquês_da_Silva_239_90-&gt; 5.145902(0.002314114)
</p>
</div>
<div class="col-xs-3" style="background-color:#00b200">
<img src='/home/davidcmm/workspace_doutorado/campinaPulse/scripts/analise/dadosSet17/percepcaoLocal/agradavel/piores/intersects/R._In%C3%A1cio_Marqu%C3%AAs_da_Silva_239_203' width='300px'>
<p style="color:white;font-size:90%">
worst<br>R._Inácio_Marquês_da_Silva_239_203-&gt; 5.135271(0.002253539)
</p>
</div>
<div class="col-xs-3" style="background-color:#00b200">
<img src='/home/davidcmm/workspace_doutorado/campinaPulse/scripts/analise/dadosSet17/percepcaoLocal/agradavel/piores/intersects/R._In%C3%A1cio_Marqu%C3%AAs_da_Silva_239_270' width='300px'>
<p style="color:white;font-size:90%">
worst<br>R._Inácio_Marquês_da_Silva_239_270-&gt; 5.251709(0.002802554)
</p>
</div>
<div class="col-xs-3" style="background-color:#009900">
<img src='/home/davidcmm/workspace_doutorado/campinaPulse/scripts/analise/dadosSet17/percepcaoLocal/agradavel/piores/intersects/R._In%C3%A1cio_Marqu%C3%AAs_da_Silva_300_10' width='300px'>
<p style="color:white;font-size:90%">
worst<br>R._Inácio_Marquês_da_Silva_300_10-&gt; 4.947092(0.001016932)
</p>
</div>
<div class="col-xs-3" style="background-color:#009900">
<img src='/home/davidcmm/workspace_doutorado/campinaPulse/scripts/analise/dadosSet17/percepcaoLocal/agradavel/piores/intersects/R._In%C3%A1cio_Marqu%C3%AAs_da_Silva_300_112' width='300px'>
<p style="color:white;font-size:90%">
worst<br>R._Inácio_Marquês_da_Silva_300_112-&gt; 4.866142(0.0005018608)
</p>
</div>
<div class="col-xs-3" style="background-color:#00b200">
<img src='/home/davidcmm/workspace_doutorado/campinaPulse/scripts/analise/dadosSet17/percepcaoLocal/agradavel/melhores/intersects/R._In%C3%A1cio_Marqu%C3%AAs_da_Silva_300_180' width='300px'>
<p style="color:white;font-size:90%">
best<br>R._Inácio_Marquês_da_Silva_300_180-&gt; 5.045754(0.001878469)
</p>
</div>
<div class="col-xs-3" style="background-color:#00b200">
<img src='/home/davidcmm/workspace_doutorado/campinaPulse/scripts/analise/dadosSet17/percepcaoLocal/agradavel/melhores/intersects/R._In%C3%A1cio_Marqu%C3%AAs_da_Silva_300_293' width='300px'>
<p style="color:white;font-size:90%">
best<br>R._Inácio_Marquês_da_Silva_300_293-&gt; 5.010201(0.001546696)
</p>
</div>
<div class="col-xs-3" style="background-color:#00b200">
<img src='/home/davidcmm/workspace_doutorado/campinaPulse/scripts/analise/dadosSet17/percepcaoLocal/agradavel/melhores/intersects/R._In%C3%A1cio_Marqu%C3%AAs_da_Silva_360_22' width='300px'>
<p style="color:white;font-size:90%">
best<br>R._Inácio_Marquês_da_Silva_360_22-&gt; 5.188208(0.003285391)
</p>
</div>
<div class="col-xs-3" style="background-color:#007f00">
<img src='/home/davidcmm/workspace_doutorado/campinaPulse/scripts/analise/dadosSet17/percepcaoLocal/agradavel/piores/intersects/R._In%C3%A1cio_Marqu%C3%AAs_da_Silva_360_90' width='300px'>
<p style="color:white;font-size:90%">
worst<br>R._Inácio_Marquês_da_Silva_360_90-&gt; 4.667856(-0.0006952679)
</p>
</div>
<div class="col-xs-3" style="background-color:#009900">
<img src='/home/davidcmm/workspace_doutorado/campinaPulse/scripts/analise/dadosSet17/percepcaoLocal/agradavel/piores/intersects/R._In%C3%A1cio_Marqu%C3%AAs_da_Silva_360_203' width='300px'>
<p style="color:white;font-size:90%">
worst<br>R._Inácio_Marquês_da_Silva_360_203-&gt; 4.736766(-9.725729e-05)
</p>
</div>
<div class="col-xs-3" style="background-color:#00b200">
<img src='/home/davidcmm/workspace_doutorado/campinaPulse/scripts/analise/dadosSet17/percepcaoLocal/agradavel/melhores/intersects/R._In%C3%A1cio_Marqu%C3%AAs_da_Silva_360_270' width='300px'>
<p style="color:white;font-size:90%">
best<br>R._Inácio_Marquês_da_Silva_360_270-&gt; 5.073327(0.002333825)
</p>
</div>
<div class="col-xs-3" style="background-color:#003300">
<img src='/home/davidcmm/workspace_doutorado/campinaPulse/scripts/analise/dadosSet17/percepcaoLocal/agradavel/piores/intersects/R._In%C3%A1cio_Marqu%C3%AAs_da_Silva_434_10' width='300px'>
<p style="color:white;font-size:90%">
worst<br>R._Inácio_Marquês_da_Silva_434_10-&gt; 3.752687(-0.006119138)
</p>
</div>
<div class="col-xs-3" style="background-color:#009900">
<img src='/home/davidcmm/workspace_doutorado/campinaPulse/scripts/analise/dadosSet17/percepcaoLocal/agradavel/melhores/intersects/R._In%C3%A1cio_Marqu%C3%AAs_da_Silva_434_112' width='300px'>
<p style="color:white;font-size:90%">
best<br>R._Inácio_Marquês_da_Silva_434_112-&gt; 4.959634(0.003608038)
</p>
</div>
<div class="col-xs-3" style="background-color:#004c00">
<img src='/home/davidcmm/workspace_doutorado/campinaPulse/scripts/analise/dadosSet17/percepcaoLocal/agradavel/piores/intersects/R._In%C3%A1cio_Marqu%C3%AAs_da_Silva_434_180' width='300px'>
<p style="color:white;font-size:90%">
worst<br>R._Inácio_Marquês_da_Silva_434_180-&gt; 4.016052(-0.004135688)
</p>
</div>
<div class="col-xs-3" style="background-color:#006600">
<img src='/home/davidcmm/workspace_doutorado/campinaPulse/scripts/analise/dadosSet17/percepcaoLocal/agradavel/piores/intersects/R._In%C3%A1cio_Marqu%C3%AAs_da_Silva_434_270' width='300px'>
<p style="color:white;font-size:90%">
worst<br>R._Inácio_Marquês_da_Silva_434_270-&gt; 4.198138(-0.002746433)
</p>
</div>
<div class="col-xs-3" style="background-color:#004c00">
<img src='/home/davidcmm/workspace_doutorado/campinaPulse/scripts/analise/dadosSet17/percepcaoLocal/agradavel/piores/intersects/R._In%C3%A1cio_Marqu%C3%AAs_da_Silva_500_22' width='300px'>
<p style="color:white;font-size:90%">
worst<br>R._Inácio_Marquês_da_Silva_500_22-&gt; 4.127347(-0.003443433)
</p>
</div>
<div class="col-xs-3" style="background-color:#007f00">
<img src='/home/davidcmm/workspace_doutorado/campinaPulse/scripts/analise/dadosSet17/percepcaoLocal/agradavel/melhores/intersects/R._In%C3%A1cio_Marqu%C3%AAs_da_Silva_500_90' width='300px'>
<p style="color:white;font-size:90%">
best<br>R._Inácio_Marquês_da_Silva_500_90-&gt; 4.416113(-0.001447962)
</p>
</div>
<div class="col-xs-3" style="background-color:#006600">
<img src='/home/davidcmm/workspace_doutorado/campinaPulse/scripts/analise/dadosSet17/percepcaoLocal/agradavel/piores/intersects/R._In%C3%A1cio_Marqu%C3%AAs_da_Silva_500_203' width='300px'>
<p style="color:white;font-size:90%">
worst<br>R._Inácio_Marquês_da_Silva_500_203-&gt; 4.138628(-0.003361445)
</p>
</div>
<div class="col-xs-3" style="background-color:#007f00">
<img src='/home/davidcmm/workspace_doutorado/campinaPulse/scripts/analise/dadosSet17/percepcaoLocal/agradavel/melhores/intersects/R._In%C3%A1cio_Marqu%C3%AAs_da_Silva_500_270' width='300px'>
<p style="color:white;font-size:90%">
best<br>R._Inácio_Marquês_da_Silva_500_270-&gt; 4.413154(-0.001477832)
</p>
</div>
<ol style="list-style-type: decimal">
<li>Locais problemáticos na rua (olhando as fotos):
<ul>
<li>54 angulos 203 e 293 (falta de manutenção e verde);</li>
<li>120 angulo 203 (falta de manutenção, lixo e verde);</li>
<li>360 angulos 90 e 203 (terreno);</li>
<li>todo o número 500</li>
</ul></li>
<li>Virtudes na rua (olhando as fotos):
<ul>
<li>54, 22 (casas bem mantidas, verde)</li>
<li>120, 22 e 293 (casas bem mantidas, verde)</li>
<li>239 todo (casas bem mantidas, verde)</li>
<li>360, 22 e 270 (museu, verde, boa manutenção)</li>
</ul></li>
</ol>
<blockquote>
<blockquote>
<p>Olhando os Q-Scores ao longo da rua</p>
</blockquote>
</blockquote>
<ol start="2" style="list-style-type: decimal">
<li>Melhor e pior local da rua:
<ul>
<li>239 p1 side1</li>
<li>54 p2 side2. Diferenca de 1.45 -&gt; boa manutenção, algum verde x menor manutenção, lixo</li>
</ul></li>
<li>Melhor e pior lado da rua:
<ul>
<li>O side2 parece ligeiramente melhor (54 e 239 empate (uma foto de um lado e outra do outro), 500 empate com igualdade, 120 e 360 side2)</li>
</ul></li>
<li>Melhor e pior área da rua (considerando os dois lados):
<ul>
<li>239 a 360 (melhor)? manutenção, verde, museu, apesar de duas visões de terreno que tiveram notas não tão ruins</li>
</ul></li>
<li>Áreas muito diferentes entre lados:
<ul>
<li>120 a 239 -&gt; no 239 temos um maior equilíbrio bom entre todos os pontos (boa manutenção, verde), mas no 120 temos um ponto pior para o side1 (menor manutenção, lixo, ausência de verde)</li>
</ul></li>
<li>Descontinuidades no mesmo lado:
<ul>
<li>54 side1, diferenca de 1.2 -&gt; melhor manutenção x pior manutenção</li>
<li>54 side2, diferença de 0.6 -&gt; melhor manutenção, verde x pior manutenção, falta de verde</li>
<li>120 side1, diferença de 1.1 -&gt; melhor manutenção, verde x pior manutenção, falta de verde</li>
</ul></li>
<li>Heterogeneidade/Homogeneidade no ponto:
<ul>
<li>os pontos mais heterogêneos foram o 54 (pior manutenção, falta de verde x melhor manutenção, verde) e 120 (pior manutenção, falta de verde x melhor manutenção);</li>
<li>o mais homogêneo foi o 500 (pouca manutenção, muros, terrenos)<br />
</li>
</ul></li>
<li>Foram encontrados os problemas?
<ul>
<li>Dos 4 pontos levantados o 360 não foi percebido pelas perguntas acima.</li>
<li>Se olhássemos o terceiro ponto mais heterogêneo encontraríamos o problema do ponto 360 (menor diferença de 0.4) ou como os pontos de cada lado tem notas parecidas se olhássemos diferenças entre lados no ponto.</li>
</ul></li>
<li>O que é a rua?
<ul>
<li>A nota média/mediana é boa ou ruim? De mediana para boa</li>
<li>Existe muita variação? Variações de locais melhores e piores ao longo de toda a rua, alguns números com grande variação no local</li>
<li>Existe um lado melhor? Side2 ligeiramente melhor</li>
<li>Existe uma área melhor pior? Não</li>
</ul></li>
</ol>
<blockquote>
<blockquote>
<p>Olhando o surprise maps (uniforme + base rate + normal)</p>
</blockquote>
</blockquote>
<ol style="list-style-type: decimal">
<li>Máximo e Mínimo?
<ul>
<li>239 p1 side1</li>
<li>54 p2 side2. Diferenca de 1.45 -&gt; boa manutenção, algum verde x menor manutenção, lixo</li>
</ul></li>
<li>Mais diversidade?</li>
</ol>
<ul>
<li>54, 1 ponto de cada side separado: melhor manutenção, verde x pior manutenção, lixo</li>
<li>120, side1 p2 estranho: lixo, falta de manutenção x melhor manutenção, verde</li>
<li>360, side1 separado de side2: visões do museu x terreno</li>
</ul>
<ol start="3" style="list-style-type: decimal">
<li>Menor diversidade?</li>
</ol>
<ul>
<li>239 homogêneo e positivo (boa manunteção, verde)</li>
<li>500 homogêneo e negativo (falta de manutenção, muros, terreno) 4 Diferenças/saltos no lado?</li>
<li>54, 1 ponto de cada side separado</li>
<li>120, side1 separado</li>
<li>360, side2 separado de side1</li>
</ul>
<ol start="5" style="list-style-type: decimal">
<li>Avaliação Problemas</li>
</ol>
<ul>
<li>Pesquisador: 4 problemas (descritos acima)</li>
<li>Recall = método / pesquisador = 4/4 = 1</li>
<li>Precisão = reais / método = 4/4 = 1</li>
</ul>
<ol start="6" style="list-style-type: decimal">
<li>Avaliação Virtudes</li>
</ol>
<ul>
<li>Pesquisador: 4 virtudes (descritos acima)</li>
<li>Recall = método / pesquisador = 4/4 = 1</li>
<li>Precisão = reais / método = 4/4 = 1</li>
</ul>
<ol start="7" style="list-style-type: decimal">
<li>Descrição</li>
</ol>
<ul>
<li>Média/mediana: 4.84/5.08 &gt; 4.68/4.82, rua de mediana para boa</li>
<li>Variação no surprise? Alguns pontos mais homogêneos ao longo da rua, um bom e outro ruim, porém existem pontos de altos e baixos ao longo da rua</li>
<li>Lado melhor? Side1 (4) x Side2 (7), side2 ligeiramente melhor</li>
<li>Região melhor? Pelo surprise parece ser a região de 120 a 360, mesma sensação olhando os scores.</li>
</ul>
</div>
<div id="floriano-peixoto" class="section level1">
<h1>Floriano peixoto</h1>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  floriano$qscore
## W = 0.95361, p-value = 0.4252</code></pre>
<pre><code>##       mean          sd    
##   4.95739065   0.32222894 
##  (0.07205258) (0.05094887)</code></pre>
<pre><code>## [1] &quot;&gt;&gt;&gt; GINI da rua:  0.0350719776584624&quot;</code></pre>
<pre><code>##   num      value
## 1 913 0.04636118
## 2 549 0.04371678
## 3 813 0.01747931
## 4 445 0.01482587
## 5 691 0.01205420</code></pre>
<pre><code>##   num value
## 1 445   NaN
## 2 549   NaN
## 3 691   NaN
## 4 813   NaN
## 5 913   NaN</code></pre>
<pre><code>##   num value
## 1 445   NaN
## 2 549   NaN
## 3 691   NaN
## 4 813   NaN
## 5 913   NaN</code></pre>
<pre><code>## Adding missing grouping variables: `num`</code></pre>
<p><img src="analisaPorRua2_files/figure-html/unnamed-chunk-10-1.png" width="1152"  /></p>
<table>
<thead>
<tr class="header">
<th align="left">xlabel</th>
<th align="left">side</th>
<th align="right">num</th>
<th align="right">angle</th>
<th align="right">V3</th>
<th align="left">street</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">445 - p1</td>
<td align="left">Side 1</td>
<td align="right">448</td>
<td align="right">22</td>
<td align="right">5.030961</td>
<td align="left">Av._Mal._Floriano_Peixoto</td>
</tr>
<tr class="even">
<td align="left">445 - p2</td>
<td align="left">Side 1</td>
<td align="right">452</td>
<td align="right">293</td>
<td align="right">4.906944</td>
<td align="left">Av._Mal._Floriano_Peixoto</td>
</tr>
<tr class="odd">
<td align="left">549 - p1</td>
<td align="left">Side 1</td>
<td align="right">552</td>
<td align="right">22</td>
<td align="right">4.743456</td>
<td align="left">Av._Mal._Floriano_Peixoto</td>
</tr>
<tr class="even">
<td align="left">549 - p2</td>
<td align="left">Side 1</td>
<td align="right">556</td>
<td align="right">293</td>
<td align="right">4.544730</td>
<td align="left">Av._Mal._Floriano_Peixoto</td>
</tr>
<tr class="odd">
<td align="left">691 - p1</td>
<td align="left">Side 1</td>
<td align="right">694</td>
<td align="right">22</td>
<td align="right">5.374211</td>
<td align="left">Av._Mal._Floriano_Peixoto</td>
</tr>
<tr class="even">
<td align="left">691 - p2</td>
<td align="left">Side 1</td>
<td align="right">698</td>
<td align="right">293</td>
<td align="right">5.135495</td>
<td align="left">Av._Mal._Floriano_Peixoto</td>
</tr>
<tr class="odd">
<td align="left">813 - p1</td>
<td align="left">Side 1</td>
<td align="right">816</td>
<td align="right">22</td>
<td align="right">4.717985</td>
<td align="left">Av._Mal._Floriano_Peixoto</td>
</tr>
<tr class="even">
<td align="left">813 - p2</td>
<td align="left">Side 1</td>
<td align="right">820</td>
<td align="right">293</td>
<td align="right">4.986593</td>
<td align="left">Av._Mal._Floriano_Peixoto</td>
</tr>
<tr class="odd">
<td align="left">913 - p1</td>
<td align="left">Side 1</td>
<td align="right">916</td>
<td align="right">22</td>
<td align="right">4.486147</td>
<td align="left">Av._Mal._Floriano_Peixoto</td>
</tr>
<tr class="even">
<td align="left">913 - p2</td>
<td align="left">Side 1</td>
<td align="right">920</td>
<td align="right">293</td>
<td align="right">4.088261</td>
<td align="left">Av._Mal._Floriano_Peixoto</td>
</tr>
<tr class="odd">
<td align="left">445 - p1</td>
<td align="left">Side 2</td>
<td align="right">445</td>
<td align="right">112</td>
<td align="right">5.266072</td>
<td align="left">Av._Mal._Floriano_Peixoto</td>
</tr>
<tr class="even">
<td align="left">445 - p2</td>
<td align="left">Side 2</td>
<td align="right">449</td>
<td align="right">203</td>
<td align="right">4.915208</td>
<td align="left">Av._Mal._Floriano_Peixoto</td>
</tr>
<tr class="odd">
<td align="left">549 - p1</td>
<td align="left">Side 2</td>
<td align="right">549</td>
<td align="right">112</td>
<td align="right">5.220240</td>
<td align="left">Av._Mal._Floriano_Peixoto</td>
</tr>
<tr class="even">
<td align="left">549 - p2</td>
<td align="left">Side 2</td>
<td align="right">553</td>
<td align="right">203</td>
<td align="right">5.555297</td>
<td align="left">Av._Mal._Floriano_Peixoto</td>
</tr>
<tr class="odd">
<td align="left">691 - p1</td>
<td align="left">Side 2</td>
<td align="right">691</td>
<td align="right">112</td>
<td align="right">5.087900</td>
<td align="left">Av._Mal._Floriano_Peixoto</td>
</tr>
<tr class="even">
<td align="left">691 - p2</td>
<td align="left">Side 2</td>
<td align="right">695</td>
<td align="right">203</td>
<td align="right">5.058091</td>
<td align="left">Av._Mal._Floriano_Peixoto</td>
</tr>
<tr class="odd">
<td align="left">813 - p1</td>
<td align="left">Side 2</td>
<td align="right">813</td>
<td align="right">112</td>
<td align="right">5.120962</td>
<td align="left">Av._Mal._Floriano_Peixoto</td>
</tr>
<tr class="even">
<td align="left">813 - p2</td>
<td align="left">Side 2</td>
<td align="right">817</td>
<td align="right">203</td>
<td align="right">4.821832</td>
<td align="left">Av._Mal._Floriano_Peixoto</td>
</tr>
<tr class="odd">
<td align="left">913 - p1</td>
<td align="left">Side 2</td>
<td align="right">913</td>
<td align="right">112</td>
<td align="right">5.025309</td>
<td align="left">Av._Mal._Floriano_Peixoto</td>
</tr>
<tr class="even">
<td align="left">913 - p2</td>
<td align="left">Side 2</td>
<td align="right">917</td>
<td align="right">203</td>
<td align="right">5.062120</td>
<td align="left">Av._Mal._Floriano_Peixoto</td>
</tr>
</tbody>
</table>
<p>++++++ Median all 4.80758224866 <br>++++++ Mean all 4.68814353441181 <br></p>
<table style="width:100%;">
<colgroup>
<col width="31%" />
<col width="10%" />
<col width="10%" />
<col width="12%" />
<col width="12%" />
<col width="10%" />
<col width="10%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">street</th>
<th align="right">mean</th>
<th align="right">median</th>
<th align="right">sd</th>
<th align="right">gini</th>
<th align="right">upper</th>
<th align="right">lower</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">R._Manoel_Pereira_de_Araújo</td>
<td align="right">3.672485</td>
<td align="right">3.637284</td>
<td align="right">0.1883041</td>
<td align="right">0.0276016</td>
<td align="right">3.755012</td>
<td align="right">3.589957</td>
</tr>
<tr class="even">
<td align="left">R._Edésio_Silva</td>
<td align="right">4.711095</td>
<td align="right">4.700303</td>
<td align="right">0.4719678</td>
<td align="right">0.0555839</td>
<td align="right">4.917944</td>
<td align="right">4.504246</td>
</tr>
<tr class="odd">
<td align="left">R._Inácio_Marquês_da_Silva</td>
<td align="right">4.713531</td>
<td align="right">4.859461</td>
<td align="right">0.5487980</td>
<td align="right">0.0649960</td>
<td align="right">4.954052</td>
<td align="right">4.473010</td>
</tr>
<tr class="even">
<td align="left">R._Maciel_Pinheiro</td>
<td align="right">4.777779</td>
<td align="right">4.798712</td>
<td align="right">0.2344981</td>
<td align="right">0.0273481</td>
<td align="right">4.880552</td>
<td align="right">4.675006</td>
</tr>
<tr class="odd">
<td align="left">Av._Mal._Floriano_Peixoto</td>
<td align="right">4.957391</td>
<td align="right">5.028135</td>
<td align="right">0.3305999</td>
<td align="right">0.0350720</td>
<td align="right">5.102283</td>
<td align="right">4.812499</td>
</tr>
<tr class="even">
<td align="left">R._Cristina_Procópio_Silva</td>
<td align="right">4.979669</td>
<td align="right">5.204548</td>
<td align="right">0.7201075</td>
<td align="right">0.0778490</td>
<td align="right">5.295270</td>
<td align="right">4.664068</td>
</tr>
</tbody>
</table>
<div class='row'>
<div class="col-xs-3" style="background-color:#00b200">
<img src='/home/davidcmm/workspace_doutorado/campinaPulse/scripts/analise/dadosSet17/percepcaoLocal/agradavel/piores/intersects/Av._Mal._Floriano_Peixoto_445_22' width='300px'>
<p style="color:white;font-size:90%">
worst<br>Av._Mal._Floriano_Peixoto_445_22-&gt; 5.030961(0.0005016674)
</p>
</div>
<div class="col-xs-3" style="background-color:#00cc00">
<img src='/home/davidcmm/workspace_doutorado/campinaPulse/scripts/analise/dadosSet17/percepcaoLocal/agradavel/melhores/intersects/Av._Mal._Floriano_Peixoto_480_112' width='300px'>
<p style="color:white;font-size:90%">
best<br>Av._Mal._Floriano_Peixoto_480_112-&gt; 5.266072(0.004360108)
</p>
</div>
<div class="col-xs-3" style="background-color:#009900">
<img src='/home/davidcmm/workspace_doutorado/campinaPulse/scripts/analise/dadosSet17/percepcaoLocal/agradavel/piores/intersects/Av._Mal._Floriano_Peixoto_480_203' width='300px'>
<p style="color:white;font-size:90%">
worst<br>Av._Mal._Floriano_Peixoto_480_203-&gt; 4.915208(-0.0006407116)
</p>
</div>
<div class="col-xs-3" style="background-color:#009900">
<img src='/home/davidcmm/workspace_doutorado/campinaPulse/scripts/analise/dadosSet17/percepcaoLocal/agradavel/piores/intersects/Av._Mal._Floriano_Peixoto_445_293' width='300px'>
<p style="color:white;font-size:90%">
worst<br>Av._Mal._Floriano_Peixoto_445_293-&gt; 4.906944(-0.0008427378)
</p>
</div>
<div class="col-xs-3" style="background-color:#009900">
<img src='/home/davidcmm/workspace_doutorado/campinaPulse/scripts/analise/dadosSet17/percepcaoLocal/agradavel/piores/intersects/Av._Mal._Floriano_Peixoto_549_22' width='300px'>
<p style="color:white;font-size:90%">
worst<br>Av._Mal._Floriano_Peixoto_549_22-&gt; 4.743456(-0.003701903)
</p>
</div>
<div class="col-xs-3" style="background-color:#00b200">
<img src='/home/davidcmm/workspace_doutorado/campinaPulse/scripts/analise/dadosSet17/percepcaoLocal/agradavel/melhores/intersects/Av._Mal._Floriano_Peixoto_580_112' width='300px'>
<p style="color:white;font-size:90%">
best<br>Av._Mal._Floriano_Peixoto_580_112-&gt; 5.22024(0.003761783)
</p>
</div>
<div class="col-xs-3" style="background-color:#00e500">
<img src='/home/davidcmm/workspace_doutorado/campinaPulse/scripts/analise/dadosSet17/percepcaoLocal/agradavel/melhores/intersects/Av._Mal._Floriano_Peixoto_580_203' width='300px'>
<p style="color:white;font-size:90%">
best<br>Av._Mal._Floriano_Peixoto_580_203-&gt; 5.555297(0.008390278)
</p>
</div>
<div class="col-xs-3" style="background-color:#007f00">
<img src='/home/davidcmm/workspace_doutorado/campinaPulse/scripts/analise/dadosSet17/percepcaoLocal/agradavel/piores/intersects/Av._Mal._Floriano_Peixoto_549_293' width='300px'>
<p style="color:white;font-size:90%">
worst<br>Av._Mal._Floriano_Peixoto_549_293-&gt; 4.54473(-0.006437727)
</p>
</div>
<div class="col-xs-3" style="background-color:#00cc00">
<img src='/home/davidcmm/workspace_doutorado/campinaPulse/scripts/analise/dadosSet17/percepcaoLocal/agradavel/melhores/intersects/Av._Mal._Floriano_Peixoto_691_22' width='300px'>
<p style="color:white;font-size:90%">
best<br>Av._Mal._Floriano_Peixoto_691_22-&gt; 5.374211(0.005147462)
</p>
</div>
<div class="col-xs-3" style="background-color:#00b200">
<img src='/home/davidcmm/workspace_doutorado/campinaPulse/scripts/analise/dadosSet17/percepcaoLocal/agradavel/piores/intersects/Av._Mal._Floriano_Peixoto_660_112' width='300px'>
<p style="color:white;font-size:90%">
worst<br>Av._Mal._Floriano_Peixoto_660_112-&gt; 5.0879(0.001052944)
</p>
</div>
<div class="col-xs-3" style="background-color:#00b200">
<img src='/home/davidcmm/workspace_doutorado/campinaPulse/scripts/analise/dadosSet17/percepcaoLocal/agradavel/piores/intersects/Av._Mal._Floriano_Peixoto_660_203' width='300px'>
<p style="color:white;font-size:90%">
worst<br>Av._Mal._Floriano_Peixoto_660_203-&gt; 5.058092(0.0006895255)
</p>
</div>
<div class="col-xs-3" style="background-color:#00b200">
<img src='/home/davidcmm/workspace_doutorado/campinaPulse/scripts/analise/dadosSet17/percepcaoLocal/agradavel/piores/intersects/Av._Mal._Floriano_Peixoto_691_293' width='300px'>
<p style="color:white;font-size:90%">
worst<br>Av._Mal._Floriano_Peixoto_691_293-&gt; 5.135494(0.001611101)
</p>
</div>
<div class="col-xs-3" style="background-color:#009900">
<img src='/home/davidcmm/workspace_doutorado/campinaPulse/scripts/analise/dadosSet17/percepcaoLocal/agradavel/piores/intersects/Av._Mal._Floriano_Peixoto_813_22' width='300px'>
<p style="color:white;font-size:90%">
worst<br>Av._Mal._Floriano_Peixoto_813_22-&gt; 4.717985(-0.003514282)
</p>
</div>
<div class="col-xs-3" style="background-color:#00b200">
<img src='/home/davidcmm/workspace_doutorado/campinaPulse/scripts/analise/dadosSet17/percepcaoLocal/agradavel/melhores/intersects/Av._Mal._Floriano_Peixoto_826_112' width='300px'>
<p style="color:white;font-size:90%">
best<br>Av._Mal._Floriano_Peixoto_826_112-&gt; 5.120962(0.002821638)
</p>
</div>
<div class="col-xs-3" style="background-color:#009900">
<img src='/home/davidcmm/workspace_doutorado/campinaPulse/scripts/analise/dadosSet17/percepcaoLocal/agradavel/piores/intersects/Av._Mal._Floriano_Peixoto_826_203' width='300px'>
<p style="color:white;font-size:90%">
worst<br>Av._Mal._Floriano_Peixoto_826_203-&gt; 4.821832(-0.001657022)
</p>
</div>
<div class="col-xs-3" style="background-color:#00b200">
<img src='/home/davidcmm/workspace_doutorado/campinaPulse/scripts/analise/dadosSet17/percepcaoLocal/agradavel/piores/intersects/Av._Mal._Floriano_Peixoto_813_293' width='300px'>
<p style="color:white;font-size:90%">
worst<br>Av._Mal._Floriano_Peixoto_813_293-&gt; 4.986593(0.0003616767)
</p>
</div>
<div class="col-xs-3" style="background-color:#007f00">
<img src='/home/davidcmm/workspace_doutorado/campinaPulse/scripts/analise/dadosSet17/percepcaoLocal/agradavel/piores/intersects/Av._Mal._Floriano_Peixoto_913_22' width='300px'>
<p style="color:white;font-size:90%">
worst<br>Av._Mal._Floriano_Peixoto_913_22-&gt; 4.486147(-0.005503796)
</p>
</div>
<div class="col-xs-3" style="background-color:#00b200">
<img src='/home/davidcmm/workspace_doutorado/campinaPulse/scripts/analise/dadosSet17/percepcaoLocal/agradavel/melhores/intersects/Av._Mal._Floriano_Peixoto_912_112' width='300px'>
<p style="color:white;font-size:90%">
best<br>Av._Mal._Floriano_Peixoto_912_112-&gt; 5.025309(0.002813594)
</p>
</div>
<div class="col-xs-3" style="background-color:#00b200">
<img src='/home/davidcmm/workspace_doutorado/campinaPulse/scripts/analise/dadosSet17/percepcaoLocal/agradavel/melhores/intersects/Av._Mal._Floriano_Peixoto_912_203' width='300px'>
<p style="color:white;font-size:90%">
best<br>Av._Mal._Floriano_Peixoto_912_203-&gt; 5.06212(0.003457597)
</p>
</div>
<div class="col-xs-3" style="background-color:#004c00">
<img src='/home/davidcmm/workspace_doutorado/campinaPulse/scripts/analise/dadosSet17/percepcaoLocal/agradavel/piores/intersects/Av._Mal._Floriano_Peixoto_913_293' width='300px'>
<p style="color:white;font-size:90%">
worst<br>Av._Mal._Floriano_Peixoto_913_293-&gt; 4.088261(-0.01114909)
</p>
</div>
<ol style="list-style-type: decimal">
<li>Locais problemáticos na rua (olhando as fotos):
<ul>
<li>549 angulo 22 (manutenção no prédio)</li>
<li>813 angulos 22 (manutenção no telegrafo/histórico)</li>
<li>913 angulo 203 (manutenção prédio amarelo)</li>
</ul></li>
<li>Virtudes na rua (olhando as fotos):
<ul>
<li>480 todo (verde, boa manutenção)</li>
<li>580 112 e 203 (verde)</li>
<li>660 (verde, boa manutenção)</li>
<li>826 22 (telegrafo) e 112 (igreja)</li>
</ul></li>
</ol>
<blockquote>
<blockquote>
<p>Olhando os Q-Scores ao longo da rua</p>
</blockquote>
</blockquote>
<ol start="2" style="list-style-type: decimal">
<li>Melhor e pior local da rua:
<ul>
<li>549 p2 side2 (muito verde bem mantido, praça)</li>
<li>913 p2 side1 (lojas com visual mais acanhado). Diferença de 1.4</li>
</ul></li>
<li>Melhor e pior lado da rua:
<ul>
<li>O side2 parece ligeiramente melhor (445, 549, 913 side2, 691 side1, 813 empate)</li>
</ul></li>
<li>Melhor e pior área da rua (considerando os dois lados):
<ul>
<li>691 a 813? verde, bem mantido e alguns pontos precisando de manutenção.</li>
</ul></li>
<li>Áreas muito diferentes entre lados:
<ul>
<li>549 (praça x prédios mais acanhados)??</li>
</ul></li>
<li>Descontinuidades no mesmo lado:
<ul>
<li>445 side1, diferença de 0.7 -&gt; ônibus??</li>
<li>445 side2, diferença de 0.6 -&gt; mais verde x menos verde, prédio</li>
<li>549 side2, diferença de 0.4 -&gt; mais verde, praça x menos verde, estacionamento</li>
</ul></li>
<li>Heterogeneidade/Homogeneidade no ponto:
<ul>
<li>os pontos mais heterogêneos foram o 913 (visual das lojas?) e 549 (praça, verde x estacionamento, prédio).</li>
<li>O mais homogênero foi o 691 (prédios até bem mantidos com algumas árvores)</li>
</ul></li>
<li>Foram encontrados os problemas?
<ul>
<li>O ponto 813 dos 3 apontados não foi percebido.</li>
<li>Se olhássemos outras descontinuidades no mesmo lado acabaríamos chegando nessa comparação apesar da baixa diferença de 0.2.</li>
</ul></li>
<li>O que é a rua?
<ul>
<li>A nota média/mediana é boa ou ruim? De mediana para boa</li>
<li>Existe muita variação? Rua mais homogênea, com pequenas variações entre alguns de seus pontos</li>
<li>Existe um lado melhor? Side2 ligeiramente melhor</li>
<li>Existe uma área melhor pior? Não</li>
</ul></li>
</ol>
<blockquote>
<blockquote>
<p>Olhando o surprise maps (uniforme + base rate + normal)</p>
</blockquote>
</blockquote>
<ol style="list-style-type: decimal">
<li>Máximo e Mínimo?
<ul>
<li>549 p2 side2 (muito verde bem mantido, praça)</li>
<li>913 p2 side1 (lojas com visual mais acanhado). Diferença de 1.4</li>
</ul></li>
<li>Mais diversidade?</li>
</ol>
<ul>
<li>913, side2 separado de side1: visual das lojas, manutenção?</li>
<li>549, side2 separado de side1, certa separação entre cada ponto de side2: visual de lojas x praça</li>
<li>445, 1 ponto de cada side separado: verde, praça x mais prédio?</li>
<li>813, 1 ponto side2 separado: igreja, prédios x estilo de prédios, telegráfo?</li>
</ul>
<ol start="3" style="list-style-type: decimal">
<li>Menor diversidade?</li>
</ol>
<ul>
<li>660, ponto mais homogêneo e positivo: verde, prédios bem mantidos 4 Diferenças/saltos no lado?</li>
<li>445, 1 ponto de cada side separado</li>
<li>549, side2 separado de side1</li>
<li>813, side2 separado</li>
<li>913, side2 separado de side1</li>
</ul>
<ol start="5" style="list-style-type: decimal">
<li>Avaliação Problemas</li>
</ol>
<ul>
<li>Pesquisador: 3 problemas (descritos acima)</li>
<li>Recall = método / pesquisador = 1/3 = 0.33 (menos o 549 ang 22 e o 913 ang 203 )</li>
<li>Precisão = reais / método = 1/4 = 0.25 (913 sides afastados, 549 p2 side1 afastado, 445 1 ponto de cada side afastado)</li>
</ul>
<ol start="6" style="list-style-type: decimal">
<li>Avaliação Virtudes</li>
</ol>
<ul>
<li>Pesquisador: 4 virtudes (descritos acima)</li>
<li>Recall = método / pesquisador = 3.5/4 = 0.87 (metade do 480)</li>
<li>Precisão = reais / método = 3/4 = 0.75 (menos o 913)</li>
</ul>
<ol start="7" style="list-style-type: decimal">
<li>Descrição</li>
</ol>
<ul>
<li>Média/mediana: 5.06/5.04 x 4.68/4.82 -&gt; rua de mediana para boa</li>
<li>Variação no surprise? Em cada ponto temos algumas variações ao longo da rua e um ponto mais homogêneo positivamente</li>
<li>Lado melhor? Side1 (6) x Side2 (8), side2 ligeiramente melhor</li>
<li>Região melhor? Não dá para identificar pelo surprise, pelos <strong>scores poderia-se dizer do 552 ao 694?</strong></li>
</ul>
</div>
<div id="maciel-pinheiro" class="section level1">
<h1>Maciel Pinheiro</h1>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  maciel$qscore
## W = 0.92629, p-value = 0.131</code></pre>
<pre><code>##       mean          sd    
##   4.77777896   0.22856043 
##  (0.05110767) (0.03613858)</code></pre>
<pre><code>## [1] &quot;&gt;&gt;&gt; GINI da rua:  0.0273480532370483&quot;</code></pre>
<pre><code>##   num      value
## 1 248 0.03002473
## 2 190 0.02563699
## 3 360 0.02218690
## 4 284 0.02082185
## 5 130 0.01490685</code></pre>
<pre><code>##   num value
## 1 130   NaN
## 2 190   NaN
## 3 248   NaN
## 4 284   NaN
## 5 360   NaN</code></pre>
<pre><code>##   num value
## 1 130   NaN
## 2 190   NaN
## 3 248   NaN
## 4 284   NaN
## 5 360   NaN</code></pre>
<pre><code>## Adding missing grouping variables: `num`</code></pre>
<p><img src="analisaPorRua2_files/figure-html/unnamed-chunk-12-1.png" width="1152"  /></p>
<table>
<thead>
<tr class="header">
<th align="left">xlabel</th>
<th align="left">side</th>
<th align="right">num</th>
<th align="right">angle</th>
<th align="right">V3</th>
<th align="left">street</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">130 - p1</td>
<td align="left">Side 1</td>
<td align="right">130</td>
<td align="right">90</td>
<td align="right">5.014311</td>
<td align="left">R._Maciel_Pinheiro</td>
</tr>
<tr class="even">
<td align="left">130 - p2</td>
<td align="left">Side 1</td>
<td align="right">134</td>
<td align="right">360</td>
<td align="right">4.662146</td>
<td align="left">R._Maciel_Pinheiro</td>
</tr>
<tr class="odd">
<td align="left">190 - p1</td>
<td align="left">Side 1</td>
<td align="right">190</td>
<td align="right">90</td>
<td align="right">5.093964</td>
<td align="left">R._Maciel_Pinheiro</td>
</tr>
<tr class="even">
<td align="left">190 - p2</td>
<td align="left">Side 1</td>
<td align="right">194</td>
<td align="right">360</td>
<td align="right">5.028834</td>
<td align="left">R._Maciel_Pinheiro</td>
</tr>
<tr class="odd">
<td align="left">248 - p1</td>
<td align="left">Side 1</td>
<td align="right">248</td>
<td align="right">90</td>
<td align="right">4.979997</td>
<td align="left">R._Maciel_Pinheiro</td>
</tr>
<tr class="even">
<td align="left">248 - p2</td>
<td align="left">Side 1</td>
<td align="right">252</td>
<td align="right">360</td>
<td align="right">4.491837</td>
<td align="left">R._Maciel_Pinheiro</td>
</tr>
<tr class="odd">
<td align="left">284 - p1</td>
<td align="left">Side 1</td>
<td align="right">284</td>
<td align="right">90</td>
<td align="right">4.789855</td>
<td align="left">R._Maciel_Pinheiro</td>
</tr>
<tr class="even">
<td align="left">284 - p2</td>
<td align="left">Side 1</td>
<td align="right">288</td>
<td align="right">360</td>
<td align="right">4.807568</td>
<td align="left">R._Maciel_Pinheiro</td>
</tr>
<tr class="odd">
<td align="left">360 - p1</td>
<td align="left">Side 1</td>
<td align="right">360</td>
<td align="right">90</td>
<td align="right">4.652515</td>
<td align="left">R._Maciel_Pinheiro</td>
</tr>
<tr class="even">
<td align="left">360 - p2</td>
<td align="left">Side 1</td>
<td align="right">364</td>
<td align="right">360</td>
<td align="right">4.952766</td>
<td align="left">R._Maciel_Pinheiro</td>
</tr>
<tr class="odd">
<td align="left">130 - p1</td>
<td align="left">Side 2</td>
<td align="right">133</td>
<td align="right">180</td>
<td align="right">4.807788</td>
<td align="left">R._Maciel_Pinheiro</td>
</tr>
<tr class="even">
<td align="left">130 - p2</td>
<td align="left">Side 2</td>
<td align="right">137</td>
<td align="right">270</td>
<td align="right">4.719232</td>
<td align="left">R._Maciel_Pinheiro</td>
</tr>
<tr class="odd">
<td align="left">190 - p1</td>
<td align="left">Side 2</td>
<td align="right">193</td>
<td align="right">180</td>
<td align="right">4.434079</td>
<td align="left">R._Maciel_Pinheiro</td>
</tr>
<tr class="even">
<td align="left">190 - p2</td>
<td align="left">Side 2</td>
<td align="right">197</td>
<td align="right">270</td>
<td align="right">5.002695</td>
<td align="left">R._Maciel_Pinheiro</td>
</tr>
<tr class="odd">
<td align="left">248 - p1</td>
<td align="left">Side 2</td>
<td align="right">251</td>
<td align="right">180</td>
<td align="right">5.123118</td>
<td align="left">R._Maciel_Pinheiro</td>
</tr>
<tr class="even">
<td align="left">248 - p2</td>
<td align="left">Side 2</td>
<td align="right">255</td>
<td align="right">270</td>
<td align="right">4.571920</td>
<td align="left">R._Maciel_Pinheiro</td>
</tr>
<tr class="odd">
<td align="left">284 - p1</td>
<td align="left">Side 2</td>
<td align="right">287</td>
<td align="right">180</td>
<td align="right">4.964378</td>
<td align="left">R._Maciel_Pinheiro</td>
</tr>
<tr class="even">
<td align="left">284 - p2</td>
<td align="left">Side 2</td>
<td align="right">291</td>
<td align="right">270</td>
<td align="right">4.442672</td>
<td align="left">R._Maciel_Pinheiro</td>
</tr>
<tr class="odd">
<td align="left">360 - p1</td>
<td align="left">Side 2</td>
<td align="right">363</td>
<td align="right">180</td>
<td align="right">4.594741</td>
<td align="left">R._Maciel_Pinheiro</td>
</tr>
<tr class="even">
<td align="left">360 - p2</td>
<td align="left">Side 2</td>
<td align="right">367</td>
<td align="right">270</td>
<td align="right">4.421162</td>
<td align="left">R._Maciel_Pinheiro</td>
</tr>
</tbody>
</table>
<p>++++++ Median all 4.80758224866 <br>++++++ Mean all 4.68814353441181 <br></p>
<table style="width:100%;">
<colgroup>
<col width="31%" />
<col width="10%" />
<col width="10%" />
<col width="12%" />
<col width="12%" />
<col width="10%" />
<col width="10%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">street</th>
<th align="right">mean</th>
<th align="right">median</th>
<th align="right">sd</th>
<th align="right">gini</th>
<th align="right">upper</th>
<th align="right">lower</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">R._Manoel_Pereira_de_Araújo</td>
<td align="right">3.672485</td>
<td align="right">3.637284</td>
<td align="right">0.1883041</td>
<td align="right">0.0276016</td>
<td align="right">3.755012</td>
<td align="right">3.589957</td>
</tr>
<tr class="even">
<td align="left">R._Edésio_Silva</td>
<td align="right">4.711095</td>
<td align="right">4.700303</td>
<td align="right">0.4719678</td>
<td align="right">0.0555839</td>
<td align="right">4.917944</td>
<td align="right">4.504246</td>
</tr>
<tr class="odd">
<td align="left">R._Inácio_Marquês_da_Silva</td>
<td align="right">4.713531</td>
<td align="right">4.859461</td>
<td align="right">0.5487980</td>
<td align="right">0.0649960</td>
<td align="right">4.954052</td>
<td align="right">4.473010</td>
</tr>
<tr class="even">
<td align="left">R._Maciel_Pinheiro</td>
<td align="right">4.777779</td>
<td align="right">4.798712</td>
<td align="right">0.2344981</td>
<td align="right">0.0273481</td>
<td align="right">4.880552</td>
<td align="right">4.675006</td>
</tr>
<tr class="odd">
<td align="left">Av._Mal._Floriano_Peixoto</td>
<td align="right">4.957391</td>
<td align="right">5.028135</td>
<td align="right">0.3305999</td>
<td align="right">0.0350720</td>
<td align="right">5.102283</td>
<td align="right">4.812499</td>
</tr>
<tr class="even">
<td align="left">R._Cristina_Procópio_Silva</td>
<td align="right">4.979669</td>
<td align="right">5.204548</td>
<td align="right">0.7201075</td>
<td align="right">0.0778490</td>
<td align="right">5.295270</td>
<td align="right">4.664068</td>
</tr>
</tbody>
</table>
<div class='row'>
<div class="col-xs-3" style="background-color:#00b200">
<img src='/home/davidcmm/workspace_doutorado/campinaPulse/scripts/analise/dadosSet17/percepcaoLocal/agradavel/melhores/intersects/R._Maciel_Pinheiro_130_90' width='300px'>
<p style="color:white;font-size:90%">
best<br>R._Maciel_Pinheiro_130_90-&gt; 5.014312(0.003616276)
</p>
</div>
<div class="col-xs-3" style="background-color:#009900">
<img src='/home/davidcmm/workspace_doutorado/campinaPulse/scripts/analise/dadosSet17/percepcaoLocal/agradavel/piores/intersects/R._Maciel_Pinheiro_130_180' width='300px'>
<p style="color:white;font-size:90%">
worst<br>R._Maciel_Pinheiro_130_180-&gt; 4.807788(0.000212803)
</p>
</div>
<div class="col-xs-3" style="background-color:#009900">
<img src='/home/davidcmm/workspace_doutorado/campinaPulse/scripts/analise/dadosSet17/percepcaoLocal/agradavel/piores/intersects/R._Maciel_Pinheiro_130_270' width='300px'>
<p style="color:white;font-size:90%">
worst<br>R._Maciel_Pinheiro_130_270-&gt; 4.719232(-0.0008662216)
</p>
</div>
<div class="col-xs-3" style="background-color:#007f00">
<img src='/home/davidcmm/workspace_doutorado/campinaPulse/scripts/analise/dadosSet17/percepcaoLocal/agradavel/piores/intersects/R._Maciel_Pinheiro_130_360' width='300px'>
<p style="color:white;font-size:90%">
worst<br>R._Maciel_Pinheiro_130_360-&gt; 4.662146(-0.001993311)
</p>
</div>
<div class="col-xs-3" style="background-color:#00b200">
<img src='/home/davidcmm/workspace_doutorado/campinaPulse/scripts/analise/dadosSet17/percepcaoLocal/agradavel/melhores/intersects/R._Maciel_Pinheiro_190_90' width='300px'>
<p style="color:white;font-size:90%">
best<br>R._Maciel_Pinheiro_190_90-&gt; 5.093964(0.004274293)
</p>
</div>
<div class="col-xs-3" style="background-color:#007f00">
<img src='/home/davidcmm/workspace_doutorado/campinaPulse/scripts/analise/dadosSet17/percepcaoLocal/agradavel/piores/intersects/R._Maciel_Pinheiro_190_180' width='300px'>
<p style="color:white;font-size:90%">
worst<br>R._Maciel_Pinheiro_190_180-&gt; 4.434079(-0.005836101)
</p>
</div>
<div class="col-xs-3" style="background-color:#00b200">
<img src='/home/davidcmm/workspace_doutorado/campinaPulse/scripts/analise/dadosSet17/percepcaoLocal/agradavel/melhores/intersects/R._Maciel_Pinheiro_190_270' width='300px'>
<p style="color:white;font-size:90%">
best<br>R._Maciel_Pinheiro_190_270-&gt; 5.002695(0.002957916)
</p>
</div>
<div class="col-xs-3" style="background-color:#00b200">
<img src='/home/davidcmm/workspace_doutorado/campinaPulse/scripts/analise/dadosSet17/percepcaoLocal/agradavel/melhores/intersects/R._Maciel_Pinheiro_190_360' width='300px'>
<p style="color:white;font-size:90%">
best<br>R._Maciel_Pinheiro_190_360-&gt; 5.028834(0.003362825)
</p>
</div>
<div class="col-xs-3" style="background-color:#00b200">
<img src='/home/davidcmm/workspace_doutorado/campinaPulse/scripts/analise/dadosSet17/percepcaoLocal/agradavel/melhores/intersects/R._Maciel_Pinheiro_248_90' width='300px'>
<p style="color:white;font-size:90%">
best<br>R._Maciel_Pinheiro_248_90-&gt; 4.979997(0.00318237)
</p>
</div>
<div class="col-xs-3" style="background-color:#00b200">
<img src='/home/davidcmm/workspace_doutorado/campinaPulse/scripts/analise/dadosSet17/percepcaoLocal/agradavel/melhores/intersects/R._Maciel_Pinheiro_248_180' width='300px'>
<p style="color:white;font-size:90%">
best<br>R._Maciel_Pinheiro_248_180-&gt; 5.123118(0.005190108)
</p>
</div>
<div class="col-xs-3" style="background-color:#007f00">
<img src='/home/davidcmm/workspace_doutorado/campinaPulse/scripts/analise/dadosSet17/percepcaoLocal/agradavel/piores/intersects/R._Maciel_Pinheiro_248_270' width='300px'>
<p style="color:white;font-size:90%">
worst<br>R._Maciel_Pinheiro_248_270-&gt; 4.57192(-0.003372157)
</p>
</div>
<div class="col-xs-3" style="background-color:#007f00">
<img src='/home/davidcmm/workspace_doutorado/campinaPulse/scripts/analise/dadosSet17/percepcaoLocal/agradavel/piores/intersects/R._Maciel_Pinheiro_248_360' width='300px'>
<p style="color:white;font-size:90%">
worst<br>R._Maciel_Pinheiro_248_360-&gt; 4.491837(-0.00447087)
</p>
</div>
<div class="col-xs-3" style="background-color:#009900">
<img src='/home/davidcmm/workspace_doutorado/campinaPulse/scripts/analise/dadosSet17/percepcaoLocal/agradavel/melhores/intersects/R._Maciel_Pinheiro_284_90' width='300px'>
<p style="color:white;font-size:90%">
best<br>R._Maciel_Pinheiro_284_90-&gt; 4.789855(0.0001411447)
</p>
</div>
<div class="col-xs-3" style="background-color:#009900">
<img src='/home/davidcmm/workspace_doutorado/campinaPulse/scripts/analise/dadosSet17/percepcaoLocal/agradavel/melhores/intersects/R._Maciel_Pinheiro_284_180' width='300px'>
<p style="color:white;font-size:90%">
best<br>R._Maciel_Pinheiro_284_180-&gt; 4.964378(0.003167707)
</p>
</div>
<div class="col-xs-3" style="background-color:#007f00">
<img src='/home/davidcmm/workspace_doutorado/campinaPulse/scripts/analise/dadosSet17/percepcaoLocal/agradavel/piores/intersects/R._Maciel_Pinheiro_284_270' width='300px'>
<p style="color:white;font-size:90%">
worst<br>R._Maciel_Pinheiro_284_270-&gt; 4.442672(-0.004997031)
</p>
</div>
<div class="col-xs-3" style="background-color:#009900">
<img src='/home/davidcmm/workspace_doutorado/campinaPulse/scripts/analise/dadosSet17/percepcaoLocal/agradavel/melhores/intersects/R._Maciel_Pinheiro_284_360' width='300px'>
<p style="color:white;font-size:90%">
best<br>R._Maciel_Pinheiro_284_360-&gt; 4.807568(0.0003866582)
</p>
</div>
<div class="col-xs-3" style="background-color:#007f00">
<img src='/home/davidcmm/workspace_doutorado/campinaPulse/scripts/analise/dadosSet17/percepcaoLocal/agradavel/piores/intersects/R._Maciel_Pinheiro_360_90' width='300px'>
<p style="color:white;font-size:90%">
worst<br>R._Maciel_Pinheiro_360_90-&gt; 4.652515(-0.001224873)
</p>
</div>
<div class="col-xs-3" style="background-color:#007f00">
<img src='/home/davidcmm/workspace_doutorado/campinaPulse/scripts/analise/dadosSet17/percepcaoLocal/agradavel/piores/intersects/R._Maciel_Pinheiro_360_180' width='300px'>
<p style="color:white;font-size:90%">
worst<br>R._Maciel_Pinheiro_360_180-&gt; 4.594741(-0.002244838)
</p>
</div>
<div class="col-xs-3" style="background-color:#007f00">
<img src='/home/davidcmm/workspace_doutorado/campinaPulse/scripts/analise/dadosSet17/percepcaoLocal/agradavel/piores/intersects/R._Maciel_Pinheiro_360_270' width='300px'>
<p style="color:white;font-size:90%">
worst<br>R._Maciel_Pinheiro_360_270-&gt; 4.421162(-0.004808441)
</p>
</div>
<div class="col-xs-3" style="background-color:#009900">
<img src='/home/davidcmm/workspace_doutorado/campinaPulse/scripts/analise/dadosSet17/percepcaoLocal/agradavel/melhores/intersects/R._Maciel_Pinheiro_360_360' width='300px'>
<p style="color:white;font-size:90%">
best<br>R._Maciel_Pinheiro_360_360-&gt; 4.952766(0.003531357)
</p>
</div>
<ol style="list-style-type: decimal">
<li>Locais problemáticos na rua (olhando as fotos):
<ul>
<li>130 angulo 360 (manutenção de prédio);</li>
<li>190 angulo 180 (manutenção de prédio);</li>
<li>284 360 (manutenção de prédio);</li>
<li>360 270 (manutenção de prédio).</li>
<li>Não existem árvores na rua?</li>
</ul></li>
<li>Virtudes na rua (olhando as fotos):
<ul>
<li>Em geral bem conservada</li>
<li>360, 360 (prédio conservado + praça)</li>
<li>190, 90 e 360 (prédios ainda mais bem conservados + estilo)</li>
<li>130, 90, 180 e 270 (prédios ainda mais bem conservados + estilo)</li>
</ul></li>
</ol>
<blockquote>
<blockquote>
<p>Olhando os Q-Scores ao longo da rua</p>
</blockquote>
</blockquote>
<ol start="2" style="list-style-type: decimal">
<li>Melhor e pior local da rua:
<ul>
<li>248 angulo 180 (boa manutenção)</li>
<li>190 180 (manutenção de prédio faltando)</li>
</ul></li>
<li>Melhor e pior lado da rua:
<ul>
<li>O side1 parece ligeiramente melhor (130, 284 empate, 190, 360 side1, 248 side2)</li>
</ul></li>
<li>Melhor e pior área da rua (considerando os dois lados):
<ul>
<li>confuso!</li>
</ul></li>
<li>Áreas muito diferentes entre lados:
<ul>
<li>284 a 360, com side1 ligeiramente melhor (no side2 temos um estacionamento e um caminhão na vista)</li>
</ul></li>
<li>Descontinuidades no mesmo lado:
<ul>
<li>190 side2, diferença de 0.9 -&gt; prédio precisando de manutenção x boa manutenção</li>
<li>248 side1, diferença de 0.7 -&gt; menos identificadores, prédios um pouco mais novos x identificadores e prédios um pouco mais antigos</li>
<li>248 side2, diferença de 0.5 -&gt; menos identificadores, prédios um pouco mais novos x identificadores e prédios um pouco mais antigos</li>
<li>284 side2, diferença de 0.5 -&gt; boa manutenção x estacionamento, prédio, carros</li>
</ul></li>
<li>Heterogeneidade/Homogeneidade no ponto:
<ul>
<li>Os pontos mais heterogêneos foram o 248 (boa manutenção x mais identificadores/prédios) e 190 (boa manutenção x prédio que precisa de manutenção).</li>
<li>O mais homogêneo foi o 284 (boa manutenção, apesar do estacionamento e prédio precisando de manutenção)</li>
</ul></li>
<li>Foram encontrados os problemas?
<ul>
<li>Apenas o 190 dos 4 pontos foi encontrado.</li>
<li>A valorização da presença de árvores no final da rua pareceu não fazer um efeito tão alto em relação ao restante da rua.</li>
<li>O 130 seria encontrado se continuássemos a olhar descontinuidades por lado.</li>
<li>O 360 270 seria verificado se olhando para a praça comparássemos.</li>
</ul></li>
<li>O que é a rua?
<ul>
<li>A nota média/mediana é boa ou ruim? De mediana para boa</li>
<li>Existe muita variação? Rua mais homogênea, com pequenas variações entre alguns de seus pontos. Variações parecem estar ligadas ao estado de manutenção e identificadores</li>
<li>Existe um lado melhor? O side1 parece ligeiramente melhor</li>
<li>Existe uma área melhor pior? Do 190 ao 248 parece ser a melhor área, e do 248 ao 284 a pior</li>
</ul></li>
</ol>
<blockquote>
<blockquote>
<p>Olhando o surprise maps (uniforme + base rate + normal)</p>
</blockquote>
</blockquote>
<ol style="list-style-type: decimal">
<li>Máximo e Mínimo?
<ul>
<li>248 angulo 180 (boa manutenção)</li>
<li>190 180 (manutenção de prédio faltando)</li>
</ul></li>
<li>Mais diversidade?</li>
</ol>
<ul>
<li>190, p1 side2 (180) afastado (prédio precisando de manutenção)</li>
<li>248, 1 ponto de cada side separado (prédios conservados, estilo + motos, estilos)</li>
<li>130, 1 ponto de cada side separado (prédios conservados, estilo + estilo, prédio precisando de conservação)</li>
<li>360, p2 side1 melhor (melhor conservação, estilo, sem caminhão + praça)</li>
<li>284, p2 side2 (270) pior (estacionamento + prédio + carros)</li>
</ul>
<ol start="3" style="list-style-type: decimal">
<li>Menor diversidade?</li>
</ol>
<ul>
<li>alguma heterogeneidade em todos os pontos 4 Diferenças/saltos no lado?</li>
<li>130, 1 ponto de cada side separado</li>
<li>190, side2 separado</li>
<li>248, 1 ponto de cada side separado</li>
<li>284, side2 separado</li>
<li>360, side1 separado</li>
</ul>
<ol start="5" style="list-style-type: decimal">
<li>Avaliação Problemas</li>
</ol>
<ul>
<li>Pesquisador: 5 problemas (descritos acima)</li>
<li>Recall = método / pesquisador = 3 de 5 (arvore no geral e 284 360 não foram percebidos) = 0.6</li>
<li>Precisão = reais / método = 3/5 (248 1 ponto de cada side separado, 284 270 afastado) = 0.6</li>
</ul>
<ol start="6" style="list-style-type: decimal">
<li>Avaliação Virtudes</li>
</ol>
<ul>
<li>Pesquisador: 4 virtudes (descritos acima)</li>
<li>Recall = método / pesquisador = 3.66/4 = 0.91 (130 o método acha 2 pontos legais, falta 1)</li>
<li>Precisão = reais / método = 3/5 = 0.6 (248 180, 284 3 pontos legais)</li>
</ul>
<ol start="7" style="list-style-type: decimal">
<li>Descrição</li>
</ol>
<ul>
<li>Média/mediana: 4.84/4.88 &gt; 4.68/4.82 -&gt; rua de mediana para boa</li>
<li>Variação no surprise? Temos alternância de pontos melhores e piores ao longo de toda a rua</li>
<li>Lado melhor? Side1 (7) x Side2(4) -&gt; side1 ligeiramente melhor</li>
<li>Região melhor? O meio da rua (190 a 284) parece ter mais concentração de surpresas positivas, confirmado olhando os scores</li>
</ul>
</div>
<div id="manoel-pereira" class="section level1">
<h1>Manoel Pereira</h1>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  manoel$qscore
## W = 0.96046, p-value = 0.553</code></pre>
<pre><code>##       mean          sd    
##   3.67248457   0.18353610 
##  (0.04103992) (0.02901961)</code></pre>
<pre><code>## [1] &quot;&gt;&gt;&gt; GINI da rua:  0.027601624422647&quot;</code></pre>
<pre><code>##   num      value
## 1 370 0.03995421
## 2 392 0.02564437
## 3 300 0.02507132
## 4 188 0.01555671
## 5 222 0.01203434</code></pre>
<pre><code>##   num value
## 1 188   NaN
## 2 222   NaN
## 3 300   NaN
## 4 370   NaN
## 5 392   NaN</code></pre>
<pre><code>##   num value
## 1 188   NaN
## 2 222   NaN
## 3 300   NaN
## 4 370   NaN
## 5 392   NaN</code></pre>
<pre><code>## Adding missing grouping variables: `num`</code></pre>
<p><img src="analisaPorRua2_files/figure-html/unnamed-chunk-14-1.png" width="1152"  /></p>
<table>
<thead>
<tr class="header">
<th align="left">xlabel</th>
<th align="left">side</th>
<th align="right">num</th>
<th align="right">angle</th>
<th align="right">V3</th>
<th align="left">street</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">188 - p1</td>
<td align="left">Side 1</td>
<td align="right">188</td>
<td align="right">135</td>
<td align="right">3.717965</td>
<td align="left">R._Manoel_Pereira_de_Araújo</td>
</tr>
<tr class="even">
<td align="left">188 - p2</td>
<td align="left">Side 1</td>
<td align="right">192</td>
<td align="right">22</td>
<td align="right">3.911820</td>
<td align="left">R._Manoel_Pereira_de_Araújo</td>
</tr>
<tr class="odd">
<td align="left">222 - p1</td>
<td align="left">Side 1</td>
<td align="right">222</td>
<td align="right">135</td>
<td align="right">3.562807</td>
<td align="left">R._Manoel_Pereira_de_Araújo</td>
</tr>
<tr class="even">
<td align="left">222 - p2</td>
<td align="left">Side 1</td>
<td align="right">226</td>
<td align="right">22</td>
<td align="right">3.615163</td>
<td align="left">R._Manoel_Pereira_de_Araújo</td>
</tr>
<tr class="odd">
<td align="left">300 - p1</td>
<td align="left">Side 1</td>
<td align="right">300</td>
<td align="right">135</td>
<td align="right">3.375664</td>
<td align="left">R._Manoel_Pereira_de_Araújo</td>
</tr>
<tr class="even">
<td align="left">300 - p2</td>
<td align="left">Side 1</td>
<td align="right">304</td>
<td align="right">22</td>
<td align="right">3.585796</td>
<td align="left">R._Manoel_Pereira_de_Araújo</td>
</tr>
<tr class="odd">
<td align="left">370 - p1</td>
<td align="left">Side 1</td>
<td align="right">370</td>
<td align="right">135</td>
<td align="right">4.046046</td>
<td align="left">R._Manoel_Pereira_de_Araújo</td>
</tr>
<tr class="even">
<td align="left">370 - p2</td>
<td align="left">Side 1</td>
<td align="right">374</td>
<td align="right">22</td>
<td align="right">3.321632</td>
<td align="left">R._Manoel_Pereira_de_Araújo</td>
</tr>
<tr class="odd">
<td align="left">392 - p1</td>
<td align="left">Side 1</td>
<td align="right">392</td>
<td align="right">293</td>
<td align="right">4.030718</td>
<td align="left">R._Manoel_Pereira_de_Araújo</td>
</tr>
<tr class="even">
<td align="left">392 - p2</td>
<td align="left">Side 1</td>
<td align="right">396</td>
<td align="right">22</td>
<td align="right">3.680914</td>
<td align="left">R._Manoel_Pereira_de_Araújo</td>
</tr>
<tr class="odd">
<td align="left">188 - p1</td>
<td align="left">Side 2</td>
<td align="right">191</td>
<td align="right">203</td>
<td align="right">3.616612</td>
<td align="left">R._Manoel_Pereira_de_Araújo</td>
</tr>
<tr class="even">
<td align="left">188 - p2</td>
<td align="left">Side 2</td>
<td align="right">195</td>
<td align="right">315</td>
<td align="right">3.675074</td>
<td align="left">R._Manoel_Pereira_de_Araújo</td>
</tr>
<tr class="odd">
<td align="left">222 - p1</td>
<td align="left">Side 2</td>
<td align="right">225</td>
<td align="right">203</td>
<td align="right">3.786199</td>
<td align="left">R._Manoel_Pereira_de_Araújo</td>
</tr>
<tr class="even">
<td align="left">222 - p2</td>
<td align="left">Side 2</td>
<td align="right">229</td>
<td align="right">315</td>
<td align="right">3.584980</td>
<td align="left">R._Manoel_Pereira_de_Araújo</td>
</tr>
<tr class="odd">
<td align="left">300 - p1</td>
<td align="left">Side 2</td>
<td align="right">303</td>
<td align="right">203</td>
<td align="right">3.605822</td>
<td align="left">R._Manoel_Pereira_de_Araújo</td>
</tr>
<tr class="even">
<td align="left">300 - p2</td>
<td align="left">Side 2</td>
<td align="right">307</td>
<td align="right">315</td>
<td align="right">3.850968</td>
<td align="left">R._Manoel_Pereira_de_Araújo</td>
</tr>
<tr class="odd">
<td align="left">370 - p1</td>
<td align="left">Side 2</td>
<td align="right">373</td>
<td align="right">203</td>
<td align="right">3.657956</td>
<td align="left">R._Manoel_Pereira_de_Araújo</td>
</tr>
<tr class="even">
<td align="left">370 - p2</td>
<td align="left">Side 2</td>
<td align="right">377</td>
<td align="right">315</td>
<td align="right">3.508412</td>
<td align="left">R._Manoel_Pereira_de_Araújo</td>
</tr>
<tr class="odd">
<td align="left">392 - p1</td>
<td align="left">Side 2</td>
<td align="right">395</td>
<td align="right">112</td>
<td align="right">3.768899</td>
<td align="left">R._Manoel_Pereira_de_Araújo</td>
</tr>
<tr class="even">
<td align="left">392 - p2</td>
<td align="left">Side 2</td>
<td align="right">399</td>
<td align="right">225</td>
<td align="right">3.546243</td>
<td align="left">R._Manoel_Pereira_de_Araújo</td>
</tr>
</tbody>
</table>
<p>++++++ Median all 4.80758224866 <br>++++++ Mean all 4.68814353441181 <br></p>
<table style="width:100%;">
<colgroup>
<col width="31%" />
<col width="10%" />
<col width="10%" />
<col width="12%" />
<col width="12%" />
<col width="10%" />
<col width="10%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">street</th>
<th align="right">mean</th>
<th align="right">median</th>
<th align="right">sd</th>
<th align="right">gini</th>
<th align="right">upper</th>
<th align="right">lower</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">R._Manoel_Pereira_de_Araújo</td>
<td align="right">3.672485</td>
<td align="right">3.637284</td>
<td align="right">0.1883041</td>
<td align="right">0.0276016</td>
<td align="right">3.755012</td>
<td align="right">3.589957</td>
</tr>
<tr class="even">
<td align="left">R._Edésio_Silva</td>
<td align="right">4.711095</td>
<td align="right">4.700303</td>
<td align="right">0.4719678</td>
<td align="right">0.0555839</td>
<td align="right">4.917944</td>
<td align="right">4.504246</td>
</tr>
<tr class="odd">
<td align="left">R._Inácio_Marquês_da_Silva</td>
<td align="right">4.713531</td>
<td align="right">4.859461</td>
<td align="right">0.5487980</td>
<td align="right">0.0649960</td>
<td align="right">4.954052</td>
<td align="right">4.473010</td>
</tr>
<tr class="even">
<td align="left">R._Maciel_Pinheiro</td>
<td align="right">4.777779</td>
<td align="right">4.798712</td>
<td align="right">0.2344981</td>
<td align="right">0.0273481</td>
<td align="right">4.880552</td>
<td align="right">4.675006</td>
</tr>
<tr class="odd">
<td align="left">Av._Mal._Floriano_Peixoto</td>
<td align="right">4.957391</td>
<td align="right">5.028135</td>
<td align="right">0.3305999</td>
<td align="right">0.0350720</td>
<td align="right">5.102283</td>
<td align="right">4.812499</td>
</tr>
<tr class="even">
<td align="left">R._Cristina_Procópio_Silva</td>
<td align="right">4.979669</td>
<td align="right">5.204548</td>
<td align="right">0.7201075</td>
<td align="right">0.0778490</td>
<td align="right">5.295270</td>
<td align="right">4.664068</td>
</tr>
</tbody>
</table>
<div class='row'>
<div class="col-xs-3" style="background-color:#004c00">
<img src='/home/davidcmm/workspace_doutorado/campinaPulse/scripts/analise/dadosSet17/percepcaoLocal/agradavel/melhores/intersects/R._Manoel_Pereira_de_Ara%C3%BAjo_188_22' width='300px'>
<p style="color:white;font-size:90%">
best<br>R._Manoel_Pereira_de_Araújo_188_22-&gt; 3.91182(0.004417162)
</p>
</div>
<div class="col-xs-3" style="background-color:#003300">
<img src='/home/davidcmm/workspace_doutorado/campinaPulse/scripts/analise/dadosSet17/percepcaoLocal/agradavel/piores/intersects/R._Manoel_Pereira_de_Ara%C3%BAjo_188_135' width='300px'>
<p style="color:white;font-size:90%">
worst<br>R._Manoel_Pereira_de_Araújo_188_135-&gt; 3.717965(0.0004469701)
</p>
</div>
<div class="col-xs-3" style="background-color:#003300">
<img src='/home/davidcmm/workspace_doutorado/campinaPulse/scripts/analise/dadosSet17/percepcaoLocal/agradavel/piores/intersects/R._Manoel_Pereira_de_Ara%C3%BAjo_188_203' width='300px'>
<p style="color:white;font-size:90%">
worst<br>R._Manoel_Pereira_de_Araújo_188_203-&gt; 3.616612(-0.001513601)
</p>
</div>
<div class="col-xs-3" style="background-color:#003300">
<img src='/home/davidcmm/workspace_doutorado/campinaPulse/scripts/analise/dadosSet17/percepcaoLocal/agradavel/piores/intersects/R._Manoel_Pereira_de_Ara%C3%BAjo_188_315' width='300px'>
<p style="color:white;font-size:90%">
worst<br>R._Manoel_Pereira_de_Araújo_188_315-&gt; 3.675074(-0.0001238633)
</p>
</div>
<div class="col-xs-3" style="background-color:#003300">
<img src='/home/davidcmm/workspace_doutorado/campinaPulse/scripts/analise/dadosSet17/percepcaoLocal/agradavel/piores/intersects/R._Manoel_Pereira_de_Ara%C3%BAjo_222_22' width='300px'>
<p style="color:white;font-size:90%">
worst<br>R._Manoel_Pereira_de_Araújo_222_22-&gt; 3.615163(-0.000729411)
</p>
</div>
<div class="col-xs-3" style="background-color:#001900">
<img src='/home/davidcmm/workspace_doutorado/campinaPulse/scripts/analise/dadosSet17/percepcaoLocal/agradavel/piores/intersects/R._Manoel_Pereira_de_Ara%C3%BAjo_222_135' width='300px'>
<p style="color:white;font-size:90%">
worst<br>R._Manoel_Pereira_de_Araújo_222_135-&gt; 3.562807(-0.002001285)
</p>
</div>
<div class="col-xs-3" style="background-color:#003300">
<img src='/home/davidcmm/workspace_doutorado/campinaPulse/scripts/analise/dadosSet17/percepcaoLocal/agradavel/melhores/intersects/R._Manoel_Pereira_de_Ara%C3%BAjo_222_203' width='300px'>
<p style="color:white;font-size:90%">
best<br>R._Manoel_Pereira_de_Araújo_222_203-&gt; 3.786199(0.002700322)
</p>
</div>
<div class="col-xs-3" style="background-color:#003300">
<img src='/home/davidcmm/workspace_doutorado/campinaPulse/scripts/analise/dadosSet17/percepcaoLocal/agradavel/piores/intersects/R._Manoel_Pereira_de_Ara%C3%BAjo_222_315' width='300px'>
<p style="color:white;font-size:90%">
worst<br>R._Manoel_Pereira_de_Araújo_222_315-&gt; 3.58498(-0.001468388)
</p>
</div>
<div class="col-xs-3" style="background-color:#003300">
<img src='/home/davidcmm/workspace_doutorado/campinaPulse/scripts/analise/dadosSet17/percepcaoLocal/agradavel/piores/intersects/R._Manoel_Pereira_de_Ara%C3%BAjo_300_22' width='300px'>
<p style="color:white;font-size:90%">
worst<br>R._Manoel_Pereira_de_Araújo_300_22-&gt; 3.585796(-0.001149088)
</p>
</div>
<div class="col-xs-3" style="background-color:#001900">
<img src='/home/davidcmm/workspace_doutorado/campinaPulse/scripts/analise/dadosSet17/percepcaoLocal/agradavel/piores/intersects/R._Manoel_Pereira_de_Ara%C3%BAjo_300_135' width='300px'>
<p style="color:white;font-size:90%">
worst<br>R._Manoel_Pereira_de_Araújo_300_135-&gt; 3.375664(-0.00544214)
</p>
</div>
<div class="col-xs-3" style="background-color:#003300">
<img src='/home/davidcmm/workspace_doutorado/campinaPulse/scripts/analise/dadosSet17/percepcaoLocal/agradavel/piores/intersects/R._Manoel_Pereira_de_Ara%C3%BAjo_300_203' width='300px'>
<p style="color:white;font-size:90%">
worst<br>R._Manoel_Pereira_de_Araújo_300_203-&gt; 3.605822(-0.0007038687)
</p>
</div>
<div class="col-xs-3" style="background-color:#004c00">
<img src='/home/davidcmm/workspace_doutorado/campinaPulse/scripts/analise/dadosSet17/percepcaoLocal/agradavel/melhores/intersects/R._Manoel_Pereira_de_Ara%C3%BAjo_300_315' width='300px'>
<p style="color:white;font-size:90%">
best<br>R._Manoel_Pereira_de_Araújo_300_315-&gt; 3.850968(0.004149439)
</p>
</div>
<div class="col-xs-3" style="background-color:#001900">
<img src='/home/davidcmm/workspace_doutorado/campinaPulse/scripts/analise/dadosSet17/percepcaoLocal/agradavel/piores/intersects/R._Manoel_Pereira_de_Ara%C3%BAjo_370_22' width='300px'>
<p style="color:white;font-size:90%">
worst<br>R._Manoel_Pereira_de_Araújo_370_22-&gt; 3.321632(-0.006652221)
</p>
</div>
<div class="col-xs-3" style="background-color:#004c00">
<img src='/home/davidcmm/workspace_doutorado/campinaPulse/scripts/analise/dadosSet17/percepcaoLocal/agradavel/melhores/intersects/R._Manoel_Pereira_de_Ara%C3%BAjo_370_135' width='300px'>
<p style="color:white;font-size:90%">
best<br>R._Manoel_Pereira_de_Araújo_370_135-&gt; 4.046046(0.007582035)
</p>
</div>
<div class="col-xs-3" style="background-color:#003300">
<img src='/home/davidcmm/workspace_doutorado/campinaPulse/scripts/analise/dadosSet17/percepcaoLocal/agradavel/piores/intersects/R._Manoel_Pereira_de_Ara%C3%BAjo_370_203' width='300px'>
<p style="color:white;font-size:90%">
worst<br>R._Manoel_Pereira_de_Araújo_370_203-&gt; 3.657956(-0.0001025604)
</p>
</div>
<div class="col-xs-3" style="background-color:#001900">
<img src='/home/davidcmm/workspace_doutorado/campinaPulse/scripts/analise/dadosSet17/percepcaoLocal/agradavel/piores/intersects/R._Manoel_Pereira_de_Ara%C3%BAjo_370_315' width='300px'>
<p style="color:white;font-size:90%">
worst<br>R._Manoel_Pereira_de_Araújo_370_315-&gt; 3.508412(-0.003135544)
</p>
</div>
<div class="col-xs-3" style="background-color:#003300">
<img src='/home/davidcmm/workspace_doutorado/campinaPulse/scripts/analise/dadosSet17/percepcaoLocal/agradavel/piores/intersects/R._Manoel_Pereira_de_Ara%C3%BAjo_392_22' width='300px'>
<p style="color:white;font-size:90%">
worst<br>R._Manoel_Pereira_de_Araújo_392_22-&gt; 3.680914(-0.0001814837)
</p>
</div>
<div class="col-xs-3" style="background-color:#003300">
<img src='/home/davidcmm/workspace_doutorado/campinaPulse/scripts/analise/dadosSet17/percepcaoLocal/agradavel/piores/intersects/R._Manoel_Pereira_de_Ara%C3%BAjo_392_112' width='300px'>
<p style="color:white;font-size:90%">
worst<br>R._Manoel_Pereira_de_Araújo_392_112-&gt; 3.768899(0.001273968)
</p>
</div>
<div class="col-xs-3" style="background-color:#001900">
<img src='/home/davidcmm/workspace_doutorado/campinaPulse/scripts/analise/dadosSet17/percepcaoLocal/agradavel/piores/intersects/R._Manoel_Pereira_de_Ara%C3%BAjo_392_225' width='300px'>
<p style="color:white;font-size:90%">
worst<br>R._Manoel_Pereira_de_Araújo_392_225-&gt; 3.546243(-0.003341771)
</p>
</div>
<div class="col-xs-3" style="background-color:#004c00">
<img src='/home/davidcmm/workspace_doutorado/campinaPulse/scripts/analise/dadosSet17/percepcaoLocal/agradavel/melhores/intersects/R._Manoel_Pereira_de_Ara%C3%BAjo_392_293' width='300px'>
<p style="color:white;font-size:90%">
best<br>R._Manoel_Pereira_de_Araújo_392_293-&gt; 4.030718(0.006460155)
</p>
</div>
<ol style="list-style-type: decimal">
<li>Locais problemáticos na rua (olhando as fotos):
<ul>
<li>A rua em geral precisa de manutenção.</li>
<li>Alguns pontos parecem ainda piores como o 222 angulo 22 (prédio acabado + itens na rua), 300 angulo 22 e 135 (barraca, itens na rua), 370 angulo 22, 203 e 315 (prédios acabados, barracas).</li>
<li>Ausência de árvores de fato na rua.</li>
</ul></li>
<li>Virtudes na rua (olhando as fotos):
<ul>
<li>222, 203 e 315 (prédios mais bem conservados, apesar de parecerem galpões)</li>
<li>300, 203 (prédio melhor conservado)</li>
</ul></li>
</ol>
<blockquote>
<blockquote>
<p>Olhando os Q-Scores ao longo da rua</p>
</blockquote>
</blockquote>
<ol start="2" style="list-style-type: decimal">
<li>Melhor e pior local da rua:
<ul>
<li>222 p1 side2 (prédio mais conservado da sucata)</li>
<li>188 p1 side2 (prédio acabado, carros, itens na rua)</li>
</ul></li>
<li>Melhor e pior lado da rua:
<ul>
<li>Não fica claro</li>
</ul></li>
<li>Melhor e pior área da rua (considerando os dois lados):
<ul>
<li>confuso!</li>
</ul></li>
<li>Áreas muito diferentes entre lados:
<ul>
<li>300 a 370 (um lado com alguns pontos melhor conservados, o outro lado com mais variação);</li>
<li>222 a 300 (um lado com alguns pontos melhor conservados, o outro lado com mais variação)</li>
</ul></li>
<li>Descontinuidades no mesmo lado:
<ul>
<li>188 side2, diferença de 0.4 -&gt; manutenção um pouco melhor</li>
<li>222 side2, diferença de 0.4 -&gt; manutenção de prédios e mais itens na rua na imagem menos preferida</li>
<li>370 side1, diferença de 0.6 -&gt; pequena variação de manutenção, menos itens na rua na imagem preferida</li>
</ul></li>
<li>Heterogeneidade/Homogeneidade no ponto:
<ul>
<li>Os pontos mais heterogêneos foram o 370 (manutenção um pouco melhor em alguns locais e menos itens na rua) e o 188 (manutenção um pouco melhor em alguns locais).</li>
<li>O ponto mais homogêneo foi o 392 (melhor manutenção em média dos prédios)</li>
</ul></li>
<li>Foram encontrados os problemas?
<ul>
<li>Olhando as diferenças entre lados englobamos os números 222, 300 e 370.</li>
<li>Olhando as maiores descontinuidades aparentes englobamos 222 e 370.</li>
<li>Como a rua toda praticamente não tem árvores fica difícil pesar este aspecto dado a pobreza de manutenção, todavia a imagem 370 315 apesar de péssima manutenção e barracas/itens na rua teve uma nota melhor que outros locais e as árvores foram marcadas junto com o céu.</li>
</ul></li>
<li>O que é a rua?
<ul>
<li>A nota média/mediana é boa ou ruim? De mediana para ruim, com notas baixas</li>
<li>Existe muita variação? Rua mais homogênea, com alguns pontos que se destacam positivamente por ter uma melhor manutenção ou menos itens na rua e outros que se destacam negativamente por terem manutenção ainda pior e/ou mais itens na rua</li>
<li>Existe um lado melhor? Não</li>
<li>Existe uma área melhor pior? Não</li>
</ul></li>
</ol>
<blockquote>
<blockquote>
<p>Olhando o surprise maps (uniforme + base rate + normal)</p>
</blockquote>
</blockquote>
<ol style="list-style-type: decimal">
<li>Máximo e Mínimo?
<ul>
<li>222 p1 side2 (prédio mais conservado da sucata)</li>
<li>188 p1 side2 (prédio acabado, carros, itens na rua)</li>
</ul></li>
<li>Mais diversidade?</li>
</ol>
<ul>
<li>370, side1 separado (melhor conservação, menos itens x pior conservação, mais itens na rua)</li>
<li>392, 1 ponto de cada side separado (prédios melhores conservados x construção, mais itens na rua)</li>
<li>222, side2 separado, side1 pouco separado (side2 - prédio mais conservado, menos itens na rua x prédios pior conservado a direita; side1 - prédios melhor conservado, menos itens na rua)</li>
<li>300, p1 side1 pior (muitos itens na rua)</li>
<li>188, p1 side2 pior (prédio pior conservação, estilo dos prédios?)</li>
</ul>
<ol start="3" style="list-style-type: decimal">
<li>Menor diversidade?</li>
</ol>
<ul>
<li>Todos os pontos tem alguma diversidade 4 Diferenças/saltos no lado?</li>
<li>392, 1 ponto de cada side separado</li>
<li>370, side1 separado</li>
<li>300, side1 separado</li>
<li>222, side2 mais separado que side1</li>
<li>188, side2 mais separado que side1</li>
</ul>
<ol start="5" style="list-style-type: decimal">
<li>Avaliação Problemas</li>
</ol>
<ul>
<li>Pesquisador: 5 problemas (descritos acima)</li>
<li>Recall = método / pesquisador = 3.66/5 = 0.73 (falta de arvore e um ponto do 370)</li>
<li>Precisão = reais / método = 3/6 = 0.5 (188 p1 side2, 392 1 ponto de cada side, 188 homogeneo mais negativo)</li>
</ul>
<ol start="6" style="list-style-type: decimal">
<li>Avaliação Virtudes</li>
</ol>
<ul>
<li>Pesquisador: 2 virtudes (descritos acima)</li>
<li>Recall = método / pesquisador = 2/2 = 1</li>
<li>Precisão = reais / método = 2/4 = 0.5 (392 1 ponto de cada side, 370 1 ponto de cada side)</li>
</ul>
<ol start="7" style="list-style-type: decimal">
<li>Descrição</li>
</ol>
<ul>
<li>Média/mediana: 3.65/3.65 x 4.68/4.82 -&gt; rua de mediana para ruim</li>
<li>Variação no surprise? Início da rua mais homogêneo, mas com alternâncias de melhores e piores pontos ao longo da rua</li>
<li>Lado melhor? Side1 (3) x Side2 (5) -&gt; side2 ligeiramente melhor</li>
<li>Região melhor? Não dá para dizer pelo surprise maps, olhando os scores também é complicado</li>
</ul>
</div>
<div id="sumario-comparacoes-dos-surprise-maps-com-base-rate-usando-media-ou-mediana" class="section level1">
<h1>Sumário comparações dos Surprise Maps com base rate usando média ou mediana</h1>
<p>== Versão atual - 500 execuções do surprise e calculando média dos surprises ====</p>
<ul>
<li>As versões com média e mediana foram equivalentes!</li>
</ul>
<p>=== Versão anterior ===</p>
<table style="width:56%;">
<colgroup>
<col width="22%" />
<col width="22%" />
<col width="11%" />
</colgroup>
<thead>
<tr class="header">
<th>Street</th>
<th align="center">Base Rate (median)</th>
<th align="right">Base Rate (mean)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Cristina</td>
<td align="center">0: 2* (side2 separado e side1 mais negativo), 261 (p1 side1 em cima é estranho, 1 ponto de side2 afastado)</td>
<td align="right">0: 2 (1 ponto de cada side separado), 261* (ordem e ponto de side2 afastado)</td>
</tr>
<tr class="even">
<td>Edésio</td>
<td align="center">X: 306 (1 ponto side2 mais positivo e demais juntos), 1546 (todos juntos)</td>
<td align="right">1546 (p1 side2 com destaque é estranho)</td>
</tr>
<tr class="odd">
<td>Inácio</td>
<td align="center">X: 239 (p1 side1 mais positivo)</td>
<td align="right"></td>
</tr>
<tr class="even">
<td>Floriano</td>
<td align="center"></td>
<td align="right">X: 691 (ordem de p2 side1 mais próximo a p1 side2), 913 (p2 side2 melhor que p1 side1)</td>
</tr>
<tr class="odd">
<td>Maciel</td>
<td align="center">X: 130 (p1 side1 melhor), 190 (p2 side1 melhor que p1), 284 (p2 side1 melhor que p1)</td>
<td align="right"></td>
</tr>
<tr class="even">
<td>Manoel</td>
<td align="center">X: 300 (side2 ligeiramente melhor que p2 side1), 392 (1 ponto de cada side mais próximo)</td>
<td align="right"></td>
</tr>
</tbody>
</table>
</div>
<div id="sumario-comparacoes-dos-surprise-maps-com-normal-para-todas-as-ruas-x-normal-por-rua" class="section level1">
<h1>Sumário comparações dos Surprise Maps com normal para todas as ruas x normal por rua</h1>
<table style="width:56%;">
<colgroup>
<col width="22%" />
<col width="22%" />
<col width="11%" />
</colgroup>
<thead>
<tr class="header">
<th>Street</th>
<th align="center">Normal All</th>
<th align="right">Normal Street</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Cristina</td>
<td align="center">Aceitável, mas 284 tem um ponto pouco pior que não está representado</td>
<td align="right">X</td>
</tr>
<tr class="even">
<td>Edésio</td>
<td align="center">1546 melhor modelado</td>
<td align="right">X - 602 e 1136 melhor modelados</td>
</tr>
<tr class="odd">
<td>Inácio</td>
<td align="center">500 não tem 1 ponto bem positivo</td>
<td align="right">X</td>
</tr>
<tr class="even">
<td>Floriano</td>
<td align="center">549 melhor modelado</td>
<td align="right">X - 445 e 813 melhor modelados</td>
</tr>
<tr class="odd">
<td>Maciel</td>
<td align="center"></td>
<td align="right">X - 248, 284 e 360 melhor modelados</td>
</tr>
<tr class="even">
<td>Manoel</td>
<td align="center">188 e 300 melhor modelados</td>
<td align="right">X - 222, 370 e 392 melhor modelados</td>
</tr>
</tbody>
</table>
</div>
<div id="novas-ideias-que-nao-foram-consideradas---q-scores" class="section level1">
<h1>Novas Ideias que não foram consideradas - Q-Scores</h1>
<ul>
<li>Olhar a diferença entre os lados da rua por ponto?
<ul>
<li>Acharia 2 problemas não encontrados</li>
</ul></li>
<li>Olhar a favor/contra carros e comparar os scores?
<ul>
<li>Acharia 1 problema não encontrado</li>
</ul></li>
</ul>
</div>
<div id="descartaralterar---q-scores" class="section level1">
<h1>Descartar/Alterar? - Q-Scores</h1>
<ul>
<li>Melhor e pior área por lado ao invés de melhor e pior área da rua?</li>
</ul>
</div>




</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
