---
title: "RoyalSociety"
output: pdf_document
---

#Reading data
```{r, echo=FALSE, fig.show='asis', fig.width=10, fig.height=5}
getLatLong <- function(data, fileWithCoord) {
  coord <- read.table(fileWithCoord, sep="+", header=F)#V4 and V5 -> lat and long; V2 street
  data$lat <- 0
  data$long <- 0
  
  for (i in 1:nrow(coord)){
    row <- coord[i,]
    for (j in 1:nrow(data)){
      if(length(grep(row$V2, data[j,]$image_url)) > 0){
        data[j,]$lat <- row$V4
        data[j,]$long <- row$V5
      }  
    }
  }
  return (data)
}

library(ggplot2)
library(gridExtra)
library(dplyr)
library(spdep)
source('analisaICPorFoto.R')

facet_names <- list(
  'agrad%C3%A1vel?'="Pleasantness",
  'seguro?'="Safety"
)

facet_labeller <- function(variable,value){
  return(facet_names[value])
}

#dados <- read.table("geral.dat", header=TRUE)
dados <- read.table("geralSetoresAJ.dat", header=TRUE)


#Intervalo de confiança por ponto
temp <- dados
qscoreSim <- temp [ c(4:103) ]
icData <- apply(qscoreSim, 1, ic)
temp$distance <- icData

#Subset of columns
dadosSub <- temp[, c("V2", "V1", "V3", "diag", "hor", "vert", "red", "green", "blue", "grupo", "bairro", "distance", "setor")]

novosDados <- reshape(dadosSub, timevar="grupo", idvar=c("V2", "V1", "diag", "hor", "vert", "red", "green", "blue", "bairro", "setor"), direction="wide")

#Copia com todos os dados
#dadosCopy <- temp[, c("V2", "V1", "V3", "diag", "hor", "vert", "red", "green", "blue", "grupo", "bairro")]
```


#Urban Elements
```{r, echo=FALSE, fig.show='asis', fig.width=10, fig.height=5}
library(dplyr)
library(texreg)

substituiURL <- function(dadosPorGrupo){
    localData <- lapply(as.character(dadosPorGrupo$image_url), function (x) paste(strsplit(x, split="/", fixed=TRUE)[[1]][6], "/", strsplit(x, split="/", fixed=TRUE)[[1]][7], sep=""))
    local <- unlist(lapply(localData, '[[', 1))
    return (local)
}

#Lendo resultados do CrowdFlower
dadosg1 <- read.csv("regressao100/g1.csv")
dadosg1$image_url <- substituiURL(dadosg1)

dadosg2 <- read.csv("regressao100/g2.csv")
dadosg2$image_url <- substituiURL(dadosg2)

dadosg3 <- read.csv("regressao100/g3.csv")
dadosg3$image_url <- substituiURL(dadosg3)

dadosg4 <- read.csv("regressao100/g4.csv")
dadosg4$image_url <- substituiURL(dadosg4)

dadosg5 <- read.csv("regressao100/g5.csv")
dadosg5$image_url <- substituiURL(dadosg5)

dadosg6 <- read.csv("regressao100/g6.csv")
dadosg6$image_url <- substituiURL(dadosg6)

dadosg7 <- read.csv("regressao100/g7.csv")
dadosg7$image_url <- substituiURL(dadosg7)

dadosg8 <- read.csv("regressao100/g8.csv")
dadosg8$image_url <- substituiURL(dadosg8)

dadosg9 <- read.csv("regressao100/g9.csv")
dadosg9$image_url <- substituiURL(dadosg9)

dadosg10 <- read.csv("regressao100/g10.csv")
dadosg10$image_url <- substituiURL(dadosg10)

dadosg11 <- read.csv("regressao100/g11.csv")
dadosg11$image_url <- substituiURL(dadosg11)

dadosg12 <- read.csv("regressao100/g12.csv")
dadosg12$image_url <- substituiURL(dadosg12)

dadosg13 <- read.csv("regressao100/g13.csv")
dadosg13$image_url <- substituiURL(dadosg13)

#Somando esquerda e direita
somaValores <- function(dados1, dados2, desvio1, desvio2, uplimit){
    dados1[is.na(dados1)] <- 0
    dados2[is.na(dados2)] <- 0
    
    soma = dados1 + dados2
    desvios = (desvio1 + desvio2)/2
    
    
    desvio = sd(soma)
    if (is.na(desvio)){ 
        valores = rnorm(mean = mean(soma, na.rm = TRUE), sd = mean(desvios, na.rm = TRUE), n = 3)
        valores <- ifelse(valores < 0, 0, valores)
        valores <- ifelse(valores > uplimit, uplimit, valores)
        return (mean(valores))
    }else{
        soma <- ifelse(soma < 0, 0, soma)
        soma <- ifelse(soma > uplimit, uplimit, soma)
        return (mean(soma))
    }
}

#Somando esquerda e direita
mediaValores <- function(dados1, dados2, desvio1, desvio2, uplimit){
    for (i in length(dados1)){
       if(is.na(dados1[i])){
         dados1[i] <- dados2[i]
       }
       if(is.na(dados2[i])){
         dados2[i] <- dados1[i]
       }
    }
    
    soma = (dados1 + dados2) / 2
    desvios = (desvio1 + desvio2)/2
    
    
    desvio = sd(soma)
    if (is.na(desvio)){ 
        valores = rnorm(mean = mean(soma, na.rm = TRUE), sd = mean(desvios, na.rm = TRUE), n = 3)
        valores <- ifelse(valores < 0, 0, valores)
        valores <- ifelse(valores > uplimit, uplimit, valores)
        return (mean(valores))
    }else{
        soma <- ifelse(soma < 0, 0, soma)
        soma <- ifelse(soma > uplimit, uplimit, soma)
        return (mean(soma))
    }
}


#Gerando valores para os casos com apenas 1 resposta a partir do desvio obtido em outras respostas para a mesma questão
geraValores <- function(lista, question, desvios, uplimit){
   #desvio = sd(lista)
   return (mean(lista, na.rm = TRUE))
}

Mode <- function(x) {
  ux <- unique(x)
  ux[which.max(tabulate(match(x, ux)))]
}

#Agrupando por imagem e por questao - G1
by_image <- group_by(dadosg1, image_url)
desvios <- summarise (by_image, 
                  sd1 = sd(question1, na.rm = TRUE),
                  sd2l = sd(question2__left_side, na.rm = TRUE),
                  sd2r = sd(question2__right_side, na.rm = TRUE),
                  sd3 = sd(question3, na.rm = TRUE) )
groupedData1 <- summarise(by_image,
  #count = n(),
  q1 = geraValores(question1, "1", desvios, 100),
  #sdq1 = sd(question1, na.rm = TRUE),
  q2 = mediaValores(question2__left_side, question2__right_side, desvios$sd2l, desvios$sd2r, 100),
  q2_left = geraValores(question2__left_side, "2l", desvios, 100),
  #sdq2_left = sd(question2__left_side, na.rm = TRUE),
  q2_right = geraValores(question2__right_side, "2r", desvios, 100),
  #sdq2_right = sd(question2__right_side, na.rm = TRUE),
  q3 = geraValores(question3, "3", desvios, 100)
  #sdq3 = sd(question3, na.rm = TRUE) 
  )

#Agrupando por imagem e por questao - G2
by_image <- group_by(dadosg2, image_url)
desvios <- summarise (by_image, 
                  sd1 = sd(question1, na.rm = TRUE),
                  sd2l = sd(question2__left_side, na.rm = TRUE),
                  sd2r = sd(question2__right_side, na.rm = TRUE),
                  sd3 = sd(question3, na.rm = TRUE) )
groupedData2 <- summarise(by_image,
  count = n(),
  q1 = geraValores(question1, "1", desvios, 100),
  #sdq1 = sd(question1, na.rm = TRUE),
  q2 = somaValores(question2__left_side, question2__right_side, desvios$sd2l, desvios$sd2r, 200),
  q2_left = geraValores(question2__left_side, "2l", desvios, 100),
  #sdq2_left = sd(question2__left_side, na.rm = TRUE),
  q2_right = geraValores(question2__right_side, "2r", desvios, 100),
  #sdq2_right = sd(question2__right_side, na.rm = TRUE),
  q3 = geraValores(question3, "3", desvios, 100)
  #sdq3 = sd(question3, na.rm = TRUE) 
  )

#Agrupando por imagem e por questao - G3
by_image <- group_by(dadosg3, image_url)
desvios <- summarise (by_image, 
                  sd1l = sd(question1__left_side, na.rm = TRUE),
                  sd1r = sd(question1__right_side, na.rm = TRUE),
                  sd2l = sd(question2__left_side, na.rm = TRUE),
                  sd2r = sd(question2__right_side, na.rm = TRUE),
                  sd3l = sd(question3__left_side, na.rm = TRUE),
                  sd3r = sd(question3__right_side, na.rm = TRUE) )
groupedData3 <- summarise(by_image,
  count = n(),
  q1 = mediaValores(question1__left_side, question1__right_side, desvios$sd1l, desvios$sd1r, 5),
  q1_left = geraValores(question1__left_side, "1l", desvios, 5),
  #sdq1_left = sd(question1__left_side, na.rm = TRUE),
  q1_right = geraValores(question1__right_side, "1r", desvios, 5),
  #sdq1_right = sd(question1__right_side, na.rm = TRUE),
  q2 = mediaValores(question2__left_side, question2__right_side, desvios$sd2l, desvios$sd2r, 5),
  q2_left = geraValores(question2__left_side, "2l", desvios, 5),
  #sdq2_left = sd(question2__left_side, na.rm = TRUE),
  q2_right = geraValores(question2__right_side, "2r", desvios, 5),
  #sdq2_right = sd(question2__right_side, na.rm = TRUE),
  q3 = mediaValores(question3__left_side, question3__right_side, desvios$sd3l, desvios$sd3r, 5),
  q3_left = geraValores(question3__left_side, "3l", desvios, 5),
  #sdq3_left = sd(question3__left_side, na.rm = TRUE),
  q3_right = geraValores(question3__right_side, "3r", desvios, 5)
  #sdq3_right = sd(question3__right_side, na.rm = TRUE)  
  )

#Agrupando por imagem e por questao - G4
by_image <- group_by(dadosg4, image_url)
desvios <- summarise (by_image, 
                  sd1 = sd(question1, na.rm = TRUE),
                  sd2 = sd(question2, na.rm = TRUE))
groupedData4 <- summarise(by_image,
  count = n(),
  q1 = geraValores(question1, "1", desvios, 10),
  #sdq1 = sd(question1, na.rm = TRUE),
  q2 = geraValores(question2, "2", desvios, 10)
  #sdq2 = sd(question2, na.rm = TRUE) 
  )

#Agrupando por imagem e por questao - G5
by_image <- group_by(dadosg5, image_url)
desvios <- summarise (by_image, 
                  sd1 = sd(question1, na.rm = TRUE),
                  sd2 = sd(your_answer_is, na.rm = TRUE))
groupedData5 <- summarise(by_image,
  count = n(),
  q1 = geraValores(question1, "1", desvios, 20),
  #sdq1 = sd(question1, na.rm = TRUE),
  q2 = geraValores(your_answer_is, "2", desvios, 20)
  #sdq2 = sd(question2, na.rm = TRUE) 
  )

#Agrupando por imagem e por questao - G6
by_image <- group_by(dadosg6, image_url)
desvios <- summarise (by_image, 
                  sd1l = sd(question1__left_side, na.rm = TRUE),
                  sd1r = sd(question1__right_side, na.rm = TRUE),
                  sd2l = sd(question2__left_side, na.rm = TRUE),
                  sd2r = sd(question2__right_side, na.rm = TRUE) )
groupedData6 <- summarise(by_image,
  count = n(),
  q1 = mediaValores(question1__left_side, question1__right_side, desvios$sd1l, desvios$sd1r, 1),
  q1_left = geraValores(question1__left_side, "1l", desvios, 1),
  #sdq1_left = sd(question1__left_side, na.rm = TRUE),
  q1_right = geraValores(question1__right_side, "1r", desvios, 1),
  #sdq1_right = sd(question1__right_side, na.rm = TRUE),
  q2 = mediaValores(question2__left_side, question2__right_side, desvios$sd2l, desvios$sd2r, 1),
  q2_left = geraValores(question2__left_side, "2l", desvios, 1),
  #sdq2_left = sd(question2__left_side, na.rm = TRUE),
  q2_right = geraValores(question2__right_side, "2r", desvios, 1)
  #sdq2_right = sd(question2__right_side, na.rm = TRUE) 
  )


#Agrupando por imagem e por questao - G7
by_image <- group_by(dadosg7, image_url)
desvios <- summarise (by_image, 
                  sd1 = sd(question1, na.rm = TRUE),
                  sd2 = sd(question2, na.rm = TRUE),
                  sd3l = sd(question3__left_side, na.rm = TRUE),
                  sd3r = sd(question3__right_side, na.rm = TRUE) )
groupedData7 <- summarise(by_image,
  count = n(),
  q1 = geraValores(question1, "1", desvios, 3),
  #sdq1 = sd(question1, na.rm = TRUE),
  q2 = geraValores(question2, "2", desvios, 1),
  #sdq2 = sd(question2, na.rm = TRUE),
  q3 = mediaValores(question3__left_side, question3__right_side, desvios$sd3l, desvios$sd3r, 1),
  q3_left = geraValores(question3__left_side, "3l", desvios, 1),
  #sdq3_left = sd(question3__left_side, na.rm = TRUE),
  q3_right = geraValores(question3__right_side, "3r", desvios, 1)
  #sdq3_right = sd(question3__right_side, na.rm = TRUE)  
  )

#Agrupando por imagem e por questao - G8
by_image <- group_by(dadosg8, image_url)
desvios <- summarise (by_image, 
                  sd1 = sd(question1, na.rm = TRUE),
                  sd2l = sd(question2__left_side, na.rm = TRUE),
                  sd2r = sd(question2_right_side, na.rm = TRUE),
                  sd3l = sd(question3__left_side, na.rm = TRUE),
                  sd3r = sd(question3_right_side, na.rm = TRUE)
                  )
groupedData8 <- summarise(by_image,
  count = n(),
  q1 = Mode(question1),
  #sdq1 = sd(question1, na.rm = TRUE),
  q2 = somaValores(question2__left_side, question2_right_side, desvios$sd2l, desvios$sd2r, 40),
  q2_left = geraValores(question2__left_side, "2l", desvios, 20),
  #sdq2_left = sd(question2__left_side, na.rm = TRUE),
  q2_right = geraValores(question2_right_side, "2r", desvios, 20),
  #sdq2_right = sd(question2__right_side, na.rm = TRUE)  
  q3 = somaValores(question3__left_side, question3_right_side, desvios$sd3l, desvios$sd3r, 40),
  q3_left = geraValores(question3__left_side, "3l", desvios, 20),
  q3_right = geraValores(question3_right_side, "3r", desvios, 20)
  )

#Agrupando por imagem e por questao - G9
by_image <- group_by(dadosg9, image_url)
desvios <- summarise (by_image, 
                  sd1l = sd(question1__left_side, na.rm = TRUE),
                  sd1r = sd(question1__right_side, na.rm = TRUE) )
groupedData9 <- summarise(by_image,
  count = n(),
  q1 = mediaValores(question1__left_side, question1__right_side, desvios$sd1l, desvios$sd1r, 200),
  q1_left = geraValores(question1__left_side, "1l", desvios, 200),
  #sdq1_left = sd(question1__left_side, na.rm = TRUE),
  q1_right = geraValores(question1__right_side, "1r", desvios, 200)
  #sdq1_right = sd(question1__right_side, na.rm = TRUE)  
  )

#Agrupando por imagem e por questao - G10
by_image <- group_by(dadosg10, image_url)
desvios <- summarise (by_image, 
                  sd1 = sd(question1, na.rm = TRUE),
                  sd2 = sd(question2, na.rm = TRUE),
                  sd3 = sd(question3, na.rm = TRUE))
groupedData10 <- summarise(by_image,
  count = n(),
  q1 = Mode(x = question1),
  #sdq1 = sd(question1, na.rm = TRUE),
  q2 = geraValores(question2, "2", desvios, 50),
  #sdq2 = sd(question2, na.rm = TRUE),
  q3 = geraValores(question3, "3", desvios, 1)
  #sdq3 = sd(question3, na.rm = TRUE)  
  )

#Agrupando por imagem e por questao - G11
by_image <- group_by(dadosg11, image_url)
desvios <- summarise (by_image, 
                  sd2l = sd(question2__left_side, na.rm = TRUE),
                  sd2r = sd(question2__right_side, na.rm = TRUE),
                  sd3l = sd(question3__left_side, na.rm = TRUE),
                  sd3r = sd(question3__right_side, na.rm = TRUE) )
groupedData11 <- summarise(by_image,
  count = n(),
  q2 = somaValores(question2__left_side, question2__right_side, desvios$sd2l, desvios$sd2r, 20),
  q2_left = geraValores(question2__left_side, "2l", desvios, 10),
  #sdq2_left = sd(question2__left_side, na.rm = TRUE),
  q2_right = geraValores(question2__right_side, "2r", desvios, 10),
  #sdq2_right = sd(question2__right_side, na.rm = TRUE),
  q3 = somaValores(question3__left_side, question3__right_side, desvios$sd3l, desvios$sd3r, 80),
  q3_left = geraValores(question3__left_side, "3l", desvios, 40),
  #sdq3_left = sd(question3__left_side, na.rm = TRUE),
  q3_right = geraValores(question3__right_side, "3r", desvios, 40)
  #sdq3_right = sd(question3__right_side, na.rm = TRUE)  
  )

#Agrupando por imagem e por questao - G12
by_image <- group_by(dadosg12, image_url)
desvios <- summarise (by_image, 
                  sd1 = sd(question1, na.rm = TRUE),
                  sd2l = sd(question2__left_side, na.rm = TRUE),
                  sd2r = sd(question2__right_side, na.rm = TRUE),
                  sd3 = sd(question3, na.rm = TRUE))
groupedData12 <- summarise(by_image,
  count = n(),
  q1 = geraValores(question1, "1", desvios, 10),
  #sdq1 = sd(question1, na.rm = TRUE),
  q2 = somaValores(question2__left_side, question2__right_side, desvios$sd2l, desvios$sd2r, 20),
  q2_left = geraValores(question2__left_side, "2l", desvios, 10),
  #sdq2_left = sd(question2__left_side, na.rm = TRUE),
  q2_right = geraValores(question2__right_side, "2r", desvios, 10),
  #sdq2_right = sd(question2__right_side, na.rm = TRUE),
  q3 = geraValores(question3, "3", desvios,10)
  #sdq3 = sd(question3, na.rm = TRUE)  
  )


#Agrupando por imagem e por questao - G13
by_image <- group_by(dadosg13, image_url)
desvios <- summarise (by_image, 
                  sd1l = sd(question1__left_side, na.rm = TRUE),
                  sd1r = sd(question1__right_side, na.rm = TRUE),
                  sd2l = sd(question2__left_side, na.rm = TRUE),
                  sd2r = sd(question2__right_side, na.rm = TRUE) )
groupedData13 <- summarise(by_image,
  count = n(),
  q1 = somaValores(question1__left_side, question1__right_side, desvios$sd1l, desvios$sd1r, 30),
  q1_left = geraValores(question1__left_side, "1l", desvios, 10),
  #sdq1_left = sd(question1__left_side, na.rm = TRUE),
  q1_right = geraValores(question1__right_side, "1r", desvios, 15),
  #sdq1_right = sd(question1__right_side, na.rm = TRUE),
  q2 = mediaValores(question2__left_side, question2__right_side, desvios$sd2l, desvios$sd2r, 1),
  q2_left = geraValores(question2__left_side, "2l", desvios, 1),
  #sdq2_left = sd(question2__left_side, na.rm = TRUE),
  q2_right = geraValores(question2__right_side, "2r", desvios, 1)
  #sdq2_right = sd(question2__right_side, na.rm = TRUE) 
  )


#Renomeando colunas por grupos
renomeiaGrupos <- function(dadosPorGrupo, listaColunas, idGrupo) {
    for (coluna in listaColunas){
        colnames(dadosPorGrupo)[colnames(dadosPorGrupo) == coluna] <- paste(idGrupo, coluna, sep="")
    }
    return(dadosPorGrupo)
}

renomeiaGrupos2 <- function(dadosPorGrupo, listaColunas, novosNomes) {
    for (i in seq(1, length(listaColunas))){
        coluna = listaColunas[i]
        colnames(dadosPorGrupo)[colnames(dadosPorGrupo) == coluna] <- novosNomes[i]
    }
    return(dadosPorGrupo)
}

groupedData1 <- renomeiaGrupos(groupedData1, c("q2_left", "q2_right", "count"), "g1")
groupedData2 <- renomeiaGrupos(groupedData2, c("q2_left", "q2_right", "count"), "g2")
groupedData3 <- renomeiaGrupos(groupedData3, c("q1_left", "q1_right","q2_left", "q2_right","q3_left", "q3_right", "count"), "g3")
groupedData4 <- renomeiaGrupos(groupedData4, c("count"), "g4")
groupedData5 <- renomeiaGrupos(groupedData5, c("count"), "g5")
groupedData6 <- renomeiaGrupos(groupedData6, c("q1_left", "q1_right", "q2_left", "q2_right", "count"), "g6")
groupedData7 <- renomeiaGrupos(groupedData7, c("q3_left", "q3_right", "count"), "g7")
groupedData8 <- renomeiaGrupos(groupedData8, c("q2_left", "q2_right","q3_left", "q3_right", "count"), "g8")
groupedData9 <- renomeiaGrupos(groupedData9, c("q1_left", "q1_right", "count"), "g9")
groupedData10 <- renomeiaGrupos(groupedData10, c("count"), "g10")
groupedData11 <- renomeiaGrupos(groupedData11, c("q2_left", "q2_right","q3_left", "q3_right", "count"), "g11")
groupedData12 <- renomeiaGrupos(groupedData12, c("q2_left", "q2_right", "count"), "g12")
groupedData13 <- renomeiaGrupos(groupedData13, c("q1_left", "q1_right", "q2_left", "q2_right", "count"), "g13")

groupedData1 <- renomeiaGrupos2(groupedData1, c("q1", "q2", "q3"), c("street_wid", "sidewalk_wid", "public_art"))
groupedData2 <- renomeiaGrupos2(groupedData2, c("q1", "q2", "q3"), c("mov_cars", "park_cars", "mov_ciclyst"))
groupedData3 <- renomeiaGrupos2(groupedData3, c("q1", "q2", "q3"), c("debris", "pavement", "landscape"))
groupedData4 <- renomeiaGrupos2(groupedData4, c("q1", "q2"), c("courtyards", "major_landsc"))
groupedData5 <- renomeiaGrupos2(groupedData5, c("q1", "q2"), c("build_ident", "build_nrectan"))
groupedData6 <- renomeiaGrupos2(groupedData6, c("q1", "q2"), c("prop_street_wall", "prop_wind"))
groupedData7 <- renomeiaGrupos2(groupedData7, c("q1", "q2", "q3"), c("long_sight", "prop_sky_ahead", "prop_sky_across"))
groupedData8 <- renomeiaGrupos2(groupedData8, c("q1", "q2", "q3"), c("graffiti", "trees", "small_planters"))
groupedData9 <- renomeiaGrupos2(groupedData9, c("q1"), c("build_height"))
groupedData10 <- renomeiaGrupos2(groupedData10, c("q1", "q2", "q3"), c("build_diff_ages", "diff_build", "prop_hist_build"))
groupedData11 <- renomeiaGrupos2(groupedData11, c("q2", "q3"), c("outdoor_table", "street_furnit"))
groupedData12 <- renomeiaGrupos2(groupedData12, c("q1", "q2", "q3"), c("basic_col", "lights", "accent_col"))
groupedData13 <- renomeiaGrupos2(groupedData13, c("q1","q2"), c("people", "prop_active_use"))

#Combinando dados QScores com elementos urbanos
temp <- merge(groupedData1, novosDados, by.x="image_url", by.y="V2")
temp2 <- merge(novosDados, groupedData2, by.x="V2", by.y="image_url")
temp3 <- merge(novosDados, groupedData3, by.x="V2", by.y="image_url")
temp4 <- merge(novosDados, groupedData4, by.x="V2", by.y="image_url")
temp5 <- merge(novosDados, groupedData5, by.x="V2", by.y="image_url")
temp6 <- merge(novosDados, groupedData6, by.x="V2", by.y="image_url")
temp7 <- merge(novosDados, groupedData7, by.x="V2", by.y="image_url")
temp8 <- merge(novosDados, groupedData8, by.x="V2", by.y="image_url")
temp9 <- merge(novosDados, groupedData9, by.x="V2", by.y="image_url")
temp10 <- merge(novosDados, groupedData10, by.x="V2", by.y="image_url")
temp11 <- merge(novosDados, groupedData11, by.x="V2", by.y="image_url")
temp12 <- merge(novosDados, groupedData12, by.x="V2", by.y="image_url")
temp13 <- merge(novosDados, groupedData13, by.x="V2", by.y="image_url")
colnames(novosDados)[colnames(novosDados) == "V2"] <- "image_url"
# allData <- Reduce(function(x, y) merge(x, y, all=TRUE), list(novosDados, groupedData1, groupedData2, groupedData3, groupedData3, groupedData4, groupedData5, groupedData6, groupedData7,groupedData8, groupedData9, groupedData10, groupedData11, groupedData12, groupedData13))

#Correlacao? 
calculaCorrelacoes <- function (listaDados, colunaQScore, questao, arquivo) {
    sink(arquivo, append = TRUE)
    print(questao)
  
    temp = listaDados[[1]]
    dadosAtuais <- temp[(temp$V1 == questao),] 
    res<- cor.test(dadosAtuais[[colunaQScore]], dadosAtuais$street_wid, na.action = na.exclude, method = "spearman")
    print(paste(res$estimate, res$p.value, "street_wid"))
    res <- cor.test(dadosAtuais[[colunaQScore]], dadosAtuais$sidewalk_wid, na.action = na.exclude, method = "spearman")
    print(paste(res$estimate, res$p.value, "sidewalk_wid"))
    res <- cor.test(dadosAtuais[[colunaQScore]], dadosAtuais$g1q2_left, na.action = na.exclude, method = "spearman")
    print(paste(res$estimate, res$p.value, "sidewalk_wid_left"))
    res <- cor.test(dadosAtuais[[colunaQScore]], dadosAtuais$g1q2_right, na.action = na.exclude, method = "spearman")
    print(paste(res$estimate, res$p.value, "sidewalk_wid_right"))
    res <- cor.test(dadosAtuais[[colunaQScore]], dadosAtuais$public_art, na.action = na.exclude, method = "spearman")
    print(paste(res$estimate, res$p.value, "public_art"))
    
    temp2 = listaDados[[2]]
    dadosAtuais <- temp2[(temp2$V1 == questao),] 
    res <- cor.test(dadosAtuais[[colunaQScore]], dadosAtuais$mov_cars, na.action = na.exclude, method = "spearman")
    print(paste(res$estimate, res$p.value, "mov_cars"))
    res <- cor.test(dadosAtuais[[colunaQScore]], dadosAtuais$park_cars, na.action = na.exclude, method = "spearman")
       print(paste(res$estimate, res$p.value, "park_cars"))
    res <- cor.test(dadosAtuais[[colunaQScore]], dadosAtuais$g2q2_left, na.action = na.exclude, method = "spearman")
       print(paste(res$estimate, res$p.value, "park_cars_left"))
  res <- cor.test(dadosAtuais[[colunaQScore]], dadosAtuais$g2q2_right, na.action = na.exclude, method = "spearman")
      print(paste(res$estimate, res$p.value, "park_cars_right"))
    res <- cor.test(dadosAtuais[[colunaQScore]], dadosAtuais$mov_ciclyst, na.action = na.exclude, method = "spearman")
      print(paste(res$estimate, res$p.value, "mov_ciclyst"))
    
    temp3 = listaDados[[3]]
    dadosAtuais <- temp3[(temp3$V1 == questao),] 
  res <- cor.test(dadosAtuais[[colunaQScore]], dadosAtuais$debris, na.action = na.exclude, method = "spearman")
      print(paste(res$estimate, res$p.value, "debris"))
    res <- cor.test(dadosAtuais[[colunaQScore]], dadosAtuais$g3q1_left, na.action = na.exclude, method = "spearman")
      print(paste(res$estimate, res$p.value, "debris_left"))
    res <- cor.test(dadosAtuais[[colunaQScore]], dadosAtuais$g3q1_right, na.action = na.exclude, method = "spearman")
      print(paste(res$estimate, res$p.value, "debris_right"))
  res <- cor.test(dadosAtuais[[colunaQScore]], dadosAtuais$pavement, na.action = na.exclude, method = "spearman")
      print(paste(res$estimate, res$p.value, "pavement"))
    res <- cor.test(dadosAtuais[[colunaQScore]], dadosAtuais$g3q2_left, na.action = na.exclude, method = "spearman")
      print(paste(res$estimate, res$p.value, "pavement_left"))
  res <- cor.test(dadosAtuais[[colunaQScore]], dadosAtuais$g3q2_right, na.action = na.exclude, method = "spearman")
      print(paste(res$estimate, res$p.value, "pavement_right"))
  res <- cor.test(dadosAtuais[[colunaQScore]], dadosAtuais$landscape, na.action = na.exclude, method = "spearman")
      print(paste(res$estimate, res$p.value, "landscape"))
    res <- cor.test(dadosAtuais[[colunaQScore]], dadosAtuais$g3q3_left, na.action = na.exclude, method = "spearman")
      print(paste(res$estimate, res$p.value, "landscape_left"))
    res <- cor.test(dadosAtuais[[colunaQScore]], dadosAtuais$g3q3_right, na.action = na.exclude, method = "spearman")
      print(paste(res$estimate, res$p.value, "landscape_right"))
    
    temp4 = listaDados[[4]]
    dadosAtuais <- temp4[(temp4$V1 == questao),] 
    res <- cor.test(dadosAtuais[[colunaQScore]], dadosAtuais$courtyards, na.action = na.exclude, method = "spearman")
      print(paste(res$estimate, res$p.value, "courtyards"))
    res <- cor.test(dadosAtuais[[colunaQScore]], dadosAtuais$major_landsc, na.action = na.exclude, method = "spearman")
      print(paste(res$estimate, res$p.value, "major_landsc"))
    
    temp5 = listaDados[[5]]
    dadosAtuais <- temp5[(temp5$V1 == questao),] 
    res <- cor.test(dadosAtuais[[colunaQScore]], dadosAtuais$build_ident, na.action = na.exclude, method = "spearman")
    print(paste(res$estimate, res$p.value, "build_ident"))
    res <- cor.test(dadosAtuais[[colunaQScore]], dadosAtuais$build_nrectan, na.action = na.exclude, method = "spearman")
    print(paste(res$estimate, res$p.value, "build_nrectan"))
    
    temp6 = listaDados[[6]]
    dadosAtuais <- temp6[(temp6$V1 == questao),] 
  res <- cor.test(dadosAtuais[[colunaQScore]], dadosAtuais$prop_street_wall, na.action = na.exclude, method = "spearman")
      print(paste(res$estimate, res$p.value, "prop_street_wall"))
    res <- cor.test(dadosAtuais[[colunaQScore]], dadosAtuais$g6q1_left, na.action = na.exclude, method = "spearman")
      print(paste(res$estimate, res$p.value, "prop_street_wall_left"))
    res <- cor.test(dadosAtuais[[colunaQScore]], dadosAtuais$g6q1_right, na.action = na.exclude, method = "spearman")
      print(paste(res$estimate, res$p.value, "prop_street_wall_right"))
  res <- cor.test(dadosAtuais[[colunaQScore]], dadosAtuais$prop_wind, na.action = na.exclude, method = "spearman")
      print(paste(res$estimate, res$p.value, "prop_wind"))
    res <- cor.test(dadosAtuais[[colunaQScore]], dadosAtuais$g6q2_left, na.action = na.exclude, method = "spearman")
      print(paste(res$estimate, res$p.value, "prop_wind_left"))
    res <- cor.test(dadosAtuais[[colunaQScore]], dadosAtuais$g6q2_right, na.action = na.exclude, method = "spearman")
      print(paste(res$estimate, res$p.value, "prop_wind_right"))
    
    temp7 = listaDados[[7]]
    dadosAtuais <- temp7[(temp7$V1 == questao),] 
    res <- cor.test(dadosAtuais[[colunaQScore]], dadosAtuais$long_sight, na.action = na.exclude, method = "spearman")
      print(paste(res$estimate, res$p.value, "long_sight"))
    res <- cor.test(dadosAtuais[[colunaQScore]], dadosAtuais$prop_sky_ahead, na.action = na.exclude, method = "spearman")
    print(paste(res$estimate, res$p.value, "prop_sky_ahead"))
  res <- cor.test(dadosAtuais[[colunaQScore]], dadosAtuais$prop_sky_across, na.action = na.exclude, method = "spearman")
    print(paste(res$estimate, res$p.value, "prop_sky_across"))
    res <- cor.test(dadosAtuais[[colunaQScore]], dadosAtuais$g7q3_left, na.action = na.exclude, method = "spearman")
    print(paste(res$estimate, res$p.value, "prop_sky_across_left"))
    res <- cor.test(dadosAtuais[[colunaQScore]], dadosAtuais$g7q3_right, na.action = na.exclude, method = "spearman")
    print(paste(res$estimate, res$p.value, "prop_sky_across_right"))
    
    temp8 = listaDados[[8]]
    dadosAtuais <- temp8[(temp8$V1 == questao),] 
    #res <- cor.test(dadosAtuais[[colunaQScore]], dadosAtuais$graffiti, na.action = na.exclude)
#     print(paste(res$estimate, res$p.value, "graffiti"))
res <- cor.test(dadosAtuais[[colunaQScore]], dadosAtuais$trees, na.action = na.exclude, method = "spearman")
    print(paste(res$estimate, res$p.value, "trees"))
    res <- cor.test(dadosAtuais[[colunaQScore]], dadosAtuais$g8q2_left, na.action = na.exclude, method = "spearman")
    print(paste(res$estimate, res$p.value, "trees_left"))
    res <- cor.test(dadosAtuais[[colunaQScore]], dadosAtuais$g8q2_right, na.action = na.exclude, method = "spearman")
    print(paste(res$estimate, res$p.value, "trees_right"))
res <- cor.test(dadosAtuais[[colunaQScore]], dadosAtuais$small_planters, na.action = na.exclude, method = "spearman")
    print(paste(res$estimate, res$p.value, "small_planters"))
    res <- cor.test(dadosAtuais[[colunaQScore]], dadosAtuais$g8q3_left, na.action = na.exclude, method = "spearman")
    print(paste(res$estimate, res$p.value, "small_planters_left"))
    res <- cor.test(dadosAtuais[[colunaQScore]], dadosAtuais$g8q3_right, na.action = na.exclude, method = "spearman")
    print(paste(res$estimate, res$p.value, "small_planters_right"))
    
    temp9 = listaDados[[9]]
    dadosAtuais <- temp9[(temp9$V1 == questao),] 
res <- cor.test(dadosAtuais[[colunaQScore]], dadosAtuais$build_height, na.action = na.exclude, method = "spearman")
    print(paste(res$estimate, res$p.value, "build_height"))
    res <- cor.test(dadosAtuais[[colunaQScore]], dadosAtuais$g9q1_left, na.action = na.exclude, method = "spearman")
    print(paste(res$estimate, res$p.value, "build_height_left"))
    res <- cor.test(dadosAtuais[[colunaQScore]], dadosAtuais$g9q1_right, na.action = na.exclude, method = "spearman")
    print(paste(res$estimate, res$p.value, "build_height_right"))
    
    temp10 = listaDados[[10]]
    dadosAtuais <- temp10[(temp10$V1 == questao),] 
    #res <- cor.test(dadosAtuais[[colunaQScore]], dadosAtuais$build_diff_ages, na.action = na.exclude)
#     print(res)
    res <- cor.test(dadosAtuais[[colunaQScore]], dadosAtuais$diff_build, na.action = na.exclude, method = "spearman")
    print(paste(res$estimate, res$p.value, "diff_build"))
    res <- cor.test(dadosAtuais[[colunaQScore]], dadosAtuais$prop_hist_build, na.action = na.exclude, method = "spearman")
    print(paste(res$estimate, res$p.value, "prop_hist_build"))
    
    temp11 = listaDados[[11]]
    dadosAtuais <- temp11[(temp11$V1 == questao),] 
res <- cor.test(dadosAtuais[[colunaQScore]], dadosAtuais$outdoor_table, na.action = na.exclude, method = "spearman")
    print(paste(res$estimate, res$p.value, "outdoor_table"))
    res <- cor.test(dadosAtuais[[colunaQScore]], dadosAtuais$g11q2_left, na.action = na.exclude, method = "spearman")
    print(paste(res$estimate, res$p.value, "outdoor_table_left"))
    res <- cor.test(dadosAtuais[[colunaQScore]], dadosAtuais$g11q2_right, na.action = na.exclude, method = "spearman")
    print(paste(res$estimate, res$p.value, "outdoor_table_right"))
res <- cor.test(dadosAtuais[[colunaQScore]], dadosAtuais$street_furnit, na.action = na.exclude, method = "spearman")
    print(paste(res$estimate, res$p.value, "street_furnit"))
    res <- cor.test(dadosAtuais[[colunaQScore]], dadosAtuais$g11q3_left, na.action = na.exclude, method = "spearman")
    print(paste(res$estimate, res$p.value, "street_furnit_left"))
    res <- cor.test(dadosAtuais[[colunaQScore]], dadosAtuais$g11q3_right, na.action = na.exclude, method = "spearman")
    print(paste(res$estimate, res$p.value, "street_furnit_right"))
    
    temp12 = listaDados[[12]]
    dadosAtuais <- temp12[(temp12$V1 == questao),] 
    res <- cor.test(dadosAtuais[[colunaQScore]], dadosAtuais$basic_col, na.action = na.exclude, method = "spearman")
    print(paste(res$estimate, res$p.value, "basic_col"))
res <- cor.test(dadosAtuais[[colunaQScore]], dadosAtuais$lights, na.action = na.exclude, method = "spearman")
    print(paste(res$estimate, res$p.value, "lights"))
    res <- cor.test(dadosAtuais[[colunaQScore]], dadosAtuais$g12q2_left, na.action = na.exclude, method = "spearman")
    print(paste(res$estimate, res$p.value, "lights_left"))
    res <- cor.test(dadosAtuais[[colunaQScore]], dadosAtuais$g12q2_right, na.action = na.exclude, method = "spearman")
    print(paste(res$estimate, res$p.value, "lights_right"))
    res <- cor.test(dadosAtuais[[colunaQScore]], dadosAtuais$accent_col, na.action = na.exclude, method = "spearman")
    print(paste(res$estimate, res$p.value, "accent_col"))
    
    temp13 = listaDados[[13]]
    dadosAtuais <- temp13[(temp13$V1 == questao),] 
res <- cor.test(dadosAtuais[[colunaQScore]], dadosAtuais$people, na.action = na.exclude, method = "spearman")
    print(paste(res$estimate, res$p.value, "people"))
    res <- cor.test(dadosAtuais[[colunaQScore]], dadosAtuais$g13q1_left, na.action = na.exclude, method = "spearman")
    print(paste(res$estimate, res$p.value, "people_left"))
    res <- cor.test(dadosAtuais[[colunaQScore]], dadosAtuais$g13q1_right, na.action = na.exclude, method = "spearman")
    print(paste(res$estimate, res$p.value, "people_right"))
res <- cor.test(dadosAtuais[[colunaQScore]], dadosAtuais$prop_active_use, na.action = na.exclude, method = "spearman")
    print(paste(res$estimate, res$p.value, "prop_active_use"))
    res <- cor.test(dadosAtuais[[colunaQScore]], dadosAtuais$g13q2_left, na.action = na.exclude, method = "spearman")
    print(paste(res$estimate, res$p.value, "prop_active_use_left"))
    res <- cor.test(dadosAtuais[[colunaQScore]], dadosAtuais$g13q2_right, na.action = na.exclude, method = "spearman")
    print(paste(res$estimate, res$p.value, "prop_active_use_right"))
    sink()
}

calculaCorrelacoes( list(temp, temp2, temp3, temp4, temp5, temp6, temp7, temp8, temp9, temp10, temp11, temp12, temp13), "V3.Geral", "agrad%C3%A1vel?", "correlacao-agrad.dat")
# 
# calculaCorrelacoes( list(temp, temp2, temp3, temp4, temp5, temp6, temp7, temp8, temp9, temp10, temp11, temp12, temp13), "V3.Masculino", 'agradavel?', "correlacao-agrad-masc.dat")
# calculaCorrelacoes( list(temp, temp2, temp3, temp4, temp5, temp6, temp7, temp8, temp9, temp10, temp11, temp12, temp13), "V3.Feminino", 'agradavel?', "correlacao-agrad-fem.dat")
# calculaCorrelacoes( list(temp, temp2, temp3, temp4, temp5, temp6, temp7, temp8, temp9, temp10, temp11, temp12, temp13), "V3.Jovem", 'agradavel?', "correlacao-agrad-jov.dat")
# calculaCorrelacoes( list(temp, temp2, temp3, temp4,temp5, temp6, temp7, temp8, temp9, temp10, temp11, temp12, temp13), "V3.Adulto", 'agradavel?', "correlacao-agrad-adu.dat")
# calculaCorrelacoes( list(temp, temp2, temp3, temp4, temp5, temp6, temp7, temp8, temp9, temp10, temp11, temp12, temp13), "V3.Casado", 'agradavel?', "correlacao-agrad-cas.dat")
# calculaCorrelacoes( list(temp, temp2, temp3, temp4, temp5, temp6, temp7, temp8, temp9, temp10, temp11, temp12, temp13), "V3.Solteiro", 'agradavel?', "correlacao-agrad-sol.dat")
# calculaCorrelacoes( list(temp, temp2, temp3, temp4, temp5, temp6, temp7, temp8, temp9, temp10, temp11, temp12, temp13), "V3.Baixa", 'agradavel?', "correlacao-agrad-bai.dat")
# calculaCorrelacoes( list(temp, temp2, temp3, temp4,temp5, temp6, temp7, temp8, temp9, temp10, temp11, temp12, temp13), "V3.Media", 'agradavel?', "correlacao-agrad-med.dat")
# 
calculaCorrelacoes( list(temp, temp2, temp3, temp4, temp5, temp6, temp7, temp8, temp9, temp10, temp11, temp12, temp13), "V3.Geral", 'seguro?', "correlacao-seg.dat")
# 
# calculaCorrelacoes( list(temp, temp2, temp3, temp4, temp5, temp6, temp7, temp8, temp9, temp10, temp11, temp12, temp13), "V3.Masculino", 'seguro?', "correlacao-seg-masc.dat")
# calculaCorrelacoes( list(temp, temp2, temp3, temp4, temp5, temp6, temp7, temp8, temp9, temp10, temp11, temp12, temp13), "V3.Feminino", 'seguro?', "correlacao-seg-fem.dat")
# calculaCorrelacoes( list(temp, temp2, temp3, temp4, temp5, temp6, temp7, temp8, temp9, temp10, temp11, temp12, temp13), "V3.Jovem", 'seguro?', "correlacao-seg-jov.dat")
# calculaCorrelacoes( list(temp, temp2, temp3, temp4, temp5, temp6, temp7, temp8, temp9, temp10, temp11, temp12, temp13), "V3.Adulto", 'seguro?', "correlacao-seg-adu.dat")
# calculaCorrelacoes( list(temp, temp2, temp3, temp4, temp5, temp6, temp7, temp8, temp9, temp10, temp11, temp12, temp13), "V3.Casado", 'seguro?', "correlacao-seg-cas.dat")
# calculaCorrelacoes( list(temp, temp2, temp3, temp4, temp5, temp6, temp7, temp8, temp9, temp10, temp11, temp12, temp13), "V3.Solteiro", 'seguro?', "correlacao-seg-sol.dat")
# calculaCorrelacoes( list(temp, temp2, temp3, temp4, temp5, temp6, temp7, temp8, temp9, temp10, temp11, temp12, temp13), "V3.Baixa", 'seguro?', "correlacao-seg-bai.dat")
# calculaCorrelacoes( list(temp, temp2, temp3, temp4, temp5, temp6, temp7, temp8, temp9, temp10, temp11, temp12, temp13), "V3.Media", 'seguro?', "correlacao-seg-med.dat")
# 

#Correlacoes por setor
setores <- read.table("geralSetoresAJ.dat", header=TRUE)
novosDadosSet <- reshape(setores, timevar="grupo", idvar=c("V2", "V1", "diag", "hor", "vert", "red", "green", "blue", "bairro", "setor"), direction="wide")
options("scipen"=100, "digits"=4)

#Centro
data1 <- filter(novosDadosSet, bairro == "centro")
correlacao <- cor(x = select(data1, V3.Masculino, V3.Feminino, V3.Casado, V3.Solteiro, V3.Baixa, V3.Media, V3.Jovem, V3.Adulto), method = "spearman")
library(lattice)
rb.palette <- colorRampPalette(c("yellow", "red"), space = "rgb")
levelplot(correlacao, main = "Urban Features Correlation", col.regions = rb.palette(120), cuts=100, at = seq(0, 1, 0.01), xlab = "Urban Features", ylab = "Urban Features", )

data1 <- filter(novosDadosSet, setor == "25040090500004")
correlacao <- cor(x = select(data1, V3.Masculino, V3.Feminino, V3.Casado, V3.Solteiro, V3.Baixa, V3.Media, V3.Jovem, V3.Adulto), method = "spearman")
library(lattice)
rb.palette <- colorRampPalette(c("yellow", "red"), space = "rgb")
levelplot(correlacao, main = "Urban Features Correlation", col.regions = rb.palette(120), cuts=100, at = seq(0, 1, 0.01), xlab = "Urban Features", ylab = "Urban Features")

data1 <- filter(novosDadosSet, setor == "250400905000013" | setor == "250400905000023")
correlacao <- cor(x = select(data1, V3.Masculino, V3.Feminino, V3.Casado, V3.Solteiro, V3.Baixa, V3.Media, V3.Jovem, V3.Adulto), method = "spearman")
library(lattice)
rb.palette <- colorRampPalette(c("yellow", "red"), space = "rgb")
levelplot(correlacao, main = "Urban Features Correlation", col.regions = rb.palette(120), cuts=100, at = seq(0, 1, 0.01), xlab = "Urban Features", ylab = "Urban Features")

#Catole
data1 <- filter(novosDadosSet, bairro == "catole")
correlacao <- cor(x = select(data1, V3.Masculino, V3.Feminino, V3.Casado, V3.Solteiro, V3.Baixa, V3.Media, V3.Jovem, V3.Adulto), method = "spearman")
library(lattice)
rb.palette <- colorRampPalette(c("yellow", "red"), space = "rgb")
levelplot(correlacao, main = "Urban Features Correlation", col.regions = rb.palette(120), cuts=100, at = seq(0, 1, 0.01), xlab = "Urban Features", ylab = "Urban Features")

data1 <- filter(novosDadosSet, setor == "250400905000060")
correlacao <- cor(x = select(data1, V3.Masculino, V3.Feminino, V3.Casado, V3.Solteiro, V3.Baixa, V3.Media, V3.Jovem, V3.Adulto), method = "spearman")
library(lattice)
rb.palette <- colorRampPalette(c("yellow", "red"), space = "rgb")
levelplot(correlacao, main = "Urban Features Correlation", col.regions = rb.palette(120), cuts=100, at = seq(0, 1, 0.01), xlab = "Urban Features", ylab = "Urban Features")

data1 <- filter(novosDadosSet, setor == "250400905000062")
correlacao <- cor(x = select(data1, V3.Masculino, V3.Feminino, V3.Casado, V3.Solteiro, V3.Baixa, V3.Media, V3.Jovem, V3.Adulto), method = "spearman")
library(lattice)
rb.palette <- colorRampPalette(c("yellow", "red"), space = "rgb")
levelplot(correlacao, main = "Urban Features Correlation", col.regions = rb.palette(120), cuts=100, at = seq(0, 1, 0.01), xlab = "Urban Features", ylab = "Urban Features")

#Liberdade
data1 <- filter(novosDadosSet, bairro == "liberdade")
correlacao <- cor(x = select(data1, V3.Masculino, V3.Feminino, V3.Casado, V3.Solteiro, V3.Baixa, V3.Media, V3.Jovem, V3.Adulto), method = "spearman")
library(lattice)
rb.palette <- colorRampPalette(c("yellow", "red"), space = "rgb")
levelplot(correlacao, main = "Urban Features Correlation", col.regions = rb.palette(120), cuts=100, at = seq(0, 1, 0.01), xlab = "Urban Features", ylab = "Urban Features")

data1 <- filter(novosDadosSet, setor == "250400905000089")
correlacao <- cor(x = select(data1, V3.Masculino, V3.Feminino, V3.Casado, V3.Solteiro, V3.Baixa, V3.Media, V3.Jovem, V3.Adulto), method = "spearman")
library(lattice)
rb.palette <- colorRampPalette(c("yellow", "red"), space = "rgb")
levelplot(correlacao, main = "Urban Features Correlation", col.regions = rb.palette(120), cuts=100, at = seq(0, 1, 0.01), xlab = "Urban Features", ylab = "Urban Features")

data1 <- filter(novosDadosSet, setor == "250400905000095")
correlacao <- cor(x = select(data1, V3.Masculino, V3.Feminino, V3.Casado, V3.Solteiro, V3.Baixa, V3.Media, V3.Jovem, V3.Adulto), method = "spearman")
library(lattice)
rb.palette <- colorRampPalette(c("yellow", "red"), space = "rgb")
levelplot(correlacao, main = "Urban Features Correlation", col.regions = rb.palette(120), cuts=100, at = seq(0, 1, 0.01), xlab = "Urban Features", ylab = "Urban Features")


#Resumo por bairros
temp1 <- lapply(as.character(novosDados$V2), function (x) strsplit(x, split="/", fixed=TRUE)[[1]][1])
neigs1 <- unlist(lapply(temp1, '[[', 1))
novosDados$bairro <- neigs1

colnames(novosDados)[colnames(novosDados) == "V2"] <- "image_url"
allData <- Reduce(function(x, y) merge(x, y, all=TRUE), list(novosDados, groupedData1, groupedData2, groupedData3, groupedData3, groupedData4, groupedData5, groupedData6, groupedData7,groupedData8, groupedData9, groupedData10, groupedData11, groupedData12, groupedData13))

# #Centro
centro <- filter(allData, bairro == "centro")
sink("centro-summary.dat")
mean(centro$street_wid, na.rm = TRUE)
mean(centro$sidewalk_wid, na.rm = TRUE)
#mean(centro$sidewalk_wid_right, na.rm = TRUE)
mean(centro$public_art, na.rm = TRUE)
mean(centro$mov_cars, na.rm = TRUE)
mean(centro$park_cars, na.rm = TRUE)
#mean(centro$park_cars_right, na.rm = TRUE)
mean(centro$mov_ciclyst, na.rm = TRUE)
mean(centro$debris, na.rm = TRUE)
#mean(centro$debris_right, na.rm = TRUE)
mean(centro$pavement, na.rm = TRUE)
#mean(centro$pavement_right, na.rm = TRUE)
mean(centro$landscape, na.rm = TRUE)
#mean(centro$landscape_right, na.rm = TRUE)
mean(centro$courtyards, na.rm = TRUE)
mean(centro$major_landsc, na.rm = TRUE)
mean(centro$build_ident, na.rm = TRUE)
mean(centro$build_nrectan, na.rm = TRUE)
mean(centro$prop_street_wall, na.rm = TRUE)
#mean(centro$prop_street_wall_right, na.rm = TRUE)
mean(centro$prop_wind, na.rm = TRUE)
#mean(centro$prop_wind_right, na.rm = TRUE)
mean(centro$long_sight, na.rm = TRUE)
mean(centro$prop_sky_ahead, na.rm = TRUE)
mean(centro$prop_sky_across, na.rm = TRUE)
#mean(centro$prop_sky_across_right, na.rm = TRUE)
mean(centro$trees, na.rm = TRUE)
#mean(centro$trees_right, na.rm = TRUE)
mean(centro$small_planters, na.rm = TRUE)
#mean(centro$small_planters_right, na.rm = TRUE)
mean(centro$build_height, na.rm = TRUE)
#mean(centro$build_height_right, na.rm = TRUE)
mean(centro$diff_build, na.rm = TRUE)
mean(centro$prop_hist_build, na.rm = TRUE)
mean(centro$outdoor_table, na.rm = TRUE)
#mean(centro$outdoor_table_right, na.rm = TRUE)
mean(centro$street_furnit, na.rm = TRUE)
#mean(centro$street_furnit_right, na.rm = TRUE)
mean(centro$basic_col, na.rm = TRUE)
mean(centro$lights, na.rm = TRUE)
#mean(centro$lights_right, na.rm = TRUE)
mean(centro$accent_col, na.rm = TRUE)
mean(centro$people, na.rm = TRUE)
#mean(centro$people_right, na.rm = TRUE)
mean(centro$prop_active_use, na.rm = TRUE)
#mean(centro$prop_active_use_right, na.rm = TRUE)
sink()
# 
# #Catole
catole <- filter(allData, bairro == "catole")
sink("catole-summary.dat")
mean(catole$street_wid, na.rm = TRUE)
mean(catole$sidewalk_wid, na.rm = TRUE)
#mean(catole$sidewalk_wid_right, na.rm = TRUE)
mean(catole$public_art, na.rm = TRUE)
mean(catole$mov_cars, na.rm = TRUE)
mean(catole$park_cars, na.rm = TRUE)
#mean(catole$park_cars_right, na.rm = TRUE)
mean(catole$mov_ciclyst, na.rm = TRUE)
mean(catole$debris, na.rm = TRUE)
#mean(catole$debris_right, na.rm = TRUE)
mean(catole$pavement, na.rm = TRUE)
#mean(catole$pavement_right, na.rm = TRUE)
mean(catole$landscape, na.rm = TRUE)
#mean(catole$landscape_right, na.rm = TRUE)
mean(catole$courtyards, na.rm = TRUE)
mean(catole$major_landsc, na.rm = TRUE)
mean(catole$build_ident, na.rm = TRUE)
mean(catole$build_nrectan, na.rm = TRUE)
mean(catole$prop_street_wall, na.rm = TRUE)
#mean(catole$prop_street_wall_right, na.rm = TRUE)
mean(catole$prop_wind, na.rm = TRUE)
#mean(catole$prop_wind_right, na.rm = TRUE)
mean(catole$long_sight, na.rm = TRUE)
mean(catole$prop_sky_ahead, na.rm = TRUE)
mean(catole$prop_sky_across, na.rm = TRUE)
#mean(catole$prop_sky_across_right, na.rm = TRUE)
mean(catole$trees, na.rm = TRUE)
#mean(catole$trees_right, na.rm = TRUE)
mean(catole$small_planters, na.rm = TRUE)
#mean(catole$small_planters_right, na.rm = TRUE)
mean(catole$build_height, na.rm = TRUE)
#mean(catole$build_height_right, na.rm = TRUE)
mean(catole$diff_build, na.rm = TRUE)
mean(catole$prop_hist_build, na.rm = TRUE)
mean(catole$outdoor_table, na.rm = TRUE)
#mean(catole$outdoor_table_right, na.rm = TRUE)
mean(catole$street_furnit, na.rm = TRUE)
#mean(catole$street_furnit_right, na.rm = TRUE)
mean(catole$basic_col, na.rm = TRUE)
mean(catole$lights, na.rm = TRUE)
#mean(catole$lights_right, na.rm = TRUE)
mean(catole$accent_col, na.rm = TRUE)
mean(catole$people, na.rm = TRUE)
#mean(catole$people_right, na.rm = TRUE)
mean(catole$prop_active_use, na.rm = TRUE)
#mean(catole$prop_active_use_right, na.rm = TRUE)
sink()
# 
# #Liberdade
liberdade <- filter(allData, bairro == "liberdade")
sink("liberdade-summary.dat")
mean(liberdade$street_wid, na.rm = TRUE)
mean(liberdade$sidewalk_wid, na.rm = TRUE)
#mean(liberdade$sidewalk_wid_right, na.rm = TRUE)
mean(liberdade$public_art, na.rm = TRUE)
mean(liberdade$mov_cars, na.rm = TRUE)
mean(liberdade$park_cars, na.rm = TRUE)
#mean(liberdade$park_cars_right, na.rm = TRUE)
mean(liberdade$mov_ciclyst, na.rm = TRUE)
mean(liberdade$debris, na.rm = TRUE)
#mean(liberdade$debris_right, na.rm = TRUE)
mean(liberdade$pavement, na.rm = TRUE)
#mean(liberdade$pavement_right, na.rm = TRUE)
mean(liberdade$landscape, na.rm = TRUE)
#mean(liberdade$landscape_right, na.rm = TRUE)
mean(liberdade$courtyards, na.rm = TRUE)
mean(liberdade$major_landsc, na.rm = TRUE)
mean(liberdade$build_ident, na.rm = TRUE)
mean(liberdade$build_nrectan, na.rm = TRUE)
mean(liberdade$prop_street_wall, na.rm = TRUE)
#mean(liberdade$prop_street_wall_right, na.rm = TRUE)
mean(liberdade$prop_wind, na.rm = TRUE)
#mean(liberdade$prop_wind_right, na.rm = TRUE)
mean(liberdade$long_sight, na.rm = TRUE)
mean(liberdade$prop_sky_ahead, na.rm = TRUE)
mean(liberdade$prop_sky_across, na.rm = TRUE)
#mean(liberdade$prop_sky_across_right, na.rm = TRUE)
mean(liberdade$trees, na.rm = TRUE)
#mean(liberdade$trees_right, na.rm = TRUE)
mean(liberdade$small_planters, na.rm = TRUE)
#mean(liberdade$small_planters_right, na.rm = TRUE)
mean(liberdade$build_height, na.rm = TRUE)
#mean(liberdade$build_height_right, na.rm = TRUE)
mean(liberdade$diff_build, na.rm = TRUE)
mean(liberdade$prop_hist_build, na.rm = TRUE)
mean(liberdade$outdoor_table, na.rm = TRUE)
#mean(liberdade$outdoor_table_right, na.rm = TRUE)
mean(liberdade$street_furnit, na.rm = TRUE)
#mean(liberdade$street_furnit_right, na.rm = TRUE)
mean(liberdade$basic_col, na.rm = TRUE)
mean(liberdade$lights, na.rm = TRUE)
#mean(liberdade$lights_right, na.rm = TRUE)
mean(liberdade$accent_col, na.rm = TRUE)
mean(liberdade$people, na.rm = TRUE)
#mean(liberdade$people_right, na.rm = TRUE)
mean(liberdade$prop_active_use, na.rm = TRUE)
#mean(liberdade$prop_active_use_right, na.rm = TRUE)
sink()
# 
# #Confidence interval?
# t.test(centro$people_left, na.action = na.rm )$conf.int

#Regressao
colnames(novosDados)[colnames(novosDados) == "V2"] <- "image_url"
temp <- merge(groupedData1, novosDados, by.x="image_url", by.y="image_url")
temp <- merge(temp, groupedData2, by.x="image_url", by.y="image_url")
temp <- merge(temp, groupedData3, by.x="image_url", by.y="image_url")
temp <- merge(temp, groupedData4, by.x="image_url", by.y="image_url")
temp <- merge(temp, groupedData5, by.x="image_url", by.y="image_url")
temp <- merge(temp, groupedData6, by.x="image_url", by.y="image_url")
temp <- merge(temp, groupedData7, by.x="image_url", by.y="image_url")
temp <- merge(temp, groupedData8, by.x="image_url", by.y="image_url")
temp<- merge(temp, groupedData9, by.x="image_url", by.y="image_url")
temp <- merge(temp, groupedData10, by.x="image_url", by.y="image_url")
temp <- merge(temp, groupedData11, by.x="image_url", by.y="image_url")
temp <- merge(temp, groupedData12, by.x="image_url", by.y="image_url")
temp <- merge(temp, groupedData13, by.x="image_url", by.y="image_url")

temp$area[temp$bairro == "centro"] <- "norte"
temp$area[temp$bairro == "liberdade"] <- "oeste"
temp$area[temp$bairro == "catole"] <- "oeste"

agrad <- filter(temp, V1 == "agrad%C3%A1vel?")
seg <- filter(temp, V1 == "seguro?")

#Kendall adaptation to consider weights as the difference in amount of features between images
kendallWithWeights <- function(data, iterations){
    
    data$graffiti <- as.character(data$graffiti)
    data$graffiti[data$graffiti == "No"] <- 0
    data$graffiti[data$graffiti == "Yes"] <- 1
    data$build_diff_ages <- as.character(data$build_diff_ages)
    data$build_diff_ages[data$build_diff_ages == "No"] <- 0
    data$build_diff_ages[data$build_diff_ages == "yes"] <- 1
  
    #Maximum comparisons - worst scenario ever!
    amountOfItems <- nrow(data)
#     itemsWithMax <- floor(amountOfItems/2)
#     den <- 0
#     for( i in seq(1, itemsWithMax) ) {
#         den <- den + ((amountOfItems-i) - (itemsWithMax-i))
#     }
#     #Max values of each feature
#     maxMovCars <- max(data$mov_cars)
#     maxParkCars <- max(data$park_cars)
#     maxMovCicly <- max(data$mov_ciclyst)
#     maxBuildId <- max(data$build_ident)
#     maxBuildNRec <- max(data$build_nrectan)
#     maxTree <- max(data$trees)
#     maxSmallPla <- max(data$small_planters)
#     maxDiffBuild <- max(data$diff_build)
#     maxStreeFur <- max(data$street_furnit)
#     maxBasCol <- max(data$basic_col)
#     maxLigh <- max(data$lights)
#     maxAccenCol <- max(data$accent_col)
#     maxPeop <- max(data$people)
#     maxGraff <- max(as.integer(data$graffiti))
#     maxBuildDiffAges <- max(as.integer(data$build_diff_ages))

    #Maximum comparisons - worst scenario possible between these two groups!
    #data$index2 <- seq(amountOfItems, 1)#Fake index, completely opposite rank!
    featuresMapMax <- data.frame(movCars = 0 , parkCars = 0, movCicly= 0, buildId = 0, buildNRec=0, tree=0, smallPla=0, diffBuild=0, streeFur=0, basCol=0, ligh=0, accenCol=0, peop=0, graff=0, buildDiffAges=0)
    
    #Improve? http://stackoverflow.com/questions/6269526/r-applying-a-function-to-all-row-pairs-of-a-matrix-without-for-loop
    featuresMapG1 <- data.frame(movCars = 0 , parkCars = 0, movCicly= 0, buildId = 0, buildNRec=0, tree=0, smallPla=0, diffBuild=0, streeFur=0, basCol=0, ligh=0, accenCol=0, peop=0, graff=0, buildDiffAges=0, rmovCars=0, rparkCars=0, rmovCicly=0, rbuildId=0, rbuildNRec=0, rtree=0, rsmallPla=0, rdiffBuild=0, rstreeFur=0, rbasCol=0, rligh=0, raccenCol=0, rpeop=0, rgraff=0, rbuildDiffAges=0)
    
    #First call, comparing for group 1
    data <- arrange(data, rank)
    for( i in seq(1, amountOfItems) ){
        rankLine1 <- data[i,]
        
        if(i+1 <= amountOfItems){
          
            for( j in seq(i+1, amountOfItems) ){
                rankLine2 <- data[j,]
                
                if( (rankLine1$rank < rankLine2$rank) & (rankLine1$index > rankLine2$index) ){
                    featuresMapG1$movCars <- featuresMapG1$movCars + (rankLine1$mov_cars - rankLine2$mov_cars)
                    #print(paste(rankLine1$rank, " ", rankLine2$rank, " ", rankLine1$index, " ", rankLine2$index, " ", (rankLine1$park_cars - rankLine2$park_cars)))
                    featuresMapG1$parkCars <- featuresMapG1$parkCars + (rankLine1$park_cars - rankLine2$park_cars)
                    featuresMapG1$movCicly <- featuresMapG1$movCicly + (rankLine1$mov_ciclyst - rankLine2$mov_ciclyst)
                    featuresMapG1$buildId <- featuresMapG1$buildId + (rankLine1$build_ident - rankLine2$build_ident)
                    featuresMapG1$buildNRec <- featuresMapG1$buildNRec + (rankLine1$build_nrectan - rankLine2$build_nrectan)
                    featuresMapG1$tree <- featuresMapG1$tree + (rankLine1$trees - rankLine2$trees)
                    featuresMapG1$smallPla <- featuresMapG1$smallPla + (rankLine1$small_planters - rankLine2$small_planters)
                    featuresMapG1$diffBuild <- featuresMapG1$diffBuild + (rankLine1$diff_build - rankLine2$diff_build)
                    featuresMapG1$streeFur <- featuresMapG1$streeFur + (rankLine1$street_furnit - rankLine2$street_furnit)
                    featuresMapG1$basCol <- featuresMapG1$basCol + (rankLine1$basic_col - rankLine2$basic_col)
                    featuresMapG1$ligh <- featuresMapG1$ligh + (rankLine1$lights - rankLine2$lights)
                    featuresMapG1$accenCol <- featuresMapG1$accenCol + (rankLine1$accent_col - rankLine2$accent_col)
                    featuresMapG1$peop <- featuresMapG1$peop + (rankLine1$people - rankLine2$people)
                    featuresMapG1$graff <- featuresMapG1$graff + (as.integer(rankLine1$graffiti) - as.integer(rankLine2$graffiti))
                    featuresMapG1$buildDiffAges <- featuresMapG1$buildDiffAges + (as.integer(rankLine1$build_diff_ages) - as.integer(rankLine2$build_diff_ages))
                }  
                
                #Accounting differences for max!
                featuresMapMax$movCars <- featuresMapMax$movCars + abs(rankLine1$mov_cars - rankLine2$mov_cars)
                featuresMapMax$parkCars <- featuresMapMax$parkCars + abs(rankLine1$park_cars - rankLine2$park_cars)
                featuresMapMax$movCicly <- featuresMapMax$movCicly + abs(rankLine1$mov_ciclyst - rankLine2$mov_ciclyst)
                featuresMapMax$buildId <- featuresMapMax$buildId + abs(rankLine1$build_ident - rankLine2$build_ident)
                featuresMapMax$buildNRec <- featuresMapMax$buildNRec + abs(rankLine1$build_nrectan - rankLine2$build_nrectan)
                featuresMapMax$tree <- featuresMapMax$tree + abs(rankLine1$trees - rankLine2$trees)
                featuresMapMax$smallPla <- featuresMapMax$smallPla + abs(rankLine1$small_planters - rankLine2$small_planters)
                featuresMapMax$diffBuild <- featuresMapMax$diffBuild + abs(rankLine1$diff_build - rankLine2$diff_build)
                featuresMapMax$streeFur <- featuresMapMax$streeFur + abs(rankLine1$street_furnit - rankLine2$street_furnit)
                featuresMapMax$basCol <- featuresMapMax$basCol + abs(rankLine1$basic_col - rankLine2$basic_col)
                featuresMapMax$ligh <- featuresMapMax$ligh + abs(rankLine1$lights - rankLine2$lights)
                featuresMapMax$accenCol <- featuresMapMax$accenCol + abs(rankLine1$accent_col - rankLine2$accent_col)
                featuresMapMax$peop <- featuresMapMax$peop + abs(rankLine1$people - rankLine2$people)
                featuresMapMax$graff <- featuresMapMax$graff + abs(as.integer(rankLine1$graffiti) - as.integer(rankLine2$graffiti))
                featuresMapMax$buildDiffAges <- featuresMapMax$buildDiffAges + abs(as.integer(rankLine1$build_diff_ages) - as.integer(rankLine2$build_diff_ages))
            }
        }
    }
    
    #Random world
    movCars <- parkCars <- movCicly <- buildId <- buildNRec <- tree <- smallPla <- diffBuild <-streeFur <- basCol <- ligh <-  accenCol <- peop <- graff <- buildDiffAges <- deb <- pav <- land <- propStreetWall <- propWind <- propSkyAhe <- propActiv <- streetW <- sidewalW <- buildHei <- c()
    
    for (i in seq(1, iterations)){
        #randomIndex <- sample(data$index)
        featuresMapR = data.frame(movCars = 0 , parkCars = 0, movCicly= 0, buildId = 0, buildNRec=0, tree=0, smallPla=0, diffBuild=0, streeFur=0, basCol=0, ligh=0, accenCol=0, peop=0, graff=0, buildDiffAges=0)
        randomCols <- sample(colnames(data)[3:17])
        
        for( i in seq(1, amountOfItems) ) {
            rankLine1 <- data[i,]
            if( i+1 <= amountOfItems ) {
                for( j in seq(i+1, amountOfItems) ) {
                    rankLine2 <- data[j,]
                    
                    if( (rankLine1$rank < rankLine2$rank) & (rankLine1$index > rankLine2$index) ){
                      
                        featuresMapR$movCars <- featuresMapR$movCars + ( as.double(rankLine1[[randomCols[1]]]) - as.double(rankLine2[[randomCols[1]]]) )
                        featuresMapR$parkCars <- featuresMapR$parkCars + ( as.double(rankLine1[[randomCols[2]]]) - as.double(rankLine2[[randomCols[2]]]) )
                        featuresMapR$movCicly <- featuresMapR$movCicly + ( as.double(rankLine1[[randomCols[3]]]) - as.double(rankLine2[[randomCols[3]]]) )
                        featuresMapR$buildId <- featuresMapR$buildId + ( as.double(rankLine1[[randomCols[4]]]) - as.double(rankLine2[[randomCols[4]]]) )
                        featuresMapR$buildNRec <- featuresMapR$buildNRec + ( as.double(rankLine1[[randomCols[5]]]) - as.double(rankLine2[[randomCols[5]]]) )
                        featuresMapR$tree <- featuresMapR$tree + ( as.double(rankLine1[[randomCols[6]]]) - as.double(rankLine2[[randomCols[6]]]) )
                        featuresMapR$smallPla <- featuresMapR$smallPla + ( as.double(rankLine1[[randomCols[7]]]) - as.double(rankLine2[[randomCols[7]]]) )
                        featuresMapR$diffBuild <- featuresMapR$diffBuild + ( as.double(rankLine1[[randomCols[8]]]) - as.double(rankLine2[[randomCols[8]]]) )
                        featuresMapR$streeFur <- featuresMapR$streeFur + ( as.double(rankLine1[[randomCols[9]]]) - as.double(rankLine2[[randomCols[9]]]) )
                        featuresMapR$basCol <- featuresMapR$basCol + ( as.double(rankLine1[[randomCols[10]]]) - as.double(rankLine2[[randomCols[10]]]) )
                        featuresMapR$ligh <- featuresMapR$ligh + ( as.double(rankLine1[[randomCols[11]]]) - as.double(rankLine2[[randomCols[11]]]) )
                        featuresMapR$accenCol <- featuresMapR$accenCol + ( as.double(rankLine1[[randomCols[12]]]) - as.double(rankLine2[[randomCols[12]]]) )
                        featuresMapR$peop <- featuresMapR$peop + ( as.double(rankLine1[[randomCols[13]]]) - as.double(rankLine2[[randomCols[13]]]) )
                        featuresMapR$graff <- featuresMapR$graff + (as.double(rankLine1[[randomCols[14]]]) - as.double(rankLine2[[randomCols[14]]]))
                        featuresMapR$buildDiffAges <- featuresMapR$buildDiffAges + (as.double(rankLine1[[randomCols[15]]]) - as.double(rankLine2[[randomCols[15]]]))
                    }        
                }
            }
        } 
        
        #Binding with previous iterations
        movCars <- cbind(movCars, featuresMapR$movCars)
        parkCars <- cbind(parkCars, featuresMapR$parkCars)
        movCicly <- cbind(movCicly, featuresMapR$movCicly)
        buildId <- cbind(buildId, featuresMapR$buildId)
        buildNRec <- cbind(buildNRec, featuresMapR$buildNRec)
        tree <- cbind(tree, featuresMapR$tree)
        smallPla <- cbind(smallPla, featuresMapR$smallPla)
        diffBuild <- cbind(diffBuild, featuresMapR$diffBuild)
        streeFur <- cbind(streeFur, featuresMapR$streeFur)
        basCol <- cbind(basCol, featuresMapR$basCol)
        ligh <-  cbind(ligh, featuresMapR$ligh)
        accenCol <- cbind(accenCol, featuresMapR$accenCol)
        peop <- cbind(peop, featuresMapR$peop)
        graff <- cbind(graff, featuresMapR$graff)
        buildDiffAges <- cbind(graff, featuresMapR$buildDiffAges)
    }  
    
    featuresMapG1$rmovCars <- mean(movCars) 
    featuresMapG1$rparkCars <- mean(parkCars)
    featuresMapG1$rmovCicly <- mean(movCicly)
    featuresMapG1$rbuildId <- mean(buildId) 
    featuresMapG1$rbuildNRec <- mean(buildNRec) 
    featuresMapG1$rtree <- mean(tree)
    featuresMapG1$rsmallPla <- mean(smallPla)
    featuresMapG1$rdiffBuild <- mean(diffBuild)
    featuresMapG1$rstreeFur <- mean(streeFur) 
    featuresMapG1$rbasCol <- mean(basCol) 
    featuresMapG1$rligh <- mean(ligh)
    featuresMapG1$raccenCol <- mean(accenCol) 
    featuresMapG1$rpeop <- mean(peop) 
    featuresMapG1$rgraff <- mean(graff) 
    featuresMapG1$rbuildDiffAges <- mean(buildDiffAges)

    featuresMapG1$rsdMovCars <- sd(movCars) 
    featuresMapG1$rsdParkCars <- sd(parkCars)
    featuresMapG1$rsdMovCicly <- sd(movCicly)
    featuresMapG1$rsdBuildId <- sd(buildId) 
    featuresMapG1$rsdBuildNRec <- sd(buildNRec) 
    featuresMapG1$rsdTree <- sd(tree)
    featuresMapG1$rsdSmallPla <- sd(smallPla)
    featuresMapG1$rsdDiffBuild <- sd(diffBuild)
    featuresMapG1$rsdStreeFur <- sd(streeFur) 
    featuresMapG1$rsdBasCol <- sd(basCol) 
    featuresMapG1$rsdLigh <- sd(ligh)
    featuresMapG1$rsdAccenCol <- sd(accenCol) 
    featuresMapG1$rsdPeop <- sd(peop) 
    featuresMapG1$rsdGraff <- sd(graff) 
    featuresMapG1$rsdBuildDiffAges <- sd(buildDiffAges)
    
    #Adding random mean values - normalized
    featuresMapG1$rmovCarsN <- mean(movCars) / featuresMapMax$movCars#/ (maxMovCars*den)
    featuresMapG1$rparkCarsN <- mean(parkCars) / featuresMapMax$parkCars#/ (maxParkCars*den)
    featuresMapG1$rmovCiclyN <- mean(movCicly)/ featuresMapMax$movCicly #/ (maxMovCicly*den)
    featuresMapG1$rbuildIdN <- mean(buildId) / featuresMapMax$buildId#/ (maxBuildId*den)
    featuresMapG1$rbuildNRecN <- mean(buildNRec) / featuresMapMax$buildNRec#/ (maxBuildNRec*den)
    featuresMapG1$rtreeN <- mean(tree) / featuresMapMax$tree#/ (maxTree*den)
    featuresMapG1$rsmallPlaN <- mean(smallPla) / featuresMapMax$smallPla#/ (maxSmallPla*den)
    featuresMapG1$rdiffBuildN <- mean(diffBuild) / featuresMapMax$diffBuild#/ (maxDiffBuild*den)
    featuresMapG1$rstreeFurN <- mean(streeFur) / featuresMapMax$streeFur#/ (maxStreeFur*den)
    featuresMapG1$rbasColN <- mean(basCol) / featuresMapMax$basCol#/ (maxBasCol*den)
    featuresMapG1$rlighN <- mean(ligh) / featuresMapMax$ligh#/ (maxLigh*den)
    featuresMapG1$raccenColN <- mean(accenCol) / featuresMapMax$accenCol#/ (maxAccenCol*den)
    featuresMapG1$rpeopN <- mean(peop) / featuresMapMax$peop#/ (maxPeop*den)
    featuresMapG1$rgraffN <- mean(graff) / featuresMapMax$graff#/ (maxGraff*den)
    featuresMapG1$rbuildDiffAgesN <- mean(buildDiffAges) / featuresMapMax$buildDiffAges#/ (maxBuildDiffAges*den)
    
    #Normalizing real values
    featuresMapG1$movCarsN <- featuresMapG1$movCars / featuresMapMax$movCars#(maxMovCars*den)
    featuresMapG1$parkCarsN <- featuresMapG1$parkCars  / featuresMapMax$parkCars#(maxParkCars*den)
    featuresMapG1$movCiclyN <-  featuresMapG1$movCicly / featuresMapMax$movCicly#(maxMovCicly*den)
    featuresMapG1$buildIdN <- featuresMapG1$buildId/ featuresMapMax$buildId#(maxBuildId*den)
    featuresMapG1$buildNRecN <- featuresMapG1$buildNRec / featuresMapMax$buildNRec#(maxBuildNRec*den)
    featuresMapG1$treeN <- featuresMapG1$tree / featuresMapMax$tree#(maxTree*den)
    featuresMapG1$smallPlaN <- featuresMapG1$smallPla / featuresMapMax$smallPla#(maxSmallPla*den)
    featuresMapG1$diffBuildN <- featuresMapG1$diffBuild / featuresMapMax$diffBuild#(maxDiffBuild*den)
    featuresMapG1$streeFurN <- featuresMapG1$streeFur / featuresMapMax$streeFur#(maxStreeFur*den)
    featuresMapG1$basColN <- featuresMapG1$basCol / featuresMapMax$basCol#(maxBasCol*den)
    featuresMapG1$lighN <- featuresMapG1$ligh / featuresMapMax$ligh#(maxLigh*den)
    featuresMapG1$accenColN <- featuresMapG1$accenCol / featuresMapMax$accenCol#(maxAccenCol*den)
    featuresMapG1$peopN <- featuresMapG1$peop  / featuresMapMax$peop#(maxPeop*den)
    featuresMapG1$graffN <- featuresMapG1$graff / featuresMapMax$graff#(maxGraff*den)
    featuresMapG1$buildDiffAgesN <- featuresMapG1$buildDiffAges / featuresMapMax$buildDiffAges#(maxBuildDiffAges*den)
    
    return ( featuresMapG1 )
}

#Calculates maximum denominator for normalization
calcGreatesSum <- function(maxFeature, amountOfImages) {
  sumFeat <- 0
	maxDiff <- amountOfImages - 1
	reuse <- FALSE

	for (i in seq(1, amountOfImages)){
		sumFeat <- sumFeat + maxFeature * (maxDiff)		
		if(maxDiff == 0 | maxDiff == 1){
			maxDiff <- amountOfImages - 1
		}else{
			maxDiff <- maxDiff - 2
		}
	}
	return (sumFeat)
}

#Evaluates presence and coefficients for each picture
calcDanieleCoeff <- function (data) {
    data$diff <- data$rank - data$index
    
    data$movCars <- (data$mov_cars * (data$diff/107)) / sum(data$mov_cars)
    data$parkCars <- (data$park_cars * (data$diff/107)) / sum(data$park_cars)
    data$movCicly <- (data$mov_ciclyst * (data$diff/107)) / sum(data$mov_ciclyst)
    data$buildId <- (data$build_ident * (data$diff/107)) / sum(data$build_ident)
    data$buildNRec <- (data$build_nrectan * (data$diff/107)) / sum(data$build_nrectan)
    data$tree <- (data$trees * (data$diff/107)) / sum(data$trees)
    data$smallPla <- (data$small_planters * (data$diff/107)) / sum(data$small_planters)
    data$diffBuild <- (data$diff_build * (data$diff/107)) / sum(data$diff_build)
    data$streeFur <- (data$street_furnit * (data$diff/107)) / sum(data$street_furnit)
    data$basCol <- (data$basic_col * (data$diff/107)) / sum(data$basic_col)
    data$ligh <- (data$lights * (data$diff/107)) / sum(data$lights)
    data$accenCol <- (data$accent_col * (data$diff/107)) / sum(data$accent_col)
    data$peop <- (data$people * (data$diff/107)) / sum(data$people)
    
    data$graffiti <- as.character(data$graffiti)
    data$graffiti[data$graffiti == "No"] <- 0
    data$graffiti[data$graffiti == "Yes"] <- 1
    data$graff <- (data$diff/107 * as.integer(data$graffiti)) / sum(as.integer(data$graffiti))
    data$build_diff_ages <- as.character(data$build_diff_ages)
    data$build_diff_ages[data$build_diff_ages == "No"] <- 0
    data$build_diff_ages[data$build_diff_ages == "yes"] <- 1
    data$buildDiffAges <- (data$diff/107 * as.integer(data$build_diff_ages)) / sum(as.integer(data$build_diff_ages))
    
    data$movCars2 <- (data$mov_cars * abs(data$diff))
    data$parkCars2 <- (data$park_cars * abs(data$diff))
    data$movCicly2 <- (data$mov_ciclyst * abs(data$diff))
    data$buildId2 <- (data$build_ident * abs(data$diff))
    data$buildNRec2 <- (data$build_nrectan * abs(data$diff))
    data$tree2 <- (data$trees * abs(data$diff))
    data$diffBuild2 <- (data$diff_build * abs(data$diff))
    data$streeFur2 <- (data$street_furnit * abs(data$diff))
    data$smallPla2 <- (data$small_planters * abs(data$diff))
    data$basCol2 <- (data$basic_col * abs(data$diff))
    data$ligh2 <- (data$lights * abs(data$diff))
    data$accenCol2 <- (data$accent_col * abs(data$diff))
    data$peop2 <- (data$people * abs(data$diff))
    data$graff2 <- (abs(data$diff) * as.integer(data$graffiti)) 
    data$buildDiffAges2 <- (abs(data$diff) * as.integer(data$build_diff_ages)) 

    size <- nrow(data)
    data$sumMovCars <- calcGreatesSum(max(data$mov_cars),  size)
    data$sumParkCars <- calcGreatesSum(max(data$park_cars), size)
    data$sumMovCicly <- calcGreatesSum(max(data$mov_ciclyst), size)
    data$sumBuildId <- calcGreatesSum(max(data$build_ident),size)
    data$sumBuildNRec <- calcGreatesSum(max(data$build_nrectan),size)
    data$sumTree <- calcGreatesSum(max(data$trees),size)
    data$sumSmallPla <- calcGreatesSum(max(data$small_planters),size)
    data$sumDiffBuild <- calcGreatesSum(max(data$diff_build),size)
    data$sumStreeFur <- calcGreatesSum(max(data$street_furnit),size)
    data$sumBasCol <- calcGreatesSum(max(data$basic_col),size)
    data$sumLigh <-  calcGreatesSum(max(data$lights),size)
    data$sumAccenCol <- calcGreatesSum(max(data$accent_col),size)
    data$sumPeop <- calcGreatesSum(max(data$people),size)
    data$sumGraff <- calcGreatesSum(max(as.integer(data$graffiti)),size)
    data$sumBuildDiffAges <- calcGreatesSum(max(as.integer(data$build_diff_ages)),size)

    data$maxMovCars <- max(data$mov_cars)
    data$maxParkCars <- max(data$park_cars)
    data$maxMovCicly <- max(data$mov_ciclyst)
    data$maxBuildId <- max(data$build_ident)
    data$maxBuildNRec <- max(data$build_nrectan)
    data$maxTree <- max(data$trees)
    data$maxSmallPla <- max(data$small_planters)
    data$maxDiffBuild <- max(data$diff_build)
    data$maxStreeFur <- max(data$street_furnit)
    data$maxBasCol <- max(data$basic_col)
    data$maxLigh <- max(data$lights)
    data$maxAccenCol <- max(data$accent_col)
    data$maxPeop <- max(data$people)
    data$maxGraff <- max(as.integer(data$graffiti))
    data$maxBuildDiffAges <- max(as.integer(data$build_diff_ages))

    return (data)
}


randomizeCoeff <- function (data, iterations) {
    movCars <- parkCars <- movCicly <- buildId <- buildNRec <- tree <- smallPla <- diffBuild <-streeFur <- basCol <- ligh <-  accenCol <- peop <- graff <- buildDiffAges <- deb <- pav <- land <- propStreetWall <- propWind <- propSkyAhe <- propActiv <- streetW <- sidewalW <- buildHei <- c()
    
    movCars2 <- parkCars2 <- movCicly2 <- buildId2 <- buildNRec2 <- tree2 <- smallPla2 <- diffBuild2 <- streeFur2 <- basCol2 <- ligh2 <-  accenCol2 <- peop2 <- graff2 <- buildDiffAges2 <- deb2 <- pav2 <- land2 <- propStreetWall2 <- propWind2 <- propSkyAhe2 <- propActiv2 <- streetW2 <- sidewalW2 <- buildHei2 <- c()
    
    graffiti <- as.character(data$graffiti)
    graffiti[data$graffiti == "No"] <- 0
    graffiti[data$graffiti == "Yes"] <- 1
    build_diff_ages <- as.character(data$build_diff_ages)
    build_diff_ages[data$build_diff_ages == "No"] <- 0
    build_diff_ages[data$build_diff_ages == "yes"] <- 1
    
    for (i in seq(1, iterations)){#Creating shuffled values
    
        differences <- sample(data$diff)
        
        movCars <- cbind(movCars, (data$mov_cars * differences[2]/107) / sum(data$mov_cars))
        parkCars <- cbind(parkCars, (data$park_cars * differences[3]/107) / sum(data$park_cars))
        movCicly <- cbind(movCicly, (data$mov_ciclyst * differences[4]/107) / sum(data$mov_ciclyst))
        buildId <- cbind(buildId, (data$build_ident * differences[8])/107 / sum(data$build_ident))
        buildNRec <- cbind(buildNRec,(data$build_nrectan * differences[9]/107) / sum(data$build_nrectan))
        tree <- cbind(tree,(data$trees * differences[15]/107) / sum(data$trees))
        smallPla <- cbind(smallPla,(data$small_planters * differences[16]/107) / sum(data$small_planters))
        diffBuild <- cbind(diffBuild,(data$diff_build * differences[19]/107) / sum(data$diff_build))
        streeFur <- cbind(streeFur, (data$street_furnit * differences[20]/107) / sum(data$street_furnit))
        basCol <- cbind(basCol, (data$basic_col * differences[21]/107) / sum(data$basic_col))
        ligh <- cbind(ligh, (data$lights * differences[22]/107) / sum(data$lights))
        accenCol <- cbind(accenCol, (data$accent_col * differences[23]/107) / sum(data$accent_col))
        peop <- cbind(peop, (data$people * differences[24]/107) / sum(data$people))
        
        graff <- cbind(graff, (differences[14]/107 * as.integer(data$graffiti)) / sum(as.integer(data$graffiti)))
        buildDiffAges <- cbind(buildDiffAges, (differences[18]/107 * as.integer(data$build_diff_ages)) / sum(as.integer(data$build_diff_ages)))
        
        movCars2 <- cbind(movCars2, (data$mov_cars * abs(differences[2])))
        parkCars2 <- cbind(parkCars2, (data$park_cars * abs(differences[3])))
        movCicly2 <- cbind(movCicly2, (data$mov_ciclyst * abs(differences[4])))
        buildId2 <- cbind(buildId2, (data$build_ident * abs(differences[8])))
        buildNRec2 <- cbind(buildNRec2,(data$build_nrectan * abs(differences[9])))
        tree2 <- cbind(tree2,(data$trees * abs(differences[15])))
        smallPla2 <- cbind(smallPla2,(data$small_planters * abs(differences[16])))
        diffBuild2 <- cbind(diffBuild2,(data$diff_build * abs(differences[19])))
        streeFur2 <- cbind(streeFur2, (data$street_furnit * abs(differences[20])))
        basCol2 <- cbind(basCol2, (data$basic_col * abs(differences[21])))
        ligh2 <- cbind(ligh2, (data$lights * abs(differences[22])))
        accenCol2 <- cbind(accenCol2, (data$accent_col * abs(differences[23])))
        peop2 <- cbind(peop2, (data$people * abs(differences[24])))
        
        graff2 <- cbind(graff2, (abs(differences[14]) * as.integer(data$graffiti))) 
        buildDiffAges2 <- cbind(buildDiffAges2, (abs(differences[18]) * as.integer(data$build_diff_ages)))
        
    }    
    
        #Shuffle mean and sd
        data$rmovCars <- apply(movCars, 1, mean)
        data$rsdmovCars <- apply(movCars, 1, sd)
        data$rparkCars <- apply(parkCars, 1, mean)
        data$rsdparkCars <- apply(parkCars, 1, sd)
        data$rmovCicly <- apply(movCicly, 1, mean)
        data$rsdmovCicly <- apply(movCicly, 1, sd)
        data$rbuildId <- apply(buildId, 1, mean)
        data$rsdbuildId <- apply(buildId, 1, sd)
        data$rbuildNRec <- apply(buildNRec, 1, mean)
        data$rsdbuildNRec <- apply(buildNRec, 1, sd)
        data$rtree <- apply(tree, 1, mean)
        data$rsdtree <- apply(tree, 1, sd)
        data$rsmallPla <- apply(smallPla, 1, mean)
        data$rsdsmallPla <- apply(smallPla, 1, sd)
        data$rdiffBuild <- apply(diffBuild, 1, mean)
        data$rsddiffBuild <- apply(diffBuild, 1, sd)
        data$rstreeFur <- apply(streeFur, 1, mean)
        data$rsdstreeFur <- apply(streeFur, 1, sd)
        data$rbasCol <- apply(basCol, 1, mean)
        data$rsdbasCol <- apply(basCol, 1, sd)
        data$rligh <- apply(ligh, 1, mean)
        data$rsdligh <- apply(ligh, 1, sd)
        data$raccenCol <- apply(accenCol, 1, mean)
        data$rsdaccenCol <- apply(accenCol, 1, sd)
        data$rpeop <- apply(peop, 1, mean)
        data$rsdpeop <- apply(peop, 1, sd)
        
        data$rgraff <- apply(graff, 1, mean)
        data$rsdgraff <- apply(graff, 1, sd)
        data$rbuildDiffAges <- apply(buildDiffAges, 1, mean)
        data$rsdbuildDiffAges <- apply(buildDiffAges, 1, sd)

        #Shuffle mean and sd
        data$rmovCars2 <- apply(movCars2, 1, mean)
        data$rsdmovCars2 <- apply(movCars2, 1, sd)
        data$rparkCars2 <- apply(parkCars2, 1, mean)
        data$rsdparkCars2 <- apply(parkCars2, 1, sd)
        data$rmovCicly2 <- apply(movCicly2, 1, mean)
        data$rsdmovCicly2 <- apply(movCicly2, 1, sd)
        data$rbuildId2 <- apply(buildId2, 1, mean)
        data$rsdbuildId2 <- apply(buildId2, 1, sd)
        data$rbuildNRec2 <- apply(buildNRec2, 1, mean)
        data$rsdbuildNRec2 <- apply(buildNRec2, 1, sd)
        data$rtree2 <- apply(tree2, 1, mean)
        data$rsdtree2 <- apply(tree2, 1, sd)
        data$rsmallPla2 <- apply(smallPla2, 1, mean)
        data$rsdsmallPla2 <- apply(smallPla2, 1, sd)
        data$rdiffBuild2 <- apply(diffBuild2, 1, mean)
        data$rsddiffBuild2 <- apply(diffBuild2, 1, sd)
        data$rstreeFur2 <- apply(streeFur2, 1, mean)
        data$rsdstreeFur2 <- apply(streeFur2, 1, sd)
        data$rbasCol2 <- apply(basCol2, 1, mean)
        data$rsdbasCol2 <- apply(basCol2, 1, sd)
        data$rligh2 <- apply(ligh2, 1, mean)
        data$rsdligh2 <- apply(ligh2, 1, sd)
        data$raccenCol2 <- apply(accenCol2, 1, mean)
        data$rsdaccenCol2 <- apply(accenCol2, 1, sd)
        data$rpeop2 <- apply(peop2, 1, mean)
        data$rsdpeop2 <- apply(peop2, 1, sd)
        
        data$rgraff2 <- apply(graff2, 1, mean)
        data$rsdgraff2 <- apply(graff2, 1, sd)
        data$rbuildDiffAges2 <- apply(buildDiffAges2, 1, mean)
        data$rsdbuildDiffAges2 <- apply(buildDiffAges2, 1, sd)
        
    return (data)
}

iterations <- 10000

simulateCoefShuffle <- function(agrad.l, iterations){


  cmov <- cpark <- ccic <- cbuiid <- cbuiNR <- ctree <- csmalP <- cdiffB <- cfur <- cbcol <- clig <- cacol <- cgraf <- cdiffA <- cdeb <- cpav <- clan <- cwall <- cwind <- cskyA <- cskyAc <- cstreet <- cside <- cbuiH <- cpeop <- cacti <- 0
  
  agrad.l2 <- randomizeCoeff(agrad.l, iterations)

  print("### P-values for Coeff - Flavio")
  res <- wilcox.test(agrad.l$movCars2, agrad.l2$rmovCars2, na.action = na.exclude, conf.int = TRUE, paired = TRUE)
   cmov = res$p.value

    res <- wilcox.test(agrad.l$parkCars2, agrad.l2$rparkCars2, na.action = na.exclude, conf.int = TRUE, paired = TRUE)
    cpark = res$p.value

    res <- wilcox.test(agrad.l$movCicly2, agrad.l2$rmovCicly2, na.action = na.exclude, conf.int = TRUE, paired = TRUE)
    ccic = res$p.value

    res <- wilcox.test(agrad.l$buildId2, agrad.l2$rbuildId2, na.action = na.exclude, conf.int = TRUE, paired = TRUE)
    cbuiid = res$p.value

    res <- wilcox.test(agrad.l$buildNRec2, agrad.l2$rbuildNRec2, na.action = na.exclude, conf.int = TRUE, paired = TRUE)
    cbuiNR = res$p.value

    res <- wilcox.test(agrad.l$tree2, agrad.l2$rtree2, na.action = na.exclude, conf.int = TRUE, paired = TRUE)
    ctree = res$p.value

    res <- wilcox.test(agrad.l$smallPla2, agrad.l2$rsmallPla2, na.action = na.exclude, conf.int = TRUE, paired = TRUE)
    csmalP= res$p.value

    res <- wilcox.test(agrad.l$diffBuild2, agrad.l2$rdiffBuild2, na.action = na.exclude, conf.int = TRUE, paired = TRUE)
    cdiffB = res$p.value

    res <- wilcox.test(agrad.l$streeFur2, agrad.l2$rstreeFur2, na.action = na.exclude, conf.int = TRUE, paired = TRUE)
    cfur = res$p.value

    res <- wilcox.test(agrad.l$basCol2, agrad.l2$rbasCol2, na.action = na.exclude, conf.int = TRUE, paired = TRUE)
    cbcol = res$p.value

    res <- wilcox.test(agrad.l$ligh2, agrad.l2$rligh2, na.action = na.exclude, conf.int = TRUE, paired = TRUE)
    clig = res$p.value

    res <- wilcox.test(agrad.l$accenCol2, agrad.l2$raccenCol2, na.action = na.exclude, conf.int = TRUE, paired = TRUE)
    cacol = res$p.value

    res <- wilcox.test(agrad.l$peop2, agrad.l2$rpeop2, na.action = na.exclude, conf.int = TRUE, paired = TRUE)
    cpeop = res$p.value
    
    res <- wilcox.test(agrad.l$graff2, agrad.l2$rgraff2, na.action = na.exclude, conf.int = TRUE, paired = TRUE)
    cgraf = res$p.value

    res <- wilcox.test(agrad.l$buildDiffAges2, agrad.l2$rbuildDiffAges2, na.action = na.exclude, conf.int = TRUE, paired = TRUE)
    cdiffA = res$p.value

    
  print(paste("P-values - mov cars", cmov)) #/ iterations))
  print(paste("P-values - park cars", cpark)) #/ iterations))
  print(paste("P-values - cyclists", ccic)) #/ iterations))
  print(paste("P-values - build ident", cbuiid)) #/ iterations))
  print(paste("P-values - build n rect", cbuiNR)) #/ iterations))
  print(paste("P-values - trees", ctree)) #/ iterations))
  print(paste("P-values - small planters",csmalP))# / iterations))
  print(paste("P-values - diff buildings", cdiffB)) #/ iterations))
  print(paste("P-values - furniture", cfur)) #/ iterations))
  print(paste("P-values - bas col", cbcol)) #/ iterations))
  print(paste("P-values - acce col", cacol)) #/ iterations))
  print(paste("P-values - lig", clig)) #/ iterations))
  print(paste("P-values - peop", cpeop)) #/ iterations))
  print(paste("P-values - graffiti", cgraf)) #/ iterations))
  print(paste("P-values - build diff ages", cdiffA)) #/ iterations))

print("### P-values for Coeff - Daniele")
  res <- wilcox.test(agrad.l$movCars, agrad.l2$rmovCars, na.action = na.exclude, conf.int = TRUE, paired = TRUE)
   cmov = res$p.value

    res <- wilcox.test(agrad.l$parkCars, agrad.l2$rparkCars, na.action = na.exclude, conf.int = TRUE, paired = TRUE)
    cpark = res$p.value

    res <- wilcox.test(agrad.l$movCicly, agrad.l2$rmovCicly, na.action = na.exclude, conf.int = TRUE, paired = TRUE)
    ccic = res$p.value

    res <- wilcox.test(agrad.l$buildId, agrad.l2$rbuildId, na.action = na.exclude, conf.int = TRUE, paired = TRUE)
    cbuiid = res$p.value

    res <- wilcox.test(agrad.l$buildNRec, agrad.l2$rbuildNRec, na.action = na.exclude, conf.int = TRUE, paired = TRUE)
    cbuiNR = res$p.value

    res <- wilcox.test(agrad.l$tree, agrad.l2$rtree, na.action = na.exclude, conf.int = TRUE, paired = TRUE)
    ctree = res$p.value

    res <- wilcox.test(agrad.l$smallPla, agrad.l2$rsmallPla, na.action = na.exclude, conf.int = TRUE, paired = TRUE)
    csmalP= res$p.value

    res <- wilcox.test(agrad.l$diffBuild, agrad.l2$rdiffBuild, na.action = na.exclude, conf.int = TRUE, paired = TRUE)
    cdiffB = res$p.value

    res <- wilcox.test(agrad.l$streeFur, agrad.l2$rstreeFur, na.action = na.exclude, conf.int = TRUE, paired = TRUE)
    cfur = res$p.value

    res <- wilcox.test(agrad.l$basCol, agrad.l2$rbasCol, na.action = na.exclude, conf.int = TRUE, paired = TRUE)
    cbcol = res$p.value

    res <- wilcox.test(agrad.l$ligh, agrad.l2$rligh, na.action = na.exclude, conf.int = TRUE, paired = TRUE)
    clig = res$p.value

    res <- wilcox.test(agrad.l$accenCol, agrad.l2$raccenCol, na.action = na.exclude, conf.int = TRUE, paired = TRUE)
    cacol = res$p.value

    res <- wilcox.test(agrad.l$peop, agrad.l2$rpeop, na.action = na.exclude, conf.int = TRUE, paired = TRUE)
    cpeop = res$p.value
    
    res <- wilcox.test(agrad.l$graff, agrad.l2$rgraff, na.action = na.exclude, conf.int = TRUE, paired = TRUE)
    cgraf = res$p.value

    res <- wilcox.test(agrad.l$buildDiffAges, agrad.l2$rbuildDiffAges, na.action = na.exclude, conf.int = TRUE, paired = TRUE)
    cdiffA = res$p.value

    
  print(paste("P-values - mov cars", cmov)) #/ iterations))
  print(paste("P-values - park cars", cpark)) #/ iterations))
  print(paste("P-values - cyclists", ccic)) #/ iterations))
  print(paste("P-values - build ident", cbuiid)) #/ iterations))
  print(paste("P-values - build n rect", cbuiNR)) #/ iterations))
  print(paste("P-values - trees", ctree)) #/ iterations))
  print(paste("P-values - small planters",csmalP))# / iterations))
  print(paste("P-values - diff buildings", cdiffB)) #/ iterations))
  print(paste("P-values - furniture", cfur)) #/ iterations))
  print(paste("P-values - bas col", cbcol)) #/ iterations))
  print(paste("P-values - acce col", cacol)) #/ iterations))
  print(paste("P-values - lig", clig)) #/ iterations))
  print(paste("P-values - peop", cpeop)) #/ iterations))
  print(paste("P-values - graffiti", cgraf)) #/ iterations))
  print(paste("P-values - build diff ages", cdiffA)) #/ iterations))


  return (agrad.l2)

}

printOutputOneListPerFeature <- function(agrad.l2, column1, column2){
     print(">>>>>>>> One list - top 10 ordered by real world coef and containing real world and shuffle world data - Daniele")
      print(head(arrange(select_(agrad.l2, "movCars", "rmovCars", "rsdmovCars", "maxMovCars", "sumMovCars", "image_url", column1, column2, "diff"), desc(movCars)), n = 10))
      print(head(arrange(select_(agrad.l2, "parkCars", "rparkCars", "rsdparkCars", "maxParkCars","sumParkCars", "image_url", column1, column2, "diff"), desc(parkCars)), n = 10))
      print(head(arrange(select_(agrad.l2, "movCicly", "rmovCicly", "rsdmovCicly", "maxMovCicly", "sumMovCicly", "image_url", column1, column2, "diff"), desc(movCicly)), n = 10))
      print(head(arrange(select_(agrad.l2, "buildId", "rbuildId", "rsdbuildId", "maxBuildId", "sumBuildId","image_url", column1, column2, "diff"), desc(buildId)), n = 10))
      print(head(arrange(select_(agrad.l2, "buildNRec", "rbuildNRec", "rsdbuildNRec", "maxBuildNRec", "sumBuildNRec", "image_url", column1, column2, "diff"), desc(buildNRec)), n = 10))
      print(head(arrange(select_(agrad.l2, "tree", "rtree", "rsdtree", "maxTree", "sumTree", "image_url", column1, column2, "diff"), desc(tree)), n = 10))
      print(head(arrange(select_(agrad.l2, "smallPla", "rsmallPla", "rsdsmallPla", "maxSmallPla","sumSmallPla", "image_url", column1, column2, "diff"), desc(smallPla)), n = 10))
      print(head(arrange(select_(agrad.l2, "diffBuild", "rdiffBuild", "rsddiffBuild", "maxDiffBuild", "sumDiffBuild","image_url", column1, column2, "diff"), desc(diffBuild)), n = 10))
      print(head(arrange(select_(agrad.l2, "streeFur", "rstreeFur", "rsdstreeFur", "maxStreeFur", "sumStreeFur", "image_url", column1, column2, "diff"), desc(streeFur)), n = 10))
      print(head(arrange(select_(agrad.l2, "basCol", "rbasCol", "rsdbasCol", "maxBasCol", "sumBasCol", "image_url", column1, column2, "diff"), desc(basCol)), n = 10))
      print(head(arrange(select_(agrad.l2, "accenCol", "raccenCol", "rsdaccenCol", "maxAccenCol", "sumAccenCol","image_url", column1, column2, "diff"), desc(accenCol)), n = 10))
      print(head(arrange(select_(agrad.l2, "ligh", "rligh", "rsdligh", "maxLigh", "sumLigh","image_url", column1, column2, "diff"), desc(ligh)), n = 10))
      print(head(arrange(select_(agrad.l2, "peop", "rpeop", "rsdpeop", "maxPeop", "sumPeop","image_url", column1, column2, "diff"), desc(peop)), n = 10))
      print(head(arrange(select_(agrad.l2, "graff", "rgraff", "rsdgraff", "maxGraff", "sumGraff","image_url", column1, column2, "diff"), desc(graff)), n = 10))
      print(head(arrange(select_(agrad.l2, "buildDiffAges", "rbuildDiffAges", "rsdbuildDiffAges", "maxBuildDiffAges", "sumBuildDiffAges","image_url", column1, column2, "diff"), desc(buildDiffAges)), n = 10))


     print(">>>>>>>> One list - top 10 ordered by real world coef and containing real world and shuffle world data - Flavio")
      print(head(arrange(select_(agrad.l2, "movCars2", "rmovCars2", "rsdmovCars2", "maxMovCars", "sumMovCars", "image_url", column1, column2, "diff"), desc(movCars2)), n = 10))
      print(head(arrange(select_(agrad.l2, "parkCars2", "rparkCars2", "rsdparkCars2", "maxParkCars", "sumParkCars","image_url", column1, column2, "diff"), desc(parkCars2)), n = 10))
      print(head(arrange(select_(agrad.l2, "movCicly2", "rmovCicly2", "rsdmovCicly2", "maxMovCicly", "sumMovCicly","image_url", column1, column2, "diff"), desc(movCicly2)), n = 10))
      print(head(arrange(select_(agrad.l2, "buildId2", "rbuildId2", "rsdbuildId2", "maxBuildId", "sumBuildId","image_url", column1, column2, "diff"), desc(buildId2)), n = 10))
      print(head(arrange(select_(agrad.l2, "buildNRec2", "rbuildNRec2", "rsdbuildNRec2", "maxBuildNRec", "sumBuildNRec","image_url", column1, column2, "diff"), desc(buildNRec2)), n = 10))
      print(head(arrange(select_(agrad.l2, "tree2", "rtree2", "rsdtree2", "maxTree", "sumTree", "image_url", column1, column2, "diff"), desc(tree2)), n = 10))
      print(head(arrange(select_(agrad.l2, "smallPla2", "rsmallPla2", "rsdsmallPla2", "maxSmallPla", "sumSmallPla","image_url", column1, column2, "diff"), desc(smallPla2)), n = 10))
      print(head(arrange(select_(agrad.l2, "diffBuild2", "rdiffBuild2", "rsddiffBuild2", "maxDiffBuild", "sumDiffBuild","image_url", column1, column2, "diff"), desc(diffBuild2)), n = 10))
      print(head(arrange(select_(agrad.l2, "streeFur2", "rstreeFur2", "rsdstreeFur2", "maxStreeFur", "sumStreeFur", "image_url", column1, column2, "diff"), desc(streeFur2)), n = 10))
      print(head(arrange(select_(agrad.l2, "basCol2", "rbasCol2", "rsdbasCol2", "maxBasCol", "sumBasCol","image_url", column1, column2, "diff"), desc(basCol2)), n = 10))
      print(head(arrange(select_(agrad.l2, "accenCol2", "raccenCol2", "rsdaccenCol2", "maxAccenCol", "sumAccenCol","image_url", column1, column2, "diff"), desc(accenCol2)), n = 10))
      print(head(arrange(select_(agrad.l2, "ligh2", "rligh2", "rsdligh2", "maxLigh",  "sumLigh","image_url", column1, column2, "diff"), desc(ligh2)), n = 10))
      print(head(arrange(select_(agrad.l2, "peop2", "rpeop2", "rsdpeop2", "maxPeop", "sumPeop","image_url", column1, column2, "diff"), desc(peop2)), n = 10))
      print(head(arrange(select_(agrad.l2, "graff2", "rgraff2", "rsdgraff2", "maxGraff", "sumGraff","image_url", column1, column2, "diff"), desc(graff2)), n = 10))
      print(head(arrange(select_(agrad.l2, "buildDiffAges2", "rbuildDiffAges2", "rsdbuildDiffAges2", "maxBuildDiffAges","sumBuildDiffAges", "image_url", column1, column2, "diff"), desc(buildDiffAges2)), n = 10))
  
}

printOutputTwoListsPerFeature <- function(agrad.l2, column1, column2){
      print(">>>>>>>> Two lists - top 10 ordered by real world coef ; top 10 ordered by shuffle world - Daniele")

      print(head(arrange(select_(agrad.l2, "movCars", "maxMovCars", "image_url", column1, column2, "diff"), desc(movCars)), n = 10))
      print(head(arrange(select_(agrad.l2, "rmovCars", "rsdmovCars", "maxMovCars", "image_url", column1, column2, "diff"), desc(rmovCars)), n = 10))
      print(head(arrange(select_(agrad.l2, "parkCars", "maxParkCars", "image_url", column1, column2, "diff"), desc(parkCars)), n = 10))
      print(head(arrange(select_(agrad.l2, "rparkCars", "rsdparkCars", "maxParkCars", "image_url", column1, column2, "diff"), desc(rparkCars)), n = 10))
      print(head(arrange(select_(agrad.l2, "movCicly", "maxMovCicly", "image_url", column1, column2, "diff"), desc(movCicly)), n = 10))
      print(head(arrange(select_(agrad.l2, "rmovCicly", "rsdmovCicly", "maxMovCicly", "image_url", column1, column2, "diff"), desc(rmovCicly)), n = 10))
      print(head(arrange(select_(agrad.l2, "buildId", "maxBuildId", "image_url", column1, column2, "diff"), desc(buildId)), n = 10))
      print(head(arrange(select_(agrad.l2, "rbuildId", "rsdbuildId", "maxBuildId", "image_url", column1, column2, "diff"), desc(rbuildId)), n = 10))
      print(head(arrange(select_(agrad.l2, "buildNRec", "maxBuildNRec", "image_url", column1, column2, "diff"), desc(buildNRec)), n = 10))
      print(head(arrange(select_(agrad.l2, "rbuildNRec", "rsdbuildNRec", "maxBuildNRec", "image_url", column1, column2, "diff"), desc(rbuildNRec)), n = 10))
      print(head(arrange(select_(agrad.l2, "tree", "maxTree", "image_url", column1, column2, "diff"), desc(tree)), n = 10))
      print(head(arrange(select_(agrad.l2, "rtree", "rsdtree", "maxTree", "image_url", column1, column2, "diff"), desc(rtree)), n = 10))
      print(head(arrange(select_(agrad.l2, "smallPla", "maxSmallPla", "image_url", column1, column2, "diff"), desc(smallPla)), n = 10))
      print(head(arrange(select_(agrad.l2, "rsmallPla", "rsdsmallPla", "maxSmallPla", "image_url", column1, column2, "diff"), desc(rsmallPla)), n = 10))
      print(head(arrange(select_(agrad.l2, "diffBuild", "maxDiffBuild", "image_url", column1, column2, "diff"), desc(diffBuild)), n = 10))
      print(head(arrange(select_(agrad.l2, "rdiffBuild", "rsddiffBuild", "maxDiffBuild", "image_url", column1, column2, "diff"), desc(rdiffBuild)), n = 10))
      print(head(arrange(select_(agrad.l2, "streeFur", "maxStreeFur", "image_url", column1, column2, "diff"), desc(streeFur)), n = 10))
      print(head(arrange(select_(agrad.l2, "rstreeFur", "rsdstreeFur", "maxStreeFur", "image_url", column1, column2, "diff"), desc(rstreeFur)), n = 10))
      print(head(arrange(select_(agrad.l2, "basCol", "maxBasCol", "image_url", column1, column2, "diff"), desc(basCol)), n = 10))
      print(head(arrange(select_(agrad.l2, "rbasCol", "rsdbasCol", "maxBasCol", "image_url", column1, column2, "diff"), desc(rbasCol)), n = 10))
      print(head(arrange(select_(agrad.l2, "accenCol", "maxAccenCol", "image_url", column1, column2, "diff"), desc(accenCol)), n = 10))
      print(head(arrange(select_(agrad.l2, "raccenCol", "rsdaccenCol", "maxAccenCol", "image_url", column1, column2, "diff"), desc(raccenCol)), n = 10))
      print(head(arrange(select_(agrad.l2, "ligh", "maxLigh", "image_url", column1, column2, "diff"), desc(ligh)), n = 10))
      print(head(arrange(select_(agrad.l2, "rligh", "rsdligh", "maxLigh", "image_url", column1, column2, "diff"), desc(rligh)), n = 10))
      print(head(arrange(select_(agrad.l2, "peop", "maxPeop", "image_url", column1, column2, "diff"), desc(peop)), n = 10))
      print(head(arrange(select_(agrad.l2, "rpeop", "rsdpeop", "maxPeop", "image_url", column1, column2, "diff"), desc(rpeop)), n = 10))
      print(head(arrange(select_(agrad.l2, "graff", "maxGraff", "image_url", column1, column2, "diff"), desc(graff)), n = 10))
      print(head(arrange(select_(agrad.l2, "rgraff", "rsdgraff", "maxGraff", "image_url", column1, column2, "diff"), desc(rgraff)), n = 10))
      print(head(arrange(select_(agrad.l2, "buildDiffAges", "maxBuildDiffAges", "image_url", column1, column2, "diff"), desc(buildDiffAges)), n = 10))
      print(head(arrange(select_(agrad.l2, "rbuildDiffAges", "rsdbuildDiffAges", "maxBuildDiffAges", "image_url", column1, column2, "diff"), desc(rbuildDiffAges)), n = 10))


      print(">>>>>>>> Two lists - top 10 ordered by real world coef ; top 10 ordered by shuffle world - Flavio")
      print(head(arrange(select_(agrad.l2, "movCars2", "maxMovCars", "sumMovCars","image_url", column1, column2, "diff"), desc(movCars2)), n = 10))
      print(head(arrange(select_(agrad.l2, "rmovCars2", "rsdmovCars2", "maxMovCars", "sumMovCars", "image_url", column1, column2, "diff"), desc(rmovCars2)), n = 10))
      print(head(arrange(select_(agrad.l2, "parkCars2", "maxParkCars", "sumParkCars","image_url", column1, column2, "diff"), desc(parkCars2)), n = 10))
      print(head(arrange(select_(agrad.l2, "rparkCars2", "rsdparkCars2", "maxParkCars", "sumParkCars","image_url", column1, column2, "diff"), desc(rparkCars2)), n = 10))
      print(head(arrange(select_(agrad.l2, "movCicly2", "maxMovCicly", "sumMovCicly","image_url", column1, column2, "diff"), desc(movCicly2)), n = 10))
      print(head(arrange(select_(agrad.l2, "rmovCicly2", "rsdmovCicly2", "maxMovCicly", "sumMovCicly","image_url", column1, column2, "diff"), desc(rmovCicly2)), n = 10))
      print(head(arrange(select_(agrad.l2, "buildId2", "maxBuildId", "sumBuildId","image_url", column1, column2, "diff"), desc(buildId2)), n = 10))
      print(head(arrange(select_(agrad.l2, "rbuildId2", "rsdbuildId2", "maxBuildId", "sumBuildId","image_url", column1, column2, "diff"), desc(rbuildId2)), n = 10))
      print(head(arrange(select_(agrad.l2, "buildNRec2", "maxBuildNRec", "sumBuildNRec","image_url", column1, column2, "diff"), desc(buildNRec2)), n = 10))
      print(head(arrange(select_(agrad.l2, "rbuildNRec2", "rsdbuildNRec2", "maxBuildNRec", "sumBuildNRec","image_url", column1, column2, "diff"), desc(rbuildNRec2)), n = 10))
      print(head(arrange(select_(agrad.l2, "tree2", "maxTree", "sumTree","image_url", column1, column2, "diff"), desc(tree2)), n = 10))
      print(head(arrange(select_(agrad.l2, "rtree2", "rsdtree2", "maxTree", "sumTree","image_url", column1, column2, "diff"), desc(rtree2)), n = 10))
      print(head(arrange(select_(agrad.l2, "smallPla2", "maxSmallPla", "sumSmallPla","image_url", column1, column2, "diff"), desc(smallPla2)), n = 10))
      print(head(arrange(select_(agrad.l2, "rsmallPla2", "rsdsmallPla2", "maxSmallPla", "sumSmallPla","image_url", column1, column2, "diff"), desc(rsmallPla2)), n = 10))
      print(head(arrange(select_(agrad.l2, "diffBuild2", "maxDiffBuild", "sumDiffBuild","image_url", column1, column2, "diff"), desc(diffBuild2)), n = 10))
      print(head(arrange(select_(agrad.l2, "rdiffBuild2", "rsddiffBuild2", "maxDiffBuild", "sumDiffBuild","image_url", column1, column2, "diff"), desc(rdiffBuild2)), n = 10))
      print(head(arrange(select_(agrad.l2, "streeFur2", "maxStreeFur", "sumStreeFur","image_url", column1, column2, "diff"), desc(streeFur2)), n = 10))
      print(head(arrange(select_(agrad.l2, "rstreeFur2", "rsdstreeFur2", "maxStreeFur", "sumStreeFur","image_url", column1, column2, "diff"), desc(rstreeFur2)), n = 10))
      print(head(arrange(select_(agrad.l2, "basCol2", "maxBasCol", "sumBasCol","image_url", column1, column2, "diff"), desc(basCol2)), n = 10))
      print(head(arrange(select_(agrad.l2, "rbasCol2", "rsdbasCol2", "maxBasCol", "sumBasCol","image_url", column1, column2, "diff"), desc(rbasCol2)), n = 10))
      print(head(arrange(select_(agrad.l2, "accenCol2", "maxAccenCol", "sumAccenCol","image_url", column1, column2, "diff"), desc(accenCol2)), n = 10))
      print(head(arrange(select_(agrad.l2, "raccenCol2", "rsdaccenCol2", "maxAccenCol", "sumAccenCol","image_url", column1, column2, "diff"), desc(raccenCol2)), n = 10))
      print(head(arrange(select_(agrad.l2, "ligh2", "maxLigh",  "sumLigh","image_url", column1, column2, "diff"), desc(ligh2)), n = 10))
      print(head(arrange(select_(agrad.l2, "rligh2", "rsdligh2", "maxLigh", "sumLigh","image_url", column1, column2, "diff"), desc(rligh2)), n = 10))
      print(head(arrange(select_(agrad.l2, "peop2", "maxPeop", "sumPeop","image_url", column1, column2, "diff"), desc(peop2)), n = 10))
      print(head(arrange(select_(agrad.l2, "rpeop2", "rsdpeop2", "maxPeop", "sumPeop","image_url", column1, column2, "diff"), desc(rpeop2)), n = 10))
      print(head(arrange(select_(agrad.l2, "graff2", "maxGraff","sumGraff", "image_url", column1, column2, "diff"), desc(graff2)), n = 10))
      print(head(arrange(select_(agrad.l2, "rgraff2", "rsdgraff2", "maxGraff", "sumGraff","image_url", column1, column2, "diff"), desc(rgraff2)), n = 10))
      print(head(arrange(select_(agrad.l2, "buildDiffAges2", "maxBuildDiffAges", "sumBuildDiffAges","image_url", column1, column2, "diff"), desc(buildDiffAges2)), n = 10))
      print(head(arrange(select_(agrad.l2, "rbuildDiffAges2", "rsdbuildDiffAges2", "maxBuildDiffAges", "sumBuildDiffAges","image_url", column1, column2, "diff"), desc(rbuildDiffAges2)), n = 10))
  
}

printOutputTwoListsAllFeaturesTog <- function(agrad.l2){
      library(reshape)

      print(">>>>>>>> One list with all features together with Daniele coeff - real world and shuffle world")
      all <- melt(select(agrad.l2, movCars, parkCars, movCicly, buildId, buildNRec, tree, smallPla, diffBuild, streeFur, basCol, ligh, accenCol, peop, graff, buildDiffAges, image_url), id=c("image_url"))
      
      all$random <- 0
      all[all$variable == "movCars",]$random<- sum(agrad.l2$rmovCars)
      all[all$variable == "parkCars",]$random<- sum(agrad.l2$rparkCars)
      all[all$variable == "movCicly",]$random<- sum(agrad.l2$rmovCicly)
      all[all$variable == "buildId",]$random<- sum(agrad.l2$rbuildId)
      all[all$variable == "buildNRec",]$random<- sum(agrad.l2$rbuildNRec)
      all[all$variable == "tree",]$random<- sum(agrad.l2$rtree)
      all[all$variable == "smallPla",]$random<- sum(agrad.l2$rsmallPla)
      all[all$variable == "diffBuild",]$random<- sum(agrad.l2$rdiffBuild)
      all[all$variable == "streeFur",]$random<- sum(agrad.l2$rstreeFur)
      all[all$variable == "basCol",]$random<- sum(agrad.l2$rbasCol)
      all[all$variable == "accenCol",]$random<- sum(agrad.l2$raccenCol)
      all[all$variable == "peop",]$random<- sum(agrad.l2$rpeop)
      all[all$variable == "buildDiffAges",]$random<- sum(agrad.l2$rbuildDiffAges)
      all[all$variable == "graff",]$random<- sum(agrad.l2$rgraff)
      all[all$variable == "ligh",]$random<- sum(agrad.l2$rligh)
      all$sd <- 0
      all[all$variable == "movCars",]$sd <- agrad.l2$rsdmovCars
      all[all$variable == "parkCars",]$sd <- agrad.l2$rsdparkCars
      all[all$variable == "movCicly",]$sd <- agrad.l2$rsdmovCicly
      all[all$variable == "buildId",]$sd <- agrad.l2$rsdbuildId
      all[all$variable == "buildNRec",]$sd <- agrad.l2$rsdbuildNRec
      all[all$variable == "tree",]$sd <- agrad.l2$rsdtree
      all[all$variable == "smallPla",]$sd <- agrad.l2$rsdsmallPla
      all[all$variable == "diffBuild",]$sd <- agrad.l2$rsddiffBuild
      all[all$variable == "streeFur",]$sd <- agrad.l2$rsdstreeFur
      all[all$variable == "basCol",]$sd <- agrad.l2$rsdbasCol
      all[all$variable == "accenCol",]$sd <- agrad.l2$rsdaccenCol
      all[all$variable == "peop",]$sd <- agrad.l2$rsdpeop
      all[all$variable == "buildDiffAges",]$sd <- agrad.l2$rsdbuildDiffAges
      all[all$variable == "graff",]$sd <- agrad.l2$rsdgraff
      all[all$variable == "ligh",]$sd <- agrad.l2$rsdligh

      print("### All")
      print("##### Summary")
      print( all %>% group_by(variable) %>% summarise( som=sum(value), rand=mean(random), std=mean(sd) ) %>% arrange(desc(som)) )
      print("##### List")
      print( arrange(all, desc(value)) )
      
      print(">>>>>>>> Two lists with all features together with Daniele coeff - real world and shuffle world")
      real <- melt(select(agrad.l2, movCars, parkCars, movCicly, buildId, buildNRec, tree, smallPla, diffBuild, streeFur, basCol, ligh, accenCol, peop, graff, buildDiffAges, image_url), id=c("image_url"))
      
      shuff <- melt(select(agrad.l2, rmovCars, rparkCars, rmovCicly, rbuildId, rbuildNRec, rtree, rsmallPla, rdiffBuild, rstreeFur, rbasCol, rligh, raccenCol, rpeop, rgraff, rbuildDiffAges, image_url), id=c("image_url"))
      shuff$sd <- 0
      shuff[shuff$variable == "rmovCars",]$sd <- agrad.l2$rsdmovCars
      shuff[shuff$variable == "rparkCars",]$sd <- agrad.l2$rsdparkCars
      shuff[shuff$variable == "rmovCicly",]$sd <- agrad.l2$rsdmovCicly
      shuff[shuff$variable == "rbuildId",]$sd <- agrad.l2$rsdbuildId
      shuff[shuff$variable == "rbuildNRec",]$sd <- agrad.l2$rsdbuildNRec
      shuff[shuff$variable == "rtree",]$sd <- agrad.l2$rsdtree
      shuff[shuff$variable == "rsmallPla",]$sd <- agrad.l2$rsdsmallPla
      shuff[shuff$variable == "rdiffBuild",]$sd <- agrad.l2$rsddiffBuild
      shuff[shuff$variable == "rstreeFur",]$sd <- agrad.l2$rsdstreeFur
      shuff[shuff$variable == "rbasCol",]$sd <- agrad.l2$rsdbasCol
      shuff[shuff$variable == "raccenCol",]$sd <- agrad.l2$rsdaccenCol
      shuff[shuff$variable == "rpeop",]$sd <- agrad.l2$rsdpeop
      shuff[shuff$variable == "rbuildDiffAges",]$sd <- agrad.l2$rsdbuildDiffAges
      shuff[shuff$variable == "rgraff",]$sd <- agrad.l2$rsdgraff
      shuff[shuff$variable == "rligh",]$sd <- agrad.l2$rsdligh

      print("### Real")
      print("##### Summary")
      print( real %>% group_by(variable) %>% summarise( som=sum(value) ) %>% arrange(desc(som)) )
      print("##### List")
      print( arrange(real, desc(value)) )
      print("### Shuffle")
      print("##### Summary")
      print( shuff %>% group_by(variable) %>% summarise( som=sum(value), std=mean(sd) ) %>% arrange(desc(som)) )
      print("##### List")
      print( arrange(shuff, desc(value)) )

       print(">>>>>>>> One list with all features together with Flavio coeff - real world and shuffle world")
       all <- melt(select(agrad.l2, movCars2, parkCars2, movCicly2, buildId2, buildNRec2, tree2, smallPla2, diffBuild2, streeFur2, basCol2, ligh2, accenCol2, peop2, graff2, buildDiffAges2, image_url), id=c("image_url"))
      
      all$sumDen <- 0
      all[all$variable == "movCars2",]$sumDen <- agrad.l2$sumMovCars
      all[all$variable == "parkCars2",]$sumDen <- agrad.l2$sumParkCars
      all[all$variable == "movCicly2",]$sumDen <- agrad.l2$sumMovCicly
      all[all$variable == "buildId2",]$sumDen <- agrad.l2$sumBuildId
      all[all$variable == "buildNRec2",]$sumDen <- agrad.l2$sumBuildNRec
      all[all$variable == "tree2",]$sumDen <- agrad.l2$sumTree
      all[all$variable == "smallPla2",]$sumDen <- agrad.l2$sumSmallPla
      all[all$variable == "diffBuild2",]$sumDen <- agrad.l2$sumDiffBuild
      all[all$variable == "streeFur2",]$sumDen <- agrad.l2$sumStreeFur
      all[all$variable == "basCol2",]$sumDen <- agrad.l2$sumBasCol
      all[all$variable == "accenCol2",]$sumDen <- agrad.l2$sumAccenCol
      all[all$variable == "peop2",]$sumDen <- agrad.l2$sumPeop
      all[all$variable == "buildDiffAges2",]$sumDen <- agrad.l2$sumBuildDiffAges
      all[all$variable == "graff2",]$sumDen <- agrad.l2$sumGraff
      all[all$variable == "ligh2",]$sumDen <- agrad.l2$sumLigh

      all$random <- 0
      all[all$variable == "movCars2",]$random<- sum(agrad.l2$rmovCars2)
      all[all$variable == "parkCars2",]$random<- sum(agrad.l2$rparkCars2)
      all[all$variable == "movCicly2",]$random<- sum(agrad.l2$rmovCicly2)
      all[all$variable == "buildId2",]$random<- sum(agrad.l2$rbuildId2)
      all[all$variable == "buildNRec2",]$random<- sum(agrad.l2$rbuildNRec2)
      all[all$variable == "tree2",]$random<- sum(agrad.l2$rtree2)
      all[all$variable == "smallPla2",]$random<- sum(agrad.l2$rsmallPla2)
      all[all$variable == "diffBuild2",]$random<- sum(agrad.l2$rdiffBuild2)
      all[all$variable == "streeFur2",]$random<- sum(agrad.l2$rstreeFur2)
      all[all$variable == "basCol2",]$random<- sum(agrad.l2$rbasCol2)
      all[all$variable == "accenCol2",]$random<- sum(agrad.l2$raccenCol2)
      all[all$variable == "peop2",]$random<- sum(agrad.l2$rpeop2)
      all[all$variable == "buildDiffAges2",]$random<- sum(agrad.l2$rbuildDiffAges2)
      all[all$variable == "graff2",]$random<- sum(agrad.l2$rgraff2)
      all[all$variable == "ligh2",]$random<- sum(agrad.l2$rligh2)
      all$sd <- 0
      all[all$variable == "movCars2",]$sd <- agrad.l2$rsdmovCars2
      all[all$variable == "parkCars2",]$sd <- agrad.l2$rsdparkCars2
      all[all$variable == "movCicly2",]$sd <- agrad.l2$rsdmovCicly2
      all[all$variable == "buildId2",]$sd <- agrad.l2$rsdbuildId2
      all[all$variable == "buildNRec2",]$sd <- agrad.l2$rsdbuildNRec2
      all[all$variable == "tree2",]$sd <- agrad.l2$rsdtree2
      all[all$variable == "smallPla2",]$sd <- agrad.l2$rsdsmallPla2
      all[all$variable == "diffBuild2",]$sd <- agrad.l2$rsddiffBuild2
      all[all$variable == "streeFur2",]$sd <- agrad.l2$rsdstreeFur2
      all[all$variable == "basCol2",]$sd <- agrad.l2$rsdbasCol2
      all[all$variable == "accenCol2",]$sd <- agrad.l2$rsdaccenCol2
      all[all$variable == "peop2",]$sd <- agrad.l2$rsdpeop2
      all[all$variable == "buildDiffAges2",]$sd <- agrad.l2$rsdbuildDiffAges2
      all[all$variable == "graff2",]$sd <- agrad.l2$rsdgraff2
      all[all$variable == "ligh2",]$sd <- agrad.l2$rsdligh2
      print("### All")
      print("##### Summary")
      print( all %>% group_by(variable) %>% summarise( som=sum(value)/mean(sumDen), rand=mean(random)/mean(sumDen), std=mean(sd)/mean(sumDen) ) %>% arrange(desc(som)) )
      print("##### List")
      print( arrange(all, desc(value)) )
      
      print(">>>>>>>> Two lists with all features together Flavio coeff - real world and shuffle world")
      real <- melt(select(agrad.l2, movCars2, parkCars2, movCicly2, buildId2, buildNRec2, tree2, smallPla2, diffBuild2, streeFur2, basCol2, ligh2, accenCol2, peop2, graff2, buildDiffAges2, image_url), id=c("image_url"))
      real$sumDen <- 0
      real[real$variable == "movCars2",]$sumDen <- agrad.l2$sumMovCars
      real[real$variable == "parkCars2",]$sumDen <- agrad.l2$sumParkCars
      real[real$variable == "movCicly2",]$sumDen <- agrad.l2$sumMovCicly
      real[real$variable == "buildId2",]$sumDen <- agrad.l2$sumBuildId
      real[real$variable == "buildNRec2",]$sumDen <- agrad.l2$sumBuildNRec
      real[real$variable == "tree2",]$sumDen <- agrad.l2$sumTree
      real[real$variable == "smallPla2",]$sumDen <- agrad.l2$sumSmallPla
      real[real$variable == "diffBuild2",]$sumDen <- agrad.l2$sumDiffBuild
      real[real$variable == "streeFur2",]$sumDen <- agrad.l2$sumStreeFur
      real[real$variable == "basCol2",]$sumDen <- agrad.l2$sumBasCol
      real[real$variable == "accenCol2",]$sumDen <- agrad.l2$sumAccenCol
      real[real$variable == "peop2",]$sumDen <- agrad.l2$sumPeop
      real[real$variable == "buildDiffAges2",]$sumDen <- agrad.l2$sumBuildDiffAges
      real[real$variable == "graff2",]$sumDen <- agrad.l2$sumGraff
      real[real$variable == "ligh2",]$sumDen <- agrad.l2$sumLigh
      
      shuff <- melt(select(agrad.l2, rmovCars2, rparkCars2, rmovCicly2, rbuildId2, rbuildNRec2, rtree2, rsmallPla2, rdiffBuild2, rstreeFur2, rbasCol2, rligh2, raccenCol2, rpeop2, rgraff2, rbuildDiffAges2, image_url), id=c("image_url"))
      shuff$sd <- 0
      shuff[shuff$variable == "rmovCars2",]$sd <- agrad.l2$rsdmovCars2
      shuff[shuff$variable == "rparkCars2",]$sd <- agrad.l2$rsdparkCars2
      shuff[shuff$variable == "rmovCicly2",]$sd <- agrad.l2$rsdmovCicly2
      shuff[shuff$variable == "rbuildId2",]$sd <- agrad.l2$rsdbuildId2
      shuff[shuff$variable == "rbuildNRec2",]$sd <- agrad.l2$rsdbuildNRec2
      shuff[shuff$variable == "rtree2",]$sd <- agrad.l2$rsdtree2
      shuff[shuff$variable == "rsmallPla2",]$sd <- agrad.l2$rsdsmallPla2
      shuff[shuff$variable == "rdiffBuild2",]$sd <- agrad.l2$rsddiffBuild2
      shuff[shuff$variable == "rstreeFur2",]$sd <- agrad.l2$rsdstreeFur2
      shuff[shuff$variable == "rbasCol2",]$sd <- agrad.l2$rsdbasCol2
      shuff[shuff$variable == "raccenCol2",]$sd <- agrad.l2$rsdaccenCol2
      shuff[shuff$variable == "rpeop2",]$sd <- agrad.l2$rsdpeop2
      shuff[shuff$variable == "rbuildDiffAges2",]$sd <- agrad.l2$rsdbuildDiffAges2
      shuff[shuff$variable == "rgraff2",]$sd <- agrad.l2$rsdgraff2
      shuff[shuff$variable == "rligh2",]$sd <- agrad.l2$rsdligh2

      shuff$sumDen <- 0
      shuff[shuff$variable == "rmovCars2",]$sumDen <- agrad.l2$sumMovCars
      shuff[shuff$variable == "rparkCars2",]$sumDen <- agrad.l2$sumParkCars
      shuff[shuff$variable == "rmovCicly2",]$sumDen <- agrad.l2$sumMovCicly
      shuff[shuff$variable == "rbuildId2",]$sumDen <- agrad.l2$sumBuildId
      shuff[shuff$variable == "rbuildNRec2",]$sumDen <- agrad.l2$sumBuildNRec
      shuff[shuff$variable == "rtree2",]$sumDen <- agrad.l2$sumTree
      shuff[shuff$variable == "rsmallPla2",]$sumDen <- agrad.l2$sumSmallPla
      shuff[shuff$variable == "rdiffBuild2",]$sumDen <- agrad.l2$sumDiffBuild
      shuff[shuff$variable == "rstreeFur2",]$sumDen <- agrad.l2$sumStreeFur
      shuff[shuff$variable == "rbasCol2",]$sumDen <- agrad.l2$sumBasCol
      shuff[shuff$variable == "raccenCol2",]$sumDen <- agrad.l2$sumAccenCol
      shuff[shuff$variable == "rpeop2",]$sumDen <- agrad.l2$sumPeop
      shuff[shuff$variable == "rbuildDiffAges2",]$sumDen <- agrad.l2$sumBuildDiffAges
      shuff[shuff$variable == "rgraff2",]$sumDen <- agrad.l2$sumGraff
      shuff[shuff$variable == "rligh2",]$sumDen <- agrad.l2$sumLigh
      
      print("### Real")
      print("##### Summary")
      print( real %>% group_by(variable) %>% summarise( som=sum(value)/(mean(sumDen)) ) %>% arrange(desc(som)) )
      print("##### List")
      print( arrange(real, desc(value)) )
      print("### Shuffle")
      print("##### Summary")
      print( shuff %>% group_by(variable) %>% summarise( som=sum(value)/(mean(sumDen)), std=mean(sd) ) %>% arrange(desc(som)) )
      print("##### List")
      print( arrange(shuff, desc(value)) )
}

mergeSort <- function(x){
  if(length(x) == 1){
    inv <- 0
  } else {
    n <- length(x)
    n1 <- ceiling(n/2)
    n2 <- n-n1
    y1 <- mergeSort(x[1:n1])
    y2 <- mergeSort(x[n1+1:n2])
    inv <- y1$inversions + y2$inversions
    x1 <- y1$sortedVector
    x2 <- y2$sortedVector
    i1 <- 1
    i2 <- 1
    while(i1+i2 <= n1+n2+1){
      if(i2 > n2 || (i1 <= n1 && x1[i1] <= x2[i2])){
        x[i1+i2-1] <- x1[i1]
        i1 <- i1 + 1
      } else {
        inv <- inv + n1 + 1 - i1
        x[i1+i2-1] <- x2[i2]
        i2 <- i2 + 1
      }
    }
  }
  return (list(inversions=inv,sortedVector=x))
}

numberOfInversions <- function(x){
  r <- mergeSort(x)
  return (r$inversions)
}

normalizedKendallTauDistance2 <- function(data1, data2){
  x <- data1
  y <- data2
  
  tau = numberOfInversions(order(x)[rank(y)])
  nItens = length(x)
  maxNumberOfInverstions <- (nItens*(nItens-1))/2
  normalized = tau/maxNumberOfInverstions

  print (normalized)
}

#Avaliando correlação das caracteristicas urbanas
novo <- select(temp, street_wid, sidewalk_wid,public_art,mov_cars,park_cars ,mov_ciclyst,debris ,pavement ,landscape ,courtyards ,major_landsc ,build_ident ,build_nrectan ,prop_street_wall ,prop_wind ,long_sight ,prop_sky_ahead ,prop_sky_across , trees ,small_planters ,build_height , diff_build ,prop_hist_build ,street_furnit ,basic_col ,lights ,accent_col ,people ,prop_active_use)

correlacao <- cor(x = novo)
library(lattice)
rb.palette <- colorRampPalette(c("yellow", "red"), space = "rgb")
levelplot(correlacao, main = "Urban Features Correlation", col.regions = rb.palette(120), cuts=100, at = seq(0, 1, 0.01), xlab = "Urban Features", ylab = "Urban Features", )

#Geral
# library(leaps)
# 
# regsubsetsAgrad.out <<- regsubsets(V3.Geral ~ street_wid + sidewalk_wid + public_art + mov_cars + park_cars + mov_ciclyst + debris + pavement + landscape + courtyards + major_landsc + build_ident + build_nrectan + prop_street_wall + prop_wind + long_sight + prop_sky_ahead + prop_sky_across + graffiti + trees + small_planters + build_height + build_diff_ages + diff_build + prop_hist_build + street_furnit + basic_col + lights + accent_col + people + prop_active_use, na.action = na.exclude, data = agrad, nbest = 1, nvmax = NULL, force.in = NULL, force.out = NULL, method = "exhaustive")
# plot(regsubsetsAgrad.out, scale = "adjr2", main = "Adjusted R^2")

#regGeralAgrad <- lm(agrad$V3.Geral ~ agrad$street_wid + agrad$sidewalk_wid + agrad$public_art + agrad$mov_cars + agrad$park_cars + agrad$mov_ciclyst + agrad$debris + agrad$pavement + agrad$landscape + agrad$courtyards + agrad$major_landsc + agrad$build_ident + agrad$build_nrectan + agrad$prop_street_wall + agrad$prop_wind + agrad$long_sight + agrad$prop_sky_ahead + agrad$prop_sky_across + agrad$trees + agrad$small_planters + agrad$build_height + agrad$diff_build + agrad$prop_hist_build + agrad$outdoor_table + agrad$street_furnit + agrad$basic_col + agrad$lights + agrad$accent_col + agrad$people + agrad$prop_active_use, na.action = na.exclude)
# regGeralAgrad <- lm(V3.Geral ~ street_wid + public_art + mov_cars + park_cars + mov_ciclyst + debris + pavement + landscape + courtyards + major_landsc + prop_street_wall + prop_wind + long_sight + prop_sky_ahead + prop_sky_across + graffiti + small_planters + build_height + prop_hist_build + street_furnit + basic_col + accent_col + people, na.action = na.exclude, data = agrad)
# texreg(regGeralAgrad)
# summary(regGeralAgrad)


```

```{r, echo=FALSE, fig.show='asis', fig.width=10, fig.height=5}
#Unit tests
library(RUnit)

test.kendallWithEqualRankingsAndZeroFeature <- function(){
   mov_cars <- c(0,0,0,0,0)
   park_cars <- c(0,0,0,0,0)
   mov_ciclyst <- c(0,0,0,0,0)
   build_ident <- c(0,0,0,0,0)
   build_nrectan <- c(0,0,0,0,0)
   trees <- c(0,0,0,0,0)
   small_planters <- c(0,0,0,0,0)
   diff_build <- c(0,0,0,0,0)
   street_furnit <- c(0,0,0,0,0)
   basic_col <- c(0,0,0,0,0)
   lights <- c(0,0,0,0,0)
   accent_col <- c(0,0,0,0,0)
   people <- c(0,0,0,0,0)
   graffiti <- c(0,0,0,0,0)
   build_diff_ages <- c(0,0,0,0,0)
   
   agrad.l <- data.frame(rank=c(1,2,3,4,5), index=c(1,2,3,4,5), mov_cars=mov_cars, park_cars=park_cars, mov_ciclyst = mov_ciclyst, build_ident = build_ident, build_nrectan = build_nrectan, trees = trees, small_planters = small_planters, diff_build = diff_build, street_furnit = street_furnit, basic_col = basic_col, lights = lights, accent_col = accent_col, people = people, graffiti = graffiti, build_diff_ages = build_diff_ages)
   iterations <- 1

   result <- kendallWithWeights(agrad.l, iterations)
   checkEquals(length(result), 75)
   checkTrue(result$movCars == 0)
   checkTrue(result$parkCars == 0)
   checkTrue(result$movCicly == 0)
   checkTrue(result$buildId == 0)
   checkTrue(result$buildNRec == 0)
   checkTrue(result$tree == 0)
   checkTrue(result$smallPla == 0)
   checkTrue(result$diffBuild == 0)
   checkTrue(result$streeFur == 0)
   checkTrue(result$basCol == 0)
   checkTrue(result$ligh == 0)
   checkTrue(result$accenCol == 0)
   checkTrue(result$peop == 0)
   checkTrue(result$graff == 0)
   checkTrue(result$buildDiffAges == 0)
   
   checkTrue(result$rmovCars == 0)
   checkTrue(result$rparkCars == 0)
   checkTrue(result$rmovCicly == 0)
   checkTrue(result$rbuildId == 0)
   checkTrue(result$rbuildNRec == 0)
   checkTrue(result$rtree == 0)
   checkTrue(result$rsmallPla == 0)
   checkTrue(result$rdiffBuild == 0)
   checkTrue(result$rstreeFur == 0)
   checkTrue(result$rbasCol == 0)
   checkTrue(result$rligh == 0)
   checkTrue(result$raccenCol == 0)
   checkTrue(result$rpeop == 0)
   checkTrue(result$rgraff == 0)
   checkTrue(result$rbuildDiffAges == 0)
   
   checkTrue(is.na(result$rsdMovCars))
   checkTrue(is.na(result$rsdParkCars))
   checkTrue(is.na(result$rsdMovCicly))
   checkTrue(is.na(result$rsdBuildId))
   checkTrue(is.na(result$rsdBuildNRec))
   checkTrue(is.na(result$rsdTree))
   checkTrue(is.na(result$rsdSmallPla))
   checkTrue(is.na(result$rsdDiffBuild))
   checkTrue(is.na(result$rsdStreeFur))
   checkTrue(is.na(result$rsdBasCol))
   checkTrue(is.na(result$rsdLigh))
   checkTrue(is.na(result$rsdAccenCol))
   checkTrue(is.na(result$rsdPeop))
   checkTrue(is.na(result$rsdGraff))
   checkTrue(is.na(result$rsdBuildDiffAges))
   
   checkTrue(is.na(result$movCarsN))
   checkTrue(is.na(result$parkCarsN))
   checkTrue(is.na(result$movCiclyN))
   checkTrue(is.na(result$buildIdN))
   checkTrue(is.na(result$buildNRecN))
   checkTrue(is.na(result$treeN))
   checkTrue(is.na(result$smallPlaN))
   checkTrue(is.na(result$diffBuildN))
   checkTrue(is.na(result$streeFurN))
   checkTrue(is.na(result$basColN))
   checkTrue(is.na(result$lighN))
   checkTrue(is.na(result$accenColN))
   checkTrue(is.na(result$peopN))
   checkTrue(is.na(result$graffN))
   checkTrue(is.na(result$buildDiffAgesN))
}

test.kendallWithEqualRankingsAndNonZeroFeature <- function(){
   mov_cars <- c(2,2,0,0,0)
   park_cars <- c(2,2,0,0,0)
   mov_ciclyst <- c(2,2,0,0,0)
   build_ident <- c(2,2,0,0,0)
   build_nrectan <- c(2,2,0,0,0)
   trees <- c(2,2,0,0,0)
   small_planters <- c(2,2,0,0,0)
   diff_build <- c(2,2,0,0,0)
   street_furnit <- c(2,2,0,0,0)
   basic_col <- c(2,2,0,0,0)
   lights <- c(2,2,0,0,0)
   accent_col <- c(2,2,0,0,0)
   people <- c(2,2,0,0,0)
   graffiti <- c(2,2,0,0,0)
   build_diff_ages <- c(2,2,0,0,0)
   
   agrad.l <- data.frame(rank=c(1,2,3,4,5), index=c(1,2,3,4,5), mov_cars=mov_cars, park_cars=park_cars, mov_ciclyst = mov_ciclyst, build_ident = build_ident, build_nrectan = build_nrectan, trees = trees, small_planters = small_planters, diff_build = diff_build, street_furnit = street_furnit, basic_col = basic_col, lights = lights, accent_col = accent_col, people = people, graffiti = graffiti, build_diff_ages = build_diff_ages)
   iterations <- 1

   result <- kendallWithWeights(agrad.l, iterations)
   checkEquals(length(result), 75)
   checkTrue(result$movCars == 0)
   checkTrue(result$parkCars == 0)
   checkTrue(result$movCicly == 0)
   checkTrue(result$buildId == 0)
   checkTrue(result$buildNRec == 0)
   checkTrue(result$tree == 0)
   checkTrue(result$smallPla == 0)
   checkTrue(result$diffBuild == 0)
   checkTrue(result$streeFur == 0)
   checkTrue(result$basCol == 0)
   checkTrue(result$ligh == 0)
   checkTrue(result$accenCol == 0)
   checkTrue(result$peop == 0)
   checkTrue(result$graff == 0)
   checkTrue(result$buildDiffAges == 0)
   
   checkTrue(result$rmovCars == 0)
   checkTrue(result$rparkCars == 0)
   checkTrue(result$rmovCicly  == 0)
   checkTrue(result$rbuildId  == 0)
   checkTrue(result$rbuildNRec  == 0)
   checkTrue(result$rtree  == 0)
   checkTrue(result$rsmallPla == 0)
   checkTrue(result$rdiffBuild == 0)
   checkTrue(result$rstreeFur == 0)
   checkTrue(result$rbasCol == 0)
   checkTrue(result$rligh == 0)
   checkTrue(result$raccenCol == 0)
   checkTrue(result$rpeop == 0)
   checkTrue(result$rgraff == 0)
   checkTrue(result$rbuildDiffAges == 0)
   
   checkTrue(is.na(result$rsdMovCars))
   checkTrue(is.na(result$rsdParkCars))
   checkTrue(is.na(result$rsdMovCicly))
   checkTrue(is.na(result$rsdBuildId))
   checkTrue(is.na(result$rsdBuildNRec))
   checkTrue(is.na(result$rsdTree))
   checkTrue(is.na(result$rsdSmallPla))
   checkTrue(is.na(result$rsdDiffBuild))
   checkTrue(is.na(result$rsdStreeFur))
   checkTrue(is.na(result$rsdBasCol))
   checkTrue(is.na(result$rsdLigh))
   checkTrue(is.na(result$rsdAccenCol))
   checkTrue(is.na(result$rsdPeop))
   checkTrue(is.na(result$rsdGraff))
   checkTrue(is.na(result$rsdBuildDiffAges))
   
   checkTrue(result$movCarsN == 0)
   checkTrue(result$parkCarsN == 0)
   checkTrue(result$movCiclyN == 0)
   checkTrue(result$buildIdN == 0)
   checkTrue(result$buildNRecN == 0)
   checkTrue(result$treeN == 0)
   checkTrue(result$smallPlaN == 0)
   checkTrue(result$diffBuildN == 0)
   checkTrue(result$streeFurN == 0)
   checkTrue(result$basColN == 0)
   checkTrue(result$lighN == 0)
   checkTrue(result$accenColN == 0)
   checkTrue(result$peopN == 0)
   checkTrue(result$graffN == 0)
   checkTrue(result$buildDiffAgesN == 0)
}

test.kendallWithOppRankingsAndNonZeroFeature <- function(){
   mov_cars <- c(2,2,0,0,0)
   park_cars <- c(2,2,0,0,0)
   mov_ciclyst <- c(2,2,0,0,0)
   build_ident <- c(2,2,0,0,0)
   build_nrectan <- c(2,2,0,0,0)
   trees <- c(2,2,0,0,0)
   small_planters <- c(2,2,0,0,0)
   diff_build <- c(2,2,0,0,0)
   street_furnit <- c(2,2,0,0,0)
   basic_col <- c(2,2,0,0,0)
   lights <- c(2,2,0,0,0)
   accent_col <- c(2,2,0,0,0)
   people <- c(2,2,0,0,0)
   graffiti <- c(2,2,0,0,0)
   build_diff_ages <- c(2,2,0,0,0)
   
   agrad.l <- data.frame(rank=c(1,2,3,4,5), index=c(5, 4, 3, 2, 1), mov_cars=mov_cars, park_cars=park_cars, mov_ciclyst = mov_ciclyst, build_ident = build_ident, build_nrectan = build_nrectan, trees = trees, small_planters = small_planters, diff_build = diff_build, street_furnit = street_furnit, basic_col = basic_col, lights = lights, accent_col = accent_col, people = people, graffiti = graffiti, build_diff_ages = build_diff_ages)
   iterations <- 1

   result <- kendallWithWeights(agrad.l, iterations)
   checkEquals(length(result), 75)
   checkTrue(result$movCars == 12)
   checkTrue(result$parkCars == 12)
   checkTrue(result$movCicly == 12)
   checkTrue(result$buildId == 12)
   checkTrue(result$buildNRec == 12)
   checkTrue(result$tree == 12)
   checkTrue(result$smallPla == 12)
   checkTrue(result$diffBuild == 12)
   checkTrue(result$streeFur == 12)
   checkTrue(result$basCol == 12)
   checkTrue(result$ligh == 12)
   checkTrue(result$accenCol == 12)
   checkTrue(result$peop == 12)
   checkTrue(result$graff == 12)
   checkTrue(result$buildDiffAges == 12)
   
   checkTrue(result$rmovCars > 0)
   checkTrue(result$rparkCars  > 0)
   checkTrue(result$rmovCicly  > 0)
   checkTrue(result$rbuildId  > 0)
   checkTrue(result$rbuildNRec  > 0)
   checkTrue(result$rtree  > 0)
   checkTrue(result$rsmallPla > 0)
   checkTrue(result$rdiffBuild > 0)
   checkTrue(result$rstreeFur > 0)
   checkTrue(result$rbasCol > 0)
   checkTrue(result$rligh > 0)
   checkTrue(result$raccenCol > 0)
   checkTrue(result$rpeop > 0)
   checkTrue(result$rgraff > 0)
   checkTrue(result$rbuildDiffAges > 0)
   
   checkTrue(is.na(result$rsdMovCars))
   checkTrue(is.na(result$rsdParkCars))
   checkTrue(is.na(result$rsdMovCicly))
   checkTrue(is.na(result$rsdBuildId))
   checkTrue(is.na(result$rsdBuildNRec))
   checkTrue(is.na(result$rsdTree))
   checkTrue(is.na(result$rsdSmallPla))
   checkTrue(is.na(result$rsdDiffBuild))
   checkTrue(is.na(result$rsdStreeFur))
   checkTrue(is.na(result$rsdBasCol))
   checkTrue(is.na(result$rsdLigh))
   checkTrue(is.na(result$rsdAccenCol))
   checkTrue(is.na(result$rsdPeop))
   checkTrue(is.na(result$rsdGraff))
   checkTrue(is.na(result$rsdBuildDiffAges))
   
   checkTrue(result$movCarsN == 1)
   checkTrue(result$parkCarsN == 1)
   checkTrue(result$movCiclyN == 1)
   checkTrue(result$buildIdN == 1)
   checkTrue(result$buildNRecN == 1)
   checkTrue(result$treeN == 1)
   checkTrue(result$smallPlaN == 1)
   checkTrue(result$diffBuildN == 1)
   checkTrue(result$streeFurN == 1)
   checkTrue(result$basColN == 1)
   checkTrue(result$lighN == 1)
   checkTrue(result$accenColN == 1)
   checkTrue(result$peopN == 1)
   checkTrue(result$graffN == 1)
   checkTrue(result$buildDiffAgesN == 1)
}

test.kendallWithOppRankingsAndNonZeroDiffFeature <- function(){
   mov_cars <- c(2,2,0,0,0)
   park_cars <- c(3,3,0,0,0)
   mov_ciclyst <- c(3,3,0,0,0)
   build_ident <- c(3,3,0,0,0)
   build_nrectan <- c(2,2,0,0,0)
   trees <- c(4,4,0,0,0)
   small_planters <- c(3,2,0,0,0)
   diff_build <- c(2,2,0,0,0)
   street_furnit <- c(2,2,0,0,0)
   basic_col <- c(2,2,0,0,0)
   lights <- c(2,2,0,0,0)
   accent_col <- c(2,2,0,0,0)
   people <- c(2,2,0,0,0)
   graffiti <- c(2,2,0,0,0)
   build_diff_ages <- c(2,2,0,0,0)
   
   agrad.l <- data.frame(rank=c(1,2,3,4,5), index=c(5, 4, 3, 2, 1), mov_cars=mov_cars, park_cars=park_cars, mov_ciclyst = mov_ciclyst, build_ident = build_ident, build_nrectan = build_nrectan, trees = trees, small_planters = small_planters, diff_build = diff_build, street_furnit = street_furnit, basic_col = basic_col, lights = lights, accent_col = accent_col, people = people, graffiti = graffiti, build_diff_ages = build_diff_ages)
   iterations <- 1

   result <- kendallWithWeights(agrad.l, iterations)
   checkEquals(length(result), 75)
   checkTrue(result$movCars == 12)
   checkTrue(result$parkCars == 18)
   checkTrue(result$movCicly == 18)
   checkTrue(result$buildId == 18)
   checkTrue(result$buildNRec == 12)
   checkTrue(result$tree == 24)
   checkTrue(result$smallPla == 16)
   checkTrue(result$diffBuild == 12)
   checkTrue(result$streeFur == 12)
   checkTrue(result$basCol == 12)
   checkTrue(result$ligh == 12)
   checkTrue(result$accenCol == 12)
   checkTrue(result$peop == 12)
   checkTrue(result$graff == 12)
   checkTrue(result$buildDiffAges == 12)
   
   checkTrue(result$rmovCars > 0)
   checkTrue(result$rparkCars  > 0)
   checkTrue(result$rmovCicly  > 0)
   checkTrue(result$rbuildId  > 0)
   checkTrue(result$rbuildNRec  > 0)
   checkTrue(result$rtree  > 0)
   checkTrue(result$rsmallPla > 0)
   checkTrue(result$rdiffBuild > 0)
   checkTrue(result$rstreeFur > 0)
   checkTrue(result$rbasCol > 0)
   checkTrue(result$rligh > 0)
   checkTrue(result$raccenCol > 0)
   checkTrue(result$rpeop > 0)
   checkTrue(result$rgraff > 0)
   checkTrue(result$rbuildDiffAges > 0)
   
   checkTrue(is.na(result$rsdMovCars))
   checkTrue(is.na(result$rsdParkCars))
   checkTrue(is.na(result$rsdMovCicly))
   checkTrue(is.na(result$rsdBuildId))
   checkTrue(is.na(result$rsdBuildNRec))
   checkTrue(is.na(result$rsdTree))
   checkTrue(is.na(result$rsdSmallPla))
   checkTrue(is.na(result$rsdDiffBuild))
   checkTrue(is.na(result$rsdStreeFur))
   checkTrue(is.na(result$rsdBasCol))
   checkTrue(is.na(result$rsdLigh))
   checkTrue(is.na(result$rsdAccenCol))
   checkTrue(is.na(result$rsdPeop))
   checkTrue(is.na(result$rsdGraff))
   checkTrue(is.na(result$rsdBuildDiffAges))
   
   checkTrue(result$movCarsN == 1)
   checkTrue(result$parkCarsN == 1)
   checkTrue(result$movCiclyN == 1)
   checkTrue(result$buildIdN == 1)
   checkTrue(result$buildNRecN == 1)
   checkTrue(result$treeN == 1)
   checkTrue(result$smallPlaN == 1)
   checkTrue(result$diffBuildN == 1)
   checkTrue(result$streeFurN == 1)
   checkTrue(result$basColN == 1)
   checkTrue(result$lighN == 1)
   checkTrue(result$accenColN == 1)
   checkTrue(result$peopN == 1)
   checkTrue(result$graffN == 1)
   checkTrue(result$buildDiffAgesN == 1)
}

test.kendallWithDiffRankingsAndNonZeroDiffFeature <- function(){
   mov_cars <- c(2,0,2,0,0)
   park_cars <- c(3,0,3,0,0)
   mov_ciclyst <- c(3,0,3,0,0)
   build_ident <- c(3,0,3,0,0)
   build_nrectan <- c(2,0,2,0,0)
   trees <- c(4,0,4,0,0)
   small_planters <- c(3,0,2,0,0)
   diff_build <- c(2,0,2,0,0)
   street_furnit <- c(2,0,2,0,0)
   basic_col <- c(2,0,2,0,0)
   lights <- c(2,0,2,0,0)
   accent_col <- c(2,0,2,0,0)
   people <- c(2,0,2,0,0)
   graffiti <- c(2,0,2,0,0)
   build_diff_ages <- c(2,0,2,0,0)
   
   agrad.l <- data.frame(rank=c(1,2,3,4,5), index=c(1, 2, 5, 4, 3), mov_cars=mov_cars, park_cars=park_cars, mov_ciclyst = mov_ciclyst, build_ident = build_ident, build_nrectan = build_nrectan, trees = trees, small_planters = small_planters, diff_build = diff_build, street_furnit = street_furnit, basic_col = basic_col, lights = lights, accent_col = accent_col, people = people, graffiti = graffiti, build_diff_ages = build_diff_ages)
   iterations <- 1

   result <- kendallWithWeights(agrad.l, iterations)
   checkEquals(length(result), 75)
   checkTrue(result$movCars == 2 * 2)
   checkTrue(result$parkCars == 3 * 2)
   checkTrue(result$movCicly == 3 * 2)
   checkTrue(result$buildId == 3 * 2)
   checkTrue(result$buildNRec == 2 * 2)
   checkTrue(result$tree == 4 * 2)
   checkTrue(result$smallPla == 2 * 2)
   checkTrue(result$diffBuild == 2 * 2)
   checkTrue(result$streeFur == 2 * 2)
   checkTrue(result$basCol == 2 * 2)
   checkTrue(result$ligh == 2 * 2)
   checkTrue(result$accenCol == 2 * 2)
   checkTrue(result$peop == 2 * 2)
   checkTrue(result$graff == 2 * 2)
   checkTrue(result$buildDiffAges == 2 * 2)
   
   checkTrue(result$rmovCars >= 0)
   checkTrue(result$rparkCars  >= 0)
   checkTrue(result$rmovCicly  >= 0)
   checkTrue(result$rbuildId  >= 0)
   checkTrue(result$rbuildNRec  >= 0)
   checkTrue(result$rtree  >= 0)
   checkTrue(result$rsmallPla >= 0)
   checkTrue(result$rdiffBuild >= 0)
   checkTrue(result$rstreeFur >= 0)
   checkTrue(result$rbasCol >= 0)
   checkTrue(result$rligh >= 0)
   checkTrue(result$raccenCol >= 0)
   checkTrue(result$rpeop >= 0)
   checkTrue(result$rgraff >= 0)
   checkTrue(result$rbuildDiffAges >= 0)
   
   checkTrue(is.na(result$rsdMovCars))
   checkTrue(is.na(result$rsdParkCars))
   checkTrue(is.na(result$rsdMovCicly))
   checkTrue(is.na(result$rsdBuildId))
   checkTrue(is.na(result$rsdBuildNRec))
   checkTrue(is.na(result$rsdTree))
   checkTrue(is.na(result$rsdSmallPla))
   checkTrue(is.na(result$rsdDiffBuild))
   checkTrue(is.na(result$rsdStreeFur))
   checkTrue(is.na(result$rsdBasCol))
   checkTrue(is.na(result$rsdLigh))
   checkTrue(is.na(result$rsdAccenCol))
   checkTrue(is.na(result$rsdPeop))
   checkTrue(is.na(result$rsdGraff))
   checkTrue(is.na(result$rsdBuildDiffAges))
   
   checkTrue(result$movCarsN == 4 / 12)
   checkTrue(result$parkCarsN == 6 / 18)
   checkTrue(result$movCiclyN == 6 / 18)
   checkTrue(result$buildIdN == 6 / 18)
   checkTrue(result$buildNRecN == 4 / 12)
   checkTrue(result$treeN == 8 / 24)
   checkTrue(result$smallPlaN == 4 / 16)
   checkTrue(result$diffBuildN == 4 / 12)
   checkTrue(result$streeFurN == 4 / 12)
   checkTrue(result$basColN == 4 / 12)
   checkTrue(result$lighN == 4 / 12)
   checkTrue(result$accenColN == 4 / 12)
   checkTrue(result$peopN == 4 / 12)
   checkTrue(result$graffN == 4 / 12)
   checkTrue(result$buildDiffAgesN == 4 / 12)
}

test.kendallWithDiffRankingsNonZeroDiffFeatureAndMoreThanOneIteration <- function(){
   mov_cars <- c(2,0,2,0,0)
   park_cars <- c(3,0,3,0,0)
   mov_ciclyst <- c(3,0,3,0,0)
   build_ident <- c(3,0,3,0,0)
   build_nrectan <- c(2,0,2,0,0)
   trees <- c(4,0,4,0,0)
   small_planters <- c(3,0,2,0,0)
   diff_build <- c(2,0,2,0,0)
   street_furnit <- c(2,0,2,0,0)
   basic_col <- c(2,0,2,0,0)
   lights <- c(2,0,2,0,0)
   accent_col <- c(2,0,2,0,0)
   people <- c(2,0,2,0,0)
   graffiti <- c(2,0,2,0,0)
   build_diff_ages <- c(2,0,2,0,0)
   
   agrad.l <- data.frame(rank=c(1,2,3,4,5), index=c(1, 2, 5, 4, 3), mov_cars=mov_cars, park_cars=park_cars, mov_ciclyst = mov_ciclyst, build_ident = build_ident, build_nrectan = build_nrectan, trees = trees, small_planters = small_planters, diff_build = diff_build, street_furnit = street_furnit, basic_col = basic_col, lights = lights, accent_col = accent_col, people = people, graffiti = graffiti, build_diff_ages = build_diff_ages)
   iterations <- 2

   result <- kendallWithWeights(agrad.l, iterations)
   checkEquals(length(result), 75)
   checkTrue(result$movCars == 2 * 2)
   checkTrue(result$parkCars == 3 * 2)
   checkTrue(result$movCicly == 3 * 2)
   checkTrue(result$buildId == 3 * 2)
   checkTrue(result$buildNRec == 2 * 2)
   checkTrue(result$tree == 4 * 2)
   checkTrue(result$smallPla == 2 * 2)
   checkTrue(result$diffBuild == 2 * 2)
   checkTrue(result$streeFur == 2 * 2)
   checkTrue(result$basCol == 2 * 2)
   checkTrue(result$ligh == 2 * 2)
   checkTrue(result$accenCol == 2 * 2)
   checkTrue(result$peop == 2 * 2)
   checkTrue(result$graff == 2 * 2)
   checkTrue(result$buildDiffAges == 2 * 2)
   
   checkTrue(result$rmovCars > 0)
   checkTrue(result$rparkCars > 0)
   checkTrue(result$rmovCicly > 0)
   checkTrue(result$rbuildId  > 0)
   checkTrue(result$rbuildNRec  > 0)
   checkTrue(result$rtree > 0)
   checkTrue(result$rsmallPla > 0)
   checkTrue(result$rdiffBuild > 0)
   checkTrue(result$rstreeFur > 0)
   checkTrue(result$rbasCol > 0)
   checkTrue(result$rligh > 0)
   checkTrue(result$raccenCol > 0)
   checkTrue(result$rpeop > 0)
   checkTrue(result$rgraff > 0)
   checkTrue(result$rbuildDiffAges > 0)
   
   checkTrue(result$rsdMovCars >= 0)
   checkTrue(result$rsdParkCars >= 0)
   checkTrue(result$rsdMovCicly >= 0)
   checkTrue(result$rsdBuildId  >= 0)
   checkTrue(result$rsdBuildNRec  >= 0)
   checkTrue(result$rsdTree >= 0)
   checkTrue(result$rsdSmallPla >= 0)
   checkTrue(result$rsdDiffBuild >= 0)
   checkTrue(result$rsdStreeFur >= 0)
   checkTrue(result$rsdBasCol >= 0)
   checkTrue(result$rsdLigh >= 0)
   checkTrue(result$rsdAccenCol >= 0)
   checkTrue(result$rsdPeop >= 0)
   checkTrue(result$rsdGraff >= 0)
   checkTrue(result$rsdBuildDiffAges >= 0)
   
   checkTrue(result$movCarsN == 4 / 12)
   checkTrue(result$parkCarsN == 6 / 18)
   checkTrue(result$movCiclyN == 6 / 18)
   checkTrue(result$buildIdN == 6 / 18)
   checkTrue(result$buildNRecN == 4 / 12)
   checkTrue(result$treeN == 8 / 24)
   checkTrue(result$smallPlaN == 4 / 16)
   checkTrue(result$diffBuildN == 4 / 12)
   checkTrue(result$streeFurN == 4 / 12)
   checkTrue(result$basColN == 4 / 12)
   checkTrue(result$lighN == 4 / 12)
   checkTrue(result$accenColN == 4 / 12)
   checkTrue(result$peopN == 4 / 12)
   checkTrue(result$graffN == 4 / 12)
   checkTrue(result$buildDiffAgesN == 4 / 12)
}
```


## Men x Women - Pleasantness

100 iterations

```{r, echo=FALSE, fig.show='asis', fig.width=10, fig.height=5}
#Homem x Mulher
agrad.l <- agrad %>% do(arrange(., desc(V3.Masculino))) %>% 
    mutate(rank = 1:n()) %>% do(arrange(., desc(V3.Feminino))) %>% mutate(index = 1:n())

agrad.l <- calcDanieleCoeff(agrad.l)
agrad.l2 <- simulateCoefShuffle(agrad.l, iterations)

print(paste(">>>> Kendall Distance ", normalizedKendallTauDistance2(agrad.l$V3.Masculino, agrad.l$V3.Feminino)))
print(paste(">>>> Kendall adapted Hom x Mul ", kendallWithWeights(agrad.l, iterations)))

printOutputOneListPerFeature(agrad.l2, "V3.Masculino", "V3.Feminino")
printOutputTwoListsPerFeature(agrad.l2, "V3.Masculino", "V3.Feminino")
printOutputTwoListsForAll(agrad.l2)

#Top 20 images based on diff, regression for men and women QScore
top20Diff <- arrange(agrad.l, desc(diff)) %>% slice(1:40)

regGroup1 <- lm(V3.Masculino ~ street_wid + sidewalk_wid + mov_cars + park_cars + mov_ciclyst + debris + pavement + landscape + build_ident + build_nrectan + prop_street_wall + prop_wind + long_sight + prop_sky_ahead + prop_sky_across + graffiti + trees + small_planters + build_height + build_diff_ages + diff_build + street_furnit + basic_col + lights + accent_col + people + prop_active_use, na.action = na.exclude, data = top20Diff)
regGroup2 <- lm(V3.Feminino ~ street_wid + sidewalk_wid + mov_cars + park_cars + mov_ciclyst + debris + pavement + landscape + build_ident + build_nrectan + prop_street_wall + prop_wind + long_sight + prop_sky_ahead + prop_sky_across + graffiti + trees + small_planters + build_height + build_diff_ages + diff_build + street_furnit + basic_col + lights + accent_col + people + prop_active_use, na.action = na.exclude, data = top20Diff)
summary(regGroup1)
summary(regGroup2)

#Spatial regression - consider spatial dependency and correlation!
library(spdep)
res <- getLatLong(agrad.l, "moran100/streetsQScoresLatLongAgraAll2.dat")
crd <- cbind(res$long, res$lat)
neigh <- dnearneigh(crd, 0, 100, longlat=F)
neigh2 <- nb2listw(neigh, style = "B")
test <- spautolm(diff ~ mov_cars + park_cars + mov_ciclyst + build_ident + build_nrectan + graffiti + trees + small_planters + build_diff_ages + diff_build + street_furnit + basic_col + lights + accent_col + people, data=res, listw=neigh2)
summary(test)

```

## Young x Adult - Pleasantness

100 iterations

```{r, echo=FALSE, fig.show='asis', fig.width=10, fig.height=5}

#Jovem x Adulto
agrad.l <- agrad %>% 
    do(arrange(., desc(V3.Jovem))) %>% 
    mutate(rank = 1:n()) %>% do(arrange(., desc(V3.Adulto))) %>% mutate(index = 1:n())

agrad.l <- calcDanieleCoeff(agrad.l)
agrad.l2 <- simulateCoefShuffle(agrad.l, iterations)

print(paste(">>>> Kendall Distance ", normalizedKendallTauDistance2(agrad.l$V3.Jovem, agrad.l$V3.Adulto)))
print(paste(">>>> Kendall adapted Jov x Adu ", kendallWithWeights(agrad.l, iterations)))

printOutputOneListPerFeature(agrad.l2, "V3.Jovem", "V3.Adulto")
printOutputTwoListsPerFeature(agrad.l2, "V3.Jovem", "V3.Adulto")
printOutputTwoListsForAll(agrad.l2)

#Top 20 images based on diff, regression for men and women QScore
top20Diff <- filter(agrad.l, setor == "25040090500004" | setor == "250400905000089")
top20Diff <- arrange(agrad.l, desc(diff)) %>% slice(1:40)

regGroup1 <- lm(rank ~ scale(street_wid) + scale(sidewalk_wid) + scale(mov_cars) + scale(park_cars) + scale(mov_ciclyst) + scale(debris) + scale(pavement) + scale(landscape) + scale(build_ident) + scale(build_nrectan) + scale(prop_street_wall) + scale(prop_wind) + scale(long_sight) + scale(prop_sky_ahead) + scale(prop_sky_across) + scale(as.integer(graffiti)) + scale(trees) + scale(small_planters) + scale(build_height) + scale(as.integer(build_diff_ages)) + scale(diff_build) + scale(street_furnit) + scale(basic_col) + scale(lights) + scale(accent_col) + scale(people) + scale(prop_active_use), na.action = na.exclude, data = top20Diff)
#regGroup2 <- lm(index ~ street_wid + sidewalk_wid + mov_cars + park_cars + mov_ciclyst + debris + pavement + landscape + build_ident + build_nrectan + prop_street_wall + prop_wind + long_sight + prop_sky_ahead + prop_sky_across + graffiti + trees + small_planters + build_height + build_diff_ages + diff_build + street_furnit + basic_col + lights + accent_col + people + prop_active_use, na.action = na.exclude, data = top20Diff)
regGroup2 <- lm(index ~  scale(street_wid) + scale(sidewalk_wid) + scale(mov_cars) + scale(park_cars) + scale(mov_ciclyst) + scale(debris) + scale(pavement) + scale(landscape) + scale(build_ident) + scale(build_nrectan) + scale(prop_street_wall) + scale(prop_wind) + scale(long_sight) + scale(prop_sky_ahead) + scale(prop_sky_across) + scale(as.integer(graffiti)) + scale(trees) + scale(small_planters) + scale(build_height) + scale(as.integer(build_diff_ages)) + scale(diff_build) + scale(street_furnit) + scale(basic_col) + scale(lights) + scale(accent_col) + scale(people) + scale(prop_active_use), na.action = na.exclude, data = top20Diff)
summary(regGroup1)
summary(regGroup2)

#Spatial regression - consider spatial dependency and correlation!
res <- getLatLong(agrad.l, "moran100/streetsQScoresLatLongAgraAll2.dat")
crd <- cbind(res$long, res$lat)
neigh <- dnearneigh(crd, 0, 100, longlat=F)
neigh2 <- nb2listw(neigh, style = "B")
test <- spautolm(diff ~ street_wid + sidewalk_wid + public_art + mov_cars + park_cars + mov_ciclyst + debris + pavement + landscape + courtyards + major_landsc + build_ident + build_nrectan + prop_street_wall + prop_wind + long_sight + prop_sky_ahead + prop_sky_across + graffiti + trees + small_planters + build_height + build_diff_ages + diff_build + prop_hist_build + outdoor_table + street_furnit + basic_col + lights + accent_col + people + prop_active_use, data=res, listw=neigh2)
summary(test)

# #Cross-validating
# regGeralAgrad <- lm(V3.Adulto ~ street_wid + mov_cars + debris + landscape + prop_wind + prop_sky_across + graffiti + trees + diff_build + lights + accent_col, na.action = na.exclude, data = agrad.l)
# regGeralAgrad <- lm(V3.Adulto ~ sidewalk_wid + mov_cars + debris + landscape + build_ident + build_nrectan + prop_wind + prop_sky_across + trees + build_diff_ages + lights + accent_col, na.action = na.exclude, data = subSample)
# regGeralAgrad <- lm(V3.Adulto ~ sidewalk_wid + mov_cars + debris + landscape + prop_wind + graffiti + trees + street_furnit + + accent_col, na.action = na.exclude, data = left)
# 
# summary(regGeralAgrad)
# texreg(regGeralAgrad, stars = c(0.001, 0.01, 0.05, 0.1))

```

## Married x Single - Pleasantness

100 iterations

```{r, echo=FALSE, fig.show='asis', fig.width=10, fig.height=5}

#Casado x Solteiro
agrad.l <- agrad %>% 
    do(arrange(., desc(V3.Casado))) %>% 
    mutate(rank = 1:n()) %>% do(arrange(., desc(V3.Solteiro))) %>% mutate(index = 1:n())

agrad.l <- calcDanieleCoeff(agrad.l)
agrad.l2 <- simulateCoefShuffle(agrad.l,iterations)

print(paste(">>>> Kendall Distance ", normalizedKendallTauDistance2(agrad.l$V3.Casado, agrad.l$V3.Solteiro)))
print(paste(">>>> Kendall adapted Cas x Sol ", kendallWithWeights(agrad.l, iterations)))

printOutputOneListPerFeature(agrad.l2, "V3.Casado", "V3.Solteiro")
printOutputTwoListsPerFeature(agrad.l2, "V3.Casado", "V3.Solteiro")
printOutputTwoListsForAll(agrad.l2)

#Top 20 images based on diff, regression for men and women QScore
top20Diff <- filter(agrad.l, bairro == "liberdade")
top20Diff <- arrange(agrad.l, desc(diff)) %>% slice(1:40)

regGroup1 <- lm(rank ~ scale(street_wid) + scale(sidewalk_wid) + scale(mov_cars) + scale(park_cars) + scale(mov_ciclyst) + scale(debris) + scale(pavement) + scale(landscape) + scale(build_ident) + scale(build_nrectan) + scale(prop_street_wall) + scale(prop_wind) + scale(long_sight) + scale(prop_sky_ahead) + scale(prop_sky_across) + scale(as.integer(graffiti)) + scale(trees) + scale(small_planters) + scale(build_height) + scale(as.integer(build_diff_ages)) + scale(diff_build) + scale(street_furnit) + scale(basic_col) + scale(lights) + scale(accent_col) + scale(people) + scale(prop_active_use), na.action = na.exclude, data = top20Diff)
#regGroup2 <- lm(index ~ street_wid + sidewalk_wid + mov_cars + park_cars + mov_ciclyst + debris + pavement + landscape + build_ident + build_nrectan + prop_street_wall + prop_wind + long_sight + prop_sky_ahead + prop_sky_across + graffiti + trees + small_planters + build_height + build_diff_ages + diff_build + street_furnit + basic_col + lights + accent_col + people + prop_active_use, na.action = na.exclude, data = top20Diff)
regGroup2 <- lm(index ~  scale(street_wid) + scale(sidewalk_wid) + scale(mov_cars) + scale(park_cars) + scale(mov_ciclyst) + scale(debris) + scale(pavement) + scale(landscape) + scale(build_ident) + scale(build_nrectan) + scale(prop_street_wall) + scale(prop_wind) + scale(long_sight) + scale(prop_sky_ahead) + scale(prop_sky_across) + scale(as.integer(graffiti)) + scale(trees) + scale(small_planters) + scale(build_height) + scale(as.integer(build_diff_ages)) + scale(diff_build) + scale(street_furnit) + scale(basic_col) + scale(lights) + scale(accent_col) + scale(people) + scale(prop_active_use), na.action = na.exclude, data = top20Diff)
summary(regGroup1)
summary(regGroup2)
  
#Spatial regression - consider spatial dependency and correlation!
res <- getLatLong(agrad.l, "moran100/streetsQScoresLatLongAgraAll2.dat")
crd <- cbind(res$long, res$lat)
neigh <- dnearneigh(crd, 0, 100, longlat=F)
neigh2 <- nb2listw(neigh, style = "B")
test <- spautolm(diff ~ street_wid + sidewalk_wid + public_art + mov_cars + park_cars + mov_ciclyst + debris + pavement + landscape + courtyards + major_landsc + build_ident + build_nrectan + prop_street_wall + prop_wind + long_sight + prop_sky_ahead + prop_sky_across + graffiti + trees + small_planters + build_height + build_diff_ages + diff_build + prop_hist_build + outdoor_table + street_furnit + basic_col + lights + accent_col + people + prop_active_use, data=res, listw=neigh2)
summary(test)

```

## Low x High income - Pleasantness

100 iterations

```{r, echo=FALSE, fig.show='asis', fig.width=10, fig.height=5}
#Baixa renda x Media renda
agrad.l <- agrad %>% 
    do(arrange(., desc(V3.Baixa))) %>% 
    mutate(rank = 1:n()) %>% do(arrange(., desc(V3.Media))) %>% mutate(index = 1:n())

#Danieles coefficients
agrad.l <- calcDanieleCoeff(agrad.l)
agrad.l2 <- simulateCoefShuffle(agrad.l,iterations)

print(paste(">>>> Kendall Distance ", normalizedKendallTauDistance2(agrad.l$V3.Baixa, agrad.l$V3.Media)))
print(paste(">>>> Kendall adapted Baix x Med ", kendallWithWeights(agrad.l, iterations)))

printOutputOneListPerFeature(agrad.l2, "V3.Baixa", "V3.Media")
printOutputTwoListsPerFeature(agrad.l2, "V3.Baixa", "V3.Media")
printOutputTwoListsForAll(agrad.l2)

#Top 20 images based on diff, regression for men and women QScore
top20Diff <- arrange(agrad.l, desc(diff)) %>% slice(1:40)

regGroup1 <- lm(rank ~ scale(street_wid) + scale(sidewalk_wid) + scale(mov_cars) + scale(park_cars) + scale(mov_ciclyst) + scale(debris) + scale(pavement) + scale(landscape) + scale(build_ident) + scale(build_nrectan) + scale(prop_street_wall) + scale(prop_wind) + scale(long_sight) + scale(prop_sky_ahead) + scale(prop_sky_across) + scale(as.integer(graffiti)) + scale(trees) + scale(small_planters) + scale(build_height) + scale(as.integer(build_diff_ages)) + scale(diff_build) + scale(street_furnit) + scale(basic_col) + scale(lights) + scale(accent_col) + scale(people) + scale(prop_active_use), na.action = na.exclude, data = top20Diff)
#regGroup2 <- lm(index ~ street_wid + sidewalk_wid + mov_cars + park_cars + mov_ciclyst + debris + pavement + landscape + build_ident + build_nrectan + prop_street_wall + prop_wind + long_sight + prop_sky_ahead + prop_sky_across + graffiti + trees + small_planters + build_height + build_diff_ages + diff_build + street_furnit + basic_col + lights + accent_col + people + prop_active_use, na.action = na.exclude, data = top20Diff)
regGroup2 <- lm(index ~  scale(street_wid) + scale(sidewalk_wid) + scale(mov_cars) + scale(park_cars) + scale(mov_ciclyst) + scale(debris) + scale(pavement) + scale(landscape) + scale(build_ident) + scale(build_nrectan) + scale(prop_street_wall) + scale(prop_wind) + scale(long_sight) + scale(prop_sky_ahead) + scale(prop_sky_across) + scale(as.integer(graffiti)) + scale(trees) + scale(small_planters) + scale(build_height) + scale(as.integer(build_diff_ages)) + scale(diff_build) + scale(street_furnit) + scale(basic_col) + scale(lights) + scale(accent_col) + scale(people) + scale(prop_active_use), na.action = na.exclude, data = top20Diff)
summary(regGroup1)
summary(regGroup2)

#Spatial regression - consider spatial dependency and correlation!
res <- getLatLong(agrad.l, "moran100/streetsQScoresLatLongAgraAll2.dat")
crd <- cbind(res$long, res$lat)
neigh <- dnearneigh(crd, 0, 100, longlat=F)
neigh2 <- nb2listw(neigh, style = "B")
test <- spautolm(diff ~ street_wid + sidewalk_wid + public_art + mov_cars + park_cars + mov_ciclyst + debris + pavement + landscape + courtyards + major_landsc + build_ident + build_nrectan + prop_street_wall + prop_wind + long_sight + prop_sky_ahead + prop_sky_across + graffiti + trees + small_planters + build_height + build_diff_ages + diff_build + prop_hist_build + outdoor_table + street_furnit + basic_col + lights + accent_col + people + prop_active_use, data=res, listw=neigh2)
summary(test)

```

## Men x Women - Safety

100 iterations

```{r, echo=FALSE, fig.show='asis', fig.width=10, fig.height=5}

#Homem x Mulher
seg.l <- seg %>% 
    do(arrange(., desc(V3.Masculino))) %>% 
    mutate(rank = 1:n()) %>% do(arrange(., desc(V3.Feminino))) %>% mutate(index = 1:n())

seg.l <- calcDanieleCoeff(seg.l)
seg.l2 <- simulateCoefShuffle(seg.l,iterations)

print(paste(">>>> Kendall Distance ", normalizedKendallTauDistance2(seg.l$V3.Masculino, seg.l$V3.Feminino)))
print(paste(">>>> Kendall adapted Hom x Mul ", kendallWithWeights(seg.l, iterations)))

printOutputOneListPerFeature(seg.l2, "V3.Masculino", "V3.Feminino")
printOutputTwoListsPerFeature(seg.l2, "V3.Masculino", "V3.Feminino")
printOutputTwoListsForAll(seg.l2)

#Spatial regression - consider spatial dependency and correlation!
res <- getLatLong(seg.l, "moran100/streetsQScoresLatLongAgraAll2.dat")
crd <- cbind(res$long, res$lat)
neigh <- dnearneigh(crd, 0, 100, longlat=F)
neigh2 <- nb2listw(neigh, style = "B")
test <- spautolm(diff ~ street_wid + sidewalk_wid + public_art + mov_cars + park_cars + mov_ciclyst + debris + pavement + landscape + courtyards + major_landsc + build_ident + build_nrectan + prop_street_wall + prop_wind + long_sight + prop_sky_ahead + prop_sky_across + graffiti + trees + small_planters + build_height + build_diff_ages + diff_build + prop_hist_build + outdoor_table + street_furnit + basic_col + lights + accent_col + people + prop_active_use, data=res, listw=neigh2)
summary(test)

```

## Young x Adult - Safety

100 iterations

```{r, echo=FALSE, fig.show='asis', fig.width=10, fig.height=5}

#Jovem x Adulto
seg.l <- seg %>% 
    do(arrange(., desc(V3.Jovem))) %>% 
    mutate(rank = 1:n()) %>% do(arrange(., desc(V3.Adulto))) %>% mutate(index = 1:n())

seg.l <- calcDanieleCoeff(seg.l)
seg.l2 <- simulateCoefShuffle(seg.l,iterations)

print(paste(">>>> Kendall Distance ", normalizedKendallTauDistance2(seg.l$V3.Jovem, seg.l$V3.Adulto)))
print(paste(">>>> Kendall adapted Jov x Adu ", kendallWithWeights(seg.l, iterations)))

printOutputOneListPerFeature(seg.l2, "V3.Jovem", "V3.Adulto")
printOutputTwoListsPerFeature(seg.l2, "V3.Jovem", "V3.Adulto")
printOutputTwoListsForAll(seg.l2)

#Spatial regression - consider spatial dependency and correlation!
res <- getLatLong(seg.l, "moran100/streetsQScoresLatLongAgraAll2.dat")
crd <- cbind(res$long, res$lat)
neigh <- dnearneigh(crd, 0, 100, longlat=F)
neigh2 <- nb2listw(neigh, style = "B")
test <- spautolm(diff ~ street_wid + sidewalk_wid + public_art + mov_cars + park_cars + mov_ciclyst + debris + pavement + landscape + courtyards + major_landsc + build_ident + build_nrectan + prop_street_wall + prop_wind + long_sight + prop_sky_ahead + prop_sky_across + graffiti + trees + small_planters + build_height + build_diff_ages + diff_build + prop_hist_build + outdoor_table + street_furnit + basic_col + lights + accent_col + people + prop_active_use, data=res, listw=neigh2)
summary(test)
```

## Married x Single - Safety

100 iterations

```{r, echo=FALSE, fig.show='asis', fig.width=10, fig.height=5}

#Casado x Solteiro
seg.l <- seg %>% 
    do(arrange(., desc(V3.Casado))) %>% 
    mutate(rank = 1:n()) %>% do(arrange(., desc(V3.Solteiro))) %>% mutate(index = 1:n())

seg.l <- calcDanieleCoeff(seg.l)
seg.l2 <- simulateCoefShuffle(seg.l,iterations)

print(paste(">>>> Kendall Distance ", normalizedKendallTauDistance2(seg.l$V3.Casado, seg.l$V3.Solteiro)))
print(paste(">>>> Kendall adapted Cas x Sol ", kendallWithWeights(seg.l, iterations)))

printOutputOneListPerFeature(seg.l2, "V3.Casado", "V3.Solteiro")
printOutputTwoListsPerFeature(seg.l2, "V3.Casado", "V3.Solteiro")
printOutputTwoListsForAll(seg.l2)

#Spatial regression - consider spatial dependency and correlation!
res <- getLatLong(seg.l, "moran100/streetsQScoresLatLongAgraAll2.dat")
crd <- cbind(res$long, res$lat)
neigh <- dnearneigh(crd, 0, 100, longlat=F)
neigh2 <- nb2listw(neigh, style = "B")
test <- spautolm(diff ~ mov_cars + park_cars + mov_ciclyst + build_ident + build_nrectan + graffiti + trees + small_planters + build_diff_ages + diff_build + street_furnit + basic_col + lights + accent_col + people, data=res, listw=neigh2)
summary(test)
```

## Low x High income - Safety

100 iterations

```{r, echo=FALSE, fig.show='asis', fig.width=10, fig.height=5}
#Baixa renda x Media renda
seg.l <- seg %>% 
    do(arrange(., desc(V3.Baixa))) %>% 
    mutate(rank = 1:n()) %>% do(arrange(., desc(V3.Media))) %>% mutate(index = 1:n())

seg.l <- calcDanieleCoeff(seg.l)
seg.l2 <- simulateCoefShuffle(seg.l,iterations)

print(paste(">>>> Kendall Distance ", normalizedKendallTauDistance2(seg.l$V3.Baixa, seg.l$V3.Media)))
print(paste(">>>> Kendall adapted Bai x Med ", kendallWithWeights(seg.l, iterations)))

printOutputOneListPerFeature(seg.l2, "V3.Baixa", "V3.Media")
printOutputTwoListsPerFeature(seg.l2, "V3.Baixa", "V3.Media")
printOutputTwoListsForAll(seg.l2)

#Top 20 images based on diff, regression for men and women QScore
top20Diff <- filter(seg.l, setor == "25040090500004" | setor == "250400905000089")
top20Diff <- arrange(agrad.l, desc(diff)) %>% slice(1:40)

regGroup1 <- lm(rank ~ scale(street_wid) + scale(sidewalk_wid) + scale(mov_cars) + scale(park_cars) + scale(mov_ciclyst) + scale(debris) + scale(pavement) + scale(landscape) + scale(build_ident) + scale(build_nrectan) + scale(prop_street_wall) + scale(prop_wind) + scale(long_sight) + scale(prop_sky_ahead) + scale(prop_sky_across) + scale(as.integer(graffiti)) + scale(trees) + scale(small_planters) + scale(build_height) + scale(as.integer(build_diff_ages)) + scale(diff_build) + scale(street_furnit) + scale(basic_col) + scale(lights) + scale(accent_col) + scale(people) + scale(prop_active_use), na.action = na.exclude, data = top20Diff)
#regGroup2 <- lm(index ~ street_wid + sidewalk_wid + mov_cars + park_cars + mov_ciclyst + debris + pavement + landscape + build_ident + build_nrectan + prop_street_wall + prop_wind + long_sight + prop_sky_ahead + prop_sky_across + graffiti + trees + small_planters + build_height + build_diff_ages + diff_build + street_furnit + basic_col + lights + accent_col + people + prop_active_use, na.action = na.exclude, data = top20Diff)
regGroup2 <- lm(index ~  scale(street_wid) + scale(sidewalk_wid) + scale(mov_cars) + scale(park_cars) + scale(mov_ciclyst) + scale(debris) + scale(pavement) + scale(landscape) + scale(build_ident) + scale(build_nrectan) + scale(prop_street_wall) + scale(prop_wind) + scale(long_sight) + scale(prop_sky_ahead) + scale(prop_sky_across) + scale(as.integer(graffiti)) + scale(trees) + scale(small_planters) + scale(build_height) + scale(as.integer(build_diff_ages)) + scale(diff_build) + scale(street_furnit) + scale(basic_col) + scale(lights) + scale(accent_col) + scale(people) + scale(prop_active_use), na.action = na.exclude, data = top20Diff)
summary(regGroup1)
summary(regGroup2)

#Spatial regression - consider spatial dependency and correlation!
res <- getLatLong(seg.l, "moran100/streetsQScoresLatLongAgraAll2.dat")
crd <- cbind(res$long, res$lat)
neigh <- dnearneigh(crd, 0, 100, longlat=F)
neigh2 <- nb2listw(neigh, style = "B")
test <- spautolm(diff ~ mov_cars + park_cars + mov_ciclyst + build_ident + build_nrectan + graffiti + trees + small_planters + build_diff_ages + diff_build + street_furnit + basic_col + lights + accent_col + people, data=res, listw=neigh2)
summary(test)
```

#Agradavel x Seguro
```{r, echo=FALSE, fig.show='asis', fig.width=10, fig.height=5}
grupo1 <- dadosSub[(dadosSub$grupo == 'Geral' & dadosSub$V1=='agrad%C3%A1vel?' ),] 
grupo2 <- dadosSub[(dadosSub$grupo == 'Geral' & dadosSub$V1=='seguro?'),] 
temp <- rbind(grupo1, grupo2)

novosgrupo1grupo2 <- reshape(temp, timevar="V1", idvar=c("V2", "grupo", "diag", "hor", "vert", "red", "green", "blue", "bairro"), direction="wide")
colnames(novosgrupo1grupo2)[colnames(novosgrupo1grupo2) == "V3.agrad%C3%A1vel?"] <- "V3.agradavel"
colnames(novosgrupo1grupo2)[colnames(novosgrupo1grupo2) == "V3.seguro?"] <- "V3.seguro"

#Regressao
library(texreg)

regAgrad <- lm(V3.agradavel ~ V3.seguro, data=novosgrupo1grupo2)

novosgrupo1grupo2$residuals <- regAgrad$residuals
novosgrupo1grupo2$residualsPos <- abs(regAgrad$residuals)

novosgrupo1grupo2 <- novosgrupo1grupo2[with(novosgrupo1grupo2, order(-residualsPos)), ]

plot(regAgrad$residuals, main = "Residual Plot Pleasantness", ylab = "Residuals")

#Modelo
#sink("reg-jov-adu-agrad.txt")
texreg(regAgrad)
summary(regAgrad)
#sink()

#Fotos, QScores e resíduos
write.table(novosgrupo1grupo2[, c("V2", "V3.agradavel", "V3.seguro", "residuals", "residualsPos")], file="agrad-seg.dat", sep = "\t")

#Scatterplot Pleas x Safe
geral <- select(filter(dadosCopy, grupo == "Geral"), grupo, V1, V2, V3, bairro) 

geral$bairro <- as.character(geral$bairro)
geral$bairro[geral$bairro == "catole"] <- "Catolé"
geral$bairro[geral$bairro == "liberdade"] <- "Liberdade"
geral$bairro[geral$bairro == "centro"] <- "Centro"

novosDados <- reshape(geral, timevar="V1", idvar=c("V2", "grupo", "bairro"), direction="wide")
novosDados <- rename(novosDados, c("V3.agrad%C3%A1vel?"="Pleasant", "V3.seguro?"="Safe", "bairro" = "neighborhood"))

library(plyr)

w = 5
h = 4
pdf("images/pleasXsafeAll.pdf", width = w, height = h)
ggplot(novosDados, aes(y=Pleasant, x=Safe, colour=neighborhood))+geom_point(alpha = 0.7, size=1.7)+xlab("QScore Safety")+ylab("QScore Pleasantness")+geom_abline(intercept=0, colour="red")+theme(axis.text=element_text(size=20), axis.title=element_text(size=20), legend.text = element_text(size=20), legend.title = element_text(size=20))+theme_bw()+annotate("text", x = 4, y = 7, label = "Adj. R^2 = 0.27")
dev.off()

cor.test(novosDados$Safe, novosDados$Pleasant, method="kendall")
cor.test(novosDados$Safe, novosDados$Pleasant, method="pearson")
cor.test(novosDados$Safe, novosDados$Pleasant, method="spearman")
```