---
title: "logit_musicas"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
require(gmodels)
require(vcd)
require(lme4)
library(nlme)
library(caret)
library(pscl)
library(DT)
library(ggplot2)
theme_set(theme_bw())
library(GGally)
library(dplyr, warn.conflicts = F)
library(broom)

library(car)
library(readr)
library(caret)
```

```{r lib}
compare_glms <- function(baseline, model){
  modelChi <- baseline$deviance - model$deviance
  chidf <- baseline$df.residual - model$df.residual
  chisq.prob <- 1 - pchisq(modelChi, chidf)
  print(paste(modelChi, chidf, chisq.prob))
}

compare_null <- function(baselineModel){
  modelChi <- baselineModel$null.deviance - baselineModel$deviance
  chidf <- baselineModel$df.null - baselineModel$df.residual
  chisq.prob <- 1 - pchisq(modelChi, chidf)
  print(paste(modelChi, chidf, chisq.prob))
}

computePseudoR2 <- function(baselineModel, completeModel){
  print("Hosmer and Lemeshow")
  print(  completeModel@devcomp$cmp['dev'] /  baselineModel@devcomp$cmp['dev'] )
  print("Hosmer and Lemeshow")
  print(  (baselineModel@devcomp$cmp['dev'] - completeModel@devcomp$cmp['dev']) /  baselineModel@devcomp$cmp['dev'] )
  print("Cox and Snells")
  cs <- 1 - exp( (completeModel@devcomp$cmp['dev'] - baselineModel@devcomp$cmp['dev']) / nrow(completeModel@frame)  )
  print(  cs  )
  print("Nagelkerke")
  print(  cs / ( 1 - exp(- baselineModel@devcomp$cmp['dev'] / nrow(completeModel@frame) )  )  )
}
```

```{r read}
#Leitura dos dados
raw_data <- read.csv("./training_set_sl=8_chromaOTI_mfcc.csv", header=TRUE)

data = raw_data %>% mutate_at( vars(sim.A.B....sim.A.C.), as.factor)
#Scale or not scale input?

```

```{r model.lib}
create_model_only_int = function(the_data){
  return(glm(
    sim.A.B....sim.A.C. ~ 1,
    data = the_data,
    family = binomial())) 
  #gls(choice ~ 1, data = agrad, method = "ML")
}

create_model_w_interact = function(the_data){
  return(glm(
    sim.A.B....sim.A.C. ~ simple_chroma_AB + simple_chroma_AC + simple_chroma_BC + simple_mfcc_AB + simple_mfcc_AC + simple_mfcc_BC,
    data = the_data,
    family = binomial()))
}
```

```{r}
#Explanatory Model Using all data
intercept_model <- create_model_only_int(data)
complete_model <- create_model_w_interact(data)

summary(intercept_model)
summary(complete_model)
logLik(intercept_model)*-2 
logLik(complete_model)*-2

computePseudoR2(baselineModel = intercept_model, completeModel = complete_model)
vif(complete_model)
pR2(complete_model)

#Confidence intervals: https://stats.idre.ucla.edu/r/dae/logit-regression/
cc <- confint(complete_model, parm="beta_", level = 0.95, method="boot", nsim=1, parallel="multicore", ncpus=2)

#Predicting: https://www.theanalysisfactor.com/r-tutorial-glm1/; https://www.tatvic.com/blog/logistic-regression-with-r/; https://www.analyticsvidhya.com/blog/2015/11/beginners-guide-on-logistic-regression-in-r/; **https://www.r-bloggers.com/evaluating-logistic-regression-models/

#Simple partition with 60% for training and 40% for testing
Train <- createDataPartition(data$sim.A.B....sim.A.C., p=0.6, list=FALSE, times=100)
training <- data[ Train, ]
testing <- data[ -Train, ]

mod_fit <- train(sim.A.B....sim.A.C. ~ simple_chroma_AB + simple_chroma_AC + simple_chroma_BC + simple_mfcc_AB + simple_mfcc_AC + simple_mfcc_BC, data=training, method="glm", family="binomial")
exp(coef(mod_fit$finalModel))

#Predicting and accuracy
#predict(mod_fit, newdata=testing)
#predict(mod_fit, newdata=testing, type="prob")
pred = predict(mod_fit, newdata=testing)
accuracy <- table(pred, testing[,"sim.A.B....sim.A.C."])
sum(diag(accuracy))/sum(accuracy)

#Confusion matrix to explore false positives and negatives
pred = predict(mod_fit, newdata=testing)
confusionMatrix(data=pred, testing$sim.A.B....sim.A.C.)#https://en.wikipedia.org/wiki/Sensitivity_and_specificity

#Using 10-fold cross-validation
ctrl <- trainControl(method = "repeatedcv", number = 5, savePredictions = TRUE)

mod_fit <- train(sim.A.B....sim.A.C. ~ simple_chroma_AB + simple_chroma_AC + simple_chroma_BC + simple_mfcc_AB + simple_mfcc_AC + simple_mfcc_BC, data=training, method="glm", family="binomial", trControl = ctrl)#, tuneLength = 5)
pred = predict(mod_fit, newdata=testing)

accuracy <- table(pred, testing[,"Class"])
sum(diag(accuracy))/sum(accuracy)
confusionMatrix(data=pred, testing$Class)
```
