---
title: "Moran_Corr_Reg"
output: pdf_document
---
# Moran Geral (simulações)

```{r, echo=FALSE, fig.show='asis', fig.width=4}
source('krippMoran.R')

moranI("moran100/streetsQScoresLatLongAgraAll.dat", "moran100/streetsQScoresLatLongSegAll.dat")
```

# Moran por grupo

## Adulto
```{r, echo=FALSE, fig.show='asis', fig.width=4}
moranI("moran100/streetsQScoresLatLongAgraAllAdulto.dat", "moran100/streetsQScoresLatLongSegAllAdulto.dat")
```

## Jovem
```{r, echo=FALSE, fig.show='asis', fig.width=4}
moranI("moran100/streetsQScoresLatLongAgraAllJovem.dat", "moran100/streetsQScoresLatLongSegAllJovem.dat")
```

## Baixa
```{r, echo=FALSE, fig.show='asis', fig.width=4}
moranI("moran100/streetsQScoresLatLongAgraAllBaixa.dat", "moran100/streetsQScoresLatLongSegAllBaixa.dat")
```

## Média
```{r, echo=FALSE, fig.show='asis', fig.width=4}
moranI("moran100/streetsQScoresLatLongAgraAllMedia.dat", "moran100/streetsQScoresLatLongSegAllMedia.dat")
```

## Feminino
```{r, echo=FALSE, fig.show='asis', fig.width=4}
moranI("moran100/streetsQScoresLatLongAgraAllFeminino.dat", "moran100/streetsQScoresLatLongSegAllFeminino.dat")
```

## Masculino
```{r, echo=FALSE, fig.show='asis', fig.width=4}
moranI("moran100/streetsQScoresLatLongAgraAllMasculino.dat", "moran100/streetsQScoresLatLongSegAllMasculino.dat")
```

## Solteiro
```{r, echo=FALSE, fig.show='asis', fig.width=4}
moranI("moran100/streetsQScoresLatLongAgraAllSolteiro.dat", "moran100/streetsQScoresLatLongSegAllCasado.dat")
```

## Casado
```{r, echo=FALSE, fig.show='asis', fig.width=4}
moranI("moran100/streetsQScoresLatLongAgraAllCasado.dat", "moran100/streetsQScoresLatLongSegAllCasado.dat")
```

# Correlações

## Geral

```{r, echo=FALSE, fig.show='asis', fig.width=4}
source('analisaCorrelacao.R')

calculateTests("inputCorrelacaoRegressao100/rgbQScoreAgradAll.dat", "inputCorrelacaoRegressao100/rgbQScoreSegAll.dat", shouldPlot=TRUE)
boxplot(dataAgrad$qscore, prob=TRUE, main="QScore")
boxplot(dataSeg$qscore, prob=TRUE, main="QScore")
```

## Adulto

```{r, echo=FALSE, fig.show='asis', fig.width=4}
calculateTests("inputCorrelacaoRegressao100/rgbQScoreAgradAllAdulto.dat", "inputCorrelacaoRegressao100/rgbQScoreSegAllAdulto.dat", shouldPlot=TRUE)
boxplot(dataAgrad$qscore, prob=TRUE, main="QScore")
boxplot(dataSeg$qscore, prob=TRUE, main="QScore")
```

## Jovem

```{r, echo=FALSE, fig.show='asis', fig.width=4}
calculateTests("inputCorrelacaoRegressao100/rgbQScoreAgradAllJovem.dat", "inputCorrelacaoRegressao100/rgbQScoreSegAllJovem.dat", shouldPlot=TRUE)
boxplot(dataAgrad$qscore, prob=TRUE, main="QScore")
boxplot(dataSeg$qscore, prob=TRUE, main="QScore")
```

## Baixa

```{r, echo=FALSE, fig.show='asis', fig.width=4}
calculateTests("inputCorrelacaoRegressao100/rgbQScoreAgradAllBaixa.dat", "inputCorrelacaoRegressao100/rgbQScoreSegAllBaixa.dat", shouldPlot=TRUE)
boxplot(dataAgrad$qscore, prob=TRUE, main="QScore")
boxplot(dataSeg$qscore, prob=TRUE, main="QScore")
```

## Media

```{r, echo=FALSE, fig.show='asis', fig.width=4}
calculateTests("inputCorrelacaoRegressao100/rgbQScoreAgradAllMedia.dat", "inputCorrelacaoRegressao100/rgbQScoreSegAllMedia.dat", shouldPlot=TRUE)
boxplot(dataAgrad$qscore, prob=TRUE, main="QScore")
boxplot(dataSeg$qscore, prob=TRUE, main="QScore")
```

## Feminino

```{r, echo=FALSE, fig.show='asis', fig.width=4}
calculateTests("inputCorrelacaoRegressao100/rgbQScoreAgradAllFeminino.dat", "inputCorrelacaoRegressao100/rgbQScoreSegAllFeminino.dat", shouldPlot=TRUE)
boxplot(dataAgrad$qscore, prob=TRUE, main="QScore")
boxplot(dataSeg$qscore, prob=TRUE, main="QScore")
```

## Masculino

```{r, echo=FALSE, fig.show='asis', fig.width=4}
calculateTests("inputCorrelacaoRegressao100/rgbQScoreAgradAllMasculino.dat", "inputCorrelacaoRegressao100/rgbQScoreSegAllMasculino.dat", shouldPlot=TRUE)
boxplot(dataAgrad$qscore, prob=TRUE, main="QScore")
boxplot(dataSeg$qscore, prob=TRUE, main="QScore")
```

## Solteiro

```{r, echo=FALSE, fig.show='asis', fig.width=4}
calculateTests("inputCorrelacaoRegressao100/rgbQScoreAgradAllSolteiro.dat", "inputCorrelacaoRegressao100/rgbQScoreSegAllSolteiro.dat", shouldPlot=TRUE)
boxplot(dataAgrad$qscore, prob=TRUE, main="QScore")
boxplot(dataSeg$qscore, prob=TRUE, main="QScore")
```

## Casado

```{r, echo=FALSE, fig.show='asis', fig.width=4}
calculateTests("inputCorrelacaoRegressao100/rgbQScoreAgradAllCasado.dat", "inputCorrelacaoRegressao100/rgbQScoreSegAllCasado.dat", shouldPlot=TRUE)
boxplot(dataAgrad$qscore, prob=TRUE, main="QScore")
boxplot(dataSeg$qscore, prob=TRUE, main="QScore")
```

# Regressões

## Geral

```{r, echo=FALSE, fig.show='asis', fig.width=4}
source('analisaRegressao.R')

calculateRegression("inputCorrelacaoRegressao100/rgbQScoreAgradAll.dat", "inputCorrelacaoRegressao100/rgbQScoreSegAll.dat", shouldPlot=TRUE)
plot(regsubsetsAgrad.out, scale = "adjr2", main = "Adjusted R^2")
plot(regsubsetsSeg.out, scale = "adjr2", main = "Adjusted R^2")
```

## Adulto

```{r, echo=FALSE, fig.show='asis', fig.width=4}
calculateRegression("inputCorrelacaoRegressao100/rgbQScoreAgradAllAdulto.dat", "inputCorrelacaoRegressao100/rgbQScoreSegAllAdulto.dat", shouldPlot=TRUE)
plot(regsubsetsAgrad.out, scale = "adjr2", main = "Adjusted R^2")
plot(regsubsetsSeg.out, scale = "adjr2", main = "Adjusted R^2")
```

## Jovem

```{r, echo=FALSE, fig.show='asis', fig.width=4}
calculateRegression("inputCorrelacaoRegressao100/rgbQScoreAgradAllJovem.dat", "inputCorrelacaoRegressao100/rgbQScoreSegAllJovem.dat", shouldPlot=TRUE)
plot(regsubsetsAgrad.out, scale = "adjr2", main = "Adjusted R^2")
plot(regsubsetsSeg.out, scale = "adjr2", main = "Adjusted R^2")
```

## Baixa

```{r, echo=FALSE, fig.show='asis', fig.width=4}
calculateRegression("inputCorrelacaoRegressao100/rgbQScoreAgradAllBaixa.dat", "inputCorrelacaoRegressao100/rgbQScoreSegAllBaixa.dat", shouldPlot=TRUE)
plot(regsubsetsAgrad.out, scale = "adjr2", main = "Adjusted R^2")
plot(regsubsetsSeg.out, scale = "adjr2", main = "Adjusted R^2")
```

## Media

```{r, echo=FALSE, fig.show='asis', fig.width=4}
calculateRegression("inputCorrelacaoRegressao100/rgbQScoreAgradAllMedia.dat", "inputCorrelacaoRegressao100/rgbQScoreSegAllMedia.dat", shouldPlot=TRUE)
plot(regsubsetsAgrad.out, scale = "adjr2", main = "Adjusted R^2")
plot(regsubsetsSeg.out, scale = "adjr2", main = "Adjusted R^2")
```

## Feminino

```{r, echo=FALSE, fig.show='asis', fig.width=4}
calculateRegression("inputCorrelacaoRegressao100/rgbQScoreAgradAllFeminino.dat", "inputCorrelacaoRegressao100/rgbQScoreSegAllFeminino.dat", shouldPlot=TRUE)
plot(regsubsetsAgrad.out, scale = "adjr2", main = "Adjusted R^2")
plot(regsubsetsSeg.out, scale = "adjr2", main = "Adjusted R^2")
```

## Masculino

```{r, echo=FALSE, fig.show='asis', fig.width=4}
calculateRegression("inputCorrelacaoRegressao100/rgbQScoreAgradAllMasculino.dat", "inputCorrelacaoRegressao100/rgbQScoreSegAllMasculino.dat", shouldPlot=TRUE)
plot(regsubsetsAgrad.out, scale = "adjr2", main = "Adjusted R^2")
plot(regsubsetsSeg.out, scale = "adjr2", main = "Adjusted R^2")
```

## Solteiro

```{r, echo=FALSE, fig.show='asis', fig.width=4}
calculateRegression("inputCorrelacaoRegressao100/rgbQScoreAgradAllSolteiro.dat", "inputCorrelacaoRegressao100/rgbQScoreSegAllSolteiro.dat", shouldPlot=TRUE)
plot(regsubsetsAgrad.out, scale = "adjr2", main = "Adjusted R^2")
plot(regsubsetsSeg.out, scale = "adjr2", main = "Adjusted R^2")
```

## Casado

```{r, echo=FALSE, fig.show='asis', fig.width=4}
calculateRegression("inputCorrelacaoRegressao100/rgbQScoreAgradAllCasado.dat", "inputCorrelacaoRegressao100/rgbQScoreSegAllCasado.dat", shouldPlot=TRUE)
plot(regsubsetsAgrad.out, scale = "adjr2", main = "Adjusted R^2")
plot(regsubsetsSeg.out, scale = "adjr2", main = "Adjusted R^2")
```
